### ISSUE TITLE
Preparations for clean-up Release 0.7

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#100]
Hi all,

I think, once we have the tests, the code and the new features under control, we should go for a maintenance release 0.7 and present a clean platform. This ticket could be used to collect the things we have to take care of before that:

 * Make sure the code is clean and follows the coding guidelines
 * Make sure all tests are green (we should be there very soon)
 * Make sure all files are in place and referenced correctly
 * Make sure all documentation and readme files are up to date
 * Add the compressed version to the dist folder and have it tested too

Anything I have forgotten?
//cc @neilj @fhemberger @tdeekens

**Comment by tdeekens** [comment]
Ai, suggestion pull request in #101 for minification.

**Comment by cure53** [comment]
Thank you very much :) A huge leap closer to 0.7 now!

**Comment by tdeekens** [comment]
...what are the coding guidelines btw? `jshint` and all good or something else?

**Comment by cure53** [comment]
@tdeekens I usually go for http://javascript.crockford.com/code.html and `jshint`

**Comment by cure53** [comment]
Hi all, I think we are pretty much ready for 0.7. Any objections?

**Comment by neilj** [comment]
I've been on holiday (still kind of am) so haven't had a chance to fully review the recent change for the security fix. I'm concerned that the switch to DOMParser has broken compatibility with all but *very* recent browsers. The minimums are now:

Chrome 30
Firefox 12
IE 10
Opera 17
Safari 7.1

I think we should add back in a fallback to document.implementation for older browsers (except FF due to the bug of course). I'm happy to submit a pull request; I should be able to do it sometime this week.

**Comment by cure53** [comment]
Hi @neilj - no problem, we are not in a huge hurry. Enjoy your vacation :)

About the compatibility: I had the same concern and added some code recently to cover that:
https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L306

We are now testing if the DOMParser throws and/or returns null. If either of that happens, we fall-back to the old way of doing things with `document.implementation`.

**Comment by cure53** [comment]
"Luckily", Firefox introduced the weird and buggy innerHTML that forced us to release 0.6.7 in version 37 or 38 iirc. So *not* using `DOMParser` on older versions of FF is safe. 

Note that the code also allows checks for a clobbered `getElementsByTagName` - I added this to be compatible with older Firefox which allows clobbering but breaks on using the `call()` at this point. So I think we have even better compatibility than we had before. But a review is highly appreciated of course.

**Comment by neilj** [comment]
Ah, thanks. I just noticed that and was wondering what that was for. I'm just about to get on a plane; I'll have a deeper look during the flight.

**Comment by cure53** [comment]
Great, thanks! :)

**Comment by cure53** [comment]
I think we are good here, any objections?
