### ISSUE TITLE
[bug] Version 3.1.7 build error for Angular (likely other projects)

### ISSUE THREAD

**Issue by philmayfield** [cure53/DOMPurify#1003]
This appears to be a regression of issue [895](https://github.com/cure53/DOMPurify/issues/895).

After updating to version 3.1.7 Angular project fails to run with the error:

`Error: export 'sanitize' (imported as 'DOMPurify') was not found in 'dompurify' (possible exports: default)`

### Background & Context

Using this package in an Angular 18 project, but this is likely an import issue that will affect any project using that syntax.

package.json:
`"dompurify: "^3.1.0",`

and import like this into the typescript file

`import * as DOMPurify from 'dompurify';`

Temporary solution :

Use pinned version: 
`"dompurify: "3.1.6"`

**Comment by opensourceally** [comment]
Faced issue in Angular 14. Used 
 "dompurify": [
        "node_modules/dompurify/dist/purify.min"
      ]
 in tsconfig.json and it is working now.

**Comment by jgbpercy** [comment]
Er, @jeroen1602 ? Gotta assume this is related to #990 ?

3.1.7 is also broken for me under Angular 17

**Comment by jeroen1602** [comment]
> Er, @jeroen1602 ? Gotta assume this is related to #990 ?
> 
> 3.1.7 is also broken for me under Angular 17

I only tested it against the newer vite compiler, so maybe that is the difference?

**Comment by philmayfield** [comment]
While I don't pretend to know a ton about what's going on, after some digging this is certainly an issue with using DOMPurify in a TS project, issue rather than being an Angular issue (TS projects and Angular projects just have a lot of overlap).

I _believe_ that the root of the issue is coming from the `@types/dompurify` package.  Specifically around the way it is exported: [https://github.com/DefinitelyTyped/DefinitelyTyped/blob/76b4d4a86fee7b95f2ccb90e626f40c95567edeb/types/dompurify/index.d.ts#L4](source).

Just fiddling with the code locally by changing:
```ts
export = DOMPurify;
```
to
```ts
export default DOMPurify;
```
allows me to import via:
```ts
import DOMPurify from 'dompurify';
```
and things immediately start working.

Like I mentioned I'm a bit out of my element, but the TS linting points to `allowSyntheticDefaultImports` ([docs](https://www.typescriptlang.org/tsconfig/#allowSyntheticDefaultImports)) being the source, which got me down that path.

**Comment by cure53** [comment]
@reduckted Heya - we are happy to accept any PR for this that mitigates the problem and doesn't cause any new or additional breakage.

**Comment by cure53** [comment]
I recall some related issue from 2022... https://github.com/cure53/DOMPurify/issues/713

**Comment by cure53** [comment]
Closing this for now as it feels that we cannot do much here, workarounds exist and us changing things to address this will cause breakage on other ends.

**Comment by reduckted** [comment]
> @cure53  us changing things to address this will cause breakage on other ends.

What breakage and what other ends are you referring to? If the types are fixed and provided in this package, then nothing else should break.

**Comment by cure53** [comment]
As far as I can see, that discussion was had once before and whatever path we chose, it was wrong for someone :sweat_smile: 

What benefit would you see if we delivered the types and not DefinitelyTyped?

**Comment by philmayfield** [comment]
What's frustrating is that it wasn't an update to the types that broke things, it was an update to this package.

**Comment by cure53** [comment]
> What's frustrating is that it wasn't an update to the types that broke things, it was an update to this package.

I agree and still have no idea why myself. I mean, we added one line here:

https://github.com/cure53/DOMPurify/pull/990/commits/745b5212083b8e816e58328696472d3f0d69b18c#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R22

And that seemingly messed things up. This is also one reason why I am really hesitant to add more cruft to our package, i.e. bundled types - because there is no way to predict what will happen (for me at least).

**Comment by rubenv** [comment]
I'm no expert, but you're using the same filename for `module` and `es2020`?

**Comment by cure53** [comment]
cc  @jeroen1602 who wrote the PR :D https://github.com/cure53/DOMPurify/pull/990

**Comment by jeroen1602** [comment]
@cure53 you could revert my PR for now since it only fixes a warning and has minimal space saving in the final bundle.

**Comment by cure53** [comment]
So, the steps would be:

* Remove that line again
* Prepare a new release
* Publish release

Correct? Not gonna happen before at some point next week, but I can do that. @rubenv @philmayfield @reduckted wdyt?

**Comment by rubenv** [comment]
My gut feeling is that the identical filename causes the wrong thing to end
up in the wrong place. Could be as simple as changing that, but I have
never worked with this, so could be wrong.

**Comment by philmayfield** [comment]
I would agree that reverting the PR for now makes the most sense - until whatever the underlying issue is can be fully groked.

**Comment by reduckted** [comment]
> So, the steps would be:
>  ...
>Correct? Not gonna happen before at some point next week, but I can do that. 

@cure53 If you can wait a day or two, I've almost completed adding type definitions to this repository by converting it to TypeScript. There are minimal changes to the actual code (absolutely no logic changes), and no changes to the existing JavaScript files in the `dist` folder other than the removal of some JSDoc comments and whitespace. 

I still need to test it in various use cases (for example, in an Angular project, etc), but I think this is the best path forward.

**Comment by cure53** [comment]
> > So, the steps would be:
> > ...
> > Correct? Not gonna happen before at some point next week, but I can do that.
> 
> @cure53 If you can wait a day or two, I've almost completed adding type definitions to this repository by converting it to TypeScript. There are minimal changes to the actual code (absolutely no logic changes), and no changes to the existing JavaScript files in the `dist` folder other than the removal of some JSDoc comments and whitespace.
> 
> I still need to test it in various use cases (for example, in an Angular project, etc), but I think this is the best path forward.

Cool, thanks - we will wait then :slightly_smiling_face:

**Comment by philmayfield** [comment]
The effort is much appreciated everyone!

**Comment by reduckted** [comment]
A quick update. 

I've had some trouble getting the type declarations correct for all of the different scenarios that [`arethetypeswrong`](https://www.npmjs.com/package/@arethetypeswrong/cli) checks. I thought I had that working, but have just discovered another problem with them. Hopefully I'll get that sorted out in the next day or so.

**Comment by reduckted** [comment]
Good news! I've made a pull request to add type declarations: #1006.

**Comment by cure53** [comment]
Amazing, thanks a ton, this looks great :smile: 

@philmayfield does this change do the trick for you as well?

**Comment by philmayfield** [comment]
I'll give it a shot in the next day or so and let you know! 🙇

**Comment by philmayfield** [comment]
Hey there, just thought I'd check in as I finally had a chance to sit down and try the fix out.  Unfortunately for me its still having an issue, but I'm convinced it's something to do with our main project config.  Possibly a compatibility thing to work with commonjs, not totally sure yet.  But!  When I create a new Angular project and install @reduckted s fix version, it compiles fine and the same component we use on the main project works fine with a slight adjustment to the import syntax.

```ts
import DOMPurify from 'dompurify';
```
as opposed to
```ts
import * as DOMPurify from 'dompurify';
```

So I'm confident in saying that it's a me problem now 😜 - thank you @reduckted for your hard work!

**Comment by cure53** [comment]
Alright, we are live :) https://github.com/cure53/DOMPurify/releases/tag/3.2.0

**Comment by jeroen1602** [comment]
I had to add a few things to my `tsconfig.json` to get it to play nice.

```json
{
  "compilerOptions": {
     "paths": {
      "dompurify": ["node_modules/dompurify/dist/purify.es.d.mts"],
      },
      "types": ["trusted-types"],
  }
}
```

As well as installing `@types/trusted-types` as a dev-dependency (I used version ^2.0.7)

**Comment by reduckted** [comment]
> And the `paths` part is needed for `ngpackgr` if you use it in a library. It has its own logic for module resolution and will try to load the `purify.cjs.d.ts` version and then complain that it is commonjs.

That's interesting. Are you able to link to this module resolution code? Maybe there's something that needs to be added to the package.json file for `dompurify` to make it pick the right one.

**Comment by jeroen1602** [comment]
I'm trying to recreate it so that I can work back from the error, but now it is happy to compile without specifying the `paths` variable in the `tsconfig.json`. So I'm just mostly confused, but happy it works.

**Comment by jgbpercy** [comment]
I'm not (and have actively avoided trying to become) an expert in JS modules and module resolution, so I don't currently know what the fix is, but something is definitely still wrong.

In my editor, it seems like the pre-3.1.7 import `import * as domPurify from 'dompurify';` is going to work and shows no errors, but then when actually compiling I get an error:
```
Error: export 'sanitize' (imported as 'domPurify ') was not found in 'dompurify' (possible exports: default)
```

This is a moderately complicated Angular/nx project where the code in question is in a library project, which judging from some of the comments in this thread might be relevant.

Aaaaanyway, if I'll get time at some point I'd love to try to figure out what the fix is on the DOM Purify side, but for now I'm just here to share this _seemingly_ successful workaround:
```
import * as _domPurifyBroken from 'dompurify';

const domPurify = (_domPurifyBroken as any).default as typeof _domPurifyBroken;
```
