### ISSUE TITLE
Limit browsertests to changes in specific files

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#102]
Would it make sense to limit the automated tests to changes in specific files?

Like for example:

https://github.com/cure53/DOMPurify/blob/master/src/purify.js (someone modified the spice)
https://github.com/cure53/DOMPurify/blob/master/test/fixtures/expect.js (someone modified the tests)

Maybe even the dist file to be sure. But for the majority of other files the tests might not make sense or am I mistaken? Or would it better to have a blacklist like `*.md`?

**Comment by cure53** [comment]
Oh, @tdeekens it seems this is already the case? 
So, how does this work right now? Sorry for stupid questions, am new to the whole Karma test thing.

**Comment by tdeekens** [comment]
The [karma configuration](https://github.com/cure53/DOMPurify/blob/master/test/karma.conf.js#L10) only includes and therefore only [watches](https://github.com/cure53/DOMPurify/blob/master/test/karma.conf.js#L10) a limited set of files. A change would trigger re-rerunning all tests which should also include files preprocessed with [webpack](https://github.com/cure53/DOMPurify/blob/master/test/karma.conf.js#L29). 

Still re-running all tests in our case is a lot of fun. I know that with mocha you can isolate tests with `describe.only` not sure if there is something like that with QUnit.  Furthermore, you can limit down specs run by karma but as we only have two massive specs with a lot of assertions through parameterization. Maybe split the `expect.js` up and componentize the tests or even DOMPurify to be able to run smaller sub-tests?

**Comment by cure53** [comment]
Got it, that way I think it's perfect for now :) Thx!
