### ISSUE TITLE
Endless loop of `DOMParser.parseFromString` when used with Trusted Types polyfill

### ISSUE THREAD

**Issue by orazioedoardo** [cure53/DOMPurify#1027]
### Background & Context

When trying to use DOMPurify in conjunction with the [trustedTypes polyfill](https://www.npmjs.com/package/trusted-types), the HTML is not sanitized but rather seems to run into an endless loop as if DOMPurify does not set its ["dompurify" policy](https://github.com/cure53/DOMPurify/pull/310). Not sure if it's a DOMPurify issue, or an issue with the polyfill, or if I'm using it wrong, sorry if this is the wrong place to ask.

#### Input

This is the sample JavaScript code which then I bundle with webpack.

```
import { trustedTypes, TrustedTypeConfig, TrustedTypesEnforcer } from "trusted-types";
import DOMPurify from "dompurify";

let trustedTypesObject;

if (window.trustedTypes && trustedTypes.createPolicy) {
    trustedTypesObject = window.trustedTypes;
} else {
    trustedTypesObject = trustedTypes;
    const config = new TrustedTypeConfig(false, true, ["default", "dompurify"], false);
    const enforcer = new TrustedTypesEnforcer(config);
    enforcer.install();
}

trustedTypesObject.createPolicy("default", {
    createHTML: (string, type) => {
        console.warn("Created a '" + type + "' object.");
        return DOMPurify.sanitize(string, { RETURN_TRUSTED_TYPE: false });
    },
});
```

#### Given output

Example output from Safari, caught in an endless loop of thousands of `DOMParser.parseFromString` sanitization instances. At some point it ends but I believe the browser is doing it. If I try it in Chrome, it never ends and hangs the tab.

![tt](https://github.com/user-attachments/assets/b4b39a8d-05ed-48bc-a17b-141c05b63568)

#### Expected output

Expected a TrustedHTML object.

**Comment by cure53** [comment]
Heya, thanks for filing - if this is our bug, we will happily be fixing it, but I think it's not. 

In case the issue only appears with the poly-fill in place, then I think their code might need fixing, not ours.

**Comment by orazioedoardo** [comment]
Wow thanks for the quick reply. I will post an issue on https://github.com/w3c/trusted-types and see what they think about this.

**Comment by cure53** [comment]
Cool, thanks :)
