### ISSUE TITLE
Small syntax enhancement to TMPLIT_EXPR

### ISSUE THREAD

**Issue by svdb99** [cure53/DOMPurify#1033]
> This issue proposes a small enhancement to the regexp in the `TMPLIT_EXPR` const.

### Background & Context

`const TMPLIT_EXPR = seal(/\${[\w\W]*}/gm);`

Projects that use XSLT can inline 3rd party libs before pushing out the response to the browser. While doing so they can perform code resolution/substitutions on ${} espressions. Unfortunately the `${[\w\W]*}` part can be misinterpreted as an expression even though it's in a regexp, and because it obviously doesn't resolve to anything during the transformation, it gets wiped out as a result and causes a syntax error when the browser gets it.
Result: `const TMPLIT_EXPR = seal(/\/gm);`

### Proposed workaround

The solution is extremely simple and doesn't change anything to how the regexp operates, and would improve compatibility with a wider range of mission critical projects build on "older" tech like XSLT.
All that is needed is to escape the first curly brace like so:
`const TMPLIT_EXPR = seal(/\$\{[\w\W]*}/gm);`

Would you like me to create a PR for this?

**Comment by cure53** [comment]
Heya, this looks good from my end, thanks - a PR is welcome :slightly_smiling_face:

**Comment by svdb99** [comment]
Hi,
Unfortunately my access is read-only, it seems. I can't push my scratch branch.

**Comment by cure53** [comment]
You can just create a PR, then it works as expected :)

**Comment by svdb99** [comment]
Had to remember how to do it in this non-enterprise version of Github. It's a bit different than how we use it. 😅

**Comment by cure53** [comment]
We need some changes to the PR, see failed tests.

**Comment by svdb99** [comment]
The Lint error wants to optimize the regexp by removing the escape character I added.
This "optimization" is precisely what caused the issue in the first place.

**Comment by cure53** [comment]
Oh, dang - somehow it indeed didn't make it into the dist files. Okay for you to wait for 3.2.3 for that?

**Comment by svdb99** [comment]
Yes, no pb, nothing's gonna happen until next week our side.

**Comment by svanden99** [comment]
Hi, 
Would you be able to tell me approximately when the next release is planned for?
Thanks!

**Comment by cure53** [comment]
Monday, the latest :)
