### ISSUE TITLE
HTML DOM inside ForeignObject in SVG subtree removed with version 3.2.2

### ISSUE THREAD

**Issue by alderg** [cure53/DOMPurify#1040]
### Background & Context

We are trying to upgrade from 3.1.5 to 3.2.2 in draw.io.

### Bug

We are seeing HTML DOM being removed inside foreignObjects in SVG subtrees nested in SVG in version 3.2.2 where as this was not removed with version 3.1.5.

#### Input

This is with [this draw.io file](https://app.diagrams.net/?page-id=RIgoEUiRlFwz6c4iCF_d#R%3Cmxfile%20pages%3D%222%22%3E%3Cdiagram%20name%3D%22Seite-1%22%20id%3D%22t8Uwp41vz3JLv-DJjWAi%22%3ErZNfa8MgFMU%2FjY%2BFqKHbXpv1z8tgLA9lT0PibRRMDNY2yT79TNW2boxuYxAI%2FnI813s9QbRohrVhnXjSHBQiGR8QfUSE4Jw%2BuNdERk9yjD2ojeQeZRdQyncIOyM9SA77wDyyWisruxRWum2hsgljxug%2Ble204gnoWA3JMSZQVkzBF9lWcis8vSd3F74BWYtYGc9Dww2L4mC8F4zr%2FgrRJSJzROjAEF2giaUPLYzW9qYsipuhADUNP53r6u8G594NtPafPNvtjq9I1meKvFR7%2FEqPb8%2BzUOjI1CGMfeN2aUQKR7fauDvzI7RjvBejDy2HydSVWfRCWig7Vk1fe5dEx4RtlFvh0wFP9mAsDN%2B2hn9yJ5%2B7W4NuwJrRrYPzjOS5N4%2BJD4HoL%2FHBMRPiKjrzwFhIbH22%2FtXEnTYM%2FXa%2BnPZGxILf1c9Nlx8%3D%3C%2Fdiagram%3E%3Cdiagram%20id%3D%22RIgoEUiRlFwz6c4iCF_d%22%20name%3D%22Seite-2%22%3EdZLBUoMwEIafJkdnIFHAYwut2tFTx%2Bk5JhGigcUQCvbpDQaaZqqn7H67f3azG0TyenzQtK1egAuFcMRHRAqEcXyXJfaYyLcjJMIOlFpyhyIP9vIkZuVCe8lFNzOHDIAysg0hg6YRzASMag1DmPYOigegpaUI2pjAnlElrtIOkpvK0Qynnj8KWVZL5Ti5d5E3yj5LDX3Dn%2BpzDZSuEU6%2BerDp604z7yCy8g6nhlrw2xve2jnh3GSvQ3sbH09k93y8KXYfh5W8UKeFq1rTpcX5OV1FOQwXiGwQyTVMssmqx1yoaWXhNrb%2FRM%2Fj0KIxfwis4e%2B2TvAvyOYH%3C%2Fdiagram%3E%3C%2Fmxfile%3E#%7B%22pageId%22%3A%22RIgoEUiRlFwz6c4iCF_d%22%7D) resulting in the following DOM (using page 1 as the background page for page 2 with page 1 having a foreignObject which is embedded in page 2 as a SVG subtree).

#### Given output

Left is the new output with the HTML DOM inside the foreignObject in the SVG subtree representing page 1 removed using version 3.2.2 and right is the previous output with the DOM not removed with version 3.1.5.

<img width="1637" alt="Screenshot 2024-11-30 at 09 38 30" src="https://github.com/user-attachments/assets/3172e0cd-0191-427d-86da-fc5294679b23">

#### Expected output

The HTML DOM inside the foreignObject in the SVG subtree representing page 1 should not be removed with version 3.2.2. to match the output of version 3.1.5.

**Comment by cure53** [comment]
Heya, thanks for filing this, we might have an easy fix:

```
DOMPurify.sanitize(
  '<svg><foreignObject><h1>HELLO</h1></foreignObject></svg>', 
  {
    ADD_TAGS: ['foreignObject'], 
    HTML_INTEGRATION_POINTS: {'foreignobject': true}
  }
); 
```

This should do the trick, no?

**Comment by alderg** [comment]
That works. Many thanks!
