### ISSUE TITLE
[feature] Is it possible to remove the version information in the DOMPurify license?

### ISSUE THREAD

**Issue by camelmasa** [cure53/DOMPurify#1042]
### Background & Context

The DOMPurify license includes the version information, so it may be targeted by bots that collect vulnerability information.
https://github.com/cure53/DOMPurify/blob/main/dist/purify.js#L1

### Feature

Remove `VERSION` in license_header and link this https://github.com/cure53/DOMPurify/blob/main/LICENSE.
https://github.com/cure53/DOMPurify/blob/main/src/license_header

I'll create a PR if possible.

**Comment by cure53** [comment]
Nah, if obscurity is your way to have a secure app then you are on the wrong track anyway.

**Comment by camelmasa** [comment]
Thanks for your advise
