### ISSUE TITLE
Problem with minified version and commit hook

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#105]
@tdeekens I think the minifier doesn't properly create the packed version upon commit. Is there anything we need trigger manually?

**Comment by tdeekens** [comment]
True. I am not getting them amended too. I fixed the issue and removed the `local-test` from the pre-commit hook cause it personally annoys me as tests run on CI and should be run by a responsible dev after changing things. Still, feel free to add it again if you want...

See pull request #106. Sorry about the issues.

**Comment by cure53** [comment]
Testa re looking goo so far. I will run again later when we have passed the request limit again.

**Comment by tdeekens** [comment]
Sweet so internal PRs and normal commits get testet against BrowserStack and PRs from forks don't. 

Check the minification with a test commit and reset hard after. It all works for me.

**Comment by cure53** [comment]
Okay, did that right now, CI is running...

**Comment by tdeekens** [comment]
Yeah something should have changed otherwise the minification will just yield the same output.

**Comment by cure53** [comment]
I did changes to `purify.js` and still no update to the `dist` version. Is it still broken?

Here's my change: https://github.com/cure53/DOMPurify/commit/86929b9ec421f941cddb132d5abd7e6340641c5a

**Comment by tdeekens** [comment]
Hm. So I e.g. change the version number to `0.7.1` in the `src/purify.js` git add and commit all the file. Then on my console I get 

```bash
# Ensuring ./dist directory exists...
# Minifying purify.js using Uglifyjs2...
# Amending minified assets to HEAD
```

my commit then contains changes to `src/purify.js`, `dist/purify.min.js` and `purify.min.js.map`.
I am a bit confused cause there is not much magic involved apart from the [package](https://github.com/observing/pre-commit) suggested by @fhemberger which I added as a devDependency. 

You can check if it works by hand by changing something commiting it and then running `sh scipts/minify.js && sh scripts/amend-minified.sh`.

**Comment by cure53** [comment]
Well, you could see that I did changes to the file and nothing arrived. 
Maybe there's something on my side that needs to be done/installed/changed?

**Comment by tdeekens** [comment]
Erm, nothing more than `npm install`. I just did a clean checkout ran `npm install`, changed the version to 0.7.1 in `src/purify.js` then ran `git add --all && git commit -m 'test'` the commit contained the minified version and source-map.

**Comment by cure53** [comment]
Oh. Why so complicated? Is this documented somewhere? I think we need a wiki page for that.

My understanding of a commit hook is, that things happen upon committing things. And not only upon doing entering some console commands.

**Comment by tdeekens** [comment]
No worries and `pssst` there're is so much more development magic we could add :hear_no_evil:. Still, I'll help taking care of that part and you focus on the security bits and pieces. :+1:.

Maybe I'll propose an updated readme some time after I looked at those of a couple of great projects.

**Comment by cure53** [comment]
Yeah I guess so :) Especially reviews might make sense at some point, noticed that feature in a bunch of other projects we work with.

My learning for today: A lot of magic happens here and I can test more things locally :)

```
  "scripts": {
    "build-demo": "node scripts/build-demo.js",
    "qunit": "node scripts/server.js",
    "jshint": "node node_modules/jshint/bin/jshint src/purify.js || true",
    "minify": "scripts/minify.sh",
    "amend-minified": "scripts/amend-minified.sh",
    "test": "npm run jshint && npm run-script ci-test",
    "ci-test": "[ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ] && ./node_modules/.bin/karma start test/karma.conf.js --single-run || false",
    "local-test": "npm run jshint;./node_modules/.bin/karma start test/karma.conf.js --browsers Firefox --single-run"
  },
```

Thanks!

**Comment by cure53** [comment]
I'll close this for now, this should work.

**Comment by cure53** [comment]
One note about this: Sadly, the commit hooks don’t get fired from EGit / JGit. So, note to self: Don't use Eclipse when committing changes to `purify.js`.
