### ISSUE TITLE
Unable to allow XML namespaced tags in SVG

### ISSUE THREAD

**Issue by Ampflower** [cure53/DOMPurify#1051]
### Background & Context

Namespaced tag names seem to be normally impossible to allow, including:

- By allowing its namespace (i.e. <http://www.inkscape.org/namespaces/inkscape>)
- Using the full namespace tag (i.e., `"sodipodi:namedview", "inkscape:path-effect"`)
- Using regex to allow the tag (i.e., `/inkscape\\:(path-effect)|sodipodi\\:(namedview)/`)

These tags are helpful for making an editor around SVGs by using the data to say:

 - display a checkerboard background
 - change the page background color
 - change the page border color
 
and otherwise retaining say Inkscape's editor information losslessly for further editing without losing any of the necessary metadata. This would also interfere with custom application-specific tags that the website may wish to inject into its XML for future use, should it pass through DOMPurifier in the future on reupload.

#### Input

Typescript config:
```ts
const purifyConfig: Config = {
	USE_PROFILES: { svg: true, svgFilters: true },
	PARSER_MEDIA_TYPE: "image/svg+xml",
	ADD_TAGS: [
		"body",
		"use",
		"path-effect",
		"inkscape:path-effect",

		"namedview",
		"sodipodi:namedview",
	],
	ALLOWED_NAMESPACES: [
		"http://www.w3.org/2000/svg",
		"http://www.inkscape.org/namespaces/inkscape",
		"http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd",
	],
	ADD_URI_SAFE_ATTR: ["inkscape:label"],
	ADD_ATTR: [
		"xmlns:svg",
		"xmlns:sodipodi",
		"xmlns:inkscape",

		"inkscape:label",
		"inkscape:groupmode",
		"inkscape:highlight-color",
		"inkscape:collect",
		"inkscape:menu",
		"inkscape:menu-tooltip",

		"inkscape:pagecheckerboard",

		"inkscape:transform-center-x",
		"inkscape:transform-center-y",
		"inkscape:path-effect",

		"inkscape:nodetypes",
		"inkscape:stockid",
		"inkscape:isstock",

		"sodipodi:type",
		"sodipodi:arc-type",
		"sodipodi:open",
		"sodipodi:start",
		"sodipodi:end",
		"sodipodi:cx",
		"sodipodi:cy",
		"sodipodi:rx",
		"sodipodi:ry",

		"sodipodi:nodetypes",
		"sodipodi:insensitive",

		"pagecolor",
		"bordercolor",
		"borderopacity",

		"sodipodi:pagecolor",
		"sodipodi:bordercolor",
		"sodipodi:borderopacity",

		"inkscape:showpageshadow",
		"inkscape:pageopacity",
		"inkscape:pagecheckerboard",
		"inkscape:deskcolor",
		"inkscape:document-units",
		"inkscape:zoom",
		"inkscape:cx",
		"inkscape:cy",
		"inkscape:current-layer",
	],
	CUSTOM_ELEMENT_HANDLING: {
		tagNameCheck: /inkscape:(path-effect)|sodipodi:(namedview)/,
	},
};
```

SVG+XML DOM given as is as a string:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg1"
   inkscape:version="1.4 (e7c3feb100, 2024-10-09)"
   sodipodi:docname="drawing.svg"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
  <sodipodi:namedview
     id="namedview1"
     pagecolor="#505050"
     bordercolor="#ffffff"
     borderopacity="1"
     inkscape:showpageshadow="0"
     inkscape:pageopacity="0"
     inkscape:pagecheckerboard="1"
     inkscape:deskcolor="#505050"
     inkscape:document-units="mm"
     inkscape:zoom="0.75455247"
     inkscape:cx="396.92402"
     inkscape:cy="561.25984"
     inkscape:window-width="1920"
     inkscape:window-height="1044"
     inkscape:window-x="1280"
     inkscape:window-y="0"
     inkscape:window-maximized="1"
     inkscape:current-layer="layer1" />
  <defs
     id="defs1" />
  <g
     inkscape:label="Layer 1"
     inkscape:groupmode="layer"
     id="layer1" />
</svg>
```

How DOMPurify is invoked:
```ts
export function purify(svg: string) {
	const value = DOMPurify.sanitize(svg, purifyConfig);
	console.debug("purify removed:", DOMPurify.removed, value);
	return value;
}
```

#### Given output

Captured via console.debug() in Firefox Dev Tools:
```svg
<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" id="svg1" version="1.1" viewBox="0 0 210 297" height="297mm" width="210mm">
  
  <defs id="defs1"></defs>
  <g id="layer1" inkscape:groupmode="layer" inkscape:label="Layer 1"></g>
</svg>
```

This is consistent in Ungoogled Chromium and Epiphany, suggesting a DOMPurify-specific issue.

sodipodi and inkscape namespaced elements are preserved when set in innerHTML as is, albeit not namespaced correctly by CSS behavior.

#### Expected output

```svg
<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape" id="svg1" version="1.1" viewBox="0 0 210 297" height="297mm" width="210mm">
  <sodipodi:namedview id="namedview1" pagecolor="#505050" bordercolor="#ffffff" borderopacity="1" inkscape:showpageshadow="0" inkscape:pageopacity="0" inkscape:pagecheckerboard="1" inkscape:deskcolor="#505050" inkscape:document-units="mm" inkscape:zoom="0.75455247" inkscape:cx="396.92402" inkscape:cy="561.25984" inkscape:current-layer="layer1"></sodipodi:namedview>
  <defs id="defs1"></defs>
  <g id="layer1" inkscape:groupmode="layer" inkscape:label="Layer 1"></g>
</svg>
```

#### Additional Notes:

`CUSTOM_ELEMENT_HANDLING` appears entirely ignored.

#### Probable solutions:

- Regex or `ADD_TAGS` to match the namespaced element as long as the namespace is valid to `ALLOWED_NAMESPACES`.
- Namespace-specific matching rules, to allow strictness or leniency of the xmlns name.

**Comment by cure53** [comment]
Heya, thanks for submitting. The problem is a complex one and frankly, related to a need that we don't really try to fulfill with DOMPurify. 

The issue here is that we do namespace checks to see if a certain child element is allowed to be a descendant of a specific parent element. Such as for example, whether a `<p>` element is allowed to be inside a specific kind of MathML element , or whether is only permitted as child of the respective integration points. 

The namespace check is critically important to protect our core goals, which is preventing XSS, so we cannot build any bypasses to that. So I am not 100% sure how we can fix this.

**Comment by cure53** [comment]
The problem is nested here:

```javascript
          if (element.namespaceURI === SVG_NAMESPACE) {
            // The only way to switch from HTML namespace to SVG
            // is via <svg>. If it happens via any other tag, then
            // it should be killed.
            if (parent.namespaceURI === HTML_NAMESPACE) {
              return tagName === 'svg';
            }            // The only way to switch from MathML to SVG is via`
            // svg if parent is either <annotation-xml> or MathML
            // text integration points.
            if (parent.namespaceURI === MATHML_NAMESPACE) {
              return tagName === 'svg' &&
              (
                parentTagName === 'annotation-xml' ||
                MATHML_TEXT_INTEGRATION_POINTS[parentTagName]
              );
            }            
            // We only allow elements that are defined in SVG
            // spec. All others are disallowed in SVG namespace.
            return Boolean(ALL_SVG_TAGS[tagName]);
          }
```
The final line does not manage to find the element among the ones that are known SVG element, and that is why it is being removed.

**Comment by Ampflower** [comment]
> Heya, thanks for submitting. The problem is a complex one and frankly, related to a need that we don't really try to fulfill with DOMPurify.

Fairs; I just happened to be building a tool that was built on top of the browser, and wanted to add a layer of defense on top of using a sandboxed iframe with a strict CSP, in case any browser didn't sandbox properly.

> The issue here is that we do namespace checks to see if a certain child element is allowed to be a descendant of a specific parent element. Such as for example, whether a `<p>` element is allowed to be inside a specific kind of MathML element , or whether is only permitted as child of the respective integration points.
> 
> The namespace check is critically important to protect our core goals, which is preventing XSS, so we cannot build any bypasses to that. So I am not 100% sure how we can fix this.

Yeah, that's a tricky one when considering general purpose doesn't usually expect this. It's likely too unusual of a usecase that I did consider extending it just for the project at least, if allowing an exception generally isn't happening.


> > `CUSTOM_ELEMENT_HANDLING` appears entirely ignored.
> 
> That is because it is not a custom HTML element that is being handled here 🙂

Makes sense, thought it was at least worth a try.

**Comment by cure53** [comment]
My guess is that the best way go handle this is using a hook. Ideally the `uponSanitizeElement` hook, because then you can check manually if all is fine, temporarily handle the name-spacing issue, and then write the tag back once everything else is done.

Also possible would be to locally override the SVG elements in the tags list and add those you want to permit as well. 

I fear that if we touch core functionality to fix this, we might create a security risk, hence so hesitant :sweat_smile:

**Comment by Ampflower** [comment]
I'd say for `uponSanitizeElement`, possible to forcefully rename the tag to `g` (a valid SVG element) then stuff the real tag name in `internal:name`, so it'd still exist on the DOM; tho that doesn't quite consider sanitizing the element's inner XML if it has any; tho I could just manually clear on the fly if sanitize can tolerate a surprise significant tree mutation. Or stuff it into a temporary list, although I would prefer to avoid making more of a global state machine.

Or, yeah, locally modifying the SVG allow list could suffice too.

> I fear that if we touch core functionality to fix this, we might create a security risk, hence so hesitant 😅

Understandable; I'd try to avoid making significant changes too with the risk involved lol

**Comment by Ampflower** [comment]
Does seem to work well; am seeing it gets included by the `namedview1` popping up from the unaware UI; I suppose now is just flipping it back on post, then letting the metadata exist as is.

Would you like the issue to remain open to see about implementing a friendlier way, or at least add this as a potential solution to the demos?

**Comment by cure53** [comment]
I would not say no to a PR against the demo folder if you have a working solution you would want to share :slightly_smiling_face: :pray: 

The ticket I would rather close, unless you any actionable items for us at this point.
