### ISSUE TITLE
Using exported name 'DOMPurify' as identifier for default import

### ISSUE THREAD

**Issue by ScorpAL** [cure53/DOMPurify#1052]
> This issue proposes a [bug, feature] which...

After upgrading from DOMPurify 3.2.0 to DOMPurify 3.2.3
`eslint` starts warn with:
` warning  Using exported name 'DOMPurify' as identifier for default import  import/no-named-as-default`

usage:
```js
import DOMPurify from 'dompurify';
//     ---------
//     ^
//     Using exported name 'DOMPurify' as identifier for default import.eslint[import/no-named-as-default](https://github.com/import-js/eslint-plugin-import/blob/v2.31.0/docs/rules/no-named-as-default.md)

export const purify = (text: string): string => {
    return DOMPurify.sanitize(text) || '';
};

```

**Comment by cure53** [comment]
Unclear what do to here, please advise :D

**Comment by cure53** [comment]
Closing this as it's unclear what needs to be done, feel free to reopen.

**Comment by Azbesciak** [comment]
@cure53 we also do not know what to do. It looks like typescript definition is broken.
When trying to compile the app we got an error like below
```
Error: ... error TS1259: Module '"node_modules/dompurify/dist/purify.cjs"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

3 import DOMPurify from 'dompurify';
         ~~~~~~~~~

  node_modules/dompurify/dist/purify.cjs.d.ts:437:1
    437 export = _default;
        ~~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```

So ok - we can understand the error, but not really be eager to change that.
I thought we are there for a high quality software, right? Not for a workarounds.

**Comment by cure53** [comment]
You can save those snarky comments for other occasions to be honest. 

As mentioned, if you have an idea for a fix, then we are open to look into it and implement it if it works and doesn't break anything else. Our job is however **not** to make sure that things work for _you_. But for as many people as possible. 

So, again, if you know how to fix this, we will do our best to make the fix work and deploy with the next release, but based on what we have for now, there is nothing we can do.

**Comment by cure53** [comment]
That being said, from what we can see, this is nothing we can or should fix. But happy to be convinced otherwise.

**Comment by Azbesciak** [comment]
@cure53 it was not snarky, it was just honest. If you close some ticket - as every other (I was very confused by no opened ticket) - without any further consideration...
Also, if you introduce a breaking change on a patch version...?
Below is a change in a `package.json` between `3.2.0` and `3.2.3` - versions mentioned by @ScorpAL - maybe that introduced the break?
![image](https://github.com/user-attachments/assets/d6c0fa51-c49b-4bc4-80da-11d2eb256ce6)

**Comment by steveschmitt** [comment]
I ended up doing this.  No compile problems, but not pretty.  Maybe there is a better way?

```ts
import * as dompurify from 'dompurify';
const purifier = dompurify['default'] as dompurify.DOMPurify;

export const purify = (s: string, cfg?: dompurify.Config) => {
  return purifier.sanitize(s, cfg) as string;
}
```

**Comment by jhrr** [comment]
This works doesn't it?

`import { default as DOMPurify } from 'dompurify';`

**Comment by unrevised6419** [comment]
Enabling `esModuleInterop` in your `tsconfig.json` might fix it.

**Comment by Anubarak** [comment]
> This works doesn't it?
> 
> `import { default as DOMPurify } from 'dompurify';`

Not unless I enable `allowSyntheticDefaultImports` in my TS config.

@cure53 As for what needs to be done: it's actually easy. Instead of exporting the default value
https://github.com/cure53/DOMPurify/blob/28a29dbd52d65dba7dae8d17377d4f8302f362e4/src/purify.ts#L1731

export it via
```ts
export function createDOMPurify(window: WindowLike = getGlobal()): DOMPurify {
````

So we can 
```ts
import {createDOMPurify} from "dompurify";
````
