### ISSUE TITLE
Chrome complains about an unsafe-eval

### ISSUE THREAD

**Issue by oparoz** [cure53/DOMPurify#107]
> Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution.

purify.js:309 ` doc = new DOMParser().parseFromString(dirty, "text/html");`

parseFromString is underlined. 

Bug in Chrome?

**Comment by cure53** [comment]
Ouch, that sounds like a Chrome bug indeed! As far as I can see, this *should* not be restricted. We'll come up with a patch... thanks for the report!

**Comment by cure53** [comment]
Hmm, I tried to reproduce the issue but didn't manage yet. I tested on:

* Version 47.0.2521.0 canary
* Version 45.0.2454.101 (64-bit)

What version did you see the effect on? Do you have a test-case somewhere we can have a look at? On the versions I checked, all worked fine.

**Comment by oparoz** [comment]
I will try to reproduce. That was happening while I was trying to parse the dirty SVG from http://svg.enshrined.co.uk/ which I was retrieving via an XMLHttpRequest.
I can never show the result in an IMG tag, but that's for another issue.

Chromium 44.0.2403.125

**Comment by cure53** [comment]
One Chrome 44 I don't see any problems either (tested via Browserstack). 

A test-case for reproduction would help a lot :)

**Comment by oparoz** [comment]
OK, so here is some info.

The SVG from http://svg.enshrined.co.uk/ is sent to the browser base64 encoded and I do this:

`var pureSvg = DOMPurify.sanitize(window.atob(imageData));`

No problem with other SVGs, but it chokes on this one.

**Comment by oparoz** [comment]
Full code is here:
https://github.com/owncloud/gallery/blob/purify-SVGs/js/thumbnail.js#L141

**Comment by oparoz** [comment]
https://github.com/cure53/DOMPurify/commit/86929b9ec421f941cddb132d5abd7e6340641c5a allows me to see the thumbnail, despite the error being shown in Chrome

**Comment by cure53** [comment]
Then I think, the CSP warning comes from something else. Likely from the SVG - and not DOMPurify. Can you try to isolate what it is? Might be a browser bug indeed.

**Comment by oparoz** [comment]
Found the problem:

```
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg onload="javascript:alert(65)" version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="600px" height="600px" viewBox="0 0 600 600" enable-background="new 0 0 600 600" xml:space="preserve">
</svg>
```

Chrome chokes on the `onload`

**Comment by cure53** [comment]
Ah, I can see the issue as well in my testcase now. But the sanitization still works, so it seems to only be a false alert in the Chrome console.correct?

**Comment by cure53** [comment]
@oparoz I think we can close this ticket for now, correct?

**Comment by oparoz** [comment]
I think so, yes. The only thing I would be worried about is if something still gets executed before being parsed. It could be a problem with a loose CSP.
But you're the expert, so if you feel it's a bug in Chrome, then let's close this.

**Comment by cure53** [comment]
I am surprised that the warning is issued at all. Can we just in case set up a test-case where the problem is isolated nicely? Meaning, with all the necessary steps and purification? I would try to have a closer look then and see where exactly it happens.

**Comment by oparoz** [comment]
Sample like this?

```
<svg onload="javascript:alert('Booh!')"></svg>
```

**Comment by cure53** [comment]
Ah, got a working clean repro now:

```
<?php
header('Content-Security-Policy: default-src \'self\' ajax.googleapis.com');
?>
<script src="test.js"></script>
```

```
new DOMParser().parseFromString('<svg onload="javascript:alert(1)"></svg>', 'text/html')
```

I am not pretty sure we are fine here - and there's no risk attached to it.

**Comment by oparoz** [comment]
From https://developer.chrome.com/extensions/contentSecurityPolicy

> Inline JavaScript will not be executed. This restriction bans both inline `<script>` blocks and inline event handlers (e.g. `<button onclick="...">`).

> Up until Chrome 45, there was no mechanism for relaxing the restriction against executing inline JavaScript. In particular, setting a script policy that includes 'unsafe-inline' will have no effect.


So I guess it's the standard behaviour and the handler is blocked.

The thing I don't understand is why this is triggered while reading the string. That content should not be executed.

**Comment by cure53** [comment]
> The thing I don't understand is why this is triggered while reading the string. That content should not be executed. 

Yep, me neither. I think that is a bug indeed. But  cannot see a security risk here. Just a overly eager warning.
