### ISSUE TITLE
Browser tests deliver faulty results, missing helpful info

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#109]
@tdeekens The browser tests in their current form are misleading and deliver false results. 
The problems I see right now are:

 - [x] Even if the tests fail, the build is green. That is not intended. When the tests fail, the build should be red.
 - [ ] In earlier versions we had an escaped version (copy&paste-ready including all the \r\n etc.) of the actual result. That was very convenient for fixes and seems gone now, can we bring it back? 
 - [ ] Tests can fail for different browsers at the same time, but only one result is shown

We had a great state some revisions ago, would it be possible to bring that back? I am currently testing if we can add the `xlink:href` attribute (we have to to produce valid SVG strings) and it's really hard to work with the current test suite.

**Comment by cure53** [comment]
Here is a sample: 

https://travis-ci.org/cure53/DOMPurify/builds/82621372

Right now, we cannot see in any way what is going wrong. It's impossible to work on the tests without guessing what broke :-/ 

The ideal output would be: 

a) What browser does the test fail on?
b) Which one(s) of the expected results are satisfied, which one(s) are not?

**Comment by tdeekens** [comment]
### Tests can fail for different browsers at the same time, but only one result is shown

As far as I can tell there's a lot of "indirection" in the runner basically running parametrized against multiple browsers simultaneously. I guess there is a cost of automation of not getting very detailed failure information. If I run tests locally with `npm run-script local-test` the library seems able to report back more eloquently:

```bash
✖ sanitize() should not hang on MSIE when hook changes textContent
      Chrome 45.0.2454 (Mac OS X 10.11.0)
    Expected: false
    Actual: true
at Object.<anonymous> (/Users/tdeekens/Development/GitHub/DOMPurify/test/purify.spec.js:66:15)
        at Object.Test.run (/Users/tdeekens/Development/GitHub/DOMPurify/node_modules/qunitjs/qunit/qunit.js:810:28)
        at /Users/tdeekens/Development/GitHub/DOMPurify/node_modules/qunitjs/qunit/qunit.js:942:11
        at process (/Users/tdeekens/Development/GitHub/DOMPurify/node_modules/qunitjs/qunit/qunit.js:624:24)
        at begin (/Users/tdeekens/Development/GitHub/DOMPurify/node_modules/qunitjs/qunit/qunit.js:606:2)
        at /Users/tdeekens/Development/GitHub/DOMPurify/node_modules/qunitjs/qunit/qunit.js:666:4
```
hence the less detailed output either comes from parametrization or the the browserstack runner.

Still on TravisCI with parametrization we get the output of 
```bash
 ✖ Sanitization test                                                                                     
      Firefox 12.0.0 (Windows 7 0.0.0)
      Chrome 22.0.1229 (Windows 8 0.0.0)
      Opera 31.0.1889 (Windows 8.1 0.0.0)
      Safari 8.0.8 (Mac OS X 10.10.5)
      Chrome 44.0.2403 (Mac OS X 10.9.5)
      Firefox 40.0.0 (Mac OS X 10.10.0)
    Payload: <div id="86"><body oninput=alert(86)><input autofocus>//["'`-->]]>]</div><div id="87"><svg xmlns="http://www.w3.org/2000/svg">
```  
lets me assume that this test broke in all the browers listed below even if the previously the output was only `✖ Sanitization test`. Furthermore, isn't it the output you "demanded" with a) and b).

## Even if the tests fail, the build is green. That is not intended. When the tests fail, the build should be red

Is an issue with TravisCI not being able to run on pull requests with encrypted data. I changed behaviour in #110. Yet this makes pull-requests fail (which indeed is a more honest thing to do) as we can not ci-test them caused by having the encrypted data in the `travis.yml`.

## In earlier versions we had an escaped version (copy&paste-ready including all the \r\n etc.) of the actual result.

Are you talking about test output in case of failure?

Sorry for the inconvenience...

**Comment by cure53** [comment]
> Are you talking about test output in case of failure?

Yep! Some days ago, we would see an escaped version of the actual value - that I could check and right away copy into the fixtures. That was awesome - not I have to do all the \r\n myself again which is extremely error-prone and time intense.

> Yet this makes pull-requests fail

Yeah, that is okay with me. I don't think CI on PR has that big of a prio.

I'll check in more detail tonight, thanks so far!

**Comment by tdeekens** [comment]
So `even if the tests fail build is green` is fixed now. The other two are both about testing output. I am confused cause versions of libraries involved shouldn't have changed much. Do you have a link to a TravisCI build giving the output helping you most.

**Comment by cure53** [comment]
Yeap, this one for example:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/81010861/log.txt

```
	Payload: <div id="38"><comment><img src="</comment><img src=x onerror=alert(38)//">//["'`-->]]>]</div><div id="39"><!-- up to Opera 11.52, FF 3.6.28 -->
	Expected: <div id="38"><img src="&lt;/comment&gt;&lt;img src=x onerror=alert(38)//">//["'`--&gt;]]&gt;]</div><div id="39"></div>,<div id="38"><img src="</comment><img src=x onerror=alert(38)//">//["'`--&gt;]]&gt;]</div><div id="39"></div>
	Actual: <div id="38"><img src="%3C/comment%3E%3Cimg%20src=x%20onerror=alert%2838%29//">//["'`--&gt;]]&gt;]</div><div id="39"></div>
	("<div id=\"38\"><img src=\"%3C/comment%3E%3Cimg%20src=x%20onerror=alert%2838%29//\">//[\"'`--&gt;]]&gt;]</div><div id=\"39\"></div>",[object Array],"Payload: <div id=\"38\"><comment><img src=\"</comment><img src=x onerror=alert(38)//\">//[\"'`-->]]>]</div><div id=\"39\"><!-- up to Opera 11.52, FF 3.6.28 -->")@/home/travis/build/cure53/DOMPurify/test/purify.spec.js:60
	([object Object],[object Object])@/home/travis/build/cure53/DOMPurify/test/purify.spec.js:70
	([object Object])@/home/travis/build/cure53/DOMPurify/node_modules/qunit-parameterize/qunit-parameterize.js:15
	()@/home/travis/build/cure53/DOMPurify/node_modules/qunitjs/qunit/qunit.js:810
	()@/home/travis/build/cure53/DOMPurify/node_modules/qunitjs/qunit/qunit.js:942
	process(true)@/home/travis/build/cure53/DOMPurify/node_modules/qunitjs/qunit/qunit.js:624
	begin()@/home/travis/build/cure53/DOMPurify/node_modules/qunitjs/qunit/qunit.js:606
	(-5)@/home/travis/build/cure53/DOMPurify/node_modules/qunitjs/qunit/qunit.js:666
```

The helpful line:
```
("<div id=\"38\"><img src=\"%3C/comment%3E%3Cimg%20src=x%20onerror=alert%2838%29//\">//[\"'`--&gt;]]&gt;]</div><div id=\"39\"></div>",[object Array],"Payload:
```

**Comment by tdeekens** [comment]
I just checked the dependencies and the versions npm revolves them too and they haven't changed. I am a bit fuzzed. Maybe it's how the sets are setup. Hm...

**Comment by cure53** [comment]
Current status:

https://travis-ci.org/cure53/DOMPurify/builds/82812584

```
SUMMARY:
✔ 7167 tests completed
✖ 17 tests failed
```

Doesn't say which ones though :)

**Comment by tdeekens** [comment]
Arr, what a pitty. I am unsure if it's karma sorta aggregating the output when running multiple browsers in the log or TravisCI just being quiet (even though the raw log does not contain more information for the build).

I'll add something so you can run the ci-tests locally from your machine before pushing cause these "attempt"-commits just get me exhausted after a while.

Status, when I run BrowserStack locally I get something like

```bash
DOMPurify src 
    ✖ Sanitization test[SVG]
      Firefox 40.0.0 (Mac OS X 10.10.0)
    Payload: <div id="137"><svg>
    <a xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="?">
    <circle r="400"></circle>
    <animate attributeName="xlink:href" begin="0" from="javascript:alert(137)" to="&" />
    </a>//["'`-->]]>]</div>
    Expected: <div id="137"><svg>
    <a xlink:href="?">
    <circle r="400"></circle>

    </a>//["'`--&gt;]]&gt;]</svg></div>,<div id="137"><svg xmlns="http://www.w3.org/2000/svg">
    <a xmlns:NS1="" NS1:xlink:href="?">
    <circle r="400" />

    </a>//["'`--&gt;]]&gt;]</svg></svg></div>,<div id="137"><svg xmlns="http://www.w3.org/2000/svg">
    <a xlink:href="?">
    <circle r="400" />

    </a>//["'`--&gt;]]&gt;]</svg></svg></div>
    Actual: <div id="137"><svg>
    <a xlink:href="?" xmlns:xlink="http://www.w3.org/1999/xlink">
    <circle r="400"></circle>

    </a>//["'`--&gt;]]&gt;]</svg></div>
    QUnit.assert.contains@/Users/tdeekens/Development/GitHub/DOMPurify/test/config/setup.js:53:4
    module.exports/<@/Users/tdeekens/Development/GitHub/DOMPurify/test/purify.spec.js:68:10
    .cases/createTest/<@/Users/tdeekens/Development/GitHub/DOMPurify/node_modules/qunit-parameterize/qunit-parameterize.js:15:31
```

which is what you're after I guess.

**Comment by tdeekens** [comment]
Alrighty. The magic #111 adds the ability to run `npm run-script ci-test` which runs all Karma tests against BrowserStack from your machine. I guess that's the workflow you were referring to before. If those pass TravisCI will also pass and the `travis-ci` entry in the `package.json` will take care of that. Furthermore, increased timeouts should give you less trouble in general.

Still, I am mildly confused why we get the detailed test results when running locally against BrowserStack but TravisCI not printing as much. As a hint: feel free to remove a browser from the karma conf to narrow failures down and speed up the testing...

**Comment by cure53** [comment]
In the online version, I still cannot see what actually fails. Or is the info hidden somewhere? If not, then I have no (feasible) possibility to fix the tests right now:

https://travis-ci.org/cure53/DOMPurify/builds/82873712

**Comment by tdeekens** [comment]
Si, that's what I meant but I don't have much influence on that at least I don't know how. Still, as mentioned run them locally from your machine with `npm run-script ci-test` and you should see detailed failure information as you did previously. That way you should be able to verify that CI runs green before committing what is what you'd usually want.

**Comment by cure53** [comment]
Fair enough, will try that later today! (at the AP right now) Thanks :)

**Comment by cure53** [comment]
So, the script doesn't find the credentials for BrowserStack yet. Is it possible to fix that? We have them in the config so it should be - just not sure how.

**Comment by tdeekens** [comment]
It's just as before: you need to export them. We discussed the same in some previous issue. Just

```bash
export BS_USERNAME=xxx
export BS_ACCESSKEY=xxx
```

and you'll get it running - it doesn't have anything to do with the `travis.yml`.

**Comment by cure53** [comment]
Okay, let me check.

**Comment by cure53** [comment]
This is still pretty much unusable. The tests are running fine locally but as soon as the HTML in the fixtures tries to load external resources, the performance goes down *dramatically*. Running the tests now takes more than twenty minutes and then eventually stall. Still waiting for results to show...

**Comment by cure53** [comment]
Okay, and no results about what tests failed and why comes out once it's finally done. This is completely useless in the current state and I cannot fix the tests without running those browsers locally.

We had a very useful and workable state before the output was "optimized". Can we roll back to that?

**Comment by tdeekens** [comment]
Ai, got you. I'll trigger the tests now see how they go then verify if speed is impacted by the karma reporter. Furthermore, I'll try to find a way for karma maybe not hitting 404 on all those blind requests.

**Comment by tdeekens** [comment]
...obviously your right: the `karma-mocha-reporter` makes the output slow locally but not with TravisCI. I never had that problem. Well the #112 reverts back to the progress reporter which speeds up things and is what we had previously. Hope makes you like the setup again :wink:.

Further more just running `./node_modules/.bin/karma start test/karma.conf.js --single-run --browsers bs_win81_ie_11` (instead of `npm run-script ci-test`) or any "BrowserStack" browser might for one save you budget on their side and speed you up debugging things one by one.

**Comment by tdeekens** [comment]
Can you stop merging pull-requests before I comment on them :laughing:.

**Comment by cure53** [comment]
Okay :) I will fix the tests tomorrow first thing and then go for 0.7.1. Then we should be in the green again.

**Comment by cure53** [comment]
All tests are green again, the current way of doing it works well. Thanks! I will prepare 0.7.1 now.

**Comment by cure53** [comment]
Just FTR, I have been working with the tests a lot today - and they are really useful the way they are! Thanks again :)

**Comment by tdeekens** [comment]
Yay. That's nice to hear!
