### ISSUE TITLE
Travis CI log too big

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#113]
@tdeekens I just saw, that in its current state, the CI generates too much over an overhead log-wise. The logs are getting to big to be useful. I would say we should have them be the same as the local logs - would that work?

Example:
```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).

The build has been terminated.
```
https://s3.amazonaws.com/archive.travis-ci.org/jobs/83095653/log.txt

**Comment by tdeekens** [comment]
I'll look into it. At least there is no configuration intending on differentiating for local and TravisCI logs. Maybe there is a difference in how much actually gets outputed from the logs' stream which we can somehow control.

**Comment by cure53** [comment]
Thanks, right now the builds always fail, seemingly because of the log volume. This kinda keeps us from releasing.

**Comment by tdeekens** [comment]
...I am working as fast as a can :racehorse:. See some more information given in #114. I hope this does the trick and solves our problems.

**Comment by cure53** [comment]
No pressure - just saying :D We don't have to release very soon - just right now we cannot.

**Comment by tdeekens** [comment]
Haha, no worries I really enjoy working on this right now and pressure I can handle (I think). :fuel pump:.

**Comment by cure53** [comment]
Green :D

**Comment by cure53** [comment]
Sweet, thanks - I will now wait 3hrs to not stress our request limit too much and then go for 0.7.1.

**Comment by tdeekens** [comment]
...it's so beautiful!
