### ISSUE TITLE
gradientUnits & gradientTransform removed from SVG

### ISSUE THREAD

**Issue by oparoz** [cure53/DOMPurify#118]
```
<radialGradient
       cx="77.703499"
       cy="2006.7791"
       r="25.94915"
       fx="77.703499"
       fy="2006.7791"
       id="radialGradient654"
       xlink:href="#linearGradient649"
       gradientUnits="userSpaceOnUse"
       gradientTransform="matrix(3.005688,0,0,0.332703,115.0647,295.6275)" />
```

becomes

```
 <radialGradient xlink:href="#linearGradient649" id="radialGradient654" r="25.94915" cy="2006.7791" cx="77.703499"></radialGradient>
```

Why is there so much info removed from that tag?

**Comment by cure53** [comment]
No specific reason. We should add those missing attributes.

So, we are talking about

 * `fx`
 * `fy`
 * `gradientUnits`
 * `gradientTransform`

Correct?

Btw, these issues of yours are extremely helpful! Only a few people sanitize SVGs - and we're super happy about anyone reporting stuff like that! Please keep em coming :)

**Comment by oparoz** [comment]
Ah, you need to manually add all of them... that might explain why some SVGs can't be rendered after parsing.
So, yes, the 4 you've mentioned are missing from the parsed version.

I'm using the parser for the Gallery app in ownCloud and I can immediately see when a standard SVG cannot be rendered, but it's tricky to try and figure out why as I don't have a deep understanding of the syntax.

**Comment by cure53** [comment]
@oparoz That problem should be fixed now, can you try if it's working as indented for you?

**Comment by cure53** [comment]
Okay, just tested - the output is now:

```svg
<radialgradient gradienttransform="matrix(3.005688,0,0,0.332703,115.0647,295.6275)" gradientunits="userSpaceOnUse" xlink:href="#linearGradient649" id="radialGradient654" fy="2006.7791" fx="77.703499" r="25.94915" cy="2006.7791" cx="77.703499"></radialgradient>
```

Does that work for you?

**Comment by oparoz** [comment]
The one SVG I was testing and which had lost its gradients now shows up with gradients, so I'd say this is fixed :+1:
