### ISSUE TITLE
Stripping out < > symbol from valid text

### ISSUE THREAD

**Issue by satishbodke** [cure53/DOMPurify#125]
I have been validating input text on this link - https://cure53.de/purify
This is sample page where we can test out different inputs, So if I give input text as "Harry wants to say this : x<y and y<0" then I get clean html as - "Harry wants to say this : x"

See sanitize() method stripped out everything after X

Is this known issue or it can be addressed by doing certain configuration?

**Comment by cure53** [comment]
That is actually expected behavior. For the browser, <y becomes an actual HTML element and thus gets stripped. I'd recommend to either say `x < 0` or simply encode those characters.

**Comment by cure53** [comment]
@satishbodke What's your thoughts on this?

**Comment by satishbodke** [comment]
Immediate solution that I see is to adding white space before and after to < >, but this looks to be tricky, as I'll first validating input text against my white list before calling sanitize method of DOMPurify, anything outside the white list will have additional space so that nothing will be stripped out. White list would be set of html tags.

But this approach results in writing additional functions with regex that iterate through all contents before control passes to DOMPurify

I was expecting that framework would allow me to hookup few things to handle such custom sanitization.

**Comment by cure53** [comment]
@satishbodke And it does :) You can easily use a hook to do so. I would recommend the `uponSanitizeElement` or `beforeSanitizeElements` hook. It does exactly what you need to allow content containing these sequences you mention.

Example: https://github.com/cure53/DOMPurify/blob/master/demos/hooks-demo.html

**Comment by cure53** [comment]
@satishbodke Did the proposed solution work for you? If so, we can close the ticket.

**Comment by satishbodke** [comment]
Sure, we should close this ticket, I yet to implement this solution but your response makes sense to me. I will reopen the ticket if I need additional details. Thanks!!
