### ISSUE TITLE
Fix for IE<=8 breaks IE9

### ISSUE THREAD

**Issue by styu** [cure53/DOMPurify#127]
I'm trying to upgrade from 0.6.5 to 0.7.2, and I notice that the fallback for IE9 no longer works. I've traced it back to this commit: https://github.com/cure53/DOMPurify/commit/1ca51dc5e252c2e044d0b2956590152a62bb98ef
It turns out typeof window.toStaticHTML returns "function" in IE9, but from the commit message it sounds like it returns "object" in IE8? This is preventing us from upgrading to the latest version :(

**Comment by cure53** [comment]
This is a very good catch, thanks! We'll fix this immediately.

**Comment by cure53** [comment]
Please check if this is working for you. 

If so, and the tests will be all green (still running) you should be able to work with the master branch. We'll release 0.7.3 early next week.

**Comment by cure53** [comment]
@styu Tests are green! I think we're good to go. Please let me know if the fix works for you and we will close the ticket.

**Comment by styu** [comment]
Yes it works! Thanks so much!

**Comment by cure53** [comment]
Phew - good :)
