### ISSUE TITLE
src attributes that start with "data:" get stripped out for audio and source tags

### ISSUE THREAD

**Issue by styu** [cure53/DOMPurify#131]
I noticed that you whitelist these src attributes for images - would it be possible to do so for audio and source tags as well?

**Comment by cure53** [comment]
Yep, that should be possible. I don't see any risks connected to that right now - and the change would be minimal. Mind sending a PR for review?

**Comment by styu** [comment]
will do!

**Comment by cure53** [comment]
Thx!

**Comment by cure53** [comment]
I'll prettify and add a test case tomorrow.

**Comment by cure53** [comment]
Build is green, tests all passing, I think we are done here :)
