### ISSUE TITLE
work with new nodejs merged with io?

### ISSUE THREAD

**Issue by pixelpaulaus** [cure53/DOMPurify#133]
will this work with the new nodejs that has been merged with iojs?

i just tried but keep getting "DOMPurify.sanitize is not a function"

**Comment by cure53** [comment]
I don't know that :) Best ask @fhemberger or @Joris-van-der-Wel.

**Comment by Joris-van-der-Wel** [comment]
DOMPurify needs a DOM, which node does not have. This library should work with jsdom, see #60
