### ISSUE TITLE
Overstripping of "javascript:" in safe attributes

### ISSUE THREAD

**Issue by timmc** [cure53/DOMPurify#135]
In the following safe HTML, the `title` attribute is removed by DOMPurify:

```html
<span title="javascript: the final frontier">hover me</span>
```

**Comment by cure53** [comment]
We remove protocol handler-like constructs from any attribute. But I think you can easily fix that with a hook and white-list the ones you deem to be safe.

Sounds okay?

**Comment by cure53** [comment]
Another option would be to specify a map of safe attributes that we check against before testing for potentially dangerous URL handlers. 

From what I can see, those safe and reasonable (e.g. `javascript:` for `color` would not be reasonable) attributes would be the following:

```
'class','for','id','label','name','pattern'
,'placeholder','summary','title','value'
``` 

Is there anything missing in your opinion/use case?

**Comment by timmc** [comment]
I don't think a hook is right here -- it's very unexpected behavior with the vanilla DOMPurify, and I don't see why it couldn't be handled correctly by default.

I like the idea of the URL-safe attr list. Those attrs look good, although I'd also add `'alt', `'cite'` from just the beginning of the attr list. I haven't looked at the rest of the list, but there are probably other items missing.

**Comment by cure53** [comment]
I agree with you. Will propose a commit for review soon. While `alt` should be safe, `cite` might not as it is supposed to accept URLs - leaving that one out.

**Comment by cure53** [comment]
Alright, we have a map for safe attributes now:

```javascript
    /* Attributes safe for values like "javascript:" */
    var URI_SAFE_ATTRIBUTES = _addToSet({}, [
        'alt','class','for','id','label','name','pattern','placeholder',
        'summary','title','value'
    ]);
```

This is being checked against when handling attributes:

```javascript
                (
                 !IS_SCRIPT_OR_DATA.test(value.replace(ATTR_WHITESPACE,'')) ||
                 /* Keep image data URIs alive if src is allowed */
                 (lcName === 'src' && value.indexOf('data:') === 0 &&
                  (DATA_URI_TAGS[currentNode.nodeName.toLowerCase()])) ||
                 /* Keep URI-like values for safe attributes */
                 (URI_SAFE_ATTRIBUTES[lcName])
                )
```

Does that fix the issue for you?

**Comment by cure53** [comment]
Builds are green.

**Comment by timmc** [comment]
Oops, yes, I was confusing it with the `cite` element -- I'm rusty on the lesser-used elements, which is part of why I don't feel comfortable saying the proposed list is complete myself!

I think that fixes it, although that list might need to expand in the future.

You might be interested to see the approach I took a number of years ago for the same problem, using a map of attributes to validators, which I think was a bit more flexible: http://lab.brainonfire.net/markup-sanitizer/demo.html (you'll have to view source, I never did package the demo up as a library...)

**Comment by cure53** [comment]
@timmc Cool, yeah - I expect the list to grow as well, feel free to PR! Once we have a good feeling about the completeness, we will go 0.7.4 I guess :)
