### ISSUE TITLE
[QUESTION] Unsupported browsers?

### ISSUE THREAD

**Issue by willdavidow** [cure53/DOMPurify#142]
Can you verify that this plugin won't work **at all** in IE 8 and 9, or is it just that your tests only cover IE10 (and up)? 

I'm working on a project where the browser requirements (unfortunately) still cover IE8/9, and I'd like to be able to use DOMPurify to sanitize our user-inputted HTML, but also need to verify that we'll have coverage in those cases.

Thanks!

**Comment by filedescriptor** [comment]
>
DOMPurify is written in JavaScript and works in all modern browsers (Safari, Opera (15+), Internet Explorer (10+), Edge, Firefox and Chrome - as well as almost anything else using Blink or WebKit). It doesn't break on IE6 or other legacy browsers. It simply does nothing there

The description states that it does nothing on legacy browsers. That being said, internally DOMPurify will fallback to use [toStaticHTML](https://msdn.microsoft.com/en-us/library/cc848922(v=vs.85).aspx) which is supported in IE 8 & 9. But then DOMPurify cannot guarantee the result.

**Comment by willdavidow** [comment]
Thanks! I had a feeling this was the case, and I just set up a quick test to verify that things work in IE8/9 and for my project needs everything seems to work just fine!

**Comment by cure53** [comment]
Thanks @filedescriptor :)
