### ISSUE TITLE
DOMpurify not suitable for case-sensitive SVG

### ISSUE THREAD

**Issue by jampy** [cure53/DOMPurify#144]
DOMpurify claims to be a sanitizer for SVG but unfortunately all tags are [transformed to lower case](https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L436).

After sanitizing, I get a document with all lowercase tags (unlike the original).

SVG tags are (unlike HTML) case-sensitive and some tags like `feBlend`, `feGaussianBlur` and all other filter tags contain uppercase letters. SVG parsers don't recognize tags like `<fegaussianblur>`, so this causes the SVG document to render incorrectly.

Can this behaviour please be made configurable?

BTW, it seems that the `ADD_TAGS` configuration expects lowercase names as well, or they won't be accepted.

**Comment by cure53** [comment]
Oh, let me check that!

**Comment by cure53** [comment]
Yep, that's a bug - nice find :) I believe, we do not really need the lower-casing here because `nodeName` should be in the correct format already. let me run some tests and commit a fix proposal.

**Comment by jampy** [comment]
Sounds great! I actually couldn't understand where in the code the node name is changed *in the document*. I hope you know better ;-)

**Comment by cure53** [comment]
Found it, fix is on the way.

**Comment by cure53** [comment]
@jampy I am quite happy with the fix now, local tests are all green, remote tests are getting there - we will release 0.7.5 after all is fine.

Please let me know if the fix works for you, then we'll wrap-up the release and publish.

**Comment by cure53** [comment]
Alright, all tests are green, I am ready to go. Waiting for your review now :)

**Comment by jampy** [comment]
SVG filter elements are now white-listed by default, that's great. 

FYI, the [`result`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/result) attribute could be white-listed as well, I'd say. It's used by nearly all filter tags.

However, my sanitized document still contains **all elements transformed to lowercase**:

```xml
          <feflood result="COLOR-white" flood-color="white"></feflood>
          <feflood result="COLOR-black" flood-color="black"></feflood>
          <feflood result="TRANSPARENT" flood-opacity="0" flood-color="rgba(0,0,0,0)"></feflood>
```

Could that be because I'm using [**jsdom** 8.3.1](https://www.npmjs.com/package/jsdom) (I'm sanitizing server-side with Node v5.9.1 [as described here](https://github.com/cure53/DOMPurify/pull/60))?

**Comment by cure53** [comment]
Thanks for having a look! No objections on white-listing `result`, will do that.

The tags are indeed all lowercased. All browsers deal with that perfectly well. Is that a problem in the scenario you are using it for? I would assume it shouldn't - thus asking.

**Comment by jampy** [comment]
AFAIK all **SVG** tags are case-sensitive:

> [SVG elements and attributes should all be entered in the case shown here since XML is case-sensitive (unlike HTML).](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Introduction#Before_you_start)

Chrome effectively ignores all lowercased filter tags (`<feXXXX>`)  :-(

**Comment by cure53** [comment]
It depends - when loading the SVG embedded inside HTML, it works perfectly well (the browser has no problem with all-lowercase tag names here). When loading the SVG standalone however, the filter elements indeed have to be mix-cased.

I don't have a good test setup for DOMPurify running on jsdom and Node. So I am a bit hesitant to build a fix for this. But happy to accept a PR addressing this.

Another way to solve it would be to simply build a hook that handles those elements the right way for your scenario. It should be pretty straight forward to do so - take a list of camel-cased elements, check if they appear in the markup, change the tag names back to mixed case after sanitation.

The ideal hook position would be `afterSanitizeElements`:

https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L474

Would that work for you?

**Comment by jampy** [comment]
I'm effectively loading the SVG embedded inside HTML. The SVG code is loaded from the server via AJAX, transformed to XML and embedded using `appendChild()`. The SVG works perfectly except for the filters which get ignored when they appear with lowercase names. Bypassing the sanitize step causes correct-case tag names and the filters work as expected.

Also, I think a test a while back showed that also creating SVG elements via `createElementNS()` only worked when using the correct case.

Anyway, your `afterSanitizeElemens` hack sounds good to me.

How can I change the tag name? `currentNode.nodeName` is a getter, so I probably can't simply overwrite that property.

Please note that the node passed to my `afterSanitizeAttributes` hook shows the **correct** case (`feFlood`). Is this perhaps actually a JSDOM problem!?

**Comment by jampy** [comment]
Yeah.. Just tried to run DOMPurify in the browser (Chrome). Tag name case is preserved, so this probably means that JSDOM is the culprit :-(

Any suggestion? Perhaps a JSDOM alternative that works in NodeJS?

**Comment by cure53** [comment]
> Is this perhaps actually a JSDOM problem!?

I think no - I think the issue here is, that browsers automatically take care of the mixed-casing while any other system is more agnostic and does not. Let me try to see what we can do using a hook...

**Comment by jampy** [comment]
Perhaps you missed [my comment](https://github.com/cure53/DOMPurify/issues/144#issuecomment-209314251) about my test in a browser environment?

**Comment by cure53** [comment]
Nope, didn't miss it :) 

The issue here is, that we use internal browser features to scan the dirty DOM and build the sane DOM. Because we do that, the browser does certain things for us "for free" - including the mixed casing that is re-applied, even if we pass the browser all-lowercase SVG tagNames.

Look:
```
var div = document.createElement('div');
div.innerHTML = '<svg><fegaussianblur>';
console.log(div.outerHTML)
```

Probably, jsdom doesn't do that. Maybe it should though. However, I guess, currently, we have to work around that. I am in the process of creating a hook for you that demos how it can be done.

**Comment by cure53** [comment]
So, here is how this *should* work:

```html
// Specify dirty HTML
var dirty = '<svg><feGaussianBlur /></svg><svg><fegaussianblur /></svg>';

// Add a hook to rename certain node names
DOMPurify.addHook('afterSanitizeElements', function(node){
	// specify one node name to replace
	var wrong   = 'fegaussianblur';
	var correct = 'feGaussianBlur';
	var index;
	// check if the node name is wrong
	if(node.tagName === wrong){
		// create a new node
		var newnode = document.createElement(correct);
		// transfer all attributes
        for (index = node.attributes.length - 1; index >= 0; --index) {
            newnode.attributes.setNamedItem(node.attributes[index].cloneNode());
        }
		// rplace old node with new node
        node.parentNode.replaceChild(newnode, node);
	}
});
// Clean HTML string and write into our DIV
var clean = DOMPurify.sanitize(dirty);
console.log(clean)
```

In the browser this of course doesn't do much - because `node.tagName === wrong` is never true :D
But, in your setup this might do - maybe?

**Comment by cure53** [comment]
Or, a slight variation just to demo it in the browser as well.

Here, the hook checks for a certain filter - and if it finds it, it replaces it with a different filter. Basically the same that you want to do - just a bit varied so it can be proven that simply replacing the node and transferring the attributes should do the trick here.

```javascript
// Specify dirty HTML
var dirty = '<svg><feGaussianBlur r="123" /></svg><svg><fegaussianblur /></svg>';

// Add a hook to rename certain node names
DOMPurify.addHook('afterSanitizeElements', function(node){
	// specify one node name to replace
	var wrong   = 'feGaussianBlur';
	var correct = 'feDiffuseLighting';
	var index;
	// check if the node name is wrong
	if(node.tagName === wrong){
		// create a new node
		var newnode = document.createElementNS('http://www.w3.org/2000/svg', correct);
		// transfer all attributes
        for (index = node.attributes.length - 1; index >= 0; --index) {
            newnode.attributes.setNamedItem(node.attributes[index].cloneNode());
        }
		// rplace old node with new node
        node.parentNode.replaceChild(newnode, node);
	}
});
```

**Comment by jampy** [comment]
Thanks for your code.

I tried both variants (removing the `for` loop which throws because of a missing `cloneNode` function). Also, I modified the code to ignore the case in the `if` statement (reason see below):

```javascript
DOMPurify.addHook('afterSanitizeElements', function(node) {
  var correct = 'feFlood';
  var index;
  // check if the node name is wrong
  if(node.tagName.toLowerCase() === 'feflood'){
    console.log("REPLACING feFlood");
    // create a new node
    var newnode = document.createElementNS('http://www.w3.org/2000/svg', correct);
    // transfer all attributes
    /*for (index = node.attributes.length - 1; index >= 0; --index) {
      newnode.attributes.setNamedItem(node.attributes[index].cloneNode());
    }*/
    // rplace old node with new node
    node.parentNode.replaceChild(newnode, node);
  }
}
```

The `replaceChild` code is executed, but I still get lowercase tag names.

That doesn't really surprise me however, because - [as said earlier](https://github.com/cure53/DOMPurify/issues/144#issuecomment-209310847) - when the hook is called the case is *correct* (ie. sensitive, with uppercase `F`). 

So your `if(node.tagName === wrong)` check won't catch anything, *unless the "dirty" code already contains wrong-cased tags* (which is not the case).

I'm pretty convinced that DOMPurify doesn't mess with the tag case (after all it works fine in the browser), but instead JSDOM mangles with the case. 

Anyway, I can see two workarounds for me:

- use the `innerHTML` trick (you shown to me) client-side, letting the browser deal with the incorrect case *of the already-sanitized, but lowercased code* (works, but I'm not sure about widespread browser support... can I be sure all browsers and -versions back to IE9 are so nice?)
- sanitize within a PhantomJS environment, since I already use that for other stuff (probably the safer alternative)

**Comment by cure53** [comment]
Hmkay, then it might be JSDOM indeed. 
I wasn't super-sure, thus the test cases and suggested solutions. 

Well, I guess for now we did all we can, correct? If so - can we close this issue? :)

**Comment by jampy** [comment]
Yeah, thanks a lot for your effort anyway! :-)

**Comment by cure53** [comment]
You're welcome :)

**Comment by cure53** [comment]
Can you describe the exact issue? This ticket covered several problems at the same time.

**Comment by dhavaljain999** [comment]
For SVG all tags are transformed to lower case tags(unlike the original).
SVG tags are (unlike HTML) case-sensitive and some tags like linearGradient, radicalGradient and all other filter tags contain uppercase letters. SVG parsers don't recognize tags like <lineargradient>, so this causes the SVG document to render incorrectly.
This seems an issue from JSDOM because when we use the after hooks we get the elements in proper case.

**Comment by cure53** [comment]
Ah okay - no we are not aware of how to best fix it. 

As far as I understand, this is not our bug. or am I wrong?

**Comment by dhavaljain999** [comment]
Yes , this is not your bug but something related to JSDOM :)
