### ISSUE TITLE
Detect which tags / attributes have been removed?

### ISSUE THREAD

**Issue by jampy** [cure53/DOMPurify#146]
Is there any way to get a list (or something) of all tags and attributes that have been sanitized (removed) when calling `sanitize()`?

There are still some (SVG-related) elements/attributes missing in the current whitelist and it's pretty laborious to find missing pieces in an over-sanitized document... ;-)

**Comment by cure53** [comment]
Not as an inbuilt feature - but easy to produce: 

Take the original, select all elements using `querySelectorAll`, take the sanitized version, do the same, diff the array :) That should do.

**Comment by jampy** [comment]
...and some more work for the attributes.

Ok, fine!

**Comment by cure53** [comment]
Happy to add what is needed to make it work flawlessly - best just file us a collective ticket. We will then review the tags and attributes for security risks and add them afterwards :)

**Comment by jampy** [comment]
Sorry to bother again: Some other, more performant hack possible maybe? Perhaps using the hooks?

**Comment by cure53** [comment]
Likely yes. They should be able to notice if anything was removed - and you can protocolize that.
