### ISSUE TITLE
Builds are broken

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#156]
Hi all,

adding this ticket because so far the conversation was spread across several PRs. cc @fhemberger @tdeekens @Joris-van-der-Wel 

It appears that the builds themselves work and are green. Only in combination things break. What I don't understand yet: Why do we have to run *all* tests three times? Currently it seems, the tests for each node versions also each run the tests for all browsers, which makes absolutely no sense at all.

**Comment by cure53** [comment]
And now it says the builds are passing. Only that they are not :D

https://travis-ci.org/cure53/DOMPurify

**Comment by Joris-van-der-Wel** [comment]
Have you tried turning of off and on again? :p

Running browserstack 3x is indeed a bit silly

**Comment by cure53** [comment]
I just committed something into the README and now all tests go through smoothly :D Not exactly sure why - but awesome!

**Comment by fhemberger** [comment]
I dug a bit and found a few things:

- At the moment, we execute the BrowserStack tests three times, also jshint.
- jshint is already part of the pre-commit check, so malformed javascript can't be committed - no need to check that again on Travis.
- Regarding Karma an browser timeouts, I found something in the Travis docs: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Karma-and-Firefox-inactivity-timeouts
- Also, the npm script "qunit" starts a server, but the index.html cannot be found. Do we still really need this?
- To avoid confusing committers, who want to run the tests locally, before submitting a PR, `npm test` should run the local tests only. You can specify `script: npm run travis-ci` in `.travis.yml` instead.

`package.json` should be changed accordingly:
```diff
"scripts": {
  "build-demo": "node scripts/build-demo.js",
-  "qunit": "node scripts/server.js",
-  "jshint": "jshint src/purify.js || true",
+  "jshint": "jshint src/purify.js",
  "minify": "scripts/minify.sh",
  "amend-minified": "scripts/amend-minified.sh",

-  "test": "npm run jshint && npm run travis-ci",
+  "test": "npm run jshint && npm run test:jsdom && npm-run test:karma --browsers Firefox,Chrome",

+  "test:karma": "karma start test/karma.conf.js --log-level warn --single-run"

-  "travis-ci": "npm run jsdom-test && ([ \"${TRAVIS_PULL_REQUEST}\" != \"false\" ] || karma start test/karma.conf.js --log-level warn --reporters dots --single-run)",
+  "test:travis": "npm run test:jsdom && ([ \"${TRAVIS_PULL_REQUEST}\" != \"false\" ] || npm run test:karma --reporters dots)",

-  "ci-test": "karma start test/karma.conf.js --single-run",
-  "local-test": "npm run jshint; npm run jsdom-test && karma start test/karma.conf.js --browsers Firefox,Chrome --single-run",

-  "jsdom-test": "node test/jsdom-node-runner --dot"
+  "test:jsdom": "node test/jsdom-node-runner --dot"
},
```


Instead, we should have the following build matrix:
- jsdom on node.js 4
- jsdom on node.js 5
- jsdom on node.js 6
- browserstack tests

Somehow this should be possible, we should ask Travis support about that.

**Comment by cure53** [comment]
Thanks :D

**Comment by tdeekens** [comment]
Agreed. BrowserStack only once with the whole set of browsers and jsdom on all node versions. I have a pretty long train ride today and I could, hoping for ICE interwebs work on it. 🎎 

1.) Run jshint before anything
2.) Run on node 4,5,6 with jsdom
3.) Run BrowserStack
4.) npm test should only run local things

I'll try to get to it and clean up the package.json script section along the way.

**Comment by tdeekens** [comment]
So as promised #157 attempts to implement things discussed there. 

Im summary:

- We're still running tests against nodejs 4, 5 and 6 and we do not run permutations of the matrix. Hence the `include` flag
- It adds a build matrix with a configurable flag for the BrowserStack tests (currently only passed to one configuration)
- The builds still run concurrently (obv) and do not have a fast exit
- Jshint will still run on CI 
   - Even though it is a commit hook `--no-verify` can be used to pass on it. Lastly, I think it's the last of our issues causing build time.
- I refactored the package.json and its run scripts according to @fhemberger's suggestions 👍 

Please first comment and discuss on things, sadly it's hard to test a test configuration these days 💃.

_...hoping the `comment` button will work from a RE in the middle of German nowhere._

**Comment by tdeekens** [comment]
I am currently a bit unhappy about the duplication of exports but can't think of another way to not have permutations run. Having a global env entry also won't work. Input appreciated. 🐥

**Comment by cure53** [comment]
So far things are looking really well! All tests are green :)

**Comment by tdeekens** [comment]
Wät. I was really confused seeing that you merged it straight away even though I marked it as a WIP. Thanks for putting in the trust 😌. Didn't really expect the global envs to propagate down as the docs aren't really clear on it 🤖. Yolo!

**Comment by cure53** [comment]
We're in "nothing to lose" mode here :D No worries. And thanks!

**Comment by Joris-van-der-Wel** [comment]
The bug within jsdom has been fixed (#1477) in 9.1.0, and I can verify the DOMPurify test cases all run successfully with it.

**Comment by tdeekens** [comment]
I think we can also add a fast exit to the jobs in oir matrix to not eat our BrowserStack time with no need. Will check later if that's possible.

**Comment by cure53** [comment]
Cool, thanks. I think after that, we can close this one and go for a next release.

**Comment by cure53** [comment]
Oh, and what is the correct CLI syntax for running the local and the CI tests?
We probably need to update the README.md.

@tdeekens @fhemberger

**Comment by fhemberger** [comment]
`npm test` runs jsdom and local karma tests in Firefox and Chrome.

**Comment by tdeekens** [comment]
Yeap, `npm test` will do the trick.

Go ahead and close it. I thing we can have further improvements once we see a need for them in other issues and PRs.

**Comment by cure53** [comment]
Cool, thanks everyone :D
