### ISSUE TITLE
template creation breaks purifyjs

### ISSUE THREAD

**Issue by devd** [cure53/DOMPurify#158]
for some reason, the https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L49 throws an exception for us at scale. Basically, we get the error document.createElement('template').content.ownerDocument;
"Cannot read property 'ownerDocument' of undefined
"

Can't figure out why, but it seems this is already behind a if, so can we just also check if .content is null / undefined in the code? Sorry, it seems it is some weird browser versions on phones that this is breaking on.

**Comment by cure53** [comment]
Heya!

Can you specify what browser version it breaks on? Happy to do some testing on BrowserStack then.

**Comment by devd** [comment]
Chrome 45 on Android,  Chrome on some Samsung Mobile devices, default
Android browser on older Android devices. It's pretty distributed.

**Comment by cure53** [comment]
Strange. I will try to set that up and have a look. Does the fix work for you?

**Comment by devd** [comment]
trying it out.

**Comment by devd** [comment]
I think the fixed work. thanks!

**Comment by cure53** [comment]
Cool, thanks :)
