### ISSUE TITLE
DOMPurify.removed array is not modified when removed attribute is set back

### ISSUE THREAD

**Issue by dnkolegov** [cure53/DOMPurify#161]
Hello.

[The Safari trick](https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L573) removes attributes and changes `DOMPurify.removed` array. After that, [the attribute is set again](https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L619) (by try-catching), but `DOMPurify.removed` is not modified.

##### Steps to reproduce
```
var dirty = "<img width=1 height=2>";
var clean = DOMPurify.sanitize(dirty);
clean;
// "<img height="2" width="1">"
DOMPurify.removed.length
// 2

```
`DOMPurify.removed` will contain `width` and `height` attributes.

Found on `DOMPurify 0.8.0`.

Proposed fix is to modify [try-catch](https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L618):

```
                /* Handle invalid data-* attribute set by try-catching it */
                try {
                    currentNode.setAttribute(name, value);
                    DOMPurify.removed.pop();
                } catch (e) {}
```
Thanks.

**Comment by cure53** [comment]
Nice find! The suggested fix looks good, if this works for you, we can close the issue.

**Comment by dnkolegov** [comment]
Yes, it works.
Verified.
