### ISSUE TITLE
These tags are supported by Chrome but are filtered by DOMPurify, Why?

### ISSUE THREAD

**Issue by kamael** [cure53/DOMPurify#162]
i dont know why:
```
 attachment
 bgsound
 command
 isindex
 keygen
 layer
 listing
 noembed
 noframes
 nolayer
 noscript
 plaintext
 rb
 rtc
 webkitShadowContent
 xmp
```

other filtered tags but i know why:
```
 script
 base
 applet
 basefont
 meta
 embed
 frame
 frameset
 iframe
 link
 object
 param
```

**Comment by kamael** [comment]
from https://code.google.com/p/chromium/codesearch#chromium/src/out/Debug/gen/blink/core/HTMLNames.cpp&q=HTMLNames.cpp

**Comment by cure53** [comment]
We filter everything that could cause XSS / script execution or alike by default:
https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model

But, if you need those elements, you can easily add them your custom white-list via config option:
https://github.com/cure53/DOMPurify/blob/master/demos/advanced-config-demo.html
