### ISSUE TITLE
No support for boolean attributes

### ISSUE THREAD

**Issue by tansongyang** [cure53/DOMPurify#168]
# No support for boolean attributes

## Version

0.8.1, and possibly earlier

## Steps to Reproduce

1. Construct HTML with a boolean attribute, e.g. `checked`: `<input type="checkbox" checked />`.
2. Make sure DOMPurify allows the tag and attributes.
3. Call DOMPurify.

Result is missing the boolean attribute. If you assign a value, e.g. `<input type="checkbox" checked="checked" />`, then it works. See the demo.

## Expected Result

Boolean attributes, which work in HTML5, also work in DOMPurify.

## Demo

[JSFiddle](https://jsfiddle.net/ftan/d8t28jn8/). With DOMPurify, only the checkbox that sets `checked="checked"` is checked. Without DOMPurify, both checkboxes are checked.

**Comment by cure53** [comment]
Interesting find! I think I managed to spot the problem, committing a fix soon.

**Comment by cure53** [comment]
It should work again as expected - please check! :)

**Comment by tansongyang** [comment]
@cure53 Wow, that was fast! Thanks a lot. Everything's working as expected now. Could we all get a new tagged version?

**Comment by cure53** [comment]
Yes, 0.8.2 will come in later today :)
