### ISSUE TITLE
Allow target for same origin links

### ISSUE THREAD

**Issue by devd** [cure53/DOMPurify#170]
Some engineers were surprised that DOMPurify removes the target attribute for anchor elements. Given the risk is really cross origin links, I wonder if DOMPurify could allow target=_blank for same origin links. It seems there isn't much risk here and makes the defaults great! Right now, we either have to explicitly allow target attribute but then it will be allowed even for cross origin links.

**Comment by cure53** [comment]
Heya, yeah, I see the need for that. But I think, that might be a bit of an overkill for a core feature. Would a hook do as well?

**Comment by devd** [comment]
yeah; I just wonder if its a sensible default to have though? I can write the hook for us, but others will copy paste it from Stackoverflow and make a mistake etc.

**Comment by devd** [comment]
(also, sorry .. I keep forgetting about hooks )

**Comment by cure53** [comment]
Haha no worries :D I think the hardest part will be a reliable same-domain detection. Also, there is open redirects to bypass that - and the CKEditor XSS from 2013 abused the `target` attribute for XSS despite being same-domain.

If you do write a hook, we can add it to the test-suite and see, that it behaves as expected on all tested browsers. Makes sense?

**Comment by cure53** [comment]
Is it okay to close this one?

**Comment by devd** [comment]
yup
