### ISSUE TITLE
Add noreferrer for anchor links (and noopener?) ?

### ISSUE THREAD

**Issue by devd** [cure53/DOMPurify#171]
I was wondering if DOMPurify could just add the rel="noreferrer noopener" to all anchor tags (and other tags that support it) by default. noreferrer is supported in Gecko, Webkit, and Blink which is a huge chunk of browsers and noopener works in Chrome, which has a huge market share.

**Comment by cure53** [comment]
We have a hook that does something very similar already :)

https://github.com/cure53/DOMPurify/blob/master/demos/hooks-target-blank-demo.html

I do believe that makes sense - but not for the core library. Many existing applications could break if we add that. 

I am kinda tempted though to for example set up *and* document a "high paranoia hook", meaning a curated collection of transformations in one hook that are particularly meant for extra security and privacy - and each is documented well so people can indeed secure copy&paste. What do you think?

**Comment by devd** [comment]
that would be perfect, actually!

**Comment by devd** [comment]
I wonder if you can make it a build step that creates a new 'purify-paranoia.js' or something like that

**Comment by dnkolegov** [comment]
Agree with @devd.
It would be great!

**Comment by cure53** [comment]
So, let's enumerate some use cases and transformations :) Then we can build a hook first and - if it works well, maybe even implement it into the core at some point.

**Comment by dnkolegov** [comment]
Maybe you should create a separate page to document these cases. Something like HTTPLeaks...

**Comment by cure53** [comment]
We could, upon having it finished, also do a small challenge to encourage people finding bypasses.

**Comment by dnkolegov** [comment]
Maybe it will be also useful to create a separate tool based on the core or add a new mode to DOMPurify to transform whole document (not suppplied HTML markup).

**Comment by cure53** [comment]
So, where do we move from here?

**Comment by dnkolegov** [comment]
The plan:
1. Choose where this mini-project will be located.
2. Create pages.
3. Describe uses cases and transformations.
4. Implement a hook.

I think it should be placed in @cure53 repositories ;-)

**Comment by cure53** [comment]
Okay, I'll set up something soon. I think however it might be better as part of the DOMPurify itself. Why would you rather go for an independent project instead?

**Comment by dnkolegov** [comment]
I agree that it can be (maybe should be) a part of DOMPurify. I only say that `Issue` is not a best place for enumeration of use cases, transformations, examples, etc...

**Comment by cure53** [comment]
Fully agree. 

I'd suggest to first set up a Google doc (or alike) where we can collect ideas. As soon as everyone is happy, we can start planning specifics and coding. By then, we should also know, if a new project or rather a hook will be better. 

Sounds good?

**Comment by dnkolegov** [comment]
Sounds great.

**Comment by cure53** [comment]
Can you send me an email to mario@cure53.de? I will invite your account of choice then.

**Comment by ArtemBernatskyy** [comment]
Guys, what's the status for this ? Thx !

**Comment by cure53** [comment]
Oh, tales from the crypt :D  

No new status, but all of the above can now be easily implemented using hooks. Should be 3-4 LoC and we have demos and sample code available [here](https://github.com/cure53/DOMPurify/blob/master/demos/hooks-target-blank-demo.html)

**Comment by ArtemBernatskyy** [comment]
Thx !

**Comment by ArtemBernatskyy** [comment]
@cure53 pushed a little pull request https://github.com/cure53/DOMPurify/pull/337 to fix demo
