### ISSUE TITLE
DOMPurify breaks on SGML DTD's

### ISSUE THREAD

**Issue by wirehead** [cure53/DOMPurify#172]
The following was generated by Illustrator 4.0's SVG export plugin:
```svg
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 14.0.0, SVG Export Plug-In  -->
<!DOCTYPE svg [
	<!ENTITY ns_flows "http://ns.adobe.com/Flows/1.0/">
]>
<svg version="1.2" baseProfile="tiny"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:a="http://ns.adobe.com/AdobeSVGViewerExtensions/3.0/"
	 x="0px" y="0px" width="1024px" height="768px" viewBox="0.577 -16.649 1024 768" xml:space="preserve">
<defs>
</defs>
<polygon fill="#E6E6E6" stroke="#000000" points="64.577,222.202 0.577,111.351 64.577,0.5 192.577,0.5 256.577,111.351 
	192.577,222.202 "/>
<polygon fill="#E6E6E6" stroke="#000000" points="64.577,478.203 0.577,367.351 64.577,256.5 192.577,256.5 256.577,367.351 
	192.577,478.203 "/>
<polygon fill="#E6E6E6" stroke="#000000" points="64.577,734.203 0.577,623.351 64.577,512.5 192.577,512.5 256.577,623.351 
	192.577,734.203 "/>
<polygon fill="#B3B3B3" stroke="#000000" points="576.577,222.202 512.577,111.351 576.577,0.5 704.577,0.5 768.577,111.351 
	704.577,222.202 "/>
<polygon fill="#B3B3B3" stroke="#000000" points="576.577,478.203 512.577,367.351 576.577,256.5 704.577,256.5 768.577,367.351 
	704.577,478.203 "/>
<polygon fill="#B3B3B3" stroke="#000000" points="576.577,734.203 512.577,623.351 576.577,512.5 704.577,512.5 768.577,623.351 
	704.577,734.203 "/>
<polygon fill="#CCCCCC" stroke="#000000" points="320.577,350.202 256.577,239.351 320.577,128.5 448.577,128.5 512.577,239.351 
	448.577,350.202 "/>
<polygon fill="#CCCCCC" stroke="#000000" points="320.577,606.203 256.577,495.351 320.577,384.5 448.577,384.5 512.577,495.351 
	448.577,606.203 "/>
<polygon fill="#999999" stroke="#000000" points="832.577,606.203 768.577,495.351 832.577,384.5 960.577,384.5 1024.577,495.351 
	960.577,606.203 "/>
</svg>
```

The DOMPurify output looks something like this:
```svg
]&gt;
<svg xml:space="preserve" viewBox="0.577 -16.649 1024 768" height="768px" width="1024px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg">
<defs>
</defs>
<polygon points="64.577,222.202 0.577,111.351 64.577,0.5 192.577,0.5 256.577,111.351 
	192.577,222.202 " stroke="#000000" fill="#E6E6E6"></polygon>
<polygon points="64.577,478.203 0.577,367.351 64.577,256.5 192.577,256.5 256.577,367.351 
	192.577,478.203 " stroke="#000000" fill="#E6E6E6"></polygon>
<polygon points="64.577,734.203 0.577,623.351 64.577,512.5 192.577,512.5 256.577,623.351 
	192.577,734.203 " stroke="#000000" fill="#E6E6E6"></polygon>
<polygon points="576.577,222.202 512.577,111.351 576.577,0.5 704.577,0.5 768.577,111.351 
	704.577,222.202 " stroke="#000000" fill="#B3B3B3"></polygon>
<polygon points="576.577,478.203 512.577,367.351 576.577,256.5 704.577,256.5 768.577,367.351 
	704.577,478.203 " stroke="#000000" fill="#B3B3B3"></polygon>
<polygon points="576.577,734.203 512.577,623.351 576.577,512.5 704.577,512.5 768.577,623.351 
	704.577,734.203 " stroke="#000000" fill="#B3B3B3"></polygon>
<polygon points="320.577,350.202 256.577,239.351 320.577,128.5 448.577,128.5 512.577,239.351 
	448.577,350.202 " stroke="#000000" fill="#CCCCCC"></polygon>
<polygon points="320.577,606.203 256.577,495.351 320.577,384.5 448.577,384.5 512.577,495.351 
	448.577,606.203 " stroke="#000000" fill="#CCCCCC"></polygon>
<polygon points="832.577,606.203 768.577,495.351 832.577,384.5 960.577,384.5 1024.577,495.351 
	960.577,606.203 " stroke="#000000" fill="#999999"></polygon>
</svg>
```

As far as I can tell, the problematic section, which I can remove in a text editor, is this:
```svg
<!-- Generator: Adobe Illustrator 14.0.0, SVG Export Plug-In  -->
<!DOCTYPE svg [
	<!ENTITY ns_flows "http://ns.adobe.com/Flows/1.0/">
]>
```

getting turned into this:

```svg
]&gt;
```

(note: all of this is being tested on the node.js side)

**Comment by cure53** [comment]
Heya! Yep, that issue is known. DOMPurify doesn't support XML entities in doctypes - the best would be right now to strip them with either a hook or in the business logic around the DOMPurify-using code.

There is a couple of additional XML features we do not really have capabilities to deal with right now. Reason for that is, that we create an HTML document to sanitize the content (with the goal of preventing XSS, the core-user case of DOMPurify).

You think implementing and being able to use a specific XML-enabled mode might make sense here?

**Comment by wirehead** [comment]
Well, DOMPurify is the only tool I found that seemed like it would do SVG sanitization inside of JS.  And, unfortunately, that probably means that whatever garbage Illustrator outputs I'm stuck with accepting and trying to sanitize.  And part of why I'm using DOMPurify on SVG files is because they'll potentially end up inserted into HTML documents.

Given the known fun involved with XML entity parsing (e.g. Billion Laughs), it's probably not the worst thing for DOMPurify to strip them, even though I think a lot of the more popular libraries have been patched for that particular attack.  *shrug*

**Comment by cure53** [comment]
I'll have a look at what possibilities we have to work with an optional XML-mode. 

I fear though, that things might fall apart quickly since DOMPurify is made for HTML and inline SVG, MathML etc. Let's see...

**Comment by cure53** [comment]
So, it looks like we can make it work by changing the MIME type for the DOM parser call. 

But then, we also have to change the element selector at the end of `_initDocument` and we cannot at all rely on older browsers to deliver safe results. And some of the config flags might die - because they are specifically made for HTML documents.

What do you think?

**Comment by cure53** [comment]
Heya, any thoughts on the above? Else we should probably close this one.
I would recommend to maybe fork DOMPurify and create a stripped down XML-only version.

**Comment by wirehead** [comment]
Sorry, this is for my weekend project, so I tend to ignore a lot of the github traffic during the work week.

I'm totally OK with the idea of a sanitizeXML or sanitizeSVG API call instead of sanitize.  Even if the same app is using DOMPurify to sanitize HTML and SVG (or other similar formats), you aren't going to be doing it from the same spot in the same way.

**Comment by cure53** [comment]
Ah, no problem :) 

I think it might make sense to fork out an entire new library. The purpose is a very much different one and the attack classes a proper DON-aware XML sanitizer could handle are quite different too (XXE, XEE, etc.).

**Comment by wirehead** [comment]
Given that I know some real security practitioners and had one directly reporting to me for a while, my level of security-fu feels sufficiently inadequate that I'd feel a bit awkward having something such as a sanitizer on the internets with my name as the person responsible. :/

**Comment by cure53** [comment]
Hm, okay. I won't have tome to for out an XMLPurify on my own right now - but happy to help if someone starts it :) Closing this one for now.
