### ISSUE TITLE
Is there a way to encode the elements that will be removed instead of removing them? 

### ISSUE THREAD

**Issue by RamyaSenGit** [cure53/DOMPurify#174]
For example, my input string is <script> abc </script> hello, i would like my output to be "encoded version of <script> abc </script>" hello. 

I tried adding a hook in beforeSanitizeElements, but modifying the elements does'nt seem to do anything. Or perhaps am getting it wrong.

Here is my code snippet: http://jsfiddle.net/ramyasen/c121v955/23/

**Comment by cure53** [comment]
Nothing by default - but super-easy to do with a hook :) Basically, take the element that would be removed and replace it with a text node that contains its own `outerHTML`.

Have you checked the demo hooks for inspiration?

**Comment by RamyaSenGit** [comment]
Thanks. I did take a look at the demo hooks - unfortunately i did not find one that involves modifying the node itself. Instead most of them reflect modify the attributes of the node. 

I tried what you suggested - but the textnode is not retained: https://jsfiddle.net/ramyasen/b66h4s1f/1/

**Comment by RamyaSenGit** [comment]
I think i see why what i want is not happening. The code: 

 ```
var _sanitizeElements = function(currentNode) {
        var tagName, content;
        /* Execute a hook if present */
        _executeHook('beforeSanitizeElements', currentNode, null);

```
does not accept the newly modified currentNode if it does get modified in the 'beforeSanitizeElement'. 

Ideally it should be:

` /* Execute a hook if present */
    `   **currentNode =**  `_executeHook('beforeSanitizeElements', currentNode, null);`

@cure53 right? Or is this by design :)

**Comment by cure53** [comment]
Check this :)

https://jsfiddle.net/b66h4s1f/7/

**Comment by RamyaSenGit** [comment]
This does'nt work on Chrome :( Works on edge and firefox. The insertBefore instead of replaceChild did the trick on Chrome. Thanks for your help.

**Comment by cure53** [comment]
Ah, cool :)
