### ISSUE TITLE
Allow specified tag with attribute equal to value?

### ISSUE THREAD

**Issue by track0x1** [cure53/DOMPurify#175]
Is there any chance we can do something like
`sanitize(dirty, {ADD_TAG: ['script'], WITH_ATTR: ['type='application/json']})`

What this would do is sanitize as normal, but additionally allow script tags that only have a type attribute equal to 'application/json'?

Would be so great!!!

**Comment by cure53** [comment]
Heya, yep - you can easily do that with a hook. 

Basically, just allow the element via config and use the hook API to check, if the elements ships the necessary attribute(-value) and decide, whether to remove it or leave it in.

**Comment by cure53** [comment]
Heya - any progress on this or any help needed?

**Comment by cure53** [comment]
Closing this for now, please re-open if any help is needed :)
