### ISSUE TITLE
NPM repo weight

### ISSUE THREAD

**Issue by SwordSoul** [cure53/DOMPurify#178]
Hello, you have a really great purifier/sanitizer, but your npm package weights almost 700kb, while the actual code is 12kb. Such size makes npm download it for minutes on a machine without ssd behind a corporate proxy .
Could you please lighten npm package? Thanks!

**Comment by mathiasbynens** [comment]
Please do so by using the `files` property in `package.json` (which acts as a whitelist) instead of `.npmignore` (which is a blacklist).

**Comment by cure53** [comment]
Hi all, thanks a bunch :) I am no NPM expert and honestly have no idea how to optimize things like that. Please feel free to send us a PR, we will review and merge that then.

**Comment by tdeekens** [comment]
I will look into it during the weekend @cure53. If that's fine by you. I've been reading, listening about quite a few things regarding npm deployments and whitelisting.

**Comment by cure53** [comment]
Oh, awesome - thank you :D

**Comment by mathiasbynens** [comment]
Ref. #173.

**Comment by mathiasbynens** [comment]
Hah. @cure53, this issue can probably already be closed after publishing a new release that includes the changes from #173 (which is merged already).

**Comment by cure53** [comment]
Hah, okay - now, can someone find a bypass so we need to do another release? :P

**Comment by tdeekens** [comment]
haha. fix version should be all good, right?

**Comment by SwordSoul** [comment]
60kb(which is aprrox weight of fixed package) is much better for sure.

**Comment by mathiasbynens** [comment]
This calls for a minor release, i.e. v0.8.3!

**Comment by mathiasbynens** [comment]
This calls for a patch release, i.e. v0.8.3!

**Comment by cure53** [comment]
Okay, so no further changes have to be made? 100% sure?

**Comment by SwordSoul** [comment]
If dist is needed then yes. I am not sure if it can be used because requiring module currently leads to adding src/purify.js.

**Comment by cure53** [comment]
`/dist/` is just the compressed *and* tested version. We are scared of JavaScript compressors over-optimizing DOMPurify and leading to bypasses - thus we ship our own.

**Comment by SwordSoul** [comment]
Yeah sure) If someone will choose to relink to dist through their project's package.json or webpack or whatever it can be a wise choice to leave it bundled. +1 for new version

**Comment by cure53** [comment]
Alright, so be it then!

**Comment by cure53** [comment]
Alright, issue should be solved!

**Comment by mathiasbynens** [comment]
Worth it!

```sh
$ fs dom*
 92K   	dompurify-0.8.2.tgz
 28K   	dompurify-0.8.3.tgz

$ tar xzf dompurify-0.8.2.tgz; fs package; rm -rf package
736K   	package

$ tar xzf dompurify-0.8.3.tgz; fs package; rm -rf package
 80K   	package
```

**Comment by cure53** [comment]
:) Thx!
