### ISSUE TITLE
Support Node 0.12

### ISSUE THREAD

**Issue by strugee** [cure53/DOMPurify#179]
Over in e14n/pump.io, we still need to support Node.js 0.12 because lots of our users use the Node.js that ships with their Linux distribution.

Why is DOMPurify currently incompatible with Node 0.12? Newer ES6 features? I'm willing to put in some work to make this happen, if it can be done in a maintainable way.

**Comment by tdeekens** [comment]
The source code does not use any ES201* features to date from what I know. It should run and work as expected on 0.12. However, it is not covered in our test suite. 

You can easily verify it thinks work for you by cloning down the repo and running the tests against 0.12 locally with `nam run test:jsdom`. However, keep in mind that the effort has been put into the fact that the library runs in loads of browsers. The mentioned command uses jsdom.

Anybody feel free to correct me if I am wrong.

**Comment by strugee** [comment]
So I looked into this and jsdom uses lots of ES6 features. The newest jsdom that still supports Node 0.12 is `jsdom@3`, which isn't good enough. The latest version of jsdom, `jsdom@7`, uses unpollyfillable (read: presumably untranspilable) ES6 features.

It's conceivable that one could find a version of jsdom that a) can be transpiled to run on 0.12 and b) works with DOMPurify, but I didn't bother. That kind of hack can only turn into a maintenance nightmare, so we're going with a different plan in pump.io.

**Comment by cure53** [comment]
Aye, okay :)
