### ISSUE TITLE
JSON is deleted in SAFE_FOR_TEMPLATES mode

### ISSUE THREAD

**Issue by dnkolegov** [cure53/DOMPurify#181]
Hello.

`SAFE_FOR_TEMPLATES` mode uses the following regex:
```
var MUSTACHE_EXPR = /\{\{[\s\S]*|[\s\S]*\}\}/gm;
```

Case:

```
DOMPurify.sanitize('{"foo":{"bar":1}}', {SAFE_FOR_TEMPLATES: true, WHOLE_DOCUMENT: true})
//<html><head></head><body> </body></html>
```

Is it possible to fix the regex to pass JSON?

Is it possible to use this regex?
```
var MUSTACHE_EXPR = /\{\{[\s\S]*\}\}/gm;
```

Thanks.

**Comment by cure53** [comment]
Hmmm - potentially yes. We'd have to run some tests though. 
Are the existing tests green for this regex?

**Comment by dnkolegov** [comment]
> Are the existing tests green for this regex?
No.

Some tests are ok, but should be correct. For example:

Test:
```
assert.equal( DOMPurify.sanitize( '<a>123{{456}}<b><style><% alert(1) %></style>456</b></a>', {SAFE_FOR_TEMPLATES: true}), "<a> <b><style> </style>456</b></a>" );
```
Result:
```
Expected: "<a> <b><style> </style>456</b></a>"
Got: "<a>123 <b><style> </style>456</b></a>"
```

Another tests shows that proposed regex can not be used if expression covers several nodes:

Test:

```
assert.equal( DOMPurify.sanitize( '<a>123{{<b>456}}</b><style><% alert(1) %></style>456</a>', {SAFE_FOR_TEMPLATES: true}), "<a>123 <b> </b><style> </style>456</a>" );
```

Result:

```
Expected: "<a>123 <b> </b><style> </style>456</a>"
Got: "<a>123{{<b>456}}</b><style> </style>456</a>"
```

**Comment by cure53** [comment]
I would say, the level of distinguishable difference between JSON and template expressions is too fragile to be safe for regex.

**Comment by dnkolegov** [comment]
I performed some tests and now I strongly agree.
I think that one way to filter JSON in a concrete application is to use `isJSON` function.

```
function sanitize(dirty) {
    if (isJSON(dirty)) {
        return dirty;
    } else {
        return DOMPurify.sanitize(dirty);
    }
}
```

The bug can be closed.
Thanks.

**Comment by cure53** [comment]
Okay :)

**Comment by dnkolegov** [comment]
> I think that one way to filter JSON in a concrete application is to use isJSON function.

Hello @cure53.
There is one problem with this approach. It is possible to use polyglots that will be XSS and valid JSON.
For example: `{";alert(1);1+":"+"}`.
It is a valid XSS-vector for double-qoute context: 
```
var t = "{";alert(1);1+":"+"}"
```
Any ideas?
Thanks.

**Comment by cure53** [comment]
Allow only alphanumerical labels maybe?

**Comment by dnkolegov** [comment]
Unfortunately, JSON often contains base64 encoded value with `==`, `+`, or even `()`.
My idea is the following:

```
function sanitizeJSON(input) {
    var s = '"' + input + '"';
    // if input can be parsed without erros in double-quote context then input variable is XSS vector
    if (JSParser.parse(s)) {
        return "";
    }
    return json;
}

function sanitize(dirty) {
    if (isJSON(dirty)) {
        return sanitizeJSON(dirty);
    } else {
        return DOMPurify.sanitize(dirty);
    }
}

```

Does it make sense?
Thanks.

**Comment by cure53** [comment]
Hmmmm, looks awfully specific. Why only cover dbl-quotes?

**Comment by dnkolegov** [comment]
Of course it should cover a single-quote context too. But idea is the same: check if an input is successfully parsed in a list of contexts. Maybe it is possible to use one polyglot-context.
