### ISSUE TITLE
Can I use DOMPurify in the Gulp/grunt Build for HTML Files ?

### ISSUE THREAD

**Issue by destromas1** [cure53/DOMPurify#183]
I am using Gulp for building my Frontend app.

Like I have  a Folder `app/views` .  I want to use DOMPurify to purify all Html files  *.html and build those to `/dist` folder.

Is this something I Can do?

**Comment by cure53** [comment]
Pretty sure that this is possible :)

**Comment by destromas1** [comment]
@cure53  Awesome to know!
```
var dirty = '<p>HELLO<iframe/\/src=JavScript:alert&lpar;1)></ifrAMe><br>goodbye</p>';
var clean = DOMPurify.sanitize(dirty);
```

Like this upper code ,

I need to read all string from `.html` File then keep that in a variable something like `dirty` then do the sanitization and write that String into '/dist/index.html` ? Something like that?
Or is there any better way?
Thanks in advance!

**Comment by cure53** [comment]
No idea :D We only provide the library functionality - and are pretty much agnostic towards how folks implement it. But - it sounds like a good idea without knowing more context.

**Comment by destromas1** [comment]
I will check this and If I find any good way , I will let you know  👍

**Comment by cure53** [comment]
Cool :) If you are missing any features or APIs let us know please!
