### ISSUE TITLE
Issue with escaped qutes

### ISSUE THREAD

**Issue by waterplea** [cure53/DOMPurify#186]
Hi there!

I'm new to using DOMPurify, I'm working on some email app and it has generated content from Word/Outlook. When you style text with highlight, Outlook generates FONT tag with background color style, which is invalid. So I want to replace it with SPAN using a hook like this:

```
DOMPurify.addHook('beforeSanitizeElements', function(currentNode, data, config) {
    if (currentNode.tagName === 'FONT') {
       //Do the thing
    }
    return updatedNode;
});
```

However I receive this code from the server and I get escaped quotes in the string. And when I pass this string into DOMPurify using sanitize method it turns this:

`<FONT style=&quot;BACKGROUND-COLOR: #ffff00&quot;>This should be highligted in yellow</FONT>`

Into this:

`<font style="&quot;BACKGROUND-COLOR:" #ffff00&quot;="">This should be highligted in yellow</font>`

Which breaks style attribute. Although it could be fixed by messing with the string prior to feeding it to DOMPurify, I think it could be a common situation and it would probably be better to fix this in DOMPurify itself, if it should support working with strings.

**Comment by waterplea** [comment]
After I fixed the string prior to feeding it to DOMPurify, I noticed that neither beforeSanitizeElements, nor afterSanitizeElements cannot change the actual element tag, even if I return an updated element with different tag inside them. How am I suppose to change the element then?

**Comment by cure53** [comment]
Heya :)

> it would probably be better to fix this in DOMPurify itself, if it should support working with strings.

Nope, not gonna happen. Ever. If we start fiddling around with the strings we receive before they hit the DOM implementation we sanitize with, we open a can of worms. And likely break existing implementations all over the place.

> I noticed that neither beforeSanitizeElements, nor afterSanitizeElements cannot change the actual element tag

Of course you can - that's what the hooks are there for :D I can however not help solve this problem before having seen the code. Let me know how your code looks like and I can help.

**Comment by waterplea** [comment]
Thanks for a quick reply! Sure, I'll fix it prior to DOMPurify then, was just not sure what DOMPurify is supposed to do and what it isn't.

Here's the code I have for replacing FONT tag:

```
DOMPurify.addHook('afterSanitizeElements', function(currentNode, data, config) {
    if (currentNode.tagName === 'FONT') {
      var replacement = document.createElement('SPAN');
      for(var i = 0; i < currentNode.attributes.length; i++){
        var nodeName  = currentNode.attributes.item(i).nodeName;
        var nodeValue = currentNode.attributes.item(i).nodeValue;

        replacement.setAttribute(nodeName, nodeValue);
      }
      replacement.innerHTML = currentNode.innerHTML;
      currentNode = replacement;
    }
    return currentNode;
  });
```

At the end currentNode is indeed SPAN, however if I run:
```
var node = DOMPurify.sanitize("<FONT style='BACKGROUND-COLOR: #ffff00'>This should be highligted in yellow</FONT>");
console.log(node);
```

I get FONT tag.

**Comment by cure53** [comment]
Is this the desired result (not tested on all browsers)?

```javascript
            DOMPurify.addHook('afterSanitizeElements', function(currentNode, data, config) {
                if (currentNode.tagName === 'FONT') {
                    var replacement = document.createElement('span');
                    replacement.innerHTML = currentNode.innerHTML;
                    replacement.style.cssText = currentNode.style.cssText;
                    currentNode.insertAdjacentElement('afterend', replacement);
                    currentNode.parentNode.removeChild(currentNode);
                }
            });

            // Clean HTML string and write into our DIV
            var node = DOMPurify.sanitize("<b><FONT style='BACKGROUND-COLOR: #ffff00'>This should be highligted in yellow</FONT></b>");
            document.write(node);
```

**Comment by waterplea** [comment]
Yes, it works, thank you. Kinda seems counter-intuitive though :)

**Comment by cure53** [comment]
You're welcome ;) 

>  Kinda seems counter-intuitive though :)

Not really given how the DOM works. Take an element, create a replacement, populate it. Attach it after the element, remove the element. 

By the way - here is an API that mostly does the same but is available on older browsers as well:
https://developer.mozilla.org/en-US/docs/Web/API/Element/insertAdjacentHTML#Browser_Compatibility
