### ISSUE TITLE
Sanitize REST JSON response 

### ISSUE THREAD

**Issue by smasam** [cure53/DOMPurify#188]
I want to sanitize REST response which is of type JSON, it pretty much works except for in few places where the sanitizer tries to introduce HTML entity codes, which lands in to JSON parsing issues.

My intention is to sanitize the REST response before being parsed as JSON object, is this supported

**Comment by cure53** [comment]
Hm, not directly. What exactly gets messed up?

**Comment by smasam** [comment]
Here is the sample 

<!doctype html>
<html>
    <head>
		<script src="./lib/purify.js"></script>
		<script>
		
		var dirty = '{"type":"string","value":"<img src=\"test.png\">"}';
		var purifyText = DOMPurify.sanitize(dirty);
		console.log(purifyText);
		console.log(JSON.parse(purifyText));
		
		
		</script>

    </head>
    <body>
        <div>Test Page</div>
        
        <div id="sampleTxt"></div>
    </body>

</html>

Once sanitized JSON.parse complains about double quotes, some times I even find &quote plus double quotes

**Comment by cure53** [comment]
Oh, I understand. Why not parse first, purify later?

```javascript
var json = '{"type":"string","value":"<img src=\"test.png\">"}';
var parsed = JSON.parse(json); 
parsed.value = DOMPurify.sanitize(parsed.value);
console.log(parsed.value);
```

**Comment by smasam** [comment]
This will be the longest form, the REST response will not be this simple it will be a huge JSON strings running into KB's, deeply nested, hence I wanted to apply on the complete JSON at once, Can we make this possible?

**Comment by cure53** [comment]
Short answer: Nope. 

DOMPurify is not meant to first _prepare_ strings from various sources and _then_ sanitize them - but only to take a string when it's prepared already. Else we would have to build connectors for whatever data source and that is far outside our scope.

If we changed the library core for this use case, the next user would come and ask for DOMPurify working with HTML that is embedded in PCDATA elements of an XML response.. and so on :)

**Comment by smasam** [comment]
okey,
I thought JSON should be atleast be supported source as it is most widely used REST response format

**Comment by cure53** [comment]
We are response format-agnostic :) No matter if widely supported or not.

Throw us a string with HTML and we will sanitize it as good as we can. 

If you _cannot_ get hands on that string before you can throw it into DOMPurify, your application has an architectural problem and we cannot solve that for you - sorry.
