### ISSUE TITLE
Can't whitelist attributes as URI-safe

### ISSUE THREAD

**Issue by edg2s** [cure53/DOMPurify#192]
I want to add RDFa attributes to the whiltelist, but I also want them to be able to have values that may not pass `IS_ALLOWED_URI`, e.g.

`<div typeof="mw:Extension/Template">Data</div>`

I can add `'typeof'` to `ALLOWED_ATTR` but there's no way to add to `URI_SAFE_ATTRIBUTES`

**Comment by cure53** [comment]
Hmmmm, good point! This should indeed be worth a core-fix.

**Comment by cure53** [comment]
This should technically do - shouldn't it?

```javascript
        if (cfg.ADD_URI_SAFE_ATTR) {
            _addToSet(URI_SAFE_ATTRIBUTES, cfg.ADD_URI_SAFE_ATTR);
        }
```

According to a quick local test, that should already be sufficient:

```javascript
            // Specify dirty HTML
            var dirty = document.body;
            
            // Clean HTML string and write into our DIV
            var clean = DOMPurify.sanitize('<b typeof="bla:h">123</b>', {ALLOWED_ATTR: ['typeof'], ADD_URI_SAFE_ATTR: ['typeof']});
            console.log(clean); // <b typeof="bla:h">123</b>
```

**Comment by edg2s** [comment]
Yeah, looks great.

**Comment by cure53** [comment]
Assuming the BrowserStack tests will be green too, the only problem left now is *node->sanitize->string* in MSIE9 versus *node->sanitize->node* in all other browsers - correct?

**Comment by edg2s** [comment]
That sounds about right. _initDocument would work, but for the outerHTML issue I mentioned earlier.
