### ISSUE TITLE
Demo site's Certificate Revoked

### ISSUE THREAD

**Issue by ramakay** [cure53/DOMPurify#194]
The Demo site is inaccessible because Google says your certificate is Revoked https://cure53.de/purify

**Comment by cure53** [comment]
Hm, works for me - just tested with latest Chrome and Firefox. What's the error you see?

**Comment by ramakay** [comment]
http://screencast.com/t/27a68SZTIA9a

**Comment by cure53** [comment]
Interesting. I get no errors with latest Chrome 55 on Linux/Windows.
But I do get an error on Chrome Canary.

What's the Chrome version you are using?
