### ISSUE TITLE
sanitizeHTML with empty HTML returns null on IE11

### ISSUE THREAD

**Issue by MasahiroMorita** [cure53/DOMPurify#198]
When using `RETURN_DOM` and `RETURN_DOM_FRAGMENT` options,  `sanitizeHTML` with empty HTML returns `null` on IE11. On Chrome or other browsers, it returns empty DocumentFragment object correctly.

Please seee this: [JSFiddle](https://jsfiddle.net/ssxf2zwx/3/).

**Comment by cure53** [comment]
Oh, that is unpleasant - thanks for this finding! We will have a look and see what we can do.

**Comment by cure53** [comment]
I think I found the problem and may have fixed it. Local tests are looking well, now running CI. We'll release 0.8.5 right after - had enough small changes in the past to justify a new release :)

**Comment by MasahiroMorita** [comment]
Thanks for your quick response!
I'm looking forward to the release.

**Comment by cure53** [comment]
You're welcome, please let us know if it works for you as expected.
