### ISSUE TITLE
Add DOMPurify to jsdelivr cdn service

### ISSUE THREAD

**Issue by agauniyal** [cure53/DOMPurify#204]
Please add DOMPurify to jsdelivr cdn service, I couldn't find it here - https://www.jsdelivr.com/?query=dompurify

I'm currently using cdnjs version but it would be much better if DOMPurify is also available there so that all of our cdn resources are available at a single place. Thankyou :)

**Comment by cure53** [comment]
I'll have a look :)

**Comment by cure53** [comment]
Alright, PR is out, let's see https://github.com/jsdelivr/jsdelivr/pull/16824

**Comment by agauniyal** [comment]
Thanks a lot 👍

**Comment by cure53** [comment]
Done :)

https://github.com/jsdelivr/jsdelivr/tree/master/files/dompurify
https://www.jsdelivr.com/?query=dompurify

**Comment by agauniyal** [comment]
@cure53 could you please check the cdn is configured properly? It is giving me error - ### Could not find file specified in mainfile for project: dompurify.

**Comment by cure53** [comment]
Looks okay to me:

https://cdn.jsdelivr.net/dompurify/0.8.5/purify.min.js
