### ISSUE TITLE
Safari (All Platforms) <input type="file"> replaced with <input type="text">

### ISSUE THREAD

**Issue by reddogtutby** [cure53/DOMPurify#207]
> Safari (All Platforms) <input type="file"> replaced with <input type="text">

### Background & Context

Safari specific issue. 

#### Input

&lt;input type="file"&gt;

#### Given output

&lt;input type="text"&gt;

#### Expected output

&lt;input type="file"&gt;

**Comment by cure53** [comment]
Yikes! That looks to me like a bug in Safari / Webkit. Is the same behavior visible on other browsers?

**Comment by reddogtutby** [comment]
No, Chrome on OSX works correct, looks like its Safari specific

**Comment by cure53** [comment]
I think I found the problem. Safari cannot seem to use `type="file"` in conjunction with `node.setAttribute`. Looking for a fix now.

**Comment by cure53** [comment]
Okay, I think we have a working fix, can you check please? :)

**Comment by reddogtutby** [comment]
Thanks, fixed, checked in Safari (iOS, OSX)

**Comment by cure53** [comment]
Cool, thx!
