### ISSUE TITLE
Bug strips out id attributes that match global JavaScript variable names

### ISSUE THREAD

**Issue by PickJBennett** [cure53/DOMPurify#208]
> This issue proposes a bug that strips out id attributes that match global window-level JavaScript variable names, even when "id" is specifically added to the allowed attributes array.

### Background & Context

I've implemented the DOMPurify JavaScript into a webpage with lots of global window-level variables, such as "a", "b", "c", etc. The purpose of this is to process and filter out any dangerous SVG code.

### Bug

Every time I parse a SVG with DOMPurify, when the SVG itself has `id="a"`, `id="b"`, or `id="c"`, these attributes and values are removed entirely. This breaks the SVG image more often than not.

Notice `id="s"` is NOT removed from the processed output (this is what I want to happen).

#### Input

`<svg viewBox="-50 -50 100 100" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><title>SVG Logo</title><rect id="background" x="-50" y="-50" width="100" height="100" rx="4" fill="#f90"/><rect id="top-left" x="-50" y="-50" width="50" height="50" rx="4" fill="#ffb13b"/><rect id="bottom-right" width="50" height="50" rx="4" fill="#de8500"/><use stroke="#f90" stroke-width="22.6" xlink:href="#a"/><circle r="26"/><use stroke="#000" stroke-width="12" xlink:href="#a"/><g id="a"><g id="b"><g id="c"><circle id="n" cy="-31.6" r="7.1" fill="#fff"/><path d="m0 31.6v-63.2" stroke="#fff" stroke-width="10"/><use y="63.2" xlink:href="#n"/></g><use transform="rotate(90)" xlink:href="#c"/></g><use transform="rotate(45)" xlink:href="#b"/></g><path id="text-backdrop" d="m44.68 0v40c0 3.333-1.667 5-5 5h-79.38c-3.333 0-5-1.667-5-5v-40"/><path id="shine" d="m36 4.21c2.9 0 5.3 2.4 5.3 5.3v18c-27.6-3.4-54.9-8-82-7.7v-10.2c0-2.93 2.4-5.3 5.3-5.3z" fill="#3f3f3f"/><use stroke="#000" stroke-width="7.4" xlink:href="#s"/><g id="svg-text" stroke="#fff" stroke-width="6.4"><g id="s"><path fill="none" d="m-31.74 31.17a8.26 8.26 0 1 0 8.26 -8.26 8.26 8.26 0 1 1 8.26 -8.26M23.23 23h8.288v 8.26a8.26 8.26 0 0 1 -16.52 0v-16.52a8.26 8.26 0 0 1 16.52 0"/><g stroke-width=".5" stroke="#000"><path d="m4.76 3h6.83l-8.24 39.8h-6.85l-8.26-39.8h6.85l4.84 23.3z" fill="#fff"/><path d="m23.23 19.55v6.9m4.838-11.71h6.9m-70.16 16.43h6.9m9.62-16.52h6.9" stroke-linecap="square"/></g></g></g></svg>`

#### Given output

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-50 -50 100 100" width="150" height="150" preserveAspectRatio="xMidYMid meet"><rect fill="#f90" rx="4" height="100" width="100" y="-50" x="-50" id="background"></rect><rect fill="#ffb13b" rx="4" height="50" width="50" y="-50" x="-50" id="top-left"></rect><rect fill="#de8500" rx="4" height="50" width="50" id="bottom-right"></rect><use xlink:href="#a" stroke-width="22.6" stroke="#f90"></use><circle r="26"></circle><use xlink:href="#a" stroke-width="12" stroke="#000"></use><g><g><g><circle fill="#fff" r="7.1" cy="-31.6" id="n"></circle><path stroke-width="10" stroke="#fff" d="m0 31.6v-63.2"></path><use xlink:href="#n" y="63.2"></use></g><use xlink:href="#c" transform="rotate(90)"></use></g><use xlink:href="#b" transform="rotate(45)"></use></g><path d="m44.68 0v40c0 3.333-1.667 5-5 5h-79.38c-3.333 0-5-1.667-5-5v-40" id="text-backdrop"></path><path fill="#3f3f3f" d="m36 4.21c2.9 0 5.3 2.4 5.3 5.3v18c-27.6-3.4-54.9-8-82-7.7v-10.2c0-2.93 2.4-5.3 5.3-5.3z" id="shine"></path><use xlink:href="#s" stroke-width="7.4" stroke="#000"></use><g stroke-width="6.4" stroke="#fff" id="svg-text"><g id="s"><path d="m-31.74 31.17a8.26 8.26 0 1 0 8.26 -8.26 8.26 8.26 0 1 1 8.26 -8.26M23.23 23h8.288v 8.26a8.26 8.26 0 0 1 -16.52 0v-16.52a8.26 8.26 0 0 1 16.52 0" fill="none"></path><g stroke="#000" stroke-width=".5"><path fill="#fff" d="m4.76 3h6.83l-8.24 39.8h-6.85l-8.26-39.8h6.85l4.84 23.3z"></path><path stroke-linecap="square" d="m23.23 19.55v6.9m4.838-11.71h6.9m-70.16 16.43h6.9m9.62-16.52h6.9"></path></g></g></g></svg>`

#### Expected output

`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="-50 -50 100 100" width="150" height="150" preserveAspectRatio="xMidYMid meet"><rect fill="#f90" rx="4" height="100" width="100" y="-50" x="-50" id="background"></rect><rect fill="#ffb13b" rx="4" height="50" width="50" y="-50" x="-50" id="top-left"></rect><rect fill="#de8500" rx="4" height="50" width="50" id="bottom-right"></rect><use xlink:href="#a" stroke-width="22.6" stroke="#f90"></use><circle r="26"></circle><use xlink:href="#a" stroke-width="12" stroke="#000"></use><g id="a"><g id="b"><g id="c"><circle fill="#fff" r="7.1" cy="-31.6" id="n"></circle><path stroke-width="10" stroke="#fff" d="m0 31.6v-63.2"></path><use xlink:href="#n" y="63.2"></use></g><use xlink:href="#c" transform="rotate(90)"></use></g><use xlink:href="#b" transform="rotate(45)"></use></g><path d="m44.68 0v40c0 3.333-1.667 5-5 5h-79.38c-3.333 0-5-1.667-5-5v-40" id="text-backdrop"></path><path fill="#3f3f3f" d="m36 4.21c2.9 0 5.3 2.4 5.3 5.3v18c-27.6-3.4-54.9-8-82-7.7v-10.2c0-2.93 2.4-5.3 5.3-5.3z" id="shine"></path><use xlink:href="#s" stroke-width="7.4" stroke="#000"></use><g stroke-width="6.4" stroke="#fff" id="svg-text"><g id="s"><path d="m-31.74 31.17a8.26 8.26 0 1 0 8.26 -8.26 8.26 8.26 0 1 1 8.26 -8.26M23.23 23h8.288v 8.26a8.26 8.26 0 0 1 -16.52 0v-16.52a8.26 8.26 0 0 1 16.52 0" fill="none"></path><g stroke="#000" stroke-width=".5"><path fill="#fff" d="m4.76 3h6.83l-8.24 39.8h-6.85l-8.26-39.8h6.85l4.84 23.3z"></path><path stroke-linecap="square" d="m23.23 19.55v6.9m4.838-11.71h6.9m-70.16 16.43h6.9m9.62-16.52h6.9"></path></g></g></g></svg>`

### Feature

Somehow isolate the executing JavaScript from these global variable names, so these important attributes remain.

**Comment by cure53** [comment]
That's actually a security feature and helps us to prevent DOM Clobbering.

Have you tried to set the configuration flag `SANITIZE_DOM` to false? That should get rid of the problem for you with ease:

```javascript
var clean = DOMPurify.sanitize(dirty, {SANITIZE_DOM: false});
```

**Comment by PickJBennett** [comment]
Well, that seems to have worked like a charm! Thank you so much! I'll close this bug then. :)

**Comment by cure53** [comment]
Perfecto :) Yw!
