### ISSUE TITLE
dist/purify.js is broken

### ISSUE THREAD

**Issue by neilj** [cure53/DOMPurify#220]
The current `dist/purify.js` file **does not work** in a browser. It tries to assign to `module.exports` and `module` is undefined. Was this really not tested before the PR was merged?

**Comment by tdeekens** [comment]
Have you checked the integration tests? To my knowledge they test the dist file specifically. Will investigate later. Thanks for reporting!

**Comment by cure53** [comment]
Still looks broken to me.

**Comment by cure53** [comment]
Looking good now :) @neilj What thinks you?

**Comment by tdeekens** [comment]
Weeeh.

**Comment by neilj** [comment]
Yep, that seems to be working again now. Thanks guys.

**Comment by cure53** [comment]
<3
