### ISSUE TITLE
Add sanitization through tagged template literals

### ISSUE THREAD

**Issue by tdeekens** [cure53/DOMPurify#223]
> This issue proposes feature to use [template literals](http://exploringjs.com/es6/ch_template-literals.html) to sanitize HTML.

### Background & Context

When sanitizing HTML using DOMPurify we mostly have a variable at hand which we want sanitized. This is definately one of the main use cases. However, we could also support template literals and their nature of invoking a function ([tagged template literals](http://exploringjs.com/es6/ch_template-literals.html#_tagged-template-literals)) to allow inline santization when defining an HTML sting.

### Feature

Examples of where this might help are already in our readme e.g. 

```js
DOMPurify.sanitize('<img src=x onerror=alert(1)//>');
```

```js
import { safeHtml } from 'DOMPurify';

const html = safeHtml`
   <body>
       <img src=x onerror=alert(1)//>
   <body/>
`;
```

To my knowledge you can not pass options to tagged template literals. If we would want to support our options e.g. `{FORBID_TAGS: ['style']}` we could create a factory. `safeHtml` would be our default without options whereas `createSafeHtml(options)` would return a custom tagged template literal function configured with options passed.

**Comment by cure53** [comment]
Ah, awesome, we wanted to build this anyway some time ago. Thx :D

**Comment by tdeekens** [comment]
Cool that it hits positive feedback.

> provide context and make use of the dollar-curly notation

means string interpolation? 

I think a 

```js
const html = safeHtml`
   <body>
       <img src=x onerror=alert(1)//>
       ${myHref}
   <body/>
`;
```

would work out of the box. We can check how it could work or what we plan on doing if the user has functions there as in

```js
const html = safeHtml`
   <body>
       <img src=x onerror=alert(1)//>
       ${(someArgWeProvide) => `some other string` }
   <body/>
`;
```

in case we want to pass an arg along. Styled-components passes the `props` along. I am not sure if there a valid use case for us here? A good article on the whole thing can be found [here](http://mxstbr.blog/2016/11/styled-components-magic-explained/).

**Comment by cure53** [comment]
I mostly meant things like:

```javascript
const html = safeHtml`
   <body>
       <a href="${url}">CLICKME</a>
   <body/>
`;
```

**Comment by tdeekens** [comment]
Yeah I think we have to support that as it's expected behaviour with tagged template literals so a

```js
const url = 'http://evil.com'

const html = safeHtml`<img src=x onerror=alert(1)//> ${url}.`
```

will make our function get 

```js
// -> [<img src=x onerror=alert(1)//> ", "."] "http://evil.com"
```

**Comment by tdeekens** [comment]
I however don't think that we can make this work without a breaking change to how we export our API if we don't "dump" the function onto `DOMPurify` itself. If we do that it would look like

```js
DOMPurify.safeHtml`
  evil
`
```

Whereas in order to allow

```js
import { safeHtml } from 'DOMPurify';
```

We would have to add another export to our bundle which will break consumers as our current `default` export (being the factory) will be assigned to `const DOMPurify = require('DOMPurify').default`. Normally that's not what people want so they either decide to only have one `default` export behind an API object (like we do) or make all `exports` named. If we decide to go with the latter it would look something like this - if possible.

```js
import { sanitize, createDOMPurify } from 'DOMPurify';

sanitize('evil')

const wrappedDOMPurify = createDOMPurify(globalThing);

wrappedDOMPurify.sanitize('evil');
```

with our `safeHtml` just being another named export

```js
import { sanitize, safeHtml } from 'DOMPurify';
```

Hope this makes sense.

**Comment by cure53** [comment]
> I however don't think that we can make this work without a breaking change to how we export our API

Breaking changes are not acceptable for the little bit of extra sugar this feature would add.

**Comment by bryanbraun** [comment]
This decision makes sense... you gotta be careful about breaking changes.

I'm still looking for a sanitization library that supports tagged template literals... do you know of any others that provide this functionality?

**Comment by tdeekens** [comment]
Have you checked: https://github.com/declandewet/common-tags?

**Comment by bryanbraun** [comment]
Nice! That's a great list for node projects.

I needed something for frontend web, and [this one](https://github.com/AntonioVdlC/html-template-tag) in [the list at the bottom of the Common Tags readme](https://github.com/declandewet/common-tags#other-es2015-template-tag-modules) looks perfect.
