### ISSUE TITLE
Examples in README are outdated

### ISSUE THREAD

**Issue by ydaniv** [cure53/DOMPurify#225]
A bit confusing, needs to be updated with output from latest version.

**Comment by cure53** [comment]
Which ones are outdated? cc @tdeekens

**Comment by tdeekens** [comment]
Which ones? Examples shouldn't be affected by our "recent" refactoring.

**Comment by ydaniv** [comment]
e.g.: `<p>abc<iframe/\/src=jAva&Tab;script:alert(3)>def ` now produces `<p>abcdef</p>` and not `<p>abc</p>

Didn't try all buy most, there aren't that many there (;

**Comment by cure53** [comment]
Aaaah, okay. I sent some fixes, can you check?
