### ISSUE TITLE
Enable allowing only tags of specific language(s)

### ISSUE THREAD

**Issue by ydaniv** [cure53/DOMPurify#228]
E.g: I'd like to enable SVG only.

Since DOMPurify has a whitelists for each specific markup language it supports, I'd like to leverage that to sanitize input and have the output include _only_ tags from languages I've enabled.

This could either be done by exporting the tags lists, or by exposing extra configs.

Will happily provide a PR if needed.

Thanks!

**Comment by ydaniv** [comment]
Also, simply exposing `TAGS` and `ATTRS` on `DOMPurify` will also do the job.

**Comment by cure53** [comment]
Why not just use `ALLOWED_TAGS`?

**Comment by ydaniv** [comment]
that's what I'm doing, but at least I'd like to rely on the existing source of default tags, and for example, use `TAGS.svg` instead of maintaining yet another list of tags.

**Comment by cure53** [comment]
Oh, so we would need for example profiles. 

Like, one profile for HTML, one for SVG, one for MathML? And maybe one (default profile) that has them all?

**Comment by ydaniv** [comment]
That will also do. As for now, I just exposed the lists, as above, and entered it back as:
```
DOMPurify.sanitize({ ALLOWED_TAGS: DOMPurify.TAGS.svg, ALLOWED_ATTRS: DOMPurify.ATTRS.svg})
```
With this access I can, for example, decide whether to add filters, etc.

But higher level params (or profiles) that will allow that are also welcome.

**Comment by cure53** [comment]
Got it. Then I would propose to add a profile config option using an array of strings, like:

`DOMPurify.sanitize({ PROFILES: ['svg', 'mathMl'] })`

That should allow all SVG and MathML but no HTML. Would that work?

**Comment by ydaniv** [comment]
yep

**Comment by cure53** [comment]
Cool, you wanna cook up a PR (a.k.a it's urgent) or shall we implement it (might take a few days)?

**Comment by ydaniv** [comment]
Let's say, if it's urgent and you still didn't commit anything I'll go ahead with a PR. OK?

**Comment by cure53** [comment]
Okay :)

**Comment by cure53** [comment]
Check please if that already works for you!

**Comment by ydaniv** [comment]
beautiful!

I see you didn't add `ATTRS`, will that be completely redundant?

I'm wondering whether it could tighten things a bit further...

**Comment by cure53** [comment]
Not yet and on purpose even so :) I am not sure if it's needed - what do you think?

**Comment by ydaniv** [comment]
hmmm... if you're already enforcing only attributes of specific profile for the correlating tags, then we're good. Otherwise having this extra safety would be great.

**Comment by cure53** [comment]
You might be right, adding that.

**Comment by ydaniv** [comment]
:+1

**Comment by cure53** [comment]
Test are still red but that seems to be a glitch. On it, other than that I think it's done :)

**Comment by ydaniv** [comment]
Great!

I see you add `ATTRS.xml` by default for `svg` and `svgFilters` profiles. Can these be excluded on demand?

**Comment by cure53** [comment]
I see no danger in them and leaving them out would destroy many SVGs.

**Comment by cure53** [comment]
Also, tests are green again, the BrowserStack glitch is gone :D I would be ready to close this.

**Comment by ydaniv** [comment]
👍 

I see what you mean, regarding xml attrs, but I also have a profile where any `xlink`s aren't permitted, and hence `xmlns` isn't required as well.

In that case we strip all of these. Not that uncommon, even [svgo](https://github.com/svg/svgo) removes it in some cases.

So any chance for opting out?

**Comment by cure53** [comment]
I would say no. It can already be done using the `FORBID_ATTR` directive and we would double-implement features if we make the profiles more granular.

**Comment by ydaniv** [comment]
fair enough. Thanks for all the fish!

**Comment by cure53** [comment]
Yw :)
