### ISSUE TITLE
New profiles remove valid attributes and tags

### ISSUE THREAD

**Issue by ydaniv** [cure53/DOMPurify#230]
Now with new profiles, attributes that are valid in more that one profile (e.g. `width` and `height`) and would have been duplicates, are now removed when selecting a single profile.

E.g.:
This:
```
<svg viewBox="0 0 120 120">
    <rect y="10" x="10" width="50" height="100"/>
</svg>
```
Becomes:
```
<svg viewBox="0 0 120 120">
    <rect y="10" x="10"/>
</svg>
```
Where expected is:
```
<svg viewBox="0 0 120 120">
    <rect y="10" x="10" width="50" height="100"/>
</svg>
```

So when using profiles, need to make sure that valid attributes from excluded profiles are whitelisted for included profiles where they should be.

Thanks!
~Y

**Comment by cure53** [comment]
There is two ways we can fix this:

 * Create a file with shared attributes
 * Extend the existing collections and have duplicate attributes

I did the last one, PR from you is welcome :)

**Comment by ydaniv** [comment]
I'm on it (: 👍

**Comment by cure53** [comment]
Awesome, thx! :)

**Comment by ydaniv** [comment]
BTW, I'm using [this page](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute) as references, and I see some missing, I guess it's mostly on purpose or stuff related to SVG2, so currently not adding new ones.

Let me know if you'd like otherwise.

**Comment by cure53** [comment]
Yeah, some of fancy SVG2-ones we don't have yet.

**Comment by ydaniv** [comment]
OK, so not adding anything new.

Since attribute lookup is already implemented as a Set it's trivial to just add duplicates in `attrs.js`.
So I think I've covered all of them.

**Comment by cure53** [comment]
Yeah, we can check after this PR came through what else is harmless and worth adding.

**Comment by cure53** [comment]
Okay, local tests look fine, let's see what Browserstack says :)

**Comment by ydaniv** [comment]
Woops, problemo. We need to do the same for tags. E.g. it's removing `style` tags from SVG in non HTML profiles.

Shall I open a new issue/PR?

**Comment by cure53** [comment]
Yes, plz!
