### ISSUE TITLE
xlink:href filtering (particularly in <use>)

### ISSUE THREAD

**Issue by phinch** [cure53/DOMPurify#233]
When filtering SVGs, DOMPurify seems to be over-eager in eliminating certain tags - I noticed it in one of my SVG `<use>` tags being removed. Specifically, I defined a path in an SVG file and then referred to it using a `use` tag later in the document: 

```
<defs>
    <path id="path-1" d="M11.2357619,11.3004444 ..."></path>
</defs>
...
<mask id="mask-2" sketch:name="Clip 12" fill="white">
    <use xlink:href="#path-1"></use>
</mask>
```

but after being sanitized, the `<mask>` became:

```
<mask id="mask-2" sketch:name="Clip 12" fill="white">

</mask>
```

with the `<use>` tag removed, and the SVG image was thus missing that element when it was loaded. 

In my understanding, it should be safe to have internal references in `xlink:href` paths like I had above, so long as other scripts in the file are sanitized. Is there any way to improve the sanitizer to only block dangerous (e.g. cross-origin) hrefs inside `<use>` tags?

**Comment by cure53** [comment]
Hmmm, I think blocking only same-origin `xlink:href` for `<use>` is risky as all you need to make an XSS out of it is an Open Redirect.

I would recommend working with a hook, that checks if the xlink:href starts with # and then permit it. Should be easily doable by allowing `<use>` via config and then using a hook like `afterSanitizeAttributes`. Would that work for you?

**Comment by cure53** [comment]
I think this might do, no?

```html
<!doctype html>
<html>
    <head>
        <script src="../purify.js"></script>
    </head>
    <body>
        <!-- Now let's sanitize that content -->
        <script>
            'use strict';
           
            DOMPurify.addHook('afterSanitizeAttributes', function(node){
                if(node.hasAttribute('xlink:href') && !node.getAttribute('xlink:href').match(/^#/)){
                    node.remove();
                } 
            });

            // Clean HTML string and write into our DIV
            var clean = DOMPurify.sanitize("<svg>\
                <use xlink:href='#foo' />\
                <use xlink:href='//evil' />\
            </svg>", {ADD_TAGS: ['use']});
            console.dir(clean);
        </script>
    </body>
</html>
```

**Comment by phinch** [comment]
That looks good to me, thanks! I'm still pretty unfamiliar with XSS, so I wasn't sure if it was possible to sneak some javascript in after the `#`, but this works great for me. Thanks!

**Comment by rodrigofariow** [comment]
Glad there is a work around for this! :) 

> https://github.com/cure53/DOMPurify/issues/233#issuecomment-314384301

Is there a reason why this is not done by default, though? Performance related?
I feel like it's a relatively common use case to have `use` tags on svgs.

Thanks for your time.
