### ISSUE TITLE
Using SVG profile with KEEP_CONTENT: false removes TEXT content

### ISSUE THREAD

**Issue by ydaniv** [cure53/DOMPurify#236]
Apparently when using the config combination of `{USE_PROFILES: {svg: true}, KEEP_CONTENT: false}` the content of `<text>` tags is completely removed.

The following test will fail:
```
assert.equal(
  DOMPurify.sanitize(
    '<svg><text>HEY</text></svg>',
    {KEEP_CONTENT: false, USE_PROFILES: {svg: true}}
  ),
  '<svg><text>HEY</text></svg>');
});
```
Giving the following output:
```
not ok 1 - expected: "<svg><text>HEY</text></svg>", got: "<svg><text></text></svg>"
```

When removing one or both of the config options above the test passes.

Trying to find the cause, but not much luck so far :(

**Comment by ydaniv** [comment]
OK, I think I've found it. `#text` tags are now always removed in case profiles are used and `KEEP_CONTENT: false` is set.

So you probably want to add
```
addToSet(ALLOWED_TAGS, TAGS.text);
```
To both `html` and `svg` profiles (maybe others as well?).

Also, regardless of that, it's not possible to combine `ALLOWED_TAGS` option together with a profile, so you can't fix this by adding `ALLOWED_TAGS: ['#text']` to config. Not sure whether this is intended.

**Comment by cure53** [comment]
I think adding this to the HTML/MathML/SVG profiles is okay. Technically, this should be present in all profiles.

> so you can't fix this by adding ALLOWED_TAGS: ['#text'] to config. Not sure whether this is intended.

Is this only for text nodes or pother elements as well? The latter would be a bug.

**Comment by ydaniv** [comment]
OK, so I'll send a PR with `TAGS.text` added to these profiles.

From looking at the code I see you reset `ALLOWED_TSGS = []` after taking the value from config, so I guess to all elements, hence a bug.

**Comment by ydaniv** [comment]
Oops, I confused `ALLOWED_TAGS` with `ADD_TAGS`. And using the latter works fine.
As it stands now, `USE_PROFILES` and `ALLOWED_TAGS` are conflicting, and `USE_PROFILES` will override `ALLOWED_TAGS`.

I've fixed the text issue with profiles, for now.

**Comment by cure53** [comment]
So, `ADD_TAGS` adds more tags to the white-list, `ALLOWED_TAGS` defines the white-list and `USE PROFILES` sets a baseline - which should be customizable via `ADD_TAGS` - yet when you work with `ALLOWED_TAGS` they should have priority.

So I think they are not conflicting.

**Comment by ydaniv** [comment]
OK, but currently, in the code, if `USE_PROFILES` is set `ALLOWED_TAGS` and `ALLOWED_ATTR` are bot reset to `[]`. It's simply the current procedural order.

I could change it so that if `USE_PRODILES` is set, it sets the baseline, otherwise it defaults default, meaning all tags (same for attributes, of course). And then, if `ALLOWED_TAGS` is set in config, it overrides it.

Shall I add with that?

**Comment by cure53** [comment]
What would be a use-case where we need both `ALLOWED_TAGS` and `USE_PROFILES`?

Not sure yet why we _wouldn't_ reset `ALLOWED_TAGS` if a profile is picked.

**Comment by ydaniv** [comment]
I think there isn't such use-case, but simply current config options could be confusing and give bad developer experience.

Just suggesting this as a most expected behavior. But I'll skip this and send the PR.

**Comment by cure53** [comment]
I think it makes no sense:

`ALLOWED_TAGS` makes sure that *only the given tags are permitted* for use, none other. There is no need for a profile if `ALLOWED_TAGS` are used.

`ADD_TAGS` however makes perfect sense. First set a profile, then add tags you like to permit as well.

**Comment by ydaniv** [comment]
Yes, that's what I said 👍

**Comment by cure53** [comment]
Ack :)

**Comment by cure53** [comment]
I fixed the tests, should be good. Will close when confirmed green :)

**Comment by ydaniv** [comment]
wOOt! thanks!

Any ETA on new release?

**Comment by cure53** [comment]
> Any ETA on new release?

I think we are ready. Let's wait a week until the profiles feature has been tested a bit more and the go-time.

**Comment by ydaniv** [comment]
👍
