### ISSUE TITLE
Node crashes on the "import" keyword

### ISSUE THREAD

**Issue by strugee** [cure53/DOMPurify#239]
DOMPurify 1.0.0 is causing tests to fail across Node versions for a project I maintain. Node 4 for example fails with "SyntaxError: Unexpected reserved word" on `import` in `src/purify.js`, while Node 8 fails with "SyntaxError: Unexpected token import". Note that we're on a slightly older version of JSDOM because newer versions dropped support for Node 4 (which we still need to maintain), though I don't think that's the issue.

https://travis-ci.org/pump-io/pump.io/jobs/264784683 is an example of a Travis job which failed because of this upgrade.

**Comment by strugee** [comment]
Thanks for your work on DOMPurify by the way - I really appreciate it <3

**Comment by tdeekens** [comment]
Sounds like a transpilation issue by a lack thereof. I cant remember by heart if DOMPurify has main/module/browser entries in the package.json pointing to the bundles. With that node should consume the UMD or CJS version. Will check later. Sorry for the troubles.

**Comment by cure53** [comment]
@tdeekens I believe the PR broke the tests:

https://travis-ci.org/cure53/DOMPurify/jobs/265070621

**Comment by tdeekens** [comment]
Why do we not run tests of a PR locally before merging and just hit merge without a word. Sorry but this is the 2-3rd time this happens where I am just trying to help inbetween things.

**Comment by cure53** [comment]
Because it's the browser tests and they suck to run offline. Right now there is also a bug on BrowserStack that is causing the build to be red. This is usually a hiccup that sometimes comes and sometimes doesn't.

**Comment by tdeekens** [comment]
Yeah I think we need something closer to BrowerStack to run on PRs like a sample against one browser or a karma run.

**Comment by cure53** [comment]
Is there any way we can run the BrowserStack tests before actually merging?

**Comment by tdeekens** [comment]
Sure. We should probably extract the run-script test:ci into a scripts/test-ci.js switch over the env vars and run BS tests only for 1-2 browsers on a PR. We disabled it due to the quota problem with BS as we're on a free plan.

**Comment by tdeekens** [comment]
If we'd pay, we'd preferably run everything against the whole fleet of browsers at any time.

**Comment by cure53** [comment]
Yeah.. anyhow :) Let's get back to the topic. Anything I can do?

**Comment by ydaniv** [comment]
Aren't there any alternatives for OS projects? Maybe [Sauce Labs](https://saucelabs.com/open-source)? they have OS plans.

**Comment by cure53** [comment]
We in fact have a generous OS plan from BrowserStack. Yet no unlimited requests.

**Comment by tdeekens** [comment]
Not really. It's just that I am at work. I can have a look soon but not now.

**Comment by strugee** [comment]
I would suggest yanking the 1.0.0 release until this is fixed, since it's breaking all Node.js version.

**Comment by tdeekens** [comment]
Its not a recent bug. It wasnt working for a long time. Sorry again.

**Comment by tdeekens** [comment]
Let's hope that [this](https://github.com/cure53/DOMPurify/pull/243) fixes master I'll the dig some deeper later on.

**Comment by strugee** [comment]
@tdeekens no problem!

I realize it wasn't a recent bug but it only recently appeared for npm users... seems like a shame to have a known-broken version just sitting out there.

**Comment by tdeekens** [comment]
Yes. Absolutely. Sadly, I dont think we can unpublish at this time.  Even if the last 3-4 versions are broken.

**Comment by strugee** [comment]
@tdeekens I'm not sure I follow - why can't this be unpublished? No one will be using it since it's broken.

**Comment by tdeekens** [comment]
Due to the rules of play for unpublishing npm modules. http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy
Moreover, it's not only an npm module. Most people just use the UMD bundle in the browser. That one still works fine. It's just that node goes after whats under main in the package.json which goes to src. Which will work whenever consumers have babel registered. I dont want to just pin it to UMD but also want a tree shakeable version offered.

**Comment by cure53** [comment]
I merged the recent PR, what's the status now?

**Comment by tdeekens** [comment]
Sadly CIs is still red for unknown reasons. Will set aside some time tomorrow to fix this properly. This is too much poking in the dark with PRs being tested at least in a smoke fashion. Sorry again.

**Comment by cure53** [comment]
Any news here? Anything that I can help with?

**Comment by tdeekens** [comment]
Currently working on it. Just got home.

**Comment by cure53** [comment]
Releasing 1.0.1 now which should fix the issue.

**Comment by cure53** [comment]
@strugee Is the bug fixed for you?

**Comment by strugee** [comment]
Yes, all tests passing now :tada:

Thanks all!
