### ISSUE TITLE
VERSION is not defined

### ISSUE THREAD

**Issue by khakulov** [cure53/DOMPurify#242]
You don't have transpiled your internal src/* code for node.

![image](https://user-images.githubusercontent.com/441436/29405656-d0052500-833e-11e7-8946-be80e5451805.png)

![image](https://user-images.githubusercontent.com/441436/29405693-ecd54552-833e-11e7-9c33-ac0c6cb81b0b.png)

**Comment by tdeekens** [comment]
Sorry, yes. We're working on that. The current tip of `master` has the needed entries in the `package.json` for `main`, `module` and `browser`. We only have one issue with CI which will be fixed in #241 and then we'll - I hope - release 1.0.1. /cc @cure53

**Comment by silviopaganini** [comment]
any updates on this issue?

**Comment by cure53** [comment]
cc @tdeekens

**Comment by cure53** [comment]
Releasing 1.0.1 now which should fix the issue.

**Comment by cure53** [comment]
@khakulov Is the bug fixed for you? We are planning to release soon, thus asking.

**Comment by khakulov** [comment]
@cure53 yes, the bug is fixed in new Release 1.0.1.

**Comment by cure53** [comment]
Thx!
