### ISSUE TITLE
Usage of DOMPurify requires "unsafe-eval" CSP since 1.0.0

### ISSUE THREAD

**Issue by frigus02** [cure53/DOMPurify#249]
As described in the [CSP spec](https://w3c.github.io/webappsec-csp/#directive-script-src), using `Function(...)` with a string requires the "unsafe-eval" CSP rule.

This is now the case with the implementation of `getGlobal`:

https://github.com/cure53/DOMPurify/blob/6185fe544a9fdd21453fbcddea608dcd35ace040/src/purify.js#L5-L8

I'm not sure why this pattern is used here. I guess you want to be sure to get the global object.

Do you think you can release a CSP compliant version of DOMPurify, which just returns `window`?

**Comment by cure53** [comment]
Good point, can we work around that @tdeekens?

**Comment by tdeekens** [comment]
As far as I remember it was needed to either get the `node.global` or the `window`. Suggestions welcome.

**Comment by tdeekens** [comment]
Not sure if moving to https://github.com/purposeindustries/window-or-global/blob/master/lib/index.js would solve the issue while still be working.

**Comment by cure53** [comment]
It would for sure not cause CSP warnings :D

**Comment by tdeekens** [comment]
The problem with the library is that `this` will be rewritten to undefined using rollup (https://github.com/rollup/rollup/wiki/Troubleshooting#this-is-undefined). I am not really sure what the "semantics" behind the idea for "root" at say https://github.com/cure53/DOMPurify/blob/a992d3a75031cb8bb032e5ea8399ba972bdf9a65/src/purify.js#L1 which is where the `factory` was used and interacted with which we can't do now as we bundle the library up.

**Comment by tdeekens** [comment]
Check https://github.com/cure53/DOMPurify/pull/250

**Comment by tdeekens** [comment]
Build is green. I guess it's time for 1.0.2 after all.

**Comment by frigus02** [comment]
Thanks again for the quick solution :-).

**Comment by tdeekens** [comment]
You're welcome. I hope the solution covers all our use cases of consumers.
