### ISSUE TITLE
Returned DOM doesn't reflect attributes to properties

### ISSUE THREAD

**Issue by falsandtru** [cure53/DOMPurify#251]
### Background & Context

In Chrome.

#### Input

```js
DOMPurify.sanitize('<img src="abc">', {RETURN_DOM: true}).firstChild.outerHTML;
DOMPurify.sanitize('<img src="abc">', {RETURN_DOM: true}).firstChild.src;
```

#### Given output

```js
"<img src="abc">"
""
```

#### Expected output

```js
"<img src="abc">"
".../abc"
```

**Comment by falsandtru** [comment]
This test has failed only on Chrome.

```
      assert.equal( DOMPurify.sanitize( '<img src="abc">', {RETURN_DOM: true}).firstChild.src.split('/').pop(), "abc" );
```

```
Chrome 60.0.3112 (Windows 10 0.0.0) DOMPurify dist Config-Flag tests: RETURN_DOM FAILED
        Expected: "abc"
        Actual: ""
            at Object.<anonymous> (test/purify.min.spec.js:329:16)
            at runTest (node_modules/qunitjs/qunit/qunit.js:843:28)
            at Test.run (node_modules/qunitjs/qunit/qunit.js:828:4)
            at node_modules/qunitjs/qunit/qunit.js:970:11
            at process (node_modules/qunitjs/qunit/qunit.js:629:24)
            at begin (node_modules/qunitjs/qunit/qunit.js:611:2)
```

**Comment by cure53** [comment]
I can reproduce the issue as described.

My gut feeling right now is, that Chrome/Blink might do weird things when working with external resources when the document is residing on about:blank - which it does here.

On other browsers, it inherits the origin from the page where DOMPurify runs on.

Here is what you can try - namely, to force the document to inherit the origin no matter what:

```
            console.log(DOMPurify.sanitize('<img src="/abc">', {RETURN_DOM: true, RETURN_DOM_IMPORT: true}).firstChild.outerHTML);
            console.log(DOMPurify.sanitize('<img src="/abc">', {RETURN_DOM: true, RETURN_DOM_IMPORT: true}).firstChild.src);
            console.dir(DOMPurify.sanitize('<img src="/abc">', {RETURN_DOM: true, RETURN_DOM_IMPORT: true}).firstChild);
```

Does that work for you?

**Comment by falsandtru** [comment]
It can work but it makes a request of the specified external resource.

**Comment by cure53** [comment]
Yep, that's how the browser does it. Do have an idea how this can be avoided?

**Comment by falsandtru** [comment]
Unfortunately, I have no idea.

**Comment by cure53** [comment]
Can you maybe fix that with a hook and, in case it's undefined or null just get it from somewhere else? The info is not gone - just not where it is supposed to be.

I am unsure if we can do much here given that it's a browser behavior.

**Comment by falsandtru** [comment]
Sorry, your English is difficult for me. Another, you may have to fix noscript too. Here is my impl: https://github.com/falsandtru/pjax-api/blob/master/src/lib/html.ts

**Comment by cure53** [comment]
Is that a different issue? I am not sure what to fix on our side tbh.

**Comment by falsandtru** [comment]
Yeah, that is a different issue. The following code must return `null` but actually an element.

```js
DOMPurify.sanitize('<noscript><img></noscript>', {RETURN_DOM: true}).querySelector('img')
```

**Comment by cure53** [comment]
Nope, that is incorrect. The element needs to be returned. 
Why should there be no element in your opinion?

**Comment by falsandtru** [comment]
Because noscript contents are parsed as text: https://jsfiddle.net/rfL00snc/

**Comment by cure53** [comment]
In your test-case, you _document.write_ it into an existing body. That causes **much different** behavior. When using _document.implementation_ or any other inert DOM (which we do), the behavior changes.

As far as I know, we have no extra behavior implemented for _noscript_ but follow the browser's behavior in full. So, not sure if that is a bug.

**Comment by falsandtru** [comment]
Ofcourse it has the same behavior after removing insertions. https://jsfiddle.net/rfL00snc/1/

**Comment by cure53** [comment]
Again not correct, please have a look what DOMPurify does internally and how the behavior differs on JSFiddle. JSFiddle generates a ton of HTML and then puts the _noscript_ element into the already existing body.

What DOMPurify does however is this:

```javascript
    /* Otherwise use createHTMLDocument, because DOMParser is unsafe in
    Safari (see comment below) */
    if (!doc || !doc.documentElement) {
      doc = implementation.createHTMLDocument('');
      body = doc.body;
      body.parentNode.removeChild(body.parentNode.firstElementChild);
      body.outerHTML = dirty;
    }
```

It would be more helpful if you could tell us more clearly what is actually wrong and where - right now we don't really have enough info for a fix and don't even think things are broken.

Further note that DOMPurify's goal is to prevent XSS, not to create beautiful HTML and documents. If you find something that enables XSS or any similar attack, we will fix the very same day. Right now, the issue seems to be that certain assumptions about the resulting DOM are not met - and we are not sure yet what to do about this.

**Comment by falsandtru** [comment]
So I said "may". The first case is different. It can deceive validations of properties.

**Comment by cure53** [comment]
Yes, but we proposed a fix. We cannot go beyond what the browser does :) If it's a blocker for you that the browser sends requests, then I recommend you create a custom hook and parse the missing values yourself.

Hooks are super -easy to create and should be the way to go here:
https://github.com/cure53/DOMPurify/blob/master/demos/hooks-target-blank-demo.html

**Comment by falsandtru** [comment]
In short, this library doesn't defend property-based validations from avoiding it by default?

**Comment by cure53** [comment]
Yep, it's documented what our goals and promises are:

https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model

If you can show me a generic attack that is possible with the behavior you describe above, we will find a fix. Right now, we don't have enough info to do that.

I hope I am not misunderstanding the issue described here - but so far I see nothing actionable. Please correct me if wrong.

**Comment by falsandtru** [comment]
I see. I think this library should remove DOM building feature or describe this problem clearly in readme. Thanks.

**Comment by cure53** [comment]
PRs are welcome :)

**Comment by cure53** [comment]
Also I think it might make sense to file Chrome bug - if the problem is Chrome-only.
