### ISSUE TITLE
DOMPurify extracts handlebars.js template conditionals from within HTML

### ISSUE THREAD

**Issue by zlyuk13** [cure53/DOMPurify#254]
> This issue proposes a bug which results in handlebars.js template conditionals extracted from within HTML

### Background & Context
Using DOMPurify in Backbone.js with handlebars.js templates 

### Bug
Handlebars.js template {{#if }} {{#else}} are extracted out of the HTML content and prepended to the beginning of the returned sanitized string.
Code:
`var htmlText2 = '<table><tbody>{{#if buy}}    <tr><td colspan="2"><i class="fa fa-square" style="color:green" />&nbsp;&nbsp;Buy</td></tr>    <tr><td>Price</td><td>{{buy.price}}</td></tr>    <tr><td>Qty</td><td>{{buy.leavesQty}}</td></tr>    <tr><td>Order&nbsp;ID</td><td>{{buy.orderID}}</td></tr>    <tr><td>Status</td><td>{{buy.subType}}</td></tr>{{/if}}<table><tbody>'`

`DOMPurify.sanitize(htmlText2);`

#### Input

DOMPurify input:
`'<table><tbody>{{#if buy}}    <tr><td colspan="2"><i class="fa fa-square" style="color:green" />&nbsp;&nbsp;Buy</td></tr>    <tr><td>Price</td><td>{{buy.price}}</td></tr>    <tr><td>Qty</td><td>{{buy.leavesQty}}</td></tr>    <tr><td>Order&nbsp;ID</td><td>{{buy.orderID}}</td></tr>    <tr><td>Status</td><td>{{buy.subType}}</td></tr>{{/if}}<table><tbody>'`

#### Given output

The output given by DOMPurify.
`"{{#if buy}}    {{/if}}<table><tbody><tr><td colspan="2"><i style="color:green" class="fa fa-square">&nbsp;&nbsp;Buy</i></td></tr>    <tr><td>Price</td><td>{{buy.price}}</td></tr>    <tr><td>Qty</td><td>{{buy.leavesQty}}</td></tr>    <tr><td>Order&nbsp;ID</td><td>{{buy.orderID}}</td></tr>    <tr><td>Status</td><td>{{buy.subType}}</td></tr></tbody></table><table><tbody></tbody></table>"`
#### Expected output

The expected output the same as input:
`'<table><tbody>{{#if buy}}    <tr><td colspan="2"><i class="fa fa-square" style="color:green" />&nbsp;&nbsp;Buy</td></tr>    <tr><td>Price</td><td>{{buy.price}}</td></tr>    <tr><td>Qty</td><td>{{buy.leavesQty}}</td></tr>    <tr><td>Order&nbsp;ID</td><td>{{buy.orderID}}</td></tr>    <tr><td>Status</td><td>{{buy.subType}}</td></tr>{{/if}}<table><tbody>'`

**Comment by cure53** [comment]
Oh, the problem here is that `<tbody>` has a content model by specification that allows nothing but `<tr>` elements. Since we use the browser to sanitize, the browser automatically moves the template expressions.

Not sure if we can fix this.

**Comment by zlyuk13** [comment]
Thank you very much I have suspected that spec was a constraint. I guess it is not a bug after all.
Well the solution I was suggested is to rename those table tags before parse in to some other valid html tags and then after parse rename them back. But if string is too long this operation might become quit slow.

**Comment by cure53** [comment]
Likely yes. Maybe storing the expressions in a class attribute and reapplying them later might work too.
