### ISSUE TITLE
DOMPurify strips innocuous ids if elements are already in the page.

### ISSUE THREAD

**Issue by LeaVerou** [cure53/DOMPurify#258]
Some of the headings I noticed this happening with:

```html
<h2 id="the-mv-bar-attribute-remove-buttons-enable-optional-buttons-change-order-hide-the-toolbar">The mv-bar attribute: Remove buttons, enable optional buttons, change order, hide the toolbar</h2>
<h2 id="hide-the-toolbar-completely">Hide the toolbar completely</h2>
<h2 id="change-its-placement-andor-use-your-own-html-element-for-it">Change its placement and/or use your own HTML element for it</h2>
<h2 id="remove-default-styling">Remove default styling</h2>
<h2 id="custom-button-elements">Custom button elements</h2>
```

Perfectly innocuous ids, right? No DOM clobbering or anything, right?
And yet, DOMPurify was stripping them! 
But only sometimes, which almost drove me insane.

After digging into it, it looks like the culprit is [this line](https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L675)
If this HTML was already on my page (hence the sometimes!), `value in window` was returning true.
Now, I understand that this check is needed, but perhaps DP can somehow make sure it's not the element itself causing it to be true? I can suggest a few (imperfect) solutions, if needed.

**Comment by cure53** [comment]
Heya! Yeah, might be innocuous if the context is known. 
DOMPurify usually doesn't have that kind of info and hence is double careful.

But, you can do this:

```javascript
// disable DOM Clobbering protection on output (default is true, handle with care!)
var clean = DOMPurify.sanitize(dirty, {SANITIZE_DOM: false});
```

The the clobbering protection is inactive. Would that already help? Or should we have a better and more fine-grained check ion place?

**Comment by LeaVerou** [comment]
Hey, thanks for the quick response!

But I don't want to disable clobbering protection altogether, that's like cutting off my arm because a finger hurt 😛 

I do want to strip ids that genuinely clash with existing properties on `window` or `document`, but not those that have been created by the very same HTML I'm trying to purify. E.g. `<h2 id=onload>` should still be stripped.

**Comment by cure53** [comment]
Hmm, you could probably implement that in a hook. But it's a bit yucky.

Or we can add a new config flag for i.e. ignoring these and these only. How common would you judge the problem to be, roughly?

**Comment by LeaVerou** [comment]
> How common would you judge the problem to be, roughly?

I suspect the pattern of using DOMPurify repeatedly to inject updating content on a page is pretty common, and if any of this content has ids it will hit this bug.

**Comment by cure53** [comment]
So, what say you? New config flag?

**Comment by LeaVerou** [comment]
Sure.
Do you have any ideas on how to detect these cases from legit DOM clobbering cases?

**Comment by cure53** [comment]
I think I have an idea, check this:

```html
<img src=x name=cookie>
<script>
console.log(window.cookie)
console.log(document.cookie)
</script>

<div id=foobar></div>
<script>
console.log(window.foobar)
console.log(document.foobar)
</script>
```

True clobbering affects document **and** window, soft-clobbering with IDs only window.

**Comment by LeaVerou** [comment]
Oh, that's a great idea! Beats all of mine!
Is there any risk in enabling clobbering protection only in those cases?

**Comment by cure53** [comment]
I believe the issue should be fixed with the latest comments, can you give it a try please?

**Comment by cure53** [comment]
Can I close this one @LeaVerou?

**Comment by LeaVerou** [comment]
Sorry, I haven't tested it yet. Will do so now!

**Comment by LeaVerou** [comment]
Yes, it works great, thank you!!
