### ISSUE TITLE
SVG animation support enhancements

### ISSUE THREAD

**Issue by blerner** [cure53/DOMPurify#260]
> This issue proposes a small feature request, to support the additional elements and attributes of https://www.w3.org/TR/SVG/animate.html#AnimationElements

### Background & Context

https://github.com/cure53/DOMPurify/blob/master/src/tags.js#L126-L128 already support `animateColor`, `animateMotion` and `animateTransform` tags, but the SVG animation spec says that `animateColor` is deprecated in favor of just `animate`.  Please add the `animate` and `set` elements to `TAGS.svg`.

https://www.w3.org/TR/SVG/animate.html#complexDistances also defines the `to`, `from`, `by` and `values` attributes, of which https://github.com/cure53/DOMPurify/blob/master/src/attrs.js supports just `by` and `values`.  Please add the `from` and `to` attributes to `ATTR.svg`.

**Comment by cure53** [comment]
No. 

Both `animate` and `set` introduce XSS attacks and will not be added.

Same goes for `from` and `to`. If you need them supported in your application you can easily do that via configuration. The DOMPurify core will *not* white-list those attributes given our core goals of preventing XSS.

**Comment by blerner** [comment]
Oh, really?  I did not know that -- obviously that wasn't my intent!  Is there a link you could give that shows an example of this?  (My current configuration of DOMPurify is in the context of attempting to allow student-submitted homeworks to be displayed, while neutering all links within it.  So I'm using essentially https://github.com/cure53/DOMPurify/blob/master/demos/hooks-link-proxy-demo.html as my baseline, but I noticed that my students' animations weren't rendering because these elements&attributes were being filtered away.  So I added them to my ADD_TAGS/ADD_ATTR lists to bring them back.  I'm aware of one potential attach via `<set attributeName="xlink:href" to="evil.com">`, shown in https://raw.githubusercontent.com/cure53/HTTPLeaks/master/leak.html, so I check for that...but I didn't know from/to could be abused more generally than that.)

**Comment by cure53** [comment]
No worries :)  Check this example:

```html
<svg>
<a xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="?">
<circle r="400"></circle>
<animate
attributeName="xlink:href" begin="0"
from="javascript:alert(1)" to="&"
/>
</a>
```

**Comment by blerner** [comment]
I........don't even see what that's supposed to *mean*, let alone how that could be *animated* :(  To quote [Isidor Rabi](http://www.nytimes.com/1987/09/27/books/science-technology-who-ordered-the-muon.html), "who ordered _that_?"  (Unfortunately, that complaint can be leveled against an awful lot of web "features" at this point.)

Thanks for the quick responses.

**Comment by cure53** [comment]
Yup :) Check out the SVG keylogger in Firefox. Works even when scripts are prohibited (i.e. CSP): https://html5sec.org/keylogger/ (type things and watch network traffic)
