### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by skeggse** [cure53/DOMPurify#262]
We'd like to be able to configure the allowed protocols. It looks like this is a feature on `master`, but it hasn't been released yet. Are there any blockers to publishing a new release with the [latest changes](https://github.com/cure53/DOMPurify/compare/1.0.2...master)? What's DOMPurify's general policy on releases?

**Comment by cure53** [comment]
Oh, sorry :D Didn't know you were waiting for it, release will come tomorrow if all gos well!

**Comment by skeggse** [comment]
No problem :)

**Comment by cure53** [comment]
1.0.3 is out :) One of the tests is still red but it appears to be a BrowserStack hiccup.

**Comment by skeggse** [comment]
Thanks!
