### ISSUE TITLE
DOMException - code: 5: InvalidCharacterError with Edge

### ISSUE THREAD

**Issue by dhoko** [cure53/DOMPurify#264]
> This issue is about a bug with Edge only, an attribute creates a DOMException.

### Background & Context

We use DOMPurify to display emails, some emails are weird.

#### Env
Microsoft Edge 41.16299.15.0
Microsoft EdgeHTML 16.16299

#### Input

```html
<div &nbsp;=""></div>
```

Some HTML which is thrown at DOMPurify.

#### Given output

![screenshot from 2018-01-02 15-58-55](https://user-images.githubusercontent.com/713283/34487903-9613ec0a-efd6-11e7-9214-825472625d0e.png)

#### Expected output

![screenshot from 2018-01-02 16-04-43](https://user-images.githubusercontent.com/713283/34487921-a9c91b44-efd6-11e7-8a0c-72f7e3f879c1.png)

The error is only with Edge.
> we don't manipulate the string before.

**Comment by cure53** [comment]
Ew, nice find! We will have a look asap.

**Comment by cure53** [comment]
I think the issue is fixed, please check @dhoko

**Comment by dhoko** [comment]
Yes it works :+1: 
Thx

**Comment by cure53** [comment]
Cool :)
