### ISSUE TITLE
DOMPurify.removed misses nodes removed at the very beginning

### ISSUE THREAD

**Issue by M4riuZ** [cure53/DOMPurify#266]
### Background & Context

If something at the very beginning of the string is removed, then it will not be listed in DOMPurify.removed. Note that this does not happen with `{WHOLE_DOCUMENT: true}`, but this not exactly obvious.

#### Input

```
DOMPurify.sanitize("<script>alert(1)</script>foo");
DOMPurify.removed.length;
```

#### Given output

`0`

#### Expected output

`1`

### Edit

After reading about `FORCE_BODY` I understand why that happens, but I still think that it can be very confusing if the script is removed as intended but then DOMPurify.removed claims that there was nothing removed. 

Maybe this behavior should be explained in more detail in the documentation. Looking through the closed issues, I am not the only one, e.g. #257

**Comment by cure53** [comment]
Check this :)

https://github.com/cure53/DOMPurify/issues/257

**Comment by cure53** [comment]
This is browser behavior and nothing we can handle easily in the library. 
More documentation is welcome and so is a PR for it :)

**Comment by kimmin920** [comment]
I have a little trick, don't know if its okay for you but for me its suitable trick.

```
const sanitized = DOMPurify.sanitize(`<div></div> ${embedCode}`, PURIFY_CONFIG);
```

or I can give to this empty div an id='delete-this' and add a hook to remove it.
