### ISSUE TITLE
svgFilters in attrs.js missing 4 filters

### ISSUE THREAD

**Issue by ydaniv** [cure53/DOMPurify#269]
Hey,

Question, I see 4 filters missing form `svgFilters`:

- `feDistantLight`
- `feSpotLight`
- `fePointLight`
- `feImage`

Is this intentional? Why?
If not, shall I send a PR adding them?

much obliged!
~Y

**Comment by cure53** [comment]
I think light sources are harmless, so the three _Light_-related filters can be added. 

With _feImage_ I would be careful though, this caused XSS in the past.

**Comment by ydaniv** [comment]
Yeah, that's what I thought. I'll send a PR with the light filters.

**Comment by cure53** [comment]
<3 thanks!
