### ISSUE TITLE
Tag specific attributes

### ISSUE THREAD

**Issue by ssylvia** [cure53/DOMPurify#272]
It looks like `ALLOWED_ATTR` is global to all tags. Is there anyway to whitelist attributes specific to a tags, something similar to [js-xss whitelist](https://github.com/leizongmin/js-xss#whitelist)? For example, we could do something like:

```js
var clean = DOMPurify.sanitize(dirty, {
  ALLOWED_TAGS: {
    'a': ['href', 'target'],
    'div': ['class'],
    'strong': []
  }
});
```
When the array is empty, the tag would be allowed but strip all attributes.

**Comment by cure53** [comment]
Closing this for now, no plans to implement that in the core functionality at the moment.

**Comment by robclancy** [comment]
This seems to be a weird thing to do. At the core of HTML is attribute that belong to specific tags.

**Comment by cure53** [comment]
Yup, but for sanitization purposes, so far, this approach was more than sufficient.

**Comment by mjrjoh** [comment]
Tag specific attributes configuration is supported in [browser sanitizer API draft](https://wicg.github.io/sanitizer-api/#attr-match-list). Really make sense to support it.

**Comment by 64BitAsura** [comment]
it is possible via hook https://www.linkedin.com/feed/update/urn:li:activity:7034210540885282816/
