### ISSUE TITLE
Not an issue - just not sure where to ask

### ISSUE THREAD

**Issue by CoderJason123** [cure53/DOMPurify#274]
Hello.  I am wondering about html entities, so if someone wrote out the word script using all html entities and maybe the greater than or less than sign too.

I am unclear what the browser does automagically, but are entities autotranslated by the time a bad string is about to be written, meaning that dompurify would never receive it in encoded form, and there's no danger thus, or having an html entity script string pass thru?

Make sense?  I will close this asap.  thanks for your response.

**Comment by cure53** [comment]
Heya, that is an unlikely scenario and the browser does nothing of that kind (not even in XML CDATA context anymore). 

Usually, those entity-based attack vector samples are used in cases where the server actually decodes entities and we want to bypass a WAF or alike.

**Comment by CoderJason123** [comment]
ok - thank you.  i noticed that when i put html entities for script on jsfiddle or codeine, it was translated to script and got a message thru.  i do not think that dompurify let the final bad thing thru...which is good.
