### ISSUE TITLE
Preserve attribute order

### ISSUE THREAD

**Issue by mayfield** [cure53/DOMPurify#276]
> This issue proposes a feature which preserves attribute order.

I compare input and output html passed through dompurify to detect if something has changed (and thus if I need to mutate my document).  A simple string comparison generally works except when there are multiple attributes on input html.  The attributes get reordered by dompurify and the resulting string is different despite being effectively identical.  It would be great if the attribute order was preserved so simple string compares more accurately elucidated change state.

**Comment by cure53** [comment]
Heya,

> The attributes get reordered by dompurify

Nope, it's the browsers - not us. There is little to nothing we can do here. You would have to reorder them manually - and reverse the browser's behavior.

**Comment by mayfield** [comment]
Bummer.   Thanks for quick reply.

**Comment by mayfield** [comment]
This might be impl specific but it looks like `_sanitizeAttributes`  is iterating over the attributes in reverse order and calling `removeAttribute` for every attribute regardless of sanitization being required or not.  Cleaned values are then reapplied using `setAttribute`.  According to MDN, `setAttribute` will "replace" the attribute if it already exists.  Testing in chromium seems to validate that this DOES preserve order.

Again, I don't know if that's impl specific, but for at least chrome it appears the procedure could be massaged to not call removeAttribute unless it needs to.  Additional coverage for explicitly calling removeAttribute would be required;  Such as the `setAttribute`'s `catch()` clause.

An alternative approach would be to collect the attribute map first, remove all of them from the node and then iterate forward.  Again, this is perhaps impl specific, but in chrome setAttribute appears to preserve insertion order in the resulting HTML string.

Thoughts?

**Comment by mayfield** [comment]
I was able to prototype a patch that implements the latter technique and it appears to preserve attr order on chromium.  It does involving cloning the node first so the attributes NamedNodeMap order is preserved during forward iteration (and subsequent alteration).  There surely exists a technique to avoid this clone but it would require more substantial alteration.

**Comment by cure53** [comment]
Nope. That won't work. We have to work through attributes from bottom to top because otherwise the index of the attributes gets screwed up and we have bypasses.

**Comment by mayfield** [comment]
Re: Nope;   Did you notice the cloneNode().attributes assignment for the iteration?
