### ISSUE TITLE
Web workers

### ISSUE THREAD

**Issue by Charuru** [cure53/DOMPurify#278]
How do I use this library inside a web worker? I'm using the purify.min.js dist. Doing DOMPurify.sanitize works fine in a browser but is not found inside a webworker. Presumably this is because there is no window. How would I make DOMPurify into a global?

**Comment by cure53** [comment]
I am not 100% sure but I think this library will do: https://github.com/leizongmin/js-xss

**Comment by Charuru** [comment]
Thanks!

**Comment by curran** [comment]
Just curious if anyone has had suggess running DOMPurify or other sanitizer library inside of a Web Worker?

**Comment by curran** [comment]
Indeed, I also landed on `js-xss` as the best option.

They have an example with Web Workers: https://github.com/leizongmin/js-xss/blob/master/example/worker.js
