### ISSUE TITLE
Travis CI builds fail after adding new browsers & updating dependencies

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#280]
### Background & Context

We updated the array of browsers to test against and, with that, also updated the dependencies after multiple complaints from _npm_. The library code was also updated slightly to comply with latest _eslint_ requirements.

It appears that the updated decencies have broken the builds on Travis CI - locally everything works fine though. Any idea what can be done to get the builds on Travis CI to be green again?

https://travis-ci.org/cure53/DOMPurify/builds/383671178
https://github.com/cure53/DOMPurify/commit/6b64be370ee8b9f98928ca5d257ddb98a370625a

I think it is safe to assume that the updated dependencies cause the problem, not the changes in tjhe source or any of the added browsers.

cc @tdeekens

**Comment by cure53** [comment]
```
error xo@0.21.1: The engine "node" is incompatible with this module. Expected version ">=6".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Does that mean we should downgrade to an older yarn version  - or rather ditch the legacy tests?

**Comment by tdeekens** [comment]
Guess that depends on what you are after. If you want to keep the "legacy" tests you'd have to install an older version of `yarn` for that part on TravisCI. If you don't want to test against anything which is not "Active" in Node.JS terms, ditch them. [ref](https://github.com/nodejs/Release).

**Comment by cure53** [comment]
Okay, above mentioned seems to be the problem indeed. 

@tdeekens where can we find the version numbers for the NodeJS tests? I would propose to simply ditch 4.0, 5.0 and add 8.0 and 10.0 instead.

**Comment by cure53** [comment]
Ah, found it :D @tdeekens

**Comment by cure53** [comment]
Okay, the tests are green again but it appears, that the BrowserStack tests are fragged now. 

Investigating... @tdeekens

**Comment by cure53** [comment]
I think I solved it, thanks for checking :D
