### ISSUE TITLE
Consider removing the Safari workaround

### ISSUE THREAD

**Issue by koto** [cure53/DOMPurify#281]
In Safari/OSX Version 11.1.1 (12605.2.8) `new DOMParser().parseFromString('<svg onload=alert(document.domain)>', 'text/html');` doesn't execute JS anymore, suggesting the bug was fixed. I'm not sure in which version this was fixed, but if the mobile version numbers follow the desktop ones, the fix should already be present for the majority of the users (based on https://caniuse.com/ stats).

Given that the workaround is quite ugly, maybe it's OK to remove it now?

**Comment by cure53** [comment]
I was thinking that as well, but cannot really tell how many people are using the vulnerable versions.

If only we had someone here with access to large-scale browser-stats :D

**Comment by cure53** [comment]
Or, in other words - happy to remove it. But some data w.r.t. usage of those Safari versions would be awesome first @koto Doable?

**Comment by koto** [comment]
I'll look around and report back.

**Comment by cure53** [comment]
That is much appreciated!

**Comment by cure53** [comment]
We indeed decided to remove the workaround for the Safari Tech Preview bugs.
