### ISSUE TITLE
infinite loop when sanitizing tables

### ISSUE THREAD

**Issue by vmarquet** [cure53/DOMPurify#286]
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/1.0.3/purify.min.js" integrity="sha256-ehDYSmZ6Mm1JEHnKdyzNAoSsrl81E04j8iLxD2RgAU8=" crossorigin="anonymous"></script>
</head>
<body>
    <script>
        var s = `aa<table>
                  <tr>
                    <td>toto</td>
                    <td>tata</td>
                  </tr>
                   <tr>
                    <td>titi</td>
                    <td>tutu</td>
                  </tr>
                </table>bb`

        s = DOMPurify.sanitize(s, {
          ALLOWED_TAGS: [
            'table', 'tr', 'th', 'td',
          ]
        })

        alert(s)
    </script>
</body>
</html>
```

`alert` never opens, instead Firefox complains that a script is hanging the page and asks to terminate it.

[jsfiddle here](https://jsfiddle.net/nh2vw4js/1/)

**Comment by cure53** [comment]
The problem here is that you allow 'table', 'tr', 'th', 'td' but not 'tbody'. The browser automatically creates a tbody element and - given that it is not allowed, removes it again. Eventually this causes a loop.

A workaround for you would be this:
```javascript
s = DOMPurify.sanitize(s, {
          ALLOWED_TAGS: [
            'table', 'tbody', 'tr', 'th', 'td',
          ]
        })
```

We'll look for a fix for the looping behavior in the meantime.

**Comment by cure53** [comment]
Okay, the fix should work now - could you give it a try please?

**Comment by vmarquet** [comment]
Yes it works now. I completely forgot about tbody, but it shouldn't have looped anyway.

Thank you very much, awesome lib and great support!

**Comment by cure53** [comment]
Yw :)
