### ISSUE TITLE
Unexpected token \\ in JSON during sanitizing array of JSONs

### ISSUE THREAD

**Issue by rols2015** [cure53/DOMPurify#287]
Hi,
I am geting the following error when trying to sanitize array of JSONs

batch = JSON.parse(DOMPurify.sanitize(JSON.stringify(batch)))

#### Given output
[{
	"TEST": "10000311",
	"title": "<a rel=\"noopener\" target=\"_blank\" href=\"example.by\">Link</a>",
},
	{
	"TEST": "10000311"
}]

I believe it's happening because of decoding quotes: `&quot;`
`"<a href="\&quot;example.by\&quot;" rel="\&quot;noopener\&quot;">Link</a>"`

**Comment by cure53** [comment]
Yeah, this cannot work. You are throwing, as it seems, a stringified JSON array in and expect valid JSON output. Of course, DOMPurify does not know that you expect valid JSON output and cannot deliver.

I would recommend not to stringify the whole array but only sanitize the actual strings in there.

**Comment by rols2015** [comment]
@cure53 I have 1000 jsons (each has 30+ keys) in my array and I am afraid it will decelerate speed of processing if I'll be sanitizing each key separately.

**Comment by cure53** [comment]
Eventually, they will get placed somewhere in some DOM. Why not sanitize them then? By the way, DOMPurify is quite fast with repetitive calls, we had a client in the past who required that feature.

**Comment by cure53** [comment]
Either way, we will not implement any new core logic that helps producing valid JSON from stringified JSON inpout. That is something the developers have to take care of themselves.

**Comment by rols2015** [comment]
It's for back-end sanitization, so it's not placed in DOM.
yeah, thanks. I will take care on sanitization it string by string in the JSON's keys. Just the last question, why if a sanitize
`{key: true}` it return me a string "true"  and `{key: false}` returns me an empty string. How can we keep a Boolean values? Thank you!

**Comment by cure53** [comment]
I would recommend to only send to the sanitizer what _needs_ to be sanitized. If you have a boolean, simply don't send it to DOMPurify. Check the type and skip it if it says `Boolean`.

**Comment by rols2015** [comment]
@cure53 Thank you! I have written the following function which works fine for me:
```javascript
    sanitizeBatch(batch) {
      batch = batch.map(item => {
        for (let key in item) {
          if (typeof item[key] === 'object' && !Array.isArray(item[key])) {
            for (let keyobj in item[key]) {
              item[key][keyobj] = DOMPurify.sanitize(item[key][keyobj], DOMPurifyOptions)
            }
          } else if (Array.isArray(item[key])) {
            item[key] = this.sanitizeBatch(item[key])
          } else if (typeof item[key] === 'boolean') {
            item[key] = item[key]
          } else {
            item[key] = DOMPurify.sanitize(item[key], DOMPurifyOptions)
          }
        }
        return item
      });
      return batch
    }
```

**Comment by cure53** [comment]
Awesome :)
