### ISSUE TITLE
Tags inside styles are not sanitized

### ISSUE THREAD

**Issue by Sathis25** [cure53/DOMPurify#290]
> This issue proposes a [bug, feature] which...

### Background & Context

When having vector images inside <style> tags are not sanitized and returns as it is

#### Input

<b><style><style/><img src=x onerror=alert(1)>

<b><style><style////><img src=x onerror=alert(1)></style>
#### Given output

<b><style><style/><img src=x onerror=alert(1)>

<b><style><style////><img src=x onerror=alert(1)></style>
#### Expected output

<b><style><style/><img src=x>

<b><style><style////><img src=x></style>
### Feature

Briefly outline the proposed feature, its value and a potentially proposed implementation from a high level.

**Comment by cure53** [comment]
Hey there, thanks for the ticket. What is the problem here and how should we address this?

**Comment by Sathis25** [comment]
Try to sanitize the above mentioned content and the content return as it is

**Comment by cure53** [comment]
And why would be do that? The examples you pasted above are harmless and just garbage CSS. 

No XSS can happen here.
