### ISSUE TITLE
[feature] Bundle tags and attributes in separate module

### ISSUE THREAD

**Issue by thomasthiebaud** [cure53/DOMPurify#293]
### Background & Context

Currently the library includes a list of [tags](https://github.com/cure53/DOMPurify/blob/master/src/tags.js) and [attributes](https://github.com/cure53/DOMPurify/blob/master/src/attrs.js) even if the user is not going to use them (or just a subset)

### Feature

It would be nice if this data can be bundle in separates modules, something like `dompurify-html-preset`, `dompurify-svg-preset` and so one. 

So users who only want to support `html` can just install `dompurify-html-preset`. And users that want to only support a few tags can manually specify them using `ALLOWED_TAGS` or `ALLOWED_ATTR`

**Comment by cure53** [comment]
Hi Thomas, the idea is to present a safe default to users who don't want to bother micro-managing tags and attributes. Would that proposal not mess this up a bit?

**Comment by thomasthiebaud** [comment]
The safe default should still be present in the `*-preset` libraries. So users that don't want to micro managing tags and attributes can just install them.

I'm thinking about this presets:
- `dompurify-html-preset`
- `dompurify-svg-preset`
- `dompurify-mathml-preset`
- `dompurify-all-preset` => includes all safe defaults

**Comment by cure53** [comment]
So, how would that change the API? Would that not break the way people are using DOMPurify right now?

**Comment by thomasthiebaud** [comment]
I'm not sure it is possible to avoid a breaking change here

If the a preset exports `tags` and `attrs`, the user can destructure them and pass them in the config

```
  ALLOWED_ATTR: ...htmlPreset.attrs,
  ALLOWED_TAGS: ...htmlPreset.tags,
```

It does not change the API, but it is still a breaking changes because the user will need to pass a preset to have default values

Another would be to add a `PRESET` key in the configuration

**Comment by cure53** [comment]
> I'm not sure it is possible to avoid a breaking change here

Then sadly we have to reject this feature request. Sorry :-/

**Comment by thomasthiebaud** [comment]
I understand, but is it really a problem to have breaking change if you bump the version correctly ?

**Comment by cure53** [comment]
Yes. Sadly it is. We did this in the past and people were freaking out. 

Ever since then we avoid breaking API changes like the devil avoids holy water. And we plan not to deviate from that pattern unless we have to (a.k.a. security bug).

**Comment by thomasthiebaud** [comment]
Sounds reasonable ;) Thanks a lot for your time

**Comment by cure53** [comment]
Yw and sry again :)
