### ISSUE TITLE
Feature Request: CSS Media Queries 

### ISSUE THREAD

**Issue by christopherblaser** [cure53/DOMPurify#298]
### Feature
Are media queries currently supported? (Sorry if this is already a supported feature)

**Comment by cure53** [comment]
What do you mean?

**Comment by christopherblaser** [comment]
So in the demo -> https://github.com/cure53/DOMPurify/blob/master/demos/hooks-sanitize-css-demo.html

There's a note specifying that only selector rules are supported by that function. I've tried modyifing it to allow for rules which are media queries, e.g. "@media only screen and (min-device-width: 321px) {}" but the returned rule appears to be missing the underlying stylesheets/ coming out malformed.

**Comment by cure53** [comment]
Ah okay, yes - the hook just shows how you can sanitize CSS using the DOM but doesn't fully implement rules. We'll totally accept a PR that adds that though :)

**Comment by cure53** [comment]
Closing for now, please re-open if necessary.
