### ISSUE TITLE
Leading whitespace is discarded

### ISSUE THREAD

**Issue by edg2s** [cure53/DOMPurify#299]
### Bug
Leading whitespace is discarded when sanitizing.

#### Input
```
DOMPurify.sanitize("   <b>foo</b>   ")
```
#### Given output
```
"<b>foo</b>   "
```
#### Expected output
```
"   <b>foo</b>   "
```

**Comment by cure53** [comment]
The browsers do that internally, not DOMPurify's fault :)

**Comment by cure53** [comment]
Check the following config option to fix this issue:

```
// glue elements like style, script or others to document.body and prevent unintuitive browser behavior in several edge-cases (default is false)
var clean = DOMPurify.sanitize(dirty, {FORCE_BODY: true});
```

**Comment by edg2s** [comment]
> The browsers do that internally, not DOMPurify's fault :)

Agreed! Although I think it's possible to workaround, I'll submit a PR later.

**Comment by cure53** [comment]
Does the config flag not work for you as a fix? We introduced it extra for this and comparable weirdness.

**Comment by edg2s** [comment]
It does, but shouldn't that be the default behaviour?

**Comment by edg2s** [comment]
My idea was to strip leading whitespace early on, and restore it as a prepended TextNode. That fixes the issue, even if FORCE_BODY is not set...

**Comment by cure53** [comment]
No, the default should be to do it as the browser would do it anyway. 

The more we deviate from that, the more customization we will need and that will in the long term corrode the security promises - in my opinion.

So, given the flag fixes the issue, I would propose to not touch the core. Wdyt?

**Comment by edg2s** [comment]
I'm not sure I agree. If I want to sanitize `' <b>foo</b> '`, there is nothing about the API call `DOMPurify.sanitize(' <b>foo</b> ')` that says I want it sanitized in the context of inserting it directly into a `<body>`, I'm far more likely sanitizing the HTML for insertion elsewhere into the DOM.

The body element is the only element in the DOM that has this strange leading whitespace stripping behaviour. The fact that the library is internally using the body element as the wrapper for the user's content when sanitizing should be transparent to the user.

**Comment by cure53** [comment]
That all might be - but it's not strong enough of a reason to change the default behavior mid-flight.

We can turn this into the default behavior when we hit a larger version leap (i.e. when approaching 2.0 for example), but doing this between 1.0.8 and 1.0.9 will cause lots of trouble.

**Comment by edg2s** [comment]
I'd want to keep a fix, unless you removed the option entirely. If the user sets FORCE_BODY back to false they still wouldn't want to strip leading whitespace.

**Comment by cure53** [comment]
Thanks, let me see what the tests say...

**Comment by cure53** [comment]
Alright, things seem to look good. I am not a huge fan of this change but can accept it until we clean up the handling of this and other quirks for a major release.

Thanks :)
