### ISSUE TITLE
Sanitizing SVG removes any <title> elements

### ISSUE THREAD

**Issue by ryan-codingintrigue** [cure53/DOMPurify#301]
> This issue proposes a bug which...

### Background & Context

When sanitizing SVGs, any `<title>` elements seem to be stripped regardless of the options passed in. As far as I can tell, the `<title>` element is in the whitelist for the SVG profile so this should work out-of-the-box without any additional options provided.

#### Input

```js
const input = `<svg width="1440" height="622" xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg">
 <g class="layer">
  <title>Layer 1</title>
	</g>
</svg>`;
const options = { USE_PROFILES: { svg: true }, ADD_TAGS: ["title"] };
const result = DOMPurify.sanitize(input, options);
```

#### Given output

```svg
<svg xmlns="http://www.w3.org/2000/svg" height="622" width="1440">
    <g class="layer">
        Layer 1
    </g>
</svg>
```

#### Expected output

```svg
<svg xmlns="http://www.w3.org/2000/svg" height="622" width="1440">
    <g class="layer">
        <title>Layer 1</title>
    </g>
</svg>
```

**Comment by ryan-codingintrigue** [comment]
Just found the cause at [purify.js#L442](https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L442).

This seems to trigger in Chrome 69 😦 Is there any way to work around this, rather than to remove the element completely? `<title>` in SVG are critical for accessibility so I'd ideally like to be able to at least hook into one of the events to sanitize it manually.

**Comment by cure53** [comment]
This was an XSS in Edge, caused by a browser bug. Given that Edge fixed the issue, we might be able to remove this part very soon.

**Comment by cure53** [comment]
I checked and, as far as I can see, Chrome 69 won't have XSS via that. The browser bug was in how Edge handled the encoding afterwards, I believe we should be fine removing the call.

**Comment by cure53** [comment]
Okay, I think we have a fix on master. can you check please @ryan-codingintrigue?

**Comment by ryan-codingintrigue** [comment]
LGTM 👍 I am getting my `<title>` elements now and correct sanitization when trying to inject XSS inside.

Thanks so much for the quick turnaround & the awesome lib!

**Comment by cure53** [comment]
:) yw
