### ISSUE TITLE
Found a potential xss attack that DOMPurity does not sanitize 

### ISSUE THREAD

**Issue by DonghyukJacobJang** [cure53/DOMPurify#302]
> Found a potential xss attack that DOMPurity does not sanitize 

### Background & Context

First of all, thanks for providing and maintaining this great library. I have been used this library for multiple production projects since it gives the best result compared to other libraries.

Today I found a xss attack that DOMPurify does not sanitize it.

Here :
```
<img><marquee><h1>XSS</h1></marquee> <marquee><h1>XSS</h1></marquee> “
```

#### Given output

Here is a result from the example above: http://cld.jam3.com/3413f1066d24

**Comment by cure53** [comment]
Heya. Where is the XSS here? This is only benign markup.

**Comment by DonghyukJacobJang** [comment]
I apologized that I misunderstood something. Please ignore this issue report. 

Thanks for your quick response!

Best,
Donghyuk(Jacob) Jang
