### ISSUE TITLE
TypeScript missing definitions

### ISSUE THREAD

**Issue by tomholub** [cure53/DOMPurify#305]
The following TypeScript definitions are missing in `@types/dompurify`:
```
DOMPurify.version = boolean;
DOMPurify.removed = [];
DOMPurify.isSupported = boolean;
DOMPurify.setConfig = function(cfg) => void
DOMPurify.clearConfig = function() => void
DOMPurify.isValidAttribute = function(tag, attr, value) => bool
DOMPurify.removeHook = function(entryPoint) => void
DOMPurify.removeHooks = function(entryPoint) => void
DOMPurify.removeAllHooks = function() => void
```
These are just a rough scatch, as a note for me here in case I do a PR.

Although the types are tracked at https://github.com/DefinitelyTyped/DefinitelyTyped I'm pasting the issue here so that it wouldn't drown in a sea of issues of unrelated projects.

**Comment by cure53** [comment]
A PR would be wildly appreciated :)

**Comment by tomholub** [comment]
Noted, I have some things pending, but once I get through them, I should be able to get to this.

**Comment by cure53** [comment]
Thx!

**Comment by tomholub** [comment]
Note: to also check `Config`, missing `ALLOWED_URI_REGEXP` and possibly more

**Comment by tomholub** [comment]
Still planning to do this

**Comment by tomholub** [comment]
@cure53 try to see if there's a way to give it a LGTM review @ https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30179 which may expedite the PR. These sometimes take a while.

**Comment by cure53** [comment]
LGTM :)
