### ISSUE TITLE
Ember Action Tage

### ISSUE THREAD

**Issue by SantoshRaoBlr** [cure53/DOMPurify#308]
I would like to scan my general DOM elements and permit HandleBar/mustache tags. Is there any way I can permit this while sanitizing

Please help

I tried ADD_ATTR, but the output gets stripped

var sanTest = '<input type="checkbox"  {{action "validateAttributeField" "helloworld"  on="keyUp"}} {{action "changedAttributeField" "helloworld"  on="change"}}>';
sanTest = DOMPurify.sanitize(sanTest, {ADD_ATTR: ['action']});

Both the action handles get removed

**Comment by cure53** [comment]
Oi, this looks something that is better be done with a hook rather than a core change. 

What do you think?

**Comment by SantoshRaoBlr** [comment]
Hi, Yes if a hook works it is good too, but I am not sure if I tried this out right, when I try to apply any of the hook, instead of getting the entire {{ action ...}} I get each of them ({{action,"validateAttributeField","helloworld",...)  like a attribute. So I am not sure which hook possibly to use to allow the entire {{ action ...}} to be treated as sanitized. I felt that if the entire {{ action ...}} was passed to a hook, which could decide whether any cleanup is needed for the element it might have been better as more enforcement could be done.

Ember generally uses a syntax of RegEx like this for its action handle bars

**Comment by cure53** [comment]
The problem here is, that the tags are super-invalid HTML. They might end up as whatever in the DOM. I think we cannot do much here unless you come up with some magic in a hook.  

Closing this for now as out-of-scope.
