### ISSUE TITLE
src/href blacklisting?

### ISSUE THREAD

**Issue by devd** [cure53/DOMPurify#31]
My friend was glancing at the code for purifier and he was worried by https://github.com/cure53/DOMPurify/blob/master/purify.js#L347

where it seems DOMPurify blacklists schemes instead of whitelisting http/https/mailto: URIs.

I am curious---Whats the reasoning behind this? I usually imagined all sanitizers use a whitelisting mechanism.

**Comment by cure53** [comment]
I'll close this for now.
