### ISSUE TITLE
spurious Javascript alert box in Opera Mini

### ISSUE THREAD

**Issue by tojamrok** [cure53/DOMPurify#312]
https://github.com/ampproject/amphtml/issues/19977 says: 

> All AMP pages open with spurious Javascript alert box in Opera Mini

Maintainer of AMP  HTML says that the source code of the alert box in amp-bind-0.1.max.js comes from DOMPurify, which looks like https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L500.

You can debug in Opera Mini for Android (download from Google Play and from Data Savings options choose Extreme) or in Opera Desktop version 12.16 (http://ftp.opera.com/ftp/pub/opera/win/1218/int/, http://ftp.opera.com/ftp/pub/opera/linux/1216/ or http://ftp.opera.com/ftp/pub/opera/mac/1216/).

**Comment by eagerterrier** [comment]
Sure not supporting. But if you can get rid of the JavaScript alert 1 that would be great.

**Comment by cure53** [comment]
@eagerterrier Please check if the changes above work for you!

**Comment by choumx** [comment]
Thanks for addressing this!

**Comment by cure53** [comment]
Yw!
