### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by nifgraup** [cure53/DOMPurify#313]
> This issue proposes a [bug, feature] which...

### Background & Context

An already fixed bug on master, requesting a release

### Bug
The bug applies to release 1.0.8, was fixed in 63f916155b702bdbc3d5dac7d18cfb9a20082bfc. 

#### Input
```
DOMPurify.sanitize(
  '<html><title>a title</title><body>a body</body></html>',
  { WHOLE_DOCUMENT: true }
);
```

#### Given output

`<html><head>a title</head><body>a body</body></html>`

#### Expected output

Same as input, <title> is not stripped away. Regressed in b0cd0b931a9a4188d8b29f1435d91fc064c5ee02.

**Comment by cure53** [comment]
Hey there, we released 1.0.9 today!
