### ISSUE TITLE
Breaking change in 1.0.9

### ISSUE THREAD

**Issue by Panya** [cure53/DOMPurify#316]
### Background & Context

In version 1.0.8 and earlier `DOMPurify.sanitize('some content')` returns sanitized string. But in the newer version (1.0.9) the same method call returns `TrustedHTML` object and user should call `toString` method to get the same result.

In my opinion the version should be released as major (because API of the library is changed).

**Comment by cure53** [comment]
Are you using DOMPurify in combination with an existing Trusted Types policy per chance?

**Comment by Panya** [comment]
Yep, it seems it's an environment issue. I've created a minimal test case (see https://codesandbox.io/s/2v6612mxlp in Chrome).

**Comment by cure53** [comment]
Getting a string as the return type on Chrome 71.0.3578.98 (Official Build) (64-bit). Can you provide more info?

@koto Do have any clue if the behavior described above is correct? It feels to me that this is expected behavior. But I am not 100% sure.

**Comment by Panya** [comment]
I'm using Chrome 71.0.3578.98 (latest stable) on Mac OS 10.14. And see on the console:
<img width="1279" alt="screenshot 2019-01-19 at 20 04 47" src="https://user-images.githubusercontent.com/235637/51429980-8c04c000-1c25-11e9-90bd-1e84b6dce12d.png">

**Comment by Panya** [comment]
I'm using it like so (semi-pseudocode):
```js
import DOMPurify from 'dompurify';

const sanitize = str => {
  return DOMPurify.sanitize(str)
    .replace(...)
};
```
And in this case `toString` is not being called, so my code breaks.

**Comment by Panya** [comment]
But you're right `toString` is called automatically if you're using it with e.g. concatenation, interpolation, innerHTML, ...

**Comment by cure53** [comment]
Thanks, @koto! So we are good?

**Comment by Panya** [comment]
I still think that this change (support trusted types) should not be a patch release version, because some environments can use Chrome with it, but ok :)

**Comment by cure53** [comment]
Thx :)

**Comment by toomuchdesign** [comment]
Same issue here with Chrome 71.0.3578.98 on MacOS.
In my case the error came from a failed attempt of calling `replace()` on the returned `TrustedHTML` object.

I don't know what `TrustedHTML` specs are, but I see the value of marking this release as a major one.

Thanks for your great job here. Bests.

**Comment by cure53** [comment]
Ah, okay - hmmm. 

@koto Do you think we should make changes to the code or README before going for a DOMPurify 1.1.0? I am not opposed to doing a bigger release - just wondering if there is anything we should add before that.

**Comment by Panya** [comment]
By the way, this feature is available through `Experimental Web Platform features` flag in latest Chrome. Many web developers toggle this flag to on.

**Comment by koto** [comment]
A mention in 1.1.0 sounds good. The canonical link for the feature would be https://github.com/WICG/trusted-types I think. But, as a general question, what is your use case for replacing string values in sanitized content? Potentially this allows for nasty XSSes if the replacement value is attacker controlled. Why not replace before the sanitization, or during the sanitization through the hooks in DOMPurify?

**Comment by toomuchdesign** [comment]
Hi you all, thanks for reopening.

My point here is only to suggest that if **DOMPurify v1.0.9** `sanitize` method returns a **different entity** with a **different interface** than the one returned by the previous versions, it likely means this is a **breaking change**. Which is totally fine. 😄

If this is the case a conservative approach would consist of **reverting v1.0.8 back as v1.0.10** and **rolling out v1.0.9 as v2.0.0**. But of course it's totally up to the maintainers.

**Comment by cure53** [comment]
@koto What do you think?

**Comment by koto** [comment]
Well, I'm not a very strong believer in [semver](https://semver.org/), so I personally don't feel this would need a 2.0.0. That said, what's now behind an experimental flag is intended to become just a part of web platform APIs, so this change would then be visible to all users. 

My take on this from the security perspective is the DOMPurify users should not mutate `DOMPurify.sanitize output` for security reasons (it reenables XSS), and doing so is bad practice, so we just incidentally fixed this "glitch". I understand how this might be surprising for clients, and the public API did change here. It's a maintainer call, however, how to reflect that in the release numbers. I don't think personally it warrants a 2.0.0 for such a small change.

**Comment by cure53** [comment]
It is still not clear to me what the best thing to do is here :D

I still do think we should mention the novelty in the README. Any ideas where and how?

**Comment by cure53** [comment]
We have added better documentation:

https://github.com/cure53/DOMPurify/blob/master/README.md#what-about-dompurify-and-trusted-types

Thanks @koto for the wording!
