### ISSUE TITLE
Return empty string when sanitization fails

### ISSUE THREAD

**Issue by iandunn** [cure53/DOMPurify#318]
> If not even `toStaticHTML` is supported, DOMPurify does nothing at all. It simply returns exactly the string that you fed it.

Would it be safer to just return an empty string if sanitization can't be performed? That way the user can trust that the data is safe regardless.

It seems like the fallback is probably not even needed anymore, given that [IE10 and below accounts for roughly 0.43% of all usage](https://caniuse.com/usage-table).

This may be bordering on paranoia, or simply ignorance, but I'm wondering if there's a way -- now, or in the future -- for an attacker to trick the browser or DOMPurify into thinking that sanitization can't be performed, so that the payload slips through unsanitized.

If breaking back-compat is a concern, then a config option could be added to set what gets returned during failure, and it could default to returning the dirty input.

**Comment by cure53** [comment]
Hi Ian, We actually did that in the past and people hated it :D I think a config option might indeed be best, interested in spinning up a PR?

**Comment by cure53** [comment]
@iandunn A quick question, we are getting ready for DOMPurify 1.10 very soon. 
Would the above be something you'd like to see addressed until then or rather not _super_ high prio?

**Comment by iandunn** [comment]
It turns out that I probably won't need DOMPurify in this project after all, so it's not a high priority for me now. Even if we do end up using it, I'd still consider this a low-medium priority hardening than anything urgent.

**Comment by cure53** [comment]
Git it :) Let us know when the flag is needed, will close this ticket until then.

**Comment by tomholub** [comment]
We have a similar concern but would propose a different solution: add `DOMPurify.isSupported()` method or something similar.

During app initialization, we'd test for `DOMPurify.isSupported()` and if the response is falsy, we'd render a "browser not supported" message.

**Comment by cure53** [comment]
@tomholub Would this not suffice, per chance?

`DOMPurify.isSupported`

**Comment by tomholub** [comment]
Missed it, somehow. Yes, that's all we need.
