### ISSUE TITLE
Does this handle CSS?

### ISSUE THREAD

**Issue by joelabair** [cure53/DOMPurify#32]
Does DOMPurify sanitize CSS style sheets embeded in the markup?

**Comment by waterplea** [comment]
@cure53 is there any place where current state of CSS sanitation mentioned? Am I not safe by default, doing DOMPurify.sanitize() on, say `<div style="some possibly malicious CSS">`? Do I need to use hooks and manually remove stuff I consider malicious?

**Comment by cure53** [comment]
Yes, CSS-based attacks are not part of our threat model. We prevent XSS and DOM Clobbering.
