### ISSUE TITLE
Browserstack CI halts mid-flight 

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#320]
We noticed that the builds on Travis CI don't finish anymore, resulting in a broken build, despite all tests being green.

Is there any idea where we can get better debug into on this @tdeekens ?

We tried a couple of things but so far no success.

**Comment by cure53** [comment]
This is where it stops right now:

**Comment by tdeekens** [comment]
No sorry, Can't be of much help. Maybe pinging BrowserStack can give ideas to gain more insights.

**Comment by cure53** [comment]
Oh, I think I know what it is! One of the browsers, lilkely Chrome 72 crash.

**Comment by cure53** [comment]
Turns out it was FF65. Should be good again :D
