### ISSUE TITLE
Sanitize SVG removes the SVG version tag

### ISSUE THREAD

**Issue by sitvanit** [cure53/DOMPurify#321]
> bug 

### Bug
When using DOMPurify for sanitizing SVG file, the sanitize process removes the version of the SVG (version="1.0").

#### Input
```
<svg version="1.0" height="242.0" width="490.0" viewBox="0 0 490.0 242.0" xmlns="http://www.w3.org/2000/svg">
  <path stroke-width="1" stroke="black" fill="none" d="M371.5,18.0L371.5"></path>
</svg>
```

#### Given output
```
<svg height="242.0" width="490.0" viewBox="0 0 490.0 242.0" xmlns="http://www.w3.org/2000/svg">
  <path stroke-width="1" stroke="black" fill="none" d="M371.5,18.0L371.5"></path>
</svg>
```
#### Expected output
```
<svg version="1.0" height="242.0" width="490.0" viewBox="0 0 490.0 242.0" xmlns="http://www.w3.org/2000/svg">
  <path stroke-width="1" stroke="black" fill="none" d="M371.5,18.0L371.5"></path>
</svg>
```

Is it possible not to remove that tag?

**Comment by cure53** [comment]
Heya, yep, that is possible:

`var clean = DOMPurify.sanitize(dirty, {ADD_ATTR: ['version']});`

^ should do the trick. That being said, I believe we can also add the version attribute to the list of white-listed attributes. Let me spin up a commit real quick.

**Comment by cure53** [comment]
Closing this for now, please reopen if anything is not working as expected.

**Comment by sitvanit** [comment]
Thanks, really appreciate the quick fix!
