### ISSUE TITLE
table row/cell tags removed

### ISSUE THREAD

**Issue by magumbasauce** [cure53/DOMPurify#324]
I have a JS function that i'm setting the content of the table body to some default data. A "Search" button uses ajax to load a partial view, which is the actual table data, and replaces the tbody with that data. The function is meant to "clear" or "reset" the data. 

code:

    var dirty = '<tr><td>Click "Search".</tr></td>';    console.log("purify-dirty: " + dirty);

    var clean = DOMPurify.sanitize(dirty);    console.log("purify-clean: " + clean);
    clean = DOMPurify.sanitize(dirty, { ALLOWED_TAGS: ['table','tr', 'td'], ALLOWED_ATTR: ['class', 'style'] }); console.log("purify-clean: " + clean);
    clean = DOMPurify.sanitize(dirty, { USE_PROFILES: { html: true } }); console.log("purify-clean: " + clean);
    clean = DOMPurify.sanitize(dirty, { USE_PROFILES: { table: true } }); console.log("purify-clean: " + clean);

    document.getElementById('table_body').innerHTML = clean;

output:

    purify-dirty: <tr><td>Click "Search".</tr></td>
    purify-clean: Click "Search".
    purify-clean: Click "Search".
    purify-clean: Click "Search".
    purify-clean: Click "Search".

The real version of the default HTML has class and style attributes, which is why they are in one of the specific config items. It does return a result if I include the table tag. This table has lots of columns, and I don't want to have that code in several places. 

I could re-architect the page if I HAVE to include the table tag, but that seems like overkill. Am I missing something in my understanding of injection or sanitization that requires the full table instead of being able to clean row-by-row or cell-by-cell? If so that's fine, I'd like to understand. 

Thanks!

**Comment by cure53** [comment]
Heya, thanks for the bug report. Tables are special because of the fact, that the browser removes TRs and TDs in case they are not surrounded by a parent TABLE element.

What I would recommend here is to work with a hook (we have some example hooks available [here](https://github.com/cure53/DOMPurify/blob/master/demos/hooks-target-blank-demo.html)).

By using a hook, you can quickly add the TABLE around the TR and TD and then remove it right after. Should be quite easy, 10 lines of code. Please let me know if that works for you.

**Comment by cure53** [comment]
Note that for example jQuery has the same problem, and they use some ugly and buggy string parsing for that, we don't wanna go there :D

**Comment by magumbasauce** [comment]
sure sure, pass the buck! :-)

No that makes sense. When i added the table tag around it, the return included the tbody tag as well. I don't know how common what i'm doing is, but might be good to add a comment or something to some of the documentation for the behavior of the sanitize function. (or there is something and i just missed it)

I'll take a look at the events for the hooks. I'll have to see how often this type of thing is used in my app. If it's not often, what i may do is just add the table and tbody tags around what i want to ensure is sanitized, then do a string.split() and take the middle piece out after the sanitization. 

Thanks!

**Comment by cure53** [comment]
Gotta pass that buck :) If we change the core functionality, we change how browsers deal with markup and that will likely have terrifying consequences. 

From what we hear about usage pattern, people more likely change the content of a TD rather than having the whole TR, TD around it as well. And those who do sanitize the TR, TD as well likely found their way of doing it already - and we would break it for them with such change.

**Comment by magumbasauce** [comment]
Yea, def not asking to change anything for purify, only suggesting to put a comment about it. 

Yea, i can see only purifying specific elements instead of all of the content. I'll work it out so it satisfies the intent and the security scans. Thanks!

**Comment by cure53** [comment]
Cool, thanks. If you go with a hook, please let me know if you need help. 

Also happy to accept a PR with a demo hook (and credit you), so we can point users to this in case they have a similar problem.

**Comment by chenghungma** [comment]
Hi, I am using purify and facing the same issue too. Is it possible that you can provide the code of the hook to quickly add the TABLE around the TR and TD and then remove it right after? Much appreciated!

**Comment by magumbasauce** [comment]
sure! i had to remember what i actually asked about and where I was attempting to use this. 

i didn't actually end up with a hook to do this like i was asking about (which is why no PR). I probably should have updated with what i DID end up doing, so I apologize for that until now! 

The pattern that I ended up using was to use a <div> for a container for the entire table with a loading indicator, then replacing that contents with the actual table once the call returned successfully. Something like this: 

`var tableContainer = document.getElementById('table-container-id');
tableContainer.innerHTML = '<p>Loading...</p>';

$.get({
  url: '/Data/GetTableData/',
  success: function(response) {
    tableContainer.innerHTML = DOMPurify.sanitize(response);
  }
};`

Obviously a lot depends on the API or action you are calling into to get the data and what that is actually returning, and if there are other thing inside your table you may need to adjust your sanitize() to allow for things. For example we have SVG's we use for things like checkmarks that are in some tables, so some of those calls have the {ADD_TAGS: ['use']} allowance.

**Comment by chenghungma** [comment]
Thank you for your response! I really appreciate it! What I am doing right now is appending each row to a table inside a for loop and I have multiple columns for each row. Not sure if I can do the same thing...

**Comment by dms120** [comment]
I also have a problem with this.

The hooks seems to be impossible to use because the "tr" tags are removed on _initDocument, before they being called.

Any solutions?
I'm analyzing the possibility of using this lib a relatively big project that's why I'm finding this.

Thanks.

**Comment by cure53** [comment]
This is browser behavior and outside our control, unless we start parsing and autocompleting strings - and we will not do that :) 
Our declared goal is XSS prevention, not full-stack markup management.

**Comment by dms120** [comment]
I understand, but it's a little ugly to preprocess the html before the sanitization and it's a lot of code to change.

Our idea is to use DOMPurify to process all the content that it's using JQuery... but I'm seeing too many problems.
We have a lot of code,  using different standards and a lot of "improvisation" on some ways to to the things and that means a LOT of custom attributes. 

Our jquery vulnerabilities needs to be fixed and we either do this this or upgrade JQuery and that's out of question right now.

**Comment by srcarr1515** [comment]
I know that this is a closed issue, however since I was searching for a solution for this very problem I figured I'd post the solution I used...
I wrapped the html string with a table tag, however I did not permit the table tag to be rendered.

So it looked like this: let clean = DOMPurify.sanitize(html_string, {ALLOWED_TAGS: ['tr', 'td', 'a', 'div']})

Worked perfectly, no need to write a hook.

**Comment by cure53** [comment]
Sneaky, nice :D Thanks for posting this workaround!
