### ISSUE TITLE
Pen Testing failures

### ISSUE THREAD

**Issue by digitaico** [cure53/DOMPurify#326]
> This issue proposes a [bug, feature] which...

### Background & Context

I've tested some pieces of code and checked that indeed your awesome library didn't passed.  So I'd like to help, and my humble contribution is to tell you that,  the fact that some advanced techiniques to bypass XSS filters, are not passed by DimPurify,

Here is the link,  thanks, guys,  you're doing and awesome job.
https://securityonline.info/bypass-xss-filter/?cn-reloaded=1[
](url)

**Comment by Shadowstyler** [comment]
What doesn't get sanitized properly?

**Comment by cure53** [comment]
Not sure if there is anything actionable for us here. Closing for now, please reopen if necessary.
