### ISSUE TITLE
Allow all the attribute for an allowed tag

### ISSUE THREAD

**Issue by ygjdingjie-changed** [cure53/DOMPurify#332]
> This issue proposes a feature that is desired 

### Background & Context
We are using Dompurify to sanitize our HTML document.   We want to keep all the attribute of the <meta> and <link> tag by configuring 
**var clean = DOMPurify.sanitize(dirty, {WHOLE_DOCUMENT: true,ADD_TAGS: ['meta','link']});**  

It seems that some attribute of these two elements are filtered out. Is there a way to handle it without using ADD_ATTR feature. The attribute we want to keep is safe in <meta> and <link>, but may not safe in other elements. That is why we don't want to use ADD_ATTR feature.

Thanks

**Comment by cure53** [comment]
Heya, what is that attribute? Is is by chance a standard attribute we can permit in general?

**Comment by ygjdingjie-changed** [comment]
Wow, that is a quick reply. The attribute name is  _content_.

**Comment by cure53** [comment]
@ygjdingjie-changed haha thanks :D 

So, if it is just one attribute, I would propose to add it via config. It feels a bit risky to handle it without that - given that both `LINK` and `META` can introduce XSS attacks.

**Comment by ygjdingjie-changed** [comment]
Cool. That was my original question. I just want to add this attribute for <meta> and <link> tag. I don't want to massively allow them for other tags. Is there a way?

**Comment by cure53** [comment]
Ah, I understand. The best way if you want to allow the attribute for only one tag is to use a hook. With that, you can do it in 5 lines of code or less.

**Comment by ygjdingjie-changed** [comment]
Could you please share one example with me? I am not sure that I may use the hook correctly

**Comment by cure53** [comment]
This one might be helpful:

https://github.com/cure53/DOMPurify/blob/master/demos/hooks-target-blank-demo.html

**Comment by ygjdingjie-changed** [comment]
Cool. Thank you.
