### ISSUE TITLE
controls attribute in audio and video elements

### ISSUE THREAD

**Issue by astoilkov** [cure53/DOMPurify#336]
> This issue proposes a change

### Background & Context

We have been contacted by one of our users which complaints about this behavior.

### Feature

The proposed change is described [here](https://github.com/careteditor/issues/issues/869) but in short I am asking if it would be some kind of security vulnerability if you don't remove the controls attribute from audio and video elements.

**Comment by cure53** [comment]
Heya, thanks for the ticket. We checked and don't see any reason why not to whitelist the controls attribute.

**Comment by cure53** [comment]
Should be good now, please let us know if not!

**Comment by LaurensRietveld** [comment]
Just bumped into this issue as well. Do you have more info on when the next release round is @cure53 ?

**Comment by cure53** [comment]
Heya, we can actually do a release today if that helps - we have no open issues right now afaik!

**Comment by LaurensRietveld** [comment]
That was quick! That'd be great, thanks :+1:

**Comment by cure53** [comment]
Check out https://github.com/cure53/DOMPurify/releases/tag/1.0.11 :)
