### ISSUE TITLE
Deep link cannot work

### ISSUE THREAD

**Issue by IceNeoMax** [cure53/DOMPurify#339]
i created a link like this to navigate from my webview to a route on an ios app and Dompurify clean it's tag.
So how can i add an exception for this link or some ways to bypass this?
<a href="one://somewhere/hello" target="_blank">hello</a>

**Comment by cure53** [comment]
Heya,

yep, you can configure DOMPurify to allow this:

```javascript
// allow external protocol handlers in URL attributes (default is false)
// by default only http, https, ftp, ftps, tel, mailto, callto, cid and xmpp are allowed.
var clean = DOMPurify.sanitize(dirty, {ALLOW_UNKNOWN_PROTOCOLS: true});

// allow specific protocols handlers in URL attributes (default is false)
// by default only http, https, ftp, ftps, tel, mailto, callto, cid and xmpp are allowed.
// Default RegExp: /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;
var clean = DOMPurify.sanitize(dirty, {ALLOWED_URI_REGEXP: /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp|xxx):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;});
```

These config options are the ones you wanna check, probably :)

**Comment by IceNeoMax** [comment]
@cure53 can I have a global config for that? 👯‍♂

**Comment by tomholub** [comment]
Just a note, I love the response speed here! Thanks @cure53 for maintaining this repo so well.

**Comment by cure53** [comment]
@IceNeoMax What do you mean? Not sure if I understand.

@tomholub Thanks :)

**Comment by IceNeoMax** [comment]
I mean can I add a white list to all of DOMPurify.sanitize function each time I call that?

**Comment by cure53** [comment]
Ah I get it, we had a feature request for this a while ago and you should be able to get there using this flag: https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L201

It was never a really popular flag but it should do exactly what you need. Let me know please.

**Comment by IceNeoMax** [comment]
woaw that's really fast response. thanks for that <3
