### ISSUE TITLE
A small Problem with embeded Video

### ISSUE THREAD

**Issue by IceNeoMax** [cure53/DOMPurify#340]
<iframe class="ql-video" frameborder="0" allowfullscreen="true" src="https://www.youtube.com/embed/Llw9Q6akRo4?showinfo=0"></iframe>
There's my video on youtube and i used sanitize function. and it's gone the whole iframe.
how should i avoid that?

**Comment by cure53** [comment]
Iframes are considered dangerous - would it not be possible to embed the video using the `<video>` element instead?

Alternatively, you could permit iframes and add a hook to make sure only Youtube URLs are allowed.

**Comment by IceNeoMax** [comment]
I guess I gotta permit iframe tag into sanitize function

**Comment by cure53** [comment]
You can do so using the config and then use a hook to check if the URL in the `src` attribute is really pointing at a Youtube video - then it should be secure.

**Comment by VincentDufour** [comment]
Yes you can this. I just past the code here. Note that i used this code in node so the first lines are probably different.

```
const createDOMPurify = require("dompurify");
const { JSDOM } = require("jsdom");

const window = new JSDOM("").window;
const DOMPurify = createDOMPurify(window);

      DOMPurify.addHook("uponSanitizeElement", (node: any, data) => {
         if (data.tagName === "iframe") {
            const src = node.getAttribute("src") || "";
            if (!src.startsWith("https://www.youtube.com/embed/")) {
               return node.parentNode.removeChild(node);
            }
         }
      });

      console.log(<your_dirty_html>);
      const sanitized_html= DOMPurify.sanitize(<your_dirty_html>, {
         ADD_TAGS: ["iframe"],
         ADD_ATTR: ["allow", "allowfullscreen", "frameborder", "scrolling"],
      });
      console.log(sanitized_html);
```

Solution proposed by https://dev.to/patarapolw/securely-embed-youtube-and-other-iframe-elements-in-markdown-2hoc

**Comment by gitnlsn** [comment]
How can I remove a node if it has no parentElement?
