### ISSUE TITLE
Importing DOMPurify results in a CSP violation of inline (“style-src”).

### ISSUE THREAD

**Issue by sikorsky555** [cure53/DOMPurify#343]
### Background & Context

This isn't a huge deal. I haven't noticed any side effects from the CSP violation in Firefox, but when I import DOMPurify, I automatically get a CSP violation in Firefox. I don't have to call a function, just the very nature of importing DOMPurify resulted in the CSP violation.

#### Input

N/A

#### Given output

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“style-src”).

#### Expected output

No CSP violation

**Comment by cure53** [comment]
Hmm, is it possible that this line causes it?

https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L514

**Comment by cure53** [comment]
I believe we can also replace `<style>` with a different CDATA element, i.e. `<textarea>` or `<noscript>` - will check later and see if we can get that CSP violation to be squished.

**Comment by cure53** [comment]
I think the problem might be solved now
