### ISSUE TITLE
Text that begins with a script tag will be stripped, even if ALLOWED_TAGS includes script.

### ISSUE THREAD

**Issue by DoctorBud** [cure53/DOMPurify#352]
> Text that begins with a script tag will be stripped, even if ALLOWED_TAGS includes 'script'.

### Background & Context

 I think there may be a bug when using ALLOWED_TAGS to allow 'script' tags. If my script is the first content in the 'dirty' text, then it will be stripped. Adding any other character before the script will result in the correct behavior, which is to preserve the script.

#### Input (working version)

The following HTML will use dompurify 1.0.11 via unpkg.com and will correctly sanitize the `dirty` string by *preserving* the embedded script:

```html
<!doctype html>
<html>
    <head>
        <script src="https://unpkg.com/dompurify@1.0.11/dist/purify.min.js"></script>
    </head>
    <body>
        <h1>Sanitized content below (URIEncoded so you can see script tags)</h1>
        <div
        	id="sanitized"
        	style="border:5px solid blue;padding:20px;"></div>

        <script>
            /* jshint globalstrict:true, multistr:true */
            /* global DOMPurify */
            'use strict';

            // Specify dirty HTML
            var dirty = '<script>var x = 12345;<' + '/script>';

            //
            // If you comment the following out, then the script node will be removed
            // by sanitize(). This is a bug.
            //
            dirty = '&nbsp;' + dirty;

            // Allow <script> tags
            var config = { ALLOWED_TAGS: ['script'] };
            var clean = DOMPurify.sanitize(dirty, config);
            document.getElementById('sanitized').innerHTML = encodeURIComponent(clean);
        </script>
    </body>
</html>
```

The blue `sanitized` box should contain:

```
%26nbsp%3B%3Cscript%3Evar%20x%20%3D%2012345%3B%3C%2Fscript%3E
```

#### How to demonstrate the bug

Comment out the following line from the above HTML:

```
dirty = '&nbsp;' + dirty;
```

If you refresh the page, then the blue `sanitized` box will contain  *nothing*, which is incorrect behavior. The script should be preserved because I'm using `ALLOWED_TAGS`.

#### My workaround

In my application, I prefix my dirty string with `&nbsp;` and then remove that prefix after using `sanitize()`. But it feels sort of gross to do that.

**Comment by cure53** [comment]
Heya, thanks for the bug report. I believe your problem can be fixed using the `FORCE_BODY` flag. Setting it to `true` should do the trick more elegantly than the indeed yucky non-breaking space :D  

```javascript
// Allow <script> tags
var config = { ALLOWED_TAGS: ['script'], FORCE_BODY: true };
var clean = DOMPurify.sanitize(dirty, config);
document.getElementById('sanitized').innerHTML = encodeURIComponent(clean);
```

The reason behind this is browser behavior that we don't wanna work around to much but rather compensate with some tricks.

**Comment by cure53** [comment]
@DoctorBud Did the config flag do the trick?

**Comment by cure53** [comment]
Closing this as assumed fixed

**Comment by DoctorBud** [comment]
Yes! The config flag works without requiring the kludge. Sorry for the delayed confirmation. Thank you.

**Comment by cure53** [comment]
Fantastic :)
