### ISSUE TITLE
Return nothing but trustedHTML {} in chrome

### ISSUE THREAD

**Issue by zimocode** [cure53/DOMPurify#354]
![image](https://user-images.githubusercontent.com/29518677/62830163-426cd880-bc3c-11e9-910b-a2fd587add6b.png)
![image](https://user-images.githubusercontent.com/29518677/62830172-71834a00-bc3c-11e9-8b1c-18fae643041a.png)

chrome beta/dev/canary get the same one,  but it works OK a few days ago .

**Comment by cure53** [comment]
Heya, that is expected behavior and documented here:

https://github.com/cure53/DOMPurify#what-about-dompurify-and-trusted-types
