### ISSUE TITLE
Text copied from word document is sanitized but not from mac note pad.

### ISSUE THREAD

**Issue by YIZHUANG** [cure53/DOMPurify#355]
> This issue proposes a [bug, feature] which...

### Background & Context

If the text is copied paste from word document or notepad(comes with mac) and then inject it into an editable "div" element, text is sanitized for the one that comes from word document but not from notepad.

#### Input

For word:  
`@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:roman;
	mso-font-pitch:variable;
	mso-font-signature:-536870145 1107305727 0 0 415 0;}
Hello world`

On notepad:
`
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px 'Helvetica Neue'}
Hello wolrd
`

#### Given output

On word: Only Hello world is kept, which is correct.
On notepad: Nothing is stripped out.

#### Expected output

Only plain text should be kept.

#### Config

```
const config = {
{ ALLOWED_TAGS: [], ALLOWED_ATTR: [] }
}
```

**Comment by cure53** [comment]
Hi, thanks for the bug report - not sure if this is indeed our bug. At what point is DOMPruify involved?

**Comment by YIZHUANG** [comment]
> Hi, thanks for the bug report - not sure if this is indeed our bug.
> 
> At what point is DOMPurify involved? Do you have sample code available?

Hi, after getting the text which is copied and pasted from word/notepad, i ran the following function to try to get the clean text:

```
const input = document.getElementById("#myInput")   // it's a div element which contenteditable set to true;
const config = {
{ ALLOWED_TAGS: [], ALLOWED_ATTR: [] }
}
const cleanContent = DOMPurify.sanitize(input.textContent, config);
console.log(cleanContent)  // still contains the css style.
 
```

**Comment by cure53** [comment]
I tried to reproduce the problem but need more info.

* What is the OS version you use?
* What browser and browser version do you use?

**Comment by YIZHUANG** [comment]
@cure53 
1.  macOS Mojave(Version 10.14.6).
2. Chrome  Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by cure53** [comment]
I checked and don't think the bugs is ours. 

I presume the problem might be in different copy&paste handling depending on the source data. Have you tried to set a break-point in DOMPurify to see if it actually gets called?

I could imagine that maybe DOMPurify isn't even called when using Notepad - can you confirm?

**Comment by YIZHUANG** [comment]
Hi, I will check it. Thank you👍👍

**Comment by YIZHUANG** [comment]
@cure53  i tried the following in https://cure53.de/purify:
<img width="849" alt="Screenshot 2019-08-12 at 15 26 54" src="https://user-images.githubusercontent.com/28932103/62864897-a31c1400-bd15-11e9-9a1a-4d9be02aaef4.png">

**Comment by cure53** [comment]
Yep, that is exactly the expected result, no?

**Comment by YIZHUANG** [comment]
```
<!--
 /* Font Definitions */
 @font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:roman;
	mso-font-pitch:variable;
	mso-font-signature:-536870145 1107305727 0 0 415 0;}
@font-face
	{font-family:DengXian;
	panose-1:2 1 6 0 3 1 1 1 1 1;
	mso-font-alt:等线;
	mso-font-charset:134;
	mso-generic-font-family:auto;
	mso-font-pitch:variable;
	mso-font-signature:-1610612033 953122042 22 0 262159 0;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;
	mso-font-charset:0;
	mso-generic-font-family:swiss;
	mso-font-pitch:variable;
	mso-font-signature:-536859905 -1073732485 9 0 511 0;}
@font-face
	{font-family:AppleSystemUIFont;
	panose-1:2 11 6 4 2 2 2 2 2 4;
	mso-font-alt:Calibri;
	mso-font-charset:0;
	mso-generic-font-family:auto;
	mso-font-pitch:auto;
	mso-font-signature:3 0 0 0 1 0;}
@font-face
	{font-family:"\@DengXian";
	panose-1:2 1 6 0 3 1 1 1 1 1;
	mso-font-charset:134;
	mso-generic-font-family:auto;
	mso-font-pitch:variable;
	mso-font-signature:-1610612033 953122042 22 0 262159 0;}
 /* Style Definitions */
 p.MsoNormal, li.MsoNormal, div.MsoNormal
	{mso-style-unhide:no;
	mso-style-qformat:yes;
	mso-style-parent:"";
	margin:0cm;
	margin-bottom:.0001pt;
	mso-pagination:widow-orphan;
	font-size:12.0pt;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:DengXian;
	mso-fareast-theme-font:minor-fareast;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;}
.MsoChpDefault
	{mso-style-type:export-only;
	mso-default-props:yes;
	font-family:"Calibri",sans-serif;
	mso-ascii-font-family:Calibri;
	mso-ascii-theme-font:minor-latin;
	mso-fareast-font-family:DengXian;
	mso-fareast-theme-font:minor-fareast;
	mso-hansi-font-family:Calibri;
	mso-hansi-theme-font:minor-latin;
	mso-bidi-font-family:"Times New Roman";
	mso-bidi-theme-font:minor-bidi;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 2.0cm 70.85pt 2.0cm;
	mso-header-margin:36.0pt;
	mso-footer-margin:36.0pt;
	mso-paper-source:0;}
div.WordSection1
	{page:WordSection1;}
-->
Hello world
```
I also tried this which is from word document, then it works. 
<img width="826" alt="Screenshot 2019-08-12 at 15 31 08" src="https://user-images.githubusercontent.com/28932103/62865110-39503a00-bd16-11e9-801f-7599a7295833.png">

**Comment by cure53** [comment]
Because the text is inside a comment. The other one not.

**Comment by YIZHUANG** [comment]
@cure53  Thank you.

**Comment by cure53** [comment]
Welcome :)
