### ISSUE TITLE
Why minlength is in blacklist?

### ISSUE THREAD

**Issue by YuryRybakSoftensity** [cure53/DOMPurify#357]
Could you please clarify why minlength is in blacklist, because I wasn't able to found out it by my own.

**Comment by cure53** [comment]
Afaik it is not a standard attribute and neither part of HTML/SVG or MathML - so we don't whitelist it. But happy to add if I am wrong with my assumption :)

**Comment by YuryRybakSoftensity** [comment]
I was able to find it on MDN:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text#minlength
https://caniuse.com/#search=minlength

**Comment by cure53** [comment]
Ah, interesting. Then please file to send over a PR and we will add it.
