### ISSUE TITLE
Add Ethereum name or address to package.json

### ISSUE THREAD

**Issue by lastmjs** [cure53/DOMPurify#360]
> This issue proposes a feature which...

### Background & Context

I would like to see an Ethereum name or address added to the ethereum field of the package.json file. This will allow consumers of the project to know a cannonical address to send funds to. For example, I'm building an application that will allow developers to automatically donate ETH to all of their npm dependencies that have Ethereum addresses in their package.json files: https://sustainus.io

### Feature

Just add an Ethereum address to the package.json file and any consumer of the project would have a verified address for sending funds to the project. Sustainus in particular will do this now (and since dompurify is one of my dependencies you'll at least get some donation from me).

**Comment by cure53** [comment]
Oh, that is a nice idea!

> Add the "ethereum" field to your project's package.json file.

Where to add this field and how? I saw some mixed feedback in other related tickets.

**Comment by lastmjs** [comment]
Yes, I would encourage you to setup GitHub sponsors and put the address in the custom field of the FUNDING.yml file:

```yml
custom: ['ethereum/0xyour-ethereum-address']
```

I haven't yet integrated looking in the FUNDING.yml file, but I will soon. It's a more widespread and standard-like place to put it. But, you could also put it in the ethereum field of the package.json if you'd like

**Comment by lastmjs** [comment]
Take a look at https://github.com/lastmjs/sustainus, I have GitHub Sponsors setup with the FUNDING.yml file, and you can see what happens when you click on the sponsor button

**Comment by cure53** [comment]
Sounds good, applied for GitHub Sponsors, added FUNDING.yml :)

**Comment by lastmjs** [comment]
Nice! Make sure you turn on GitHub Sponsors in your repository's settings, you don't need to apply to do that. The Sponsor button should show up immediately on your repo after you do that

**Comment by cure53** [comment]
Found it, thanks!
