### ISSUE TITLE
Removing all nodes with "</" in an attribute is too aggressive

### ISSUE THREAD

**Issue by thorn0** [cure53/DOMPurify#369]
### Background & Context

Since the version 2.0.1 DOMPurify became too aggressive.

### Bug

[jsbin](https://jsbin.com/joqitak/1/edit?html,js,console)

#### Input
```html
<span data-modal='{"markup":"<strong>foo</strong> bar"}'></span>
```

#### Given output

empty string

#### Expected output

same as input

**Comment by cure53** [comment]
It mitigates  an mXSS bug in Blink and other engines - and as far as I can see this is the best way we have for that right now. So we need to leave it in.

If you have a better proposal, we're super happy to hear it.

**Comment by cure53** [comment]
I think you can actually quite trivially fix the problem for your specific case with a hook.

**Comment by thorn0** [comment]
https://research.securitum.com/dompurify-bypass-using-mxss/ says this mXSS is not a problem if `FORBID_TAGS: ['svg', 'math']` is specified. Can we probably add such a check?

**Comment by cure53** [comment]
That is not a bad idea. Let me look into that!

**Comment by cure53** [comment]
So, the tests are quite happy about this change:

```javascript
      /* Check for possible Chrome mXSS, least aggressively */
      if (
        (!ALLOWED_TAGS.svg || FORBID_TAGS.svg) &&
        (!ALLOWED_TAGS.math || FORBID_TAGS.math)
      ) {
        if (removeSVGAttr && /<\//.test(value)) {
          _forceRemove(currentNode);
        }
      }
```

Either the tag is not allowed... or it is forbidden in the first place. And if that is the case from both SVG and Math, we should be good. Hopefully. Wdyt?

**Comment by thorn0** [comment]
At least this would work for me. :)

**Comment by cure53** [comment]
Alright, let's see :)

**Comment by thorn0** [comment]
Oh, the condition doesn't look good actually. It should be negated.

**Comment by cure53** [comment]
Sure?

**Comment by cure53** [comment]
Okay, latest commit in master should address the issue, can you check please @thorn0 ?

**Comment by thorn0** [comment]
Tested it. Works for me. Thanks.

**Comment by cure53** [comment]
Cheers!

**Comment by cure53** [comment]
Just a quick ping @thorn0 - we fixed the broken SVG check and now things are expected to work well again. Thanks a lot for spotting this, the pressure to fix the bypass made us overlook the logical bug.

The tests are now accurate as well and it seems that things are slowly moving back to normal :)
