### ISSUE TITLE
Keep text between tags || Remove only Tags

### ISSUE THREAD

**Issue by rDieCbw** [cure53/DOMPurify#377]
I have an Test string.

```const html = '{%remove%} useful {{remove}} <svg></p><style><a id="</style><img src=1 onerror=alert(1)>"> useful';```

And I'm trying to remove all the html content and the {{, }}, {%, %}. But I'd like to keep the **useful** word on string.

```const purifyConfig = {
    FORBID_TAGS: ['{{', '{%',],
    SAFE_FOR_TEMPLATES: true,
    RETURN_TRUSTED_TYPE: true,
    ALLOW_DATA_ATTR: false,
    KEEP_CONTENT: true,
};
const clean = DOMPurify.sanitize(html, purifyConfig);
```
The clean Result in a Empty string. 

What configuration should I use to do this?

**Comment by cure53** [comment]
Oof, we don't match this even if `SAFE_FOR_TEMPLATES` is on: `{%remove%}`

I would recommend to remove that manually, maybe.

**Comment by rDieCbw** [comment]
> Oof, we don't match this even if `SAFE_FOR_TEMPLATES` is on: `{%remove%}`
> 
> I would recommend to remove that manually, maybe.

Alright but, how to maintain the text between tags ?

**Comment by cure53** [comment]
With the example you are using this is hard to achieve: 

For the sanitizer, the text is _inside_ the SVG. And SVG is one of the elements where we explicitly make sure that all content is removed _if_ the SVG is removed - else we have XSS :)

https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L242
