### ISSUE TITLE
Ampersand escaped since 2.x

### ISSUE THREAD

**Issue by ChristophWurst** [cure53/DOMPurify#379]
> This issue proposes a bug which...

### Background & Context

We use this lib in Nextcloud to escape translation strings. We found that recently some of our strings show HTML-encoded ampersands on the UI. I discovered this has to do with string that have an `&` like `Devices & sessions`.

#### Input

`Devices & sessions`

#### Given output

`Devices &amp; sessions`

#### Expected output

`Devices & sessions`

Is there any config to prevent this?

Cheers :v:

**Comment by cure53** [comment]
Interesting! Are you sure it's DOMPurify doing that? We don't encode (this character) explicitly and I would assume it's the browser doing that.

**Comment by cure53** [comment]
>  Ampersand escaped since 2.x #379 

Do you happen to know in which version that behavior showed first?

**Comment by ChristophWurst** [comment]
```
> DOMPurify.version
"1.0.11"
> DOMPurify.sanitize('Devices & sessions')
"Devices & sessions"
```
and
```
> DOMPurify.version
"2.0.0"
> DOMPurify.sanitize('Devices & sessions')
"Devices &amp; sessions"
```

-> something in https://github.com/cure53/DOMPurify/compare/1.0.11...2.0.0 must have changed this, I guess.

> Are you sure it's DOMPurify doing that? We don't encode (this character) explicitly and I would assume it's the browser doing that.

How could I test this? I'm on FF72.0 right now. Don't have too much knowledge about how DOMPurify works, hence need a bit of guidance with debugging :)

**Comment by cure53** [comment]
Ah, I think I know what it is - and it might relate to some of the fixes we had to do against the mXSS bugs found several weeks ago. That version info helped.

The best might be to write a small hook and fix it like that - should be 3-4 lines of code, max.

**Comment by ChristophWurst** [comment]
So would you consider this the expected output and thus add the hook to our application or is it a regression to be fixed here?

**Comment by cure53** [comment]
I would propose not to fix it in DOMPurify, we would consider this expected output for HTML strings.

**Comment by ChristophWurst** [comment]
Okidoke, thanks for the quick help :)

**Comment by cure53** [comment]
Yw :)

**Comment by ChristophWurst** [comment]
> The best might be to write a small hook and fix it like that - should be 3-4 lines of code, max.

I tried a few things and

```js
DOMPurify.addHook('afterSanitizeElements', function(node, data, config) {
    if (node.nodeType === Node.TEXT_NODE) {
        node.nodeValue = node.nodeValue.replace('&amp;', '&');
    }
    return node;
})
```

was the final solution I came up. Although this changes the node value, the result of `sanitize` still uses `&amp;`. Do I have to use any other (later?) hook?

**Comment by cure53** [comment]
Hmm, then I am almost 100% certain that it is the browser who turns the ampersand back into its own entity. I am wondering - will the sanitized data not be rendered in HTML context later on?

Because if so, it should display things correctly nevertheless. What is the problem caused by the encoded ampersand?

**Comment by ChristophWurst** [comment]
Is there a simple way to check if that's the browser? If that is the case, why would it matter if we're using `dompurify` v1.x or v2.x?

We render HTML, but with Vue.js templates. This seems to be a problem others have also ran into: https://forum.vuejs.org/t/how-to-display-escaped-html-special-characters-the-right-way/33845/5. I'll see if I can use this decoding trick https://jsfiddle.net/jamesbrndwgn/3pfmw4cd/1/.

**Comment by ChristophWurst** [comment]
That worked for us https://github.com/nextcloud/server/pull/18741.

Thanks :v:

**Comment by cure53** [comment]
Okay :D

**Comment by fraywing** [comment]
Can we re-open this? Having this issue to after upgrading. Will probably have to downgrade, now.

**Comment by cure53** [comment]
If you downgrade you will have XSS. 

I recommend to look for the root cause why the ampersand shows as it does. Can you shed some more light on how DOMPurify is being used here?

**Comment by Thalandor** [comment]
Hi, I tried the hook approach proposed by Christoph and well...same as him, when I try to execute the sanitize the &amp is still there. I tried to debug the hook and the nodeValue property doesn't have the &amp, so basically doesn't need to replace anything. However, after the sanitize you can clearly see it. I've tried it on the chrome.

**Comment by cure53** [comment]
We still need more info from folks how and why the ampersand remains. 

It is very unlikely that we will change our sanitation behavior because of that - but we might be able to look at how the data is being used and help with that part.

**Comment by Thalandor** [comment]
It's fine if you don't change it, for some reason is the behaviour there. As far as I've seen in library's code that node's value seems correct (and it's the one we are passing to the hook) however, we're returning the innerHTML, where the '&' is encoded to '&amp!'.

The use case i'm implementing is to sanitize the whole json received from an API (communication via swagger interface), before you ask, yes, we have some architectural problems and it's a pain in the ass to try to sanitize things one by one (i've been doing it until I discovered this library ^^'), but a generic approach like this would solve a lot of problems. Probably at the end of the day we need to discard this generic approach because I doubt the & would be the only issue we find but...who knows.

Btw, thanks for answering so fast!

**Comment by cure53** [comment]
Yw and aye, we'll stay put for now then :)
