### ISSUE TITLE
sanitize throws an exception when called on a string with IN_PLACE set to true

### ISSUE THREAD

**Issue by fstanis** [cure53/DOMPurify#380]
> This issue proposes a [bug, feature] which...

### Background & Context

`sanitize` throws `TypeError: Illegal invocation` if called with a string when `IN_PLACE` is set.

I'm aware it's meaningless to sanitize a string "in place", but this can easily happen by accident e.g. when using `setConfig`. I think there should either be a better error or (preferably) `sanitize` should ignore the value of `IN_PLACE` when the input is a string.

#### Input

```js
const createDOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');
const window = (new JSDOM('')).window;
const DOMPurify = createDOMPurify(window);
DOMPurify.sanitize('<p></p>', {IN_PLACE: true}); // throws
```
#### Given output

Throws `TypeError` exception inside `_createIterator `.

#### Expected output

`"<p></p>"`

**Comment by cure53** [comment]
Interesting find, we'll have a look soon!

**Comment by fstanis** [comment]
Hey @cure53, is that the correct commit? I see it only updates versions in package.json, but no code changes?

**Comment by cure53** [comment]
Weird, let me double-check...

**Comment by cure53** [comment]
Now, check again please :)

**Comment by fstanis** [comment]
Nice, thanks for the fast fix! :)

**Comment by cure53** [comment]
Yw :)
