### ISSUE TITLE
DOMPurify is not keeping text between stripped markup in 2.0.7

### ISSUE THREAD

**Issue by leocaseiro** [cure53/DOMPurify#381]
> This issue proposes a bug

### Background & Context

Since **2.0.7**, DOMPurify changed the default behaviour in regards to stripping out markup. It used to keep the text between the markup on previous versions **(Eg: 2.0.6)**

### Bug

Since 2.0.7 removes anything after the markup

#### Input

```js
DOMPurify.sanitize('<p>abc<iframe//src=jAva&Tab;script:alert(3)>def');
```

#### Given output
**2.0.6**
```html
<p>abcdef</p>
```
See at https://stackblitz.com/edit/dompurify-207-issue?file=index.ts

**2.0.7**
```html
<p>abc</p>
```
https://stackblitz.com/edit/dompurify-207-issue-with206?file=index.ts

#### Expected output

```html
<p>abcdef</p>
```

**Comment by cure53** [comment]
Heya, this was done to fix an mXSS bypass - it will happen for all those tags listed in here:

https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L243

I fear that if we bring the text back, we will also bring the XSS back.
