### ISSUE TITLE
[feature] Guard against prototypal changes/poisoning

### ISSUE THREAD

**Issue by dejang** [cure53/DOMPurify#383]
### Background & Context

In an environment where multiple 3rd party libs may be loaded it may happen that some alter critical functionality required by DOMPurify. It may also happen that some 3rd party code is malicious and deliberately makes changes to the prototype of some global objects. Since DOMPurify does not protect against such behavior it's functionality can be affected over the lifespan of an application and its output may altered indirectly through prototypal poisoning. 

The code has very few guards for this problem, the ones I noticed in current codebase are `arraySlice` and `freeze` but that's pretty much it. There are a lot more method calls that DOMPurify relies on, specifically things that can be found on `Document.prototype`, `Node.prototype`, `String.prototype` and `Element.prototype`.

### Feature

The change I'm proposing is merely around safeguarding these APIs by taking a snapshot of them at the moment of loading DOMPurify. This snapshot works on the principle: "trust what has been loaded until DOMPurify, nothing after DOMPurify loads". If developers load DOMPurify among the first scripts in their page, and most of them do, this means that no matter what code loads after and no matter what happens to the global prototypes, DOMPurify will continue to function as expected. This will ensure the library maintains its robustness even under really tough environment situations.

For this feature a new set of utilities needs to be introduced and code needs to be rewritten in a certain way. I hope the snippets below express better what this feature request implies. 

* original code taken from purify.js
```
  if (typeof HTMLTemplateElement === 'function') {
    const template = document.createElement('template');
    if (template.content && template.content.ownerDocument) {
      document = template.content.ownerDocument;
    }
  }
```

* shared.js, set of utilities needed for this feature
```
function unapply(func: Function): Function {
    return (thisArg: any, ...args: any[]) => apply(func, thisArg, args);
}

export const {
   getOwnPropertyDescriptor as ReflectGetOwnPropertyDescriptor,
   apply,
   ....
} = Reflect;

export const createElement = unapply(Document.prototype.createElement);
export TemplateContentGetter = ReflectGetOwnPropertyDescriptor(HTMLTemplateElement.prototype, 'content').get;
export NodeOwnerDocumentGetter = ReflectGetOwnPropertyDescriptor(Node.prototype, 'ownerDocument').get;
```

* same snippet of code in purify.js, rewritten to use utilities.
```
import {
  createElement
  apply,
  ReflectGetOwnPropertyDescriptor,
  TemplateContentGetter,
  NodeOwnerDocumentGetter
} from './shared'

...
  if (typeof HTMLTemplateElement === 'function') {
    const template = createElement(document, 'template');
    const content = apply(TemplateContentGetter, [template]);
    const ownerDocument = apply(NodeOwnerDocumentGetter, [content]);

    if (content && ownerDocument) {
      document = ownerDocument;
    }
  }
...
```

We use this pattern everywhere in our code and it's been relieving to know that we have something we can always trust to work as expected throughout the entire lifespan of the application/environment. Right now, DOMPurify is the only 3rd party code we load and it's the only code that can be attacked through prototypal poisoning. If this feature request is approved I can lead the effort and start submitting PRs with code changes. By opening this issue I'd like to first start a conversation around this topic and see if the maintainers of DOMPurify would agree to something like this.

**Comment by cure53** [comment]
Heya, thanks for the feature proposal, I think that makes perfect sense. 

We do have certain protections already in place but mostly to protect against DOM clobbering. It makes sense to expand that to prototype changes/poisoning as well.

Are you planning to spin up a PR?

**Comment by dejang** [comment]
Yes, I'm planning to create a PR with all these changes. It's going to a big PR though so I just want to give a heads up.

**Comment by cure53** [comment]
Fantastic, thanks! Looking forward to it :)

**Comment by KiziKr** [comment]
Hello sorry for my english, im french.

If i understood correctly, working with node js, I should place dompurify at the first position in my dependencies?

like that ?

```
 "dependencies": { 
    "dompurify": "^2.0.8",
    "apollo-server-express": "^2.10.0",
    "bcrypt": "3.0.8",
    ...
}
```

Thanks :)

**Comment by dejang** [comment]
The order in which you import DOMPurify in your code matters. If you're using a bunch of 3rd party libraries that may alter the global prototypes it would be best to include DOMPurify in your code prior to importing those libraries. 

`package.json` does not influence the order in which libraries are used in your code, it's merely a list of dependencies and a bunch of other things which describe what this package is and does.

**Comment by KiziKr** [comment]
Ok thank you :)

So in my app.ts file, where starting my project if I import my file like that:

```
import createDOMPurify from 'dompurify';
import { JSDOM } from 'jsdom';

import { bootstrapMicroframework } from 'microframework-w3tec';
import { Logger } from './lib/logger';
...

export const DOMPurify = createDOMPurify((new JSDOM('')).window);
```

And then when I call dompurify later in my other files like that, is correct ?

```
import { DOMPurify } from 'mypath/app.ts';
```

Sorry if my question is stupid, it is to be sure to use good practices.

Thanks :)

**Comment by dejang** [comment]
I'd suggest caching the DOMPurify instance in a separate file, that way you can avoid weird circular dependencies as your application grows.

```
// dompurify.ts
import createDOMPurify from 'dompurify';
import { JSDOM } from 'jsdom';

// don't forget to configure DOMPurify according to your needs
export const DOMPurify = createDOMPurify((new JSDOM('')).window);
```

Then import in your app where you need it
```
// app.ts
import {DOMPurify} from './dompurify'
....
app.get(.....);
```

But yes, you pretty much got the point. Good luck!

**Comment by KiziKr** [comment]
Ok that's great, thank you very much :)

**Comment by cure53** [comment]
Hi @dejang, is this ticket still needed? Just doing some cleanup, hence asking.

**Comment by dejang** [comment]
Hi,

I think we can close it, I have not had time to come back to the DOM APIs yet. I do plan on doing it though. Would the issue still be required in that case or can I just open a PR with the changes when it's ready?

**Comment by cure53** [comment]
Cool, thanks and no, the PR is always welcome independently of the ticket :)
