### ISSUE TITLE
Not compatible with JSDOM 16.0

### ISSUE THREAD

**Issue by tripodsan** [cure53/DOMPurify#387]
> This issue proposes a [bug, feature] which...

### Background & Context

[JSDOM 16.0](https://github.com/jsdom/jsdom/releases/tag/16.0.0) introduces a breaking change:

> Each jsdom Window now creates new instances of all the web platform globals. That is, our old shared constructor and prototypes caveat is no longer in play.

Which is a problem when using DOMPurify on a different window instance.

#### Input

```js
const createDOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');

const { window } = (new JSDOM(''));
const DOMPurify = createDOMPurify(window);

//-----------------------------------------
const dom = new JSDOM('<!DOCTYPE html><p>Hello world</p>');
DOMPurify.sanitize(dom.window.document.body, { RETURN_DOM: true });
```

#### Given output

Throws:
```
node_modules/dompurify/dist/purify.cjs.js:513
      var matches = dirty.match(/^[\s]+/);
                          ^
```

When using **jsdom-16.x** but works with **jsdom-15.x**

#### Workaround

use the `window` from the same dom:

```js
const createDOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');

const dom = new JSDOM('<!DOCTYPE html><p>Hello world</p>');
const DOMPurify = createDOMPurify(dom.window);

DOMPurify.sanitize(dom.window.document.body, { RETURN_DOM: true });
```

**Note:** due to the architecture of our application, it is requires a hack to pass in the original window without a major rewrite. so it would be great if this still worked.

**Comment by cure53** [comment]
Heya, interesting, thanks for spotting this! 

I frankly have no idea how to fix this, @tdeekens any idea per chance?

**Comment by tdeekens** [comment]
So far no. We are also struggling in other apps to easily update to v16 due to this.

**Comment by cure53** [comment]
Yikes, I see, thanks :) So, as mentioned, I don't know how to address this and have no capacity to look into this - but happy to review any PR or proposal to address this.

**Comment by tdeekens** [comment]
1. I think we should state for now, maybe in the readme, that we're supporteding JSDOM < 16 and reference this issue.
2. We could offer mapping functions for JSDOM16 and below returning window and body checking a version property on JSDOM
3. Refactor dompurify itself to be fully JSDOM16 compatible

That's roughly what I can come up with with a first ship of morning ☕️ 😄.

**Comment by tripodsan** [comment]
> 1. I think we should state for now, maybe in the readme, that we're supporteding JSDOM < 16 and reference this issue.

IMO, using JSDOM 16.x is only a problem 
- if the sanitizer operates directly on the dom document **and**
- if the  `window` passed to dompurify doesn't belong to the same dom instance the document is from.

**Comment by tdeekens** [comment]
Can we check that somehow when receiving things as an `invariant` (tiny-invariant) before starting to work to give better DX and feedback?

**Comment by cure53** [comment]
Hmm, anything I can do at this point?

**Comment by cure53** [comment]
Closing this for now, please reopen if there is anything we can do at this point.
