### ISSUE TITLE
Difficulty removing a node

### ISSUE THREAD

**Issue by mikesnare** [cure53/DOMPurify#388]
See https://jsbin.com/kokuqecoci/8/edit?js,console for a working example of the issue.

I have some node types that I need fully removed -- i.e. not just the tag (leaving the content) but the node and all its children.  I have some node types where I need the tag stripped but the content left in place, and I have some nodes where the node and it's content are fine, subject to the previous rules.

As a simplified example, say that `DIV`s are fully allowed, but `SPAN`s need to be completely removed, including content.

So, given the input `<div><span>This is my span</span></div>` what I need for output would be `<div></div>` (this is simplified example to demonstrate the problem).

In order to achieve this I set up the following:

```js
var CONFIG = {
  ALLOWED_TAGS: [
    'div',
    '#text'
  ],
  ALLOWED_ATTR: [],
  KEEP_CONTENT: true,
};

window.DOMPurify.setConfig(CONFIG);

DOMPurify.addHook('uponSanitizeElement', function(node) {
  console.log('uponSanitizeElement: ' + node.nodeName);
  if (node.nodeName === 'SPAN') {
    console.log('Attempting to remove ' + node.nodeName + ' from ' + node.parentNode.nodeName);
    return node.parentNode.removeChild(node);
  }
});


try {
  var html = "<div><span>This is my span</span></div>";
  console.log(DOMPurify.sanitize(html).trim())
} catch(e) {
  console.error(e);
}
```

When I run this, I get errors in the console due to the removal of the SPAN.  In the demos folder, the example for removing nodes uses the `beforeSanitizeAttributes` hook, but that hook does not get called back for me for the `span` in this example.

I'm perfectly willing to believe that I'm just doing something wrong, but I don't know what that might be.  Any help would be appreciated.

**Comment by cure53** [comment]
Heya, 

hmmm - have you tried to add the SPAN`and others but DIV to `FORBID_CONTENTS`?
https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L253

**Comment by mikesnare** [comment]
Didn't know that was a thing, so thanks!  Looks like it does what I need without any callbacks needed, but it's also a private internal config so I can't change it without modifying the source.  Would you accept a PR to fix that?

**Comment by mikesnare** [comment]
Actually, I may have found another way.  The trick is that the node type you want to remove needs to be registered in `ALLOWED_TAGS`.  If you mark it as being allowed but then do the removal yourself in the callback as shown, this seems to work.  So, that's confusing, but I will play with that for a bit and see if that fixes my issue in all cases.

**Comment by cure53** [comment]
Interesting! Maybe it makes sense to turn your case into a demo for the demos-folder? Just so we can reference it when someone else runs into the problem?

**Comment by mikesnare** [comment]
Happy to.  Will do that as soon as I finish the work that started all this...  😄

**Comment by cure53** [comment]
Awesome, thanks for the PR!
