### ISSUE TITLE
Add copyright and license notice to Javascript files

### ISSUE THREAD

**Issue by mscheele7** [cure53/DOMPurify#392]
### Background & Context

The distributed javascript files pulled from NPM do not contain copyright and license notices in either the full or minified files. If loaded as-is into a project, the browser will request and receive just the javascript files at runtime. It has been raised as an issue internally that this would lead to distribution of the javascript files absent the attribution required by the license(s).

### Feature

Add a comment at the start of the distributed javascript files identifying copyright owner and license(s).

**Comment by cure53** [comment]
Heya, thanks for filing this issue. Would you mind spinning up a PR taking care of that problem?

**Comment by cure53** [comment]
My understanding is that, from looking at how jQuery does it, only a one-liner needs to be added correct? Such as:

`/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/license */`

**Comment by mscheele7** [comment]
Yes, that's all that we'd need.

**Comment by cure53** [comment]
Cool, we don't mind that change, please feel free to send a PR and we will review and accept.

**Comment by mscheele7** [comment]
Unfortunately, corporate policy raises barriers to direct contributions even for the smallest of changes.

**Comment by cure53** [comment]
We have reviewed this issue and decided to close it as it appears to read as follows:

* Massive corporation wants to use this software for free
* Massive corporation has some legal concerns though
* Massive corporation wants maintainers to fix its problem for free 

Maybe fix your corporate policies or simply find a different sanitizer?
