### ISSUE TITLE
Sanitize function does not allow Script tag

### ISSUE THREAD

**Issue by DroidUnknown** [cure53/DOMPurify#395]
> This issue proposes a [bug, feature] which...

### Background & Context

I want to sanitize an html which also has a script tag. That script tag should be allowed. I tried to use `DOMPurify.sanitize(dirty, {ADD_TAGS: ['script']});`
but it doesn't work.
#### Input
```
var data = '<script>var asd = 123;</script>'
DOMPurify.sanitize(data)
DOMPurify.sanitize(data, {ADD_TAGS: ['script']})
```
#### Given output
Empty string
#### Expected output
`<script>var asd = 123;</script>`
### Feature
This script tag introduces JS variables with data sent from backend.

**Comment by cure53** [comment]
This code should fix the issue for you:

```javascript
var sane = DOMPurify.sanitize('<script><\/script>', {
    FORCE_BODY: true, 
    ADD_TAGS: ['script']
});
```

**Comment by DroidUnknown** [comment]
> This code should fix the issue for you:
> 
> ```js
> var sane = DOMPurify.sanitize('<script><\/script>', {
>     FORCE_BODY: true, 
>     ADD_TAGS: ['script']
> });
> ```

+1

**Comment by Krishna-najpk** [comment]
Hi,

If we allow <script> tag then will it sanitize script tag or It will accept any script tag. So what I am looking for is, I want to allow valid non-fishing content in script tag but not malicious ones. If I follow above answer, then will that be achieved?
