### ISSUE TITLE
Add beforeSanitize/afterSanitize hooks

### ISSUE THREAD

**Issue by jorditpuig** [cure53/DOMPurify#399]
This issue proposes adding two new hooks,`beforeSanitize` and `afterSanitize`, that are called before and after each node is sanitized in the main loop of `DOMPurify.sanitize`. Existing hooks wrap only _partially_ some internal logic of `DOMPurify.sanitize`. For instance, when sanitizing a tag that is not in `ALLOWED_TAGS`  (e.g. `<iframe>`) the element will be removed without calling the hook `afterSanitizeElements`.

The motivation for this feature is monitoring the elements/attributes removed from `DOMPurify.sanitize`. As mentioned in issue #84 it would be great to have a way to identify the elements and attributes that are removed by DOMPurify. For instance, one could use headless browsing tools (e.g. puppeteer) to identify any pages that might break due to DOMPurify removing elements/attributes. Unfortunately, there is no existing hook in DOMPurify that wraps the function `DOMPurify.sanitize`. In issue #84 @cure53 mentions hooks `beforeSanitize` and `afterSanitize`. Unfortunately, unless I am missing something, these two hooks do not exist.

As a sidenote, someone might claim that what is really "broken" is the current implementation of `afterSanitizeElements` that is only executed when `_sanitizeElements` returns false. The problem, however, with any approach that "fixes" `afterSanitizeElements` is that it will modify the current semantics of `afterSanitizeElements` and potentially break existing tools of DOMPurify.

**Comment by cure53** [comment]
Heya, that is generally a good idea - however the requested feature we have already: 
Check out `DOMPurify.removed` please - or are you looking for something different?

**Comment by jorditpuig** [comment]
Thanks for the prompt reply @cure53 !

I am using precisely `DOMPurify.removed` to get any elements/attributes removed but since the hook `afterSanitizeElements` is not always executed one has to use a wrapper of the library in order to monitor DOMPurify.removed. If you think that such a hook or fixing `afterSanitizeElements` is beyond the scope of the library hooks feel free to close the issue.

**Comment by cure53** [comment]
Let's put it like that, we would be open for a PR :)
