### ISSUE TITLE
Created an isomorphic wrapper for DOMPurify

### ISSUE THREAD

**Issue by kkomelin** [cure53/DOMPurify#400]
Hey guys,

The issue is not typical, so excuse me for not following the issue template.

I don't have proper words to thank you for your work on the library. It's probably one of the most important projects in the JS ecosystem, even if some people don't know about it yet.

While working with DOMPurify in Next.js (with and without SSR), I noticed that it needs some additional initialization logic for server-side code (sort of a fake DOM tree). To simplify the initialization and make it universal on both frontend and backend, I've created an isomorphic wrapper https://github.com/kkomelin/isomorphic-dompurify

I would appreciate your feedback on the project and it would be an honor for me if it could give ideas on how to make DOMPurify itself even better.

Thanks,
Konstantin

**Comment by cure53** [comment]
Haha, this is cool, thanks fr pointing this out :D

**Comment by kkomelin** [comment]
@cure53 You're welcome.

**Comment by karlhorky** [comment]
For usage of DOMPurify in Next.js Server Components without the wrapper package [`isomorphic-dompurify`](https://www.npmjs.com/package/isomorphic-dompurify), here is a demo of a simple version:

- https://github.com/vercel/next.js/issues/46893#issuecomment-1458595411

Mainly the code is this:

```tsx
import DOMPurify from "dompurify";
import { JSDOM } from "jsdom";

export default function Home() {
  return (
    <div
      dangerouslySetInnerHTML={{
        __html: DOMPurify(new JSDOM("<!DOCTYPE html>").window).sanitize(
          "<img src=x onerror=alert(1)//>"
        ),
      }}
    />
  );
}
```

**Comment by kkomelin** [comment]
@karlhorky Thanks. If the webpack configuration is adjusted for better bundling of jsdom/canvas as you suggested, will `isomorphic-dompurify` suit you? Because it does pretty much the same things which you illustrated in your code example.

**Comment by karlhorky** [comment]
> If the webpack configuration is adjusted for better bundling of jsdom/canvas as you suggested, will `isomorphic-dompurify` suit you?

No, I personally think the package should be deprecated with a notice on how to achieve the same thing using the main [`dompurify`](https://www.npmjs.com/package/dompurify) library (3.5m weekly downloads vs 300k for `isomorphic-dompurify`).

I think this because:

1. What happens if you're unavailable in the future to maintain the library?
2. What happens if your supply chain security is not as strong as the `dompurify` library?
3. Other security concerns about the wrapper package...

If the wrapper can be done with a few lines of code in a project, I think the wrapper package should not exist (or maybe it should be absorbed into `dompurify` itself, so that it can be maintained and enjoy the security benefits of the more popular package / ecosystem.

**Comment by kkomelin** [comment]
@karlhorky Thank you for your opinion. I can't agree with it but I respect it.

1) People use packages because they make their work simpler. It doesn't really matter how much code is inside. There are some tiny packages in JS ecosystem which are popular enough.

2) As for your security concerns, such as what happens if I'm unavailable, I can also address this question to any opensource project maintainer. if anything happens tomorrow with any of us, the community will pick the project up and create a fork.
As for myself, I normally apply dompurify updates the same week they are released.
As for other hypothetical security concerns which are not based on anything, let's leave them unaddressed.

3) @cure53 and I already thought about merging the `isomorphic-dompurify` code into `dompurify` and decided not to proceed with it. But please let us know if you'd like to help with it.

**Comment by karlhorky** [comment]
> 1\. People use packages because they make people's work simpler. It doesn't really matter how much code is inside. There are some tiny packages in JS ecosystem which are popular enough.
> 2\. As for your security concerns, such as what happens if I'm unavailable, I can also address this question to any opensource project maintainer. if anything happens tomorrow with any of us, the community will pick the project up and create a fork.

Indeed, small packages + unavailable maintainers are not normally a problem - the community heals - but `dompurify` is a library that deals with security, so all security concerns are heightened with this.

**Comment by kkomelin** [comment]
@karlhorky ,
> Indeed, small packages + unavailable maintainers are not normally a problem - the community heals - but dompurify is a library that deals with security, so all security concerns are heightened with this.

Makes sense. If you help `dompurify` to work server-side, I will deprecate the `isomorphic-dompurify` project. No problem at all.
