### ISSUE TITLE
DOMPurify doesn't work in Production - React

### ISSUE THREAD

**Issue by BenRauzi** [cure53/DOMPurify#402]
### Background & Context

Attempting to use DOMPurify.sanitize in react: 
```JS
import React from "react"
import DOMPurify from "dompurify";

const Sanitizer = content => {
  return <div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(content.data) }} />;
}
export default Sanitizer
``` 

Works great in Development, have tested it by throwing some unsafe code into our CMS. It's working great, however we CANNOT run a production build - when we do we get the following error:

```JS
WebpackError: TypeError: dompurify__WEBPACK_IMPORTED_MODULE_1__.default.sanitize is not a function
```

**Comment by cure53** [comment]
Ooof, do you have some more info for us about this error? We know that DOMPurify works in React - so not sure if the error is on our end.

**Comment by BenRauzi** [comment]
Basically I don't. I've installed DOMPurify (In fact it was already installed into the repository - but did make sure to reinstall) and it's working and sanitizing content in Development - but then we tried to do a production build and got this error. Moved it to its own component to try and isolate it.

If I had any other key information it would be that we are using Gatsby.js. Otherwise I'm not sure.

Would you have any information you need to know?

**Comment by BenRauzi** [comment]
And is this the correct implementation in React?

**Comment by tdeekens** [comment]
Which entry file is webpack consuming in development and prod? DOMPurify has only three entries: browser, main and module. In a usual webpack setup - disregarding React as I am not sure it matters here - the entry in dev and prod would not change while in prod mode assets would obviously rightfully be processed e.g. for minification. 

Usually one gets this error whenever an export is wrong. E.g our default export is not a function but a string.

**Comment by BenRauzi** [comment]
Being new to React I am not entirely familiar with that concept. Will have a read up I guess.

**Comment by cure53** [comment]
:+1: Closing this for now, please reopen once we have more info

**Comment by tdeekens** [comment]
This is a code sandbox prooving that it works. https://codesandbox.io/s/blissful-cloud-3qc5n

I don't know the use case you're having but generally you never need to dangerously set the inner html. Just a side note :)

**Comment by cure53** [comment]
Thanks!

**Comment by BenRauzi** [comment]
@tdeekens That's why I'm confused haha. Exact same implementation works in dev but not production.

**Comment by BenRauzi** [comment]
Take a look here: https://github.com/BenRauzi/openlawnz-web/blob/230-Plugins-CMS/src/components/Sanitizer.js

**Comment by tdeekens** [comment]
True. Hm. How do you trigger prod mode in the sandbox?

**Comment by BenRauzi** [comment]
You can deploy to Netlify, or you need to fork it. I tried but it won't let me fork and gives an error message

**Comment by BenRauzi** [comment]
I wonder whether it could be an issue with Gatsby. hm.

**Comment by BenRauzi** [comment]
So when I console.log(DOMPurify) in production I get:
```
(t){return e(t)}

**Comment by BenRauzi** [comment]
Bit of an update. If I: ```JS
Console.log(DOMPurify.sanitize)
``` It builds fine and I can even see the function from console / code. However the project just won't build if I actually call the function. Quite odd.

**Comment by BenRauzi** [comment]
Yep it appears to just be an issue with Gatsby.js build process. Guess there's not much I can do then.

**Comment by NicholasEllul** [comment]
Having the same issue when using webpacker + node.js

**Comment by BenRauzi** [comment]
@NicholasEllul The issue we found with it was that it was an issue with Gatsby itself and the way it builds static pages, and doesn't initialise DOMPurify properly.

If you have an issue with Node.js I'd start a new issue. I just built sanitization into our CMS.
