### ISSUE TITLE
Custom directives sanitization

### ISSUE THREAD

**Issue by vakhariasohil** [cure53/DOMPurify#408]
> This issue proposes a [bug, feature] which...

### Background & Context
If i have created custom directive, by default it's not getting sanitized( returns blank ). So is there any configuration to keep the newly create directives/components to be white listed in the sanitization. 
I know we can add it inside the filter `ALLOWED_TAGS` , but I don't want to add 100 components in the 'ALLOWED_TAGS' attribute, instead I want every new element to get sanitized.
#### Input
```
rawHTML = <cfw-tools name="LHNTools"></cfw-tools>;
sanitizedHTML = DOMPurify.sanitize( rawHTML, {
      FORBID_TAGS: ['style', 'a', 'script']
} );
console.log( sanitizedHTML );
```

#### Given output
This returns me ('') empty string.

#### Expected output

The expected output.

### Feature

Briefly outline the proposed feature, its value and a potentially proposed implementation from a high level.

**Comment by cure53** [comment]
Heya, so, basically the idea is to allow all elements via config option and only black-list a few?

**Comment by jmanico** [comment]
Don’t sent a blacklist to do a whitelists job? Struggling for a clever comment here but this sounds bad.

--
Jim Manico
@Manicode

**Comment by cure53** [comment]
I am also not a big fan of adding this as a core feature either. I do however believe that this can be solved using the means we already offer: namely, with a hook.

Hook into the element sanitizer, check the element's tag name, add it to the whitelist unless it is on the blacklist, move on to next element. Not super-elegant but similarly elegant to us doing it in the library core.

Wdyt?

**Comment by vakhariasohil** [comment]
**basically the idea is to allow all elements via config option and only black-list a few?**

Answer: yes, want to allow 250+ components and blacklist 10 or 20

**Comment by cure53** [comment]
Then I guess using the `uponSanitizeElement` is the way to go for you!

**Comment by vakhariasohil** [comment]
Do you have any sample example on how to add the hook. Please share the link

**Comment by cure53** [comment]
Check out the demo folder, there is a lot of examples for hooks, including this one:

https://github.com/cure53/DOMPurify/blob/master/demos/hooks-node-removal2-demo.html
