### ISSUE TITLE
In Chrome 80, DOMPurify.sanitize modifies the content security policy of the page

### ISSUE THREAD

**Issue by ConradIrwin** [cure53/DOMPurify#409]
### Background & Context

This is a consequence of this chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1063556

#### Input

If you pass a string containing a meta tag which contains a meta tag with a Content-Security-Policy to DOMPurify it will modify the current page's content security policy.

e.g. running:
```
DOMPurify.sanitize(`<meta http-equiv="Content-Security-Policy" content="default-src 'none'">`)
```
Will prevent any further network requests from running on the current page.

<img width="1118" alt="Screen Shot 2020-03-31 at 14 06 58" src="https://user-images.githubusercontent.com/94272/78181363-15627580-7419-11ea-949d-c32fd87f89d8.png">

#### Suggested workaround

We can either wait for Chrome to fix this, it is a release blocker for them; or we may want to consider using `DOMParser` instead of `document.implementation.createHTMLDocument`; as that API does not seem to have the same bug.

At Superhuman we have a temporary workaround that runs a find/replace to remove such meta tags before passing the content to DOMPurify.

**Comment by cure53** [comment]
Heya, thanks for filing this, we are currently looking into defaulting into `DOMParser` instead of `createHTMLDocument`.

**Comment by cure53** [comment]
Okay, this should be fine now, can you double-check please?

**Comment by ConradIrwin** [comment]
Works for me! Thanks for the fast turnaround :).
