### ISSUE TITLE
Plugin API / Hooks for custom filters and sanitation

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#41]
Several users have recently requested specific filtering and sanitation features that would require core changes or rethinking of the configuration API. This includes custom nesting rules, different href/src filtering and many other things.

I believe it would be best to create a hooking / plugin architecture instead of adding additional complexity to the core API. Now, the question is: how to best build that? How to do it so it makes sense, works well with the existing config flags and still provides enough flexibility for developers to add their own functionality? 

My initial thought was: *Hooks*. We can implement hooks where the developer receives all DOMPurify config flags, the string and its current representation object, can work on all of them and pass them back after being done. We can put hooks into several places:

 * Before any filtering has been done
 * Right after the document has been created
 * Right after the clobbering checks happened
 * Right after the tag filtering has completed
 * Right after the attribute filtering has completed
 * Right before the serialization happens

This should allow us to do things like:

 * Specific handling of charset directives
 * Filtering to prevent deep nesting
 * Handling of CSS
 * Handling of HTTP leaks such as src, href, formaction etc.
 * Handling of special unwanted characters

Does that general strategy make sense or am I living in the 90s with that idea? :) Very much open for any form of input, please let me know. 

Spammy CC of all who requested specific features or a in core development - sorry for that but your input is needed :) @fhemberger @devd @arbixy @eoftedal @joelabair

**Comment by mozfreddyb** [comment]
If I were to write a customization on top of DOMPurify, I'd like to register call backs (the JS name for hooks :P) for events before and after the filtering of each (attribute, tag, entity).

This kinda matches what your proposal says, if I understand you correctly.

**Comment by arbixy** [comment]
It would be good that the current sanitize configuration is provided as parameter, closure or some getter to these event callbacks so that the user could modify it during the process in order to achieve better results before the next hooked stage or any api helping tools what so ever.

**Comment by cure53** [comment]
@mozfreddyb True, that's what I meant.

@arbixy Yes, that would allow you to flatten, re-configure per node, enforce tag-attribute white-lists etc.

**Comment by arbixy** [comment]
Perhaps some query tools would be great addition, too.

**Comment by cure53** [comment]
@arbixy What do you mean by query tools?

@all Now, let's do a quick dry run as to how it could look like. Let's assume we want to install a hook/callback in `_initDocument()`:

**Without**
```javascript 
            /* Exit directly if we have nothing to do */
            if (typeof dirty === 'string' && dirty.indexOf('<') === -1) { 
                return dirty; 
            }
            
            /* Create documents to map markup to */
            var dom = document.implementation.createHTMLDocument('');
                dom.body.parentNode.removeChild(dom.body.parentNode.firstElementChild);
                dom.body.outerHTML = dirty;
                
            /* Cover IE9's buggy outerHTML behavior */
            if(dom.body === null) {
                dom = document.implementation.createHTMLDocument('');
                dom.body.innerHTML = dirty;
                if(dom.body.firstChild && dom.body.firstChild.nodeName
                    && !WHOLE_DOCUMENT
                    && dom.body.firstChild.nodeName === 'STYLE'){
                    dom.body.removeChild(dom.body.firstChild);
                }
            }
```

**With Callback**
```javascript
            /* Exit directly if we have nothing to do */
            if (typeof dirty === 'string' && dirty.indexOf('<') === -1) { 
                return dirty; 
            }
            
            /* Create documents to map markup to */
            var dom = document.implementation.createHTMLDocument('');
                dom.body.parentNode.removeChild(dom.body.parentNode.firstElementChild);
                dom.body.outerHTML = dirty;

            /* NEWNEWNEW Basic Callback NEWNEWNEW */
            if(cfg.CALLBACKS['beforeFillDocument']){
                [dirty, dom, cfg] = cfg.CALLBACKS['beforeFillDocument'](dirty, dom, cfg)
            }  
                
            /* Cover IE9's buggy outerHTML behavior */
            if(dom.body === null) {
                dom = document.implementation.createHTMLDocument('');
                dom.body.innerHTML = dirty;
                if(dom.body.firstChild && dom.body.firstChild.nodeName
                    && !WHOLE_DOCUMENT
                    && dom.body.firstChild.nodeName === 'STYLE'){
                    dom.body.removeChild(dom.body.firstChild);
                }
            }
```
Of course we should have a dedicated callback loader that verifies if it's a function, has proper length (number of arguments) and what not. And for compatibility sake maybe no destructuring assignment etc. But the basic mechanism looks okay? Function objects stored in the config array and a direct call inside the DOMPurify methods?

**Comment by fhemberger** [comment]
Just a rough idea how do handle/execute those hooks:

```js
var DOMPurify = (function() {
	/* browser:true, devel:true */
	'use strict';

	var DOMPurify = {};
	var hooks = {};


	DOMPurify.sanitize = function(dirty, cfg) {

		var _sanitizeElements = function(currentNode) {
			currentNode = _executeHook('beforeSantitizeElements', currentNode);

			// do the magic
			console.log('_sanitizeElements', currentNode);

			currentNode = _executeHook('afterSantitizeElements', currentNode);
		};


		var _executeHook = function(entryPoint, currentNode) {
			var modifiedNode;

			console.log('_executeHook:%s', entryPoint);
			hooks[entryPoint].forEach(function(hook) {
				modifiedNode = hook.call(DOMPurify, currentNode, cfg);

				if (!modifiedNode) { return console.error('Hook for "' + entryPoint + '" didn\'t returned a node. Skipping.'); }
				currentNode = modifiedNode;
			});

			return currentNode;
		};

		// Dummy execution
		_sanitizeElements( document.getElementsByTagName('body')[0] );
	};


	DOMPurify.addHook = function(entryPoint, hookFunction) {

		hooks[entryPoint] = hooks[entryPoint] || [];
		hooks[entryPoint].push(hookFunction);
	};

	return DOMPurify;
})();


// --- Test code ---
DOMPurify.addHook('beforeSantitizeElements', function(currentNode, config) {
	console.log('before:function 1');
	return currentNode;
});

DOMPurify.addHook('beforeSantitizeElements', function(currentNode, config) {
	console.log('before:function 2');
});

DOMPurify.addHook('afterSantitizeElements', function(currentNode, config) {
	console.log('after:function 1');
	return currentNode;
});

DOMPurify.sanitize();
```

Additionally, you could add a validation step in `addHook` to check if the argument passed is in an array of valid entry points and throw an error if not. We should also try to have a consistent signature for the hook function if possible (some hooks might execute on the raw string, some on the current node).

**Comment by cure53** [comment]
Makes perfect sense, yes! Shall I add a branch for that? I think the earlier we have something to hack on the better. And the general idea seems to be robust enough to start playing.

**Comment by fhemberger** [comment]
Sure, go ahead. ;)

**Comment by cure53** [comment]
Created the [HOOK_API](/cure53/DOMPurify/tree/HOOK_API) branch.

**Comment by fhemberger** [comment]
I just added my basic hook handling to it.

**Comment by cure53** [comment]
See [fbe0fa46c6cd042e3807de2661410e6d517036b0](https://github.com/cure53/DOMPurify/commit/fbe0fa46c6cd042e3807de2661410e6d517036b0)

Nice, thanks! I did some changes and added a bunch of demo cases to see how it could work. I also decided to rename the demo folder as the name was misleading.

Feedback very welcome. There's also a first hook - doing nothing but capitalizing text node content for demo purposes.

**Comment by cure53** [comment]
I am mostly done with the rest of the hook implementation. I also added support for two new config flags and I think we are pretty much ready for a new release. What do you think? 

[1246610ec2431b8febc80f0096140acbef27eefd](https://github.com/cure53/DOMPurify/commit/1246610ec2431b8febc80f0096140acbef27eefd)

**Comment by fhemberger** [comment]
Cool, LGTM! :+1:
