### ISSUE TITLE
How to whitelist custom attributes

### ISSUE THREAD

**Issue by vakhariasohil** [cure53/DOMPurify#410]
> This issue proposes a [bug, feature] which...

### Background & Context
I am trying to whitelist the custom tags and custom attributes based on your previous resolution on issue [#408 ](https://github.com/cure53/DOMPurify/issues/408), but here i could see the issue for sanitizing custom attributes. The custom attributes are getting dropped in sanitization part

#### Input
```
rawHTML = '<cfw-include ng-repeat="list in lists" context="ctx" name="ERROR"></cfw-include>',
sanitizedHTML = DOMPurify.sanitize( rawHTML, {
     FORBID_TAGS: BLACKLIST_TAGS,
     ALLOWED_URI_REGEXP: REGEX_URL_PATTERN,
     ADD_TAGS: [ 'cfw-include' ],
     ADD_ATTR: [ 'ng-repeat', 'context']
 } );
console.log( sanitizedHTML );
```
output:
```
rawHTML = '<cfw-include name="ERROR"></cfw-include>',
```
Here the output should not drop the attributes `ng-repeat` and `context`.
I also tried to add the hook `uponSanitizeAttributes` but no success.

#### Given output
```
rawHTML = '<cfw-include name="ERROR"></cfw-include>',
```

#### Expected output
```
<cfw-include ng-repeat="list in lists" context="ctx" name="ERROR"></cfw-include>'
```
Here the output should not drop the attributes `ng-repeat` and `context`!!
### Feature

Briefly outline the proposed feature, its value and a potentially proposed implementation from a high level.

**Comment by cure53** [comment]
Heya, thanks for filing this, we're having a look right now.

**Comment by cure53** [comment]
Ah, found it. The problem is the following part:

`ALLOWED_URI_REGEXP: REGEX_URL_PATTERN`

The attribute gets killed if the content doesn't match the regex. Would you mind sharing the regex so we can have a look?

**Comment by vakhariasohil** [comment]
I am not passing any regex with this input. I have added the regex filter to ensure if any URL input is passed then it would get filtered.

To write this function generic, I am trying to add all the filters which covers our code base.

I still could not understand why the attributes are getting filtered with URI regex and tags are not getting filtered.

Ideally the URL regex filter should become active only when the any URL is passed thru sanitization and should not block attribute

Btw it's not blocking `name` attribute but blocking custom attributes.. isn't it strange!!

**Comment by vakhariasohil** [comment]
> I am not passing any URL with this input. I have added the regex filter to ensure if any URL input is passed then it would get filtered.
> 
> To write this function generic, I am trying to add all the filters which covers our code base.
> 
> I still could not understand why the attributes are getting filtered with URI regex and tags are not getting filtered.
> 
> Ideally the URL regex filter should become active only when the any URL is passed thru sanitization and should not block attribute
> 
> Btw it's not blocking `name` attribute but blocking custom attributes.. isn't it strange!!

**Comment by cure53** [comment]
Like I said, the regex is the problem. Things work exactly as expected.
