### ISSUE TITLE
Text after a tag is stripped along with the tag in the latest versions

### ISSUE THREAD

**Issue by pragatheeswaranshf** [cure53/DOMPurify#412]
### Background & Context
Hey, I just upgraded the DOMPurify library for my application and I found the following change was breaking my test case. I just bumped to V2.0.8 but it looks like the behaviour is changed in V2.0.7

### Bug
Normal text after an HTML tag is also removed along with the tag.

#### Input
`<p>abc<iframe/\/src=jAva&Tab;script:alert(3)>def`

#### Given output
`<p>abc</p>`

#### Expected output

`<p>abcdef</p>`

Up until the version V2.0.6, the expected output was the given output. From V2.0.7 the output changed. Is it a bug or a valid change from the library. If so, can i get the old behaviour based on a config? 

Here is a [jsbin link](https://jsbin.com/nemikodofe/edit?html,output) with the version V2.0.6 which gives the expected output.

**Comment by cure53** [comment]
Heya, this is expected behavior and needed to fix an mXSS bug in Chrome and Firefox.
