### ISSUE TITLE
Possibly broken link in the Security Goals & Threat Model's wiki page

### ISSUE THREAD

**Issue by Malvoz** [cure53/DOMPurify#413]
The wiki page links to https://appseceurope2017.sched.com/event/A65s/dont-trust-the-dom-bypassing-xss-mitigations-via-script-gadgets, IDK if it's just me, but authentication doesn't work and the resource is inaccessible to me.

Potential replacement URLs (I googled the end of the URL: `dont-trust-the-dom-bypassing-xss-mitigations-via-script-gadgets` to find these):

- https://www.youtube.com/watch?v=p07acPBi-qw
- https://github.com/google/security-research-pocs/blob/master/script-gadgets/Breaking_XSS_mitigations_via_Script_Gadgets_BHUSA.pdf
- https://www.blackhat.com/docs/us-17/thursday/us-17-Lekies-Dont-Trust-The-DOM-Bypassing-XSS-Mitigations-Via-Script-Gadgets.pdf

(And FWIW I updated a few URLs to use `https://` for all the sites with a TLS cert in [`8b24f37`](https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model/_compare/8b24f3778bae423bb1aec61bcf1456b4c1056050).)

**Comment by cure53** [comment]
Nice find - thanks. It's fixed now :)
