### ISSUE TITLE
Unable to bypass tr td tags

### ISSUE THREAD

**Issue by kerkchern** [cure53/DOMPurify#415]
I'm trying to sanitize my html but keeps the tr td tags

#### Input
var config = {
        ALLOWED_TAGS: ['tr','td'],
        KEEP_CONTENT: true
    };
    var clean = DOMPurify.sanitize("<tr><td></td></tr>",config);

#### Given output
I got an empty output

#### Expected output
<tr><td></td></tr>

**Comment by cure53** [comment]
Heya, this is expected behavior as TD and TR cannot exist without a TABLE element surrounding them. It is in fact not us removing the tags - but the browser.
