### ISSUE TITLE
Add import example?

### ISSUE THREAD

**Issue by gergelyszabo94** [cure53/DOMPurify#416]
Hi, this is not a bug report nor a feature request, just a simple proposal to improve the docs. 
I could not find any examples using import so I was googling around and found this: https://stackoverflow.com/questions/52741262/how-to-install-import-and-use-dompurify-in-frontend-js-file
It seems to work for me, just wondering if there is a reason that this type of usage is not mentioned in the docs?

**Comment by Slapbox** [comment]
`import` worked for me, but I also avoided it in case I was making some assumption that it was safe that later had me pulling my hair out. I think it should be safe though?

**Comment by gergelyszabo94** [comment]
A word of endorsement from the maintainers or someone knowledgeable would be a relief before I spend my weekend on adding this library all over my project. I have seen that people get replies to issues here so I am hopeful and big props for that!

**Comment by cure53** [comment]
I see no reason why this should not be safe. @tdeekens wdyt?

**Comment by tdeekens** [comment]
I don’t see a reason why it should not be considered safe. Generally the docs and module styles are quite outdated (containing requirejs if I recall).

**Comment by tdeekens** [comment]
We also habe an ESM bundle in our dist and a module entry in the pkg.json guiding the bundlers.

**Comment by cure53** [comment]
Generally speaking, I would never touch this area of the docs as I have no idea how those things work. So, PRs are welcome if there is better, easier or safer ways for environment XYZ :)

**Comment by tdeekens** [comment]
I think we should remove require.js. Maybe even the support. I actually don't know how many projects use it. We might get away with supporting commonjs and esm. 

We could also try to get the CI from TravisCI to GitHub Actions while updating our bundling again a bit. Still, need the time and probably more rights on the repo 🗡️.

**Comment by cure53** [comment]
> and probably more rights on the repo

Happy to grant that, let me know what you need please :)

**Comment by tdeekens** [comment]
I think I would have to enable actions and add secrets. That is repo admin if I am not mistaken. I understand that that is quite hefty. I see three ways: 

1. I fork and play there and merge and let you know what secrets etc we need
2. You trust me enough and make me an admin
3. I am an admin temporarily (maybe paired with 1.)

Anything works for me. 🤘🏼

**Comment by cure53** [comment]
I am fine with tmp-admin :)

**Comment by tdeekens** [comment]
I will not abuse any power. I will see that I get to it soon (2-3 weeks maybe). If that is okay.

**Comment by cure53** [comment]
:bow: thx!

**Comment by tdeekens** [comment]
The readme now contains an import example. I consider this done as a result. Feel free to re-open the issue or create a PR in case you see something missing. Thanks 🙇.

**Comment by gergelyszabo94** [comment]
Thanks guys. This has been the best ever experience I have had with open source!

**Comment by cure53** [comment]
One thing that comes to mind @tdeekens 

https://github.com/cure53/DOMPurify/pull/396
https://github.com/cure53/DOMPurify/pull/407

We had a request of adding license headers to minified versions. Since we changed the minifier, is this till happening?

**Comment by tdeekens** [comment]
Good point. It claims to be the same. I think it's to add a marker to the comment like `@license`?

<img width="651" alt="CleanShot 2020-04-20 at 15 11 02@2x" src="https://user-images.githubusercontent.com/1877073/79755281-2a943b00-8319-11ea-8477-6abc811c5b89.png">

**Comment by cure53** [comment]
I am just confused because I don't see the comments any longer, hence asking.

**Comment by cure53** [comment]
Also getting some weird Safari errors in the tests.

```
 Safari 8.0.8 (Mac OS X 10.10.5): Executed 0 of 0 ERROR (26.431 secs / 0 secs)
Safari 8.0.8 (Mac OS X 10.10.5) ERROR
  ReferenceError: Can't find variable: QUnit
  at node_modules/qunit-parameterize/qunit-parameterize.js:7:6
Safari 8.0.8 (Mac OS X 10.10.5): Executed 0 of 0 ERROR (26.433 secs / 0 secs)
Safari 8.0.8 (Mac OS X 10.10.5) ERROR
  ReferenceError: Can't find variable: QUnit
  at test/config/setup.js:5:6
Safari 8.0.8 (Mac OS X 10.10.5): Executed 0 of 0 ERROR (26.433 secs / 0 secs)
Safari 8.0.8 (Mac OS X 10.10.5) ERROR
  ReferenceError: Can't find variable: QUnit
  at test/purify.min.spec.js:1776:7
Safari 8.0.8 (Mac OS X 10.10.5): Executed 0 of 0 ERROR (26.434 secs / 0 secs)
Safari 8.0.8 (Mac OS X 10.10.5) ERROR
  ReferenceError: Can't find variable: QUnit
  at test/purify.spec.js:1776:7
```

Let me try to rerun..
