### ISSUE TITLE
[RFC] Automated release process

### ISSUE THREAD

**Issue by tdeekens** [cure53/DOMPurify#425]
> This issue proposes an automated release process.

### Background & Context

The library is currently being released manually from the machines of the maintainers. This seems fine but I would like to propose an alternative way of going about this.

### Automated releasing

1. We would use semantic commits (feat, bug, docs) etc
   - This would allow us to generate a change log automatically and we could experiment with a change log bot for the GitHub release
2. We would release a new canary version `dompurify@x.x.x.canary.0` to the `next` dist channel on npm on each merge to master
3. We could allow releasing via an GitHub issue on which we comment /release to publish a version to the latest dist tag
   - Using the commit history we could automatically deduct the next version

This is merely a suggestion. I just wanted that we at least had the discussion also if the outcome is: that's too much for our tiny library :)

**Comment by cure53** [comment]
This does make sense, however, so far the releases often involve a lot of extra actions which depend on the kind of release, normal release, bug-fix or even security release.

Not super sure if we can forge that into an automated process easily.

**Comment by tdeekens** [comment]
Can you list waht those extra actions are?

**Comment by cure53** [comment]
It boils down to:

Feature release: Just a tweet
Bugfix Release: Just a tweet
Security Release: Special Tweet, Signed Mail to Mailinglist, Signed Mail to NPM

**Comment by cure53** [comment]
Btw, first release with new builds system, fingers crossed :D

**Comment by cure53** [comment]
Also, I think the license file did not make it somehow. I am not super certain why, maybe it didn't work in the first place?

https://github.com/cure53/DOMPurify/blob/master/dist/purify.min.js

**Comment by tdeekens** [comment]
Oh kay. Will try to look into it.

**Comment by cure53** [comment]
Thank you! Let me know if I can help somehow. relevant PRs were:

https://github.com/cure53/DOMPurify/pull/394
https://github.com/cure53/DOMPurify/pull/407
https://github.com/cure53/DOMPurify/pull/424

**Comment by cure53** [comment]
Heya :) Should we do another release now?

**Comment by tdeekens** [comment]
For the license. Yeap. Sounds good. automating this will take some effort anyway. I just wanted collect information. Maybe I have a long train ride some time (buuuhar) again.

**Comment by cure53** [comment]
Nono, for the build-crusher described in https://github.com/cure53/DOMPurify/issues/427 :D The license doesn't have prio.

I sense a certain degree of urgency, hence asking.

**Comment by tdeekens** [comment]
> I sense a certain degree of urgency, hence asking.

Yeah we could publish for that I suppose.

**Comment by cure53** [comment]
People claim it [doesn't fix the issue](https://github.com/cure53/DOMPurify/issues/427#issuecomment-618350923) and I am slowly getting nervous.

**Comment by cure53** [comment]
Closing this for now :)
