### ISSUE TITLE
2.0.9 overrides adds a node binary to the PATH in npx calls

### ISSUE THREAD

**Issue by dustym** [cure53/DOMPurify#427]
The 2.0.9 point release installs a `node` binary in the `node_modules/.bin`. In the event that your project adds `node_modules/.bin` to the current PATH, that `node` will take precedence over the system node. In my case I use `npx` which does this PATH management automatically.

This is due to the [commit](https://github.com/cure53/DOMPurify/commit/b26420eef1b10cb8116ca1b774da41896a930d34) that adds the `node` npm package as a dependency. Is it an absolute requirement or can it be installed as a dev dependency?

Example of this unexpected behavior:

```
~/dev/testpackage
❯ npm install dompurify@2.0.7
+ dompurify@2.0.7
added 1 package from 1 contributor and audited 1 package in 0.762s
found 0 vulnerabilities


~/dev/testpackage took 2s
❯ npx node -v
v10.18.0

~/dev/testpackage
❯ npm install dompurify@2.0.9

> node@13.13.0 preinstall /Users/dustym/dev/testpackage/node_modules/node
> node installArchSpecificPackage

+ node-darwin-x64@13.13.0
added 1 package in 5.234s
found 0 vulnerabilities

+ dompurify@2.0.9
added 3 packages from 2 contributors, updated 1 package and audited 4 packages in 7.376s
found 0 vulnerabilities


~/dev/testpackage took 8s
❯ npx node -v
v13.13.0
```

**Comment by tdeekens** [comment]
Thanks for reporting. Do you know which dependency installs node locally?

**Comment by adamdecaf** [comment]
I think this is causing https://github.com/Redocly/redoc/issues/1242 in the redoc project as well.

**Comment by milesrichardson** [comment]
As an additional datapoint, this is also causing install to fail when using yarn 2 ("berry") with nodeModules linker. The downstream dependency in my case is `swagger-ui-react`:

```
➤ YN0000: ┌ Link step
➤ YN0007: │ node@npm:13.13.0 must be built because it never did before or the last one failed
➤ YN0009: │ node@npm:13.13.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-2c48a784/build.log)
➤ YN0009: │ node@npm:13.13.0 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-2c48a784/build.log)
➤ YN0000: └ Completed in 12.34s
➤ YN0000: Failed with errors in 58.33s

root@e8ea159cdb2a:/src/js/cloud# yarn why node
└─ dompurify@npm:2.0.9
   └─ node@npm:13.13.0 (via npm:^13.13.0)

root@e8ea159cdb2a:/src/js/cloud# yarn why dompurify
├─ swagger-ui-react@npm:3.25.0
│  └─ dompurify@npm:2.0.9 (via npm:^2.0.7)
│
└─ swagger-ui-react@npm:3.25.0 [d119c]
   └─ dompurify@npm:2.0.9 (via npm:^2.0.7)

root@e8ea159cdb2a:/src/js/cloud# cat /tmp/xfs-2c48a784/build.log
# This file contains the result of Yarn building a package (node@npm:13.13.0)
# Script name: preinstall

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '/src/js/cloud/node_modules/node/bin/node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by cevou** [comment]
> Thanks for reporting. Do you know which dependency installs node locally?

This library adds the node dependency locally: https://github.com/cure53/DOMPurify/blob/master/package.json#L135

Why are node and nvm dependencies of this library?

**Comment by millette** [comment]
@cevou Looks like an attempt to fix yarn install <https://github.com/cure53/DOMPurify/commit/c9661e1a4c2e32b0ad87807b12eb33edc1361095#diff-b9cfc7f2cdf78a7f4b91a753d10865a2>

**Comment by cevou** [comment]
Well, that doesn't make sense. The `dependencies` section should only list dependencies that are required for the library during runtime.

**Comment by dannystyleart** [comment]
Hi there! This is still an issue and breaks our CI for all of our apps. Why is there node binary and a dummy nvm binary as project dependencies?

Since there's no freebsd node binary provided by the package our build server cannot skip this issue.

I use npm so I have no clue on what yarn issue that this dependency tried to fix but if you want to pin the minimum required version of nodejs environment you should use [engines directive](https://docs.npmjs.com/files/package.json#engines) of npm.

**Comment by cure53** [comment]
@tdeekens Is it time for a new release? Happy to trigger that.

**Comment by cure53** [comment]
Hey all, can anyone confirm that the changes in https://github.com/cure53/DOMPurify/pull/428 fix the issue? Happy to issue a new release right away then.

**Comment by dannystyleart** [comment]
@cure53 Could you explain why node and nvm (honestly idk what this is) are (dev)dependencies of this package?

**Comment by cure53** [comment]
cc @tdeekens 

Still waiting for info if this is fixed with the PR and if we can publish a new release.

**Comment by sinjar666** [comment]
I don't think #428 fixes this issue. Ideally node and nvm should not marked as either dependencies or devDependencies. Not sure why it has been done if this is not being used anywhere.

**Comment by cure53** [comment]
Then this is outside my hands and needs to be addressed by @tdeekens

**Comment by millette** [comment]
@cure53 but you added the nvm/node deps on March 3rd according to https://github.com/cure53/DOMPurify/commit/c9661e1a4c2e32b0ad87807b12eb33edc1361095#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by cure53** [comment]
Then why did the problem not show earlier? Like, right now I mostly look for info on how to fix this.

**Comment by sinjar666** [comment]
As a workaround for those consuming this library as a second level dependency please reference v2.0.7 by adding a dependency to your package json with a fixed version unless you are dependent on any of the new features in later releases.

**Comment by tdeekens** [comment]
I removed the deps in a PR.

**Comment by dannystyleart** [comment]
> As a workaround for those consuming this library as a second level dependency please reference v2.0.7 by adding a dependency to your package json with a fixed version unless you are dependent on any of the new features in later releases.

This is what we had to do trough 12 apps :rescue_worker_helmet:

**Comment by millette** [comment]
@cure53 because the previous release https://github.com/cure53/DOMPurify/releases/tag/2.0.8 (Feb. 3rd) didn't include those deps.

**Comment by cure53** [comment]
Ah. I see, strange. Anyhow, are we safe to roll out 2.0.10 now?

**Comment by sinjar666** [comment]
> I removed the deps in a PR.

Thanks hoping for a release soon

**Comment by cure53** [comment]
I take this as a yes :)

**Comment by cure53** [comment]
Alright, here we go - doers this address the issue properly?
https://github.com/cure53/DOMPurify/releases/tag/2.0.10

**Comment by sinjar666** [comment]
Yes it seems work with master

**Comment by sinjar666** [comment]
We should be okay for a release

**Comment by sinjar666** [comment]
How long does this take to show up on npm registry?

**Comment by cure53** [comment]
I guess it should be up and registered

**Comment by dustym** [comment]
Thanks for cutting the new release.

**Comment by cure53** [comment]
Most welcome and sorry for the hassle. I initially had no idea what the original problem was and am glad we figured it out :)

**Comment by milesrichardson** [comment]
Confirmed the problem is resolved on my end. Thank you for the quick turnaround :)

**Comment by sinjar666** [comment]
Thanks @cure53 for the release and @tdeekens for the fix.
I guess it's time to revert @dannystyleart

**Comment by dannystyleart** [comment]
@cure53 It looks like our pipeline is fixed. (at least now only pngquant-bin fails, just to make the day for our devs :angry: )

Thanks for quick response

**Comment by cure53** [comment]
Cool :)

> at least now only pngquant-bin fails

But that is not because of us, no? :sweat:
