### ISSUE TITLE
Additional leading non-breaking spaces $nbsp are being added

### ISSUE THREAD

**Issue by Nisanez** [cure53/DOMPurify#433]
This issue proposes a bug. 

### Background & Context

In case we have leading non-breaking spaces we get more spaces after sanitising. (almost twice the spaces)

#### Input

`"&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;helloWorld"`
#### Given output

`"&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;helloWorld"`

#### Expected output

`"&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;helloWorld"`

Thank you very much!

**Comment by cure53** [comment]
Heya, interesting, do you have a code snippet to show the behavior? 
We tried to reproduce but no success.

**Comment by Nisanez** [comment]
Thanks you for the fast response! 
Unfortunately, Github replaces the nonbreaking spaces with regular so it is hard to provide a string for that issue.

The ascii of text with nbsp: `194 160 32 194 160 32 194 160 32 194 160 32 194 160 32 194 160 104 101 108 108 111 87 111 114 108 100`

Convert the ascii above to text using https://www.duplichecker.com/text-to-ascii.php
Put it on https://cure53.de/purify and hopefully you will be able to see the additional spaces. You will also be able to see that if you add character at the beginning the result is different.

I am using a simple command `const sanitizedText = DOMPurify.sanitize(text).toString()`

**Comment by cure53** [comment]
Ah, we managed to repro, looking into this now!

**Comment by cure53** [comment]
Okay, this should be fixed on master, can you check please?

**Comment by Nisanez** [comment]
Amazing! 
Tested my project with master and it solved the problem.
Thank you very much!

**Comment by cure53** [comment]
yw :)
