### ISSUE TITLE
blob links get removed from src

### ISSUE THREAD

**Issue by onzag** [cure53/DOMPurify#434]
I use blobs whenever available in order to internally link files in my system.

The viewer can't tell what info comes from the server nor which one is local that hasn't yet been published and its default is to sanitize all, this means sometimes src is a blob link.

Using anything other than a blob link works just fine, only blobs get removed.

**Comment by onzag** [comment]
```ts
export const PROPERTY_VIEW_SANITIZE_CONFIG = {
  ADD_TAGS: ["iframe"],
  ADD_ATTR: ["frameborder", "allow", "allowfullscreen", "scrolling", "src"],
  DATA_URI_TAGS: ["img"],
};
```

**Comment by onzag** [comment]
Tried also manually adding them on a `afterSanitizeElements` hook but DOMPurify still removes what I have manually re-added, no matter what I do, blobs seem to get removed.

**Comment by onzag** [comment]
Fixed it by using this configuration 

```
export const PROPERTY_VIEW_SANITIZE_CONFIG = {
  ADD_TAGS: ["iframe"],
  ADD_ATTR: ["frameborder", "allow", "allowfullscreen", "scrolling", "src"],
  ALLOW_UNKNOWN_PROTOCOLS: true,
};
```
It seems that despite the `afterSanitizeElements` hook doesn't seem to execute after, but rather before.

**Comment by juliendorra** [comment]
Why not: 
```
{
ALLOWED_URI_REGEXP: /^(?:(?:ftp|http|https|mailto|tel|callto|sms|cid|xmpp|blob):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i
        };
```
which allows all the default URI protocols and add the blob protocol
