### ISSUE TITLE
Allow absolute image sources on Windows

### ISSUE THREAD

**Issue by fxha** [cure53/DOMPurify#436]
> This issue proposes a [bug, feature] which...

### Background & Context

DOMPurify accepts absolute UNIX styled url/paths as image source but no Windows paths.

#### Input

```
<img src="/home/felix/abc.png" alt="">
<img src="Pictures/abc.png" alt="">
<img src="Pictures\abc.png" alt="">
<img src="file:///C:/Users/Felix/Pictures/abc.png" alt="">
<img src="C:\Users\Felix\Pictures\abc.png" alt="">
<img src="C:/Users/Felix/Pictures/abc.png" alt="">
```

#### Given output

```
<img alt="" src="/home/felix/abc.png">
<img alt="" src="Pictures/abc.png">
<img alt="" src="Pictures\abc.png">
<img alt="">
<img alt="">
<img alt="">
```

#### Expected output

All valid image paths should be allowed. Why are absolute UNIX path allowed but Windows styled paths forbidden? As a workaround it's possible to write `<img src="/C:/Users/Felix/Pictures/abc.png" alt="">` and get `<img alt="" src="/C:/Users/Felix/Pictures/abc.png">`.

**Comment by cure53** [comment]
Heya, have you tried the following?

`DOMPurify.sanitize( rawHTML, { ALLOW_UNKNOWN_PROTOCOLS: true });`

I believe this should work for your case and still not introduce any unwanted XSS :)

**Comment by fxha** [comment]
Thanks for your replay and the suggested solution. I'm using `ALLOWED_URI_REGEXP` to allow `file` protocol as we already preprocess the URL but it's a little bit confusing because even local UAC paths (`\\?\C:\`) are allowed.

**Comment by cure53** [comment]
I agree, but I think the browser internally changes the UAC paths into relative HTTP URLs, no?

Such as that `<a href="\\a?\C\">CLICK` becomes `https://a/?\C\`.

**Comment by fxha** [comment]
> I agree, but I think the browser internally changes the UAC paths into absolute or relative HTTP URLs, no?

That's a little bit tricky :smile: Chromium seems to convert all paths into URLs but Firefox only accepts `file:///<path>` on Windows. In addition, `\\<ip>\<path>` was also a valid path in Firefox, as far as I can remember, and Unix styled paths are always valid without file protocol.

**Comment by infeng** [comment]
Why windows file paths forbidden，is it because of some kind of security problem?
