### ISSUE TITLE
Typescript bug on Node JS when using this lib with JSDOM

### ISSUE THREAD

**Issue by omarryhan** [cure53/DOMPurify#437]
I followed the following instructions from this issue and it works fine without type checking.

https://github.com/cure53/DOMPurify/issues/29#issuecomment-466626162_

However on this line:

```javascript
const domPurify = DOMPurify(window);
```

This error appears:

```
error TS2345: Argument of type 'DOMWindow' is not assignable to parameter of type 'Window'.
  Types of property 'self' are incompatible.
    Type 'DOMWindow' is not assignable to type 'Window & typeof globalThis'.
      Type 'DOMWindow' is not assignable to type 'Window'.
        Types of property 'self' are incompatible.
          Type 'DOMWindow' is not assignable to type 'Window & typeof globalThis'.
            Type 'DOMWindow' is missing the following properties from type 'typeof globalThis': RTCStatsReport, AnalyserNode, Animation, AnimationEffect, and 551 more.

8 const domPurify = DOMPurify(window);
                              ~~~~~~


Found 1 error.

error Command failed with exit code 2.
```

Can someone think of a fix or workaround around this type error?

Thanks.

**Comment by cure53** [comment]
Sadly, no idea - but maybe @tdeekens has any hints?

**Comment by tdeekens** [comment]
Hi, thanks for the issue.

We don't stricly maintain the type definitions. They're external to the library. 

What I can see is that `window` you pass is a `DOMWindow` and not a `Window` what the typings seem to expect. 

Do you know why it's a `DOMWindow` what you're passing. Otherwise you can `window as Window` or inspect the typings upstream.

**Comment by omarryhan** [comment]
@tdeekens Not sure if I understand you correctly, but I'm running on Node.js (no browser Window object).

Definetely-typed will be too slow to respond unfortunately. I'm only using this lib to access the `sanitize` method.

Can you recommend another lib that would work on Node.js and Typescript?

**Comment by tdeekens** [comment]
This library should work in Node.js and with TypeScript. It's just that the typings are mistaken. Given you seem to want to move quickly I suggest to disable typechecking for that line which gives you the error or cast into the expected type.


![CleanShot 2020-05-21 at 12 24 22](https://user-images.githubusercontent.com/1877073/82549937-07e68380-9b5e-11ea-8cc1-b901b552950b.png)

**Comment by omarryhan** [comment]
If anybody happens to stumble upon this issue. This is what I ended up doing:

```
const window = new JSDOM('<!DOCTYPE html>').window as unknown as Window;
const domPurify = DOMPurify(window);
```

You can also:

```
const window = new JSDOM('<!DOCTYPE html>').window;
// eslint-disable-next-line @typescript-eslint/ban-ts-ignore
// @ts-ignore
const domPurify = DOMPurify(window);
```

**Comment by tdeekens** [comment]
Thanks for sharing the outcome. That's really cool!

**Comment by karlhorky** [comment]
Hmm... casting shouldn't be required here for users to use `dompurify` with `jsdom` with TypeScript.

The [`@types/dompurify` package](https://www.npmjs.com/package/@types/dompurify) (package [here in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/dompurify), maintained by @falsandtru, @peterblazejewicz and @Exigerr, among others) should be fixed to accept the type from `jsdom`.

**Comment by karlhorky** [comment]
Opened a PR for this, probably needs more work:

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64622

**Comment by peterblazejewicz** [comment]
Hey, I've added a comment with a proposal of generic fix using TS module augmentation, as a combat layer, so people could add this when using in server context with JSDOM (or whatever package that abstract DOM):
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64622#issuecomment-1460803478
thanks!

**Comment by karlhorky** [comment]
[`@types/dompurify`](https://www.npmjs.com/package/@types/dompurify) version `3.0.1` was released with support out of the box for jsdom 🙌  No more workarounds needed.
