### ISSUE TITLE
tel: is not sanitizing in DOMPurify || vulnerable for xss

### ISSUE THREAD

**Issue by V1dhun** [cure53/DOMPurify#440]
Found it while playing a xss challenge https://xss.pwnfunction.com/warmups/ok-boomer/. He is well explained about it.

#### Proof
![Screenshot from 2020-06-04 14-25-45](https://user-images.githubusercontent.com/29324367/83737320-70f6ec80-a670-11ea-8c29-33e14921d068.png)
##### source code
```html
<!DOCTYPE html>
<html lang="en">
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.0.11/purify.min.js" integrity="sha256-CttTBp3vqcw55O+XqmrPjeA17wiC1WxRnjIOeXwHu/s=" crossorigin="anonymous"></script>	
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/2.0.7/purify.min.js" integrity="sha256-iO9yO1Iy0P2hJNUeAvUQR2ielSsGJ4rOvK+EQUXxb6E=" crossorigin="anonymous"></script> -->
</head>
<body>
<h2 id="proof"></h2>
<script>
proof.innerHTML = DOMPurify.sanitize(new URL(location).searchParams.get('check') || "TEST")
setTimeout(ok, 2000)
</script>
</body>
</html>
```

**Comment by cure53** [comment]
Not sure what the problem is here, why is this a bypass we would want to fix?

**Comment by jmanico** [comment]
I realized this is closed but if someone does find a bypass is there a way to report it so it’s not in the public until a patch is pushed?

This is a troubling report from a process point of view.

--
Jim Manico
@Manicode

**Comment by cure53** [comment]
Here you can find the necessary info:
https://github.com/cure53/DOMPurify#what-if-i-find-a-security-bug

I believe this is not a bypass by the way and would deem it to be a false alert based on the info we have.

**Comment by jmanico** [comment]
Agreed. I'm glad to know there is a better process to report bugs.

Thanks,

Jim
