### ISSUE TITLE
use nodeType constants defined in e.g., Node.TEXT_NODE instead of hard-coded number lieterals

### ISSUE THREAD

**Issue by mozfreddyb** [cure53/DOMPurify#441]
This issue proposes a tiny code enhancement that favors constants defined in the DOM standards over hard-coded numbers. E.g., comparing a node's `nodeType` with `Node.TEXT_NODE` rather than the number `3`. This is mostly for readability.

### Background & Context

Code like 
```js
      /* Fix IE's strange behavior with manipulated textNodes #89 */
      if (currentNode.nodeType === 3 && currentNode === oldNode) {
        continue;
      }```

or 
```js  if (!window || !window.document || window.document.nodeType !== 9) {`

would become more readable.

**Comment by cure53** [comment]
That makes perfect sense, thanks! Wanna send over a PR? Happy to review and merge in.

**Comment by cure53** [comment]
Not sure what the next step is here, @freddyb is this still WIP?

**Comment by mozfreddyb** [comment]
jsdom doesn't support these constants, filing a bug over there.

**Comment by cure53** [comment]
Thank you :)

**Comment by cure53** [comment]
Closing this for now.
