### ISSUE TITLE
unexpected behavior (stripping contents of title tag)

### ISSUE THREAD

**Issue by abrin** [cure53/DOMPurify#442]
> This issue proposes a bug wherein the contents of a `<title>` tag are stripped unexpectedly.  It could well be that I'm misunderstanding how this should be used. 

### Background & Context

I'm trying to cleanup XML before rendering to HTML... the XML can have a mixture of xml tags and pseudo html tags.  

### Bug

In my node app:
```
import DOMPurify from "dompurify";

...
export function sanitize(value, config) {
  return DOMPurify.sanitize(value, config);
}
```
### test:
```
  it("strips <title> tags default", () => {
    value = "a <title>test</title> text";
    indexer.addField(obj, field, value, {
      ALLOWED_TAGS: ["b"],
      KEEP_CONTENT: true
    });
    expect(obj).toEqual({ text: "a test text" });
  });
```

#### Given output

 returned output is: `a  text`

#### Expected output

 returned output is: `a test text`

### more
I've been able to get some of it to work using a hook... but now running into issues with node and JSDOM creating a valid textNode because of JSDOM

```
DOMPurify.addHook("beforeSanitizeElements", function(
  currentNode,
  hookEvent,
  config
) {
  // Do something with the current node and return it
  // You can also mutate hookEvent (i.e. set hookEvent.forceKeepAttr = true)
  // console.log(currentNode.tagName, currentNode);
  if (currentNode.tagName == "TITLE") {
    currentNode.parentNode.insertBefore(
      document.createTextNode(currentNode.textContent),
      currentNode
    );
    currentNode.parentNode.removeChild(currentNode);
    return currentNode;
  }

  return currentNode;
});
```

**Comment by cure53** [comment]
Heya, thanks for the ticket! This happens because on older version of Edge, the title tag is considered dangerous and enables mXSS.

The code responsible for stripping the title content is here:
https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L255

Browser treat the title tag in rather special ways, is it really 100% necessary that its contents get preserved?

**Comment by abrin** [comment]
it is, in our case, but with that said, I can't get DOMPurify to run in NodeJS properly or to compile it via Webpack, so I've implemented html-sanitize instead.   Thanks for the info and looking into this. Hopefully the hook above is useful to someone else in the future

**Comment by cure53** [comment]
The hook indeed looks like right way to go. Not sure how to make it work with jsdom :sweat_smile:

**Comment by abrin** [comment]
closing this, as it seems like there's not a need and not an easy way forward
