### ISSUE TITLE
devDependency for jsdom is very outdated

### ISSUE THREAD

**Issue by mozfreddyb** [cure53/DOMPurify#449]
DOMPurify uses jsdom version 8.x.x as a *dev*Dependency, however jsdom is currently only supporting version 16 and above.
See https://raw.githubusercontent.com/jsdom/jsdom/master/.github/ISSUE_TEMPLATE.md

### Background & Context

There might be some bugs in older version of jsdom, so it would make sense to update it to something that is supported.

### Bug

N/A 

#### Input

N/A

#### Given output

N/A

#### Expected output

N/A

### Feature

N/A

**Comment by cure53** [comment]
Heya, thanks for reporting!

I am however not sure if we can easily change that, it seems the test suite depends on older jsdom to work. cc @tdeekens

**Comment by tdeekens** [comment]
Yes, the test suite doesn't allow us to update as it stands and would require quite a bit of heavy lifting I suppose.

**Comment by cure53** [comment]
Yep, I thought so too :) Thanks for checking.
