### ISSUE TITLE
Question: Is there any performance difference between hooks?

### ISSUE THREAD

**Issue by Slapbox** [cure53/DOMPurify#452]
Perhaps a silly question, but for operations which could take place in `uponSanitizeElement` or `afterSanitizeElements`, would it be more performant to add the hook to `uponSanitizeElement`? 

Am I right to think that adding it to `afterSanitizeElements` adds an extra pass to the processing of the content, while `uponSanitizeElement` is always going to run regardless of whether a user adds a hook or not?

**Comment by cure53** [comment]
Heya :)

> Am I right to think that adding it to `afterSanitizeElements` adds an extra pass to the processing of the content, while `uponSanitizeElement` is always going to run regardless of whether a user adds a hook or not?

That is mostly correct as far as I can see. 

The before-hook is being called before _anything_ was done to any element:
https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L643

The upon-hook is being called after _some_ first checks, i.e. after the DOM clobbering check:
https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L656

And the after-hook is being done after _all_ of the element sanitization has happened:
https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L745

So, if you look for the fastest way of doing things, using the upon-hook is likely the best. Or even the before-hook, depending on what you aim to do. By using the after-hook, almost all sanitization work has been done already.

**Comment by Slapbox** [comment]
Thanks so much for the speedy reply @cure53! 

I tried so many DOM cleaning solutions and DOMPurify is an absolute godsend!
