### ISSUE TITLE
<form> is not sanitized

### ISSUE THREAD

**Issue by bryanchen-d** [cure53/DOMPurify#453]
### Background & Context
Sanitize a user-generated html markup text and set it as innerHTML of a div. 

#### Input

<form action="api/post">
<input type="submit">click me</input>
</form>

#### Given output

The output is the same as input

#### Expected output

Invalidate the submit action to avoid the clickjacking attack.

**Comment by cure53** [comment]
Clickjacking is outside our threat model, sorry.
