### ISSUE TITLE
Question regarding SVG's conditional processing attributes

### ISSUE THREAD

**Issue by ydaniv** [cure53/DOMPurify#456]
### Question

SVG's [`<switch>`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/switch) is whitelisted, however, it has basically no meaning without conditional processing attributes in its children, i.e. `requiredFeatures`, `requiredEextensions`, and `systemLangauge`, which are all _NOT_ in the attribute whitelist.

Also worth noting, these attributes are deprecated in SVG2.

So, my question, obviously, are these attributes not whitelisted by design? Or were simply missed?

thanks a bunch!

**Comment by cure53** [comment]
Good catch, as far as I can see we can in fact remove `switch` from the allow-list then. Any concerns about that?

**Comment by ydaniv** [comment]
Well, actually `systemLanguage` _isn't_ deprecated, it's the only that isn't, but don't know if/where it's supported.

Are there any security concerns regarding the two?

**Comment by cure53** [comment]
As far as I can see, `systemLanguage` is safe. Wanna spin up a PR and add it? :D

**Comment by ydaniv** [comment]
sure thing 👍

**Comment by cure53** [comment]
Thank you!

**Comment by ydaniv** [comment]
@cure53 looks like you're also missing some attributes which are more important, like:

- `filterUnits`
- `primitiveUnits`
- `clipPathUnits`
- `preserveAspectRatio`

Should I put all in same PR? Or open a separate one?

**Comment by cure53** [comment]
All those should be safe as well, don't see any problems with those :+1:

**Comment by cure53** [comment]
Closing this for now, many thanks :)
