### ISSUE TITLE
Whitelist attributes

### ISSUE THREAD

**Issue by alejo-17** [cure53/DOMPurify#462]
In the following HTML, the onclick event is removed:

`<button type="button"  id="myButton" onclick="javascript:doAction();">My Button</button>`

I tried with the following configurations:
`var domPurifyConfig = {
	URI_SAFE_ATTRIBUTES: ['onclick', 'onsubmit', 'onChange', 'onkeyup']
};`
`var domPurifyConfig = {
	ADD_ATTR: ['onclick', 'onsubmit', 'onChange', 'onkeyup']
};`
But the attribute is still removed.
I am using 2.0.13 version.

**Comment by cure53** [comment]
Heya, this should fix it:

```javascript
        let rawHTML = `<button type="button" id="myButton" onclick="javascript:doAction();">My Button</button>`;
        let sanitizedHTML = DOMPurify.sanitize(
            rawHTML,
            {
                ADD_URI_SAFE_ATTR: ['onclick', 'onsubmit', 'onchange', 'onkeyup'],
                ADD_ATTR: ['onclick', 'onsubmit', 'onchange', 'onkeyup']
        });
        console.log( sanitizedHTML );
```

**Comment by cure53** [comment]
The flag was relatively new so we didn't document it yet, that was just changed :+1:

**Comment by alejo-17** [comment]
Thanks for the response, so should I duplicate the attributes in these two parameters to have a whitelist of them?

**Comment by cure53** [comment]
If you wish to use a JavaScript URI inside the event handler, then both is needed.

Step 1: Allow-list the attribute
Step 2: Tell the sanitizer that it can even have URI-like values

**Comment by alejo-17** [comment]
Thanks. Also I'm having issues with this input, not sure if the word "prefix" is listed to be removed because after processing it, the id is removed.
`<input type="tel"  id="prefix"  onkeyup="event(this)"/>`

**Comment by cure53** [comment]
In that case, likely something else in the DOM also has an ID "prefix" and DOMPurify prevents a collision. 
You can turn that behavior off though: `SANITIZE_DOM` is your flag of choice.

**Comment by alejo-17** [comment]
I tried with SANITIZE_DOM and it fixes the issue. However, the html that is processed by the sanitizer only contains one element with that id ("prefix"). After removing the logic to sanitize, it appears again.

**Comment by cure53** [comment]
Somewhere on the page mist be an element with that ID. Or a label. This code snippet here checked for it:
https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L775

Maybe check with a debugger what causes the collision?

**Comment by alejo-17** [comment]
Does the variable document make reference to all the current page? I mean is it compared with the rest of the html with the current one?

**Comment by cure53** [comment]
With the rest of the document to avoid DOM clobbering attacks

**Comment by alejo-17** [comment]
I extracted all the html source which should contain all the elements and I only see one occurrence of "prefix". Also I extracted all the content of a version without the sanitizer and the results are the same.

**Comment by cure53** [comment]
Then I don't know :) But I guess the ticket can be closed now?
