### ISSUE TITLE
Release note for 2.0.13 missing?

### ISSUE THREAD

**Issue by LeSuisse** [cure53/DOMPurify#467]
Hi!

I was taking a look at the recent changes in DOMPurify and it seems the release note for the 2.0.13 release note is missing.
From the mail notification I received when it was initially released it looks like it was published with a release note.
Is this expected?

https://github.com/cure53/DOMPurify/releases/tag/2.0.13

**Comment by cure53** [comment]
Heya, we pulled 2.0.13 short after release because it was buggy. So, yes - this is sort of expected :)

**Comment by LeSuisse** [comment]
Thanks for your answer and sorry for the noise!

I was almost certain that a recent release added some SVG attributes to allow list and I got confused for a minute when searching for the change in the release notes :) .

**Comment by cure53** [comment]
No worries at all and yes, this release also added those attributes. Sorry that the info got lost!
