### ISSUE TITLE
Attributes should not be first-class

### ISSUE THREAD

**Issue by ahri** [cure53/DOMPurify#468]
### Background & Context

The current configuration doesn't appear to allow me to allow `<script></script>` and `<img src=... />` but block `<script src=...></script>` - my feeling is that attributes are _not_ first-class and their meaning is contingent upon their parent tag

### Bug

The existence of the `ALLOWED_ATTR` config option says the opposite: that an attribute name is first-class and is treated the same regardless of its parent element.

### Feature

My suggestion is that a new config is provided, called `ALLOWED_COMBINATIONS` with values such as `{ img: ['src'], script: [] }` that acknowledges the relationship between tags and their attributes.

**Comment by cure53** [comment]
Hey, that is correct, but so far we have not witnessed any situation where more granularity is needed to prevent XSS. Given our main goal, sanitizing markup to prevent XSS, we have no plans to change the API before doing a major version leap.

In case a developer needs more granularity, they can easily implement that with a hook.

For DOMPurify 3.x we might look into changing this, but no plans for now.

**Comment by cure53** [comment]
Closing this for now.
