### ISSUE TITLE
minified purify.js for chrome extension with small overhead

### ISSUE THREAD

**Issue by QasimWani** [cure53/DOMPurify#473]
> This issue proposes a [feature] which...

### Background & Context

I have been using your package for over 3 years now on the server end. For one of my client side project which requires low-weight JS files (developing a chrome extensions), one of the features involves inputting text into one of the layouts. I looked across various other distributions but couldn't find a lightweight client side library that prevents from XSS injection attacks via proper html sanitization, not escaping characters. 

### Feature

Source available for lightweight distribution on client-side html sanitization? Vanilla.JS is preferred over jquery.
thanks

**Comment by cure53** [comment]
Hey there, thanks for filing the issue. Should this not already be sufficient?

https://github.com/cure53/DOMPurify/tree/main/dist

**Comment by QasimWani** [comment]
I'm unable to properly sanitize with that and the .map files. I used an external file (rawgit) for your source and that didn't work. So i downloaded the folder with all the src and dist (your purify.min.js.map calls functions from src/) and that gave me the following warning: `DevTools failed to load SourceMap: Could not load content for chrome-extension`. Supressing it by deleting the last line of min.js didn't work as well (i change the path of that to match with my directory but it didn't seem to read it).
With the src/min.js, the problem was that it was calling export outside of modules since i'm not connected to a server.

**Comment by cure53** [comment]
Have you tried those?

https://cdnjs.com/libraries/dompurify

**Comment by QasimWani** [comment]
Thanks for that. I tried it, but it wasn't able to sanitize it tho. 
```javascript
let dirty = document.getElementsByTagName('input')[0].value;
var clean = DOMPurify.sanitize(dirty);
```

When outputting it, it evaluates html. Is there a way of doing this? I think I'm doing it wrong.

**Comment by cure53** [comment]
Can you define "sanitize" and "evaluate"? I am not 100% sure what you want to achieve.

**Comment by cure53** [comment]
Not sure if there is a bug here, closing for now.

**Comment by QasimWani** [comment]
Fixed it! Found an easier alternative using Vanilla JS. Thanks for quick replies 👍
