### ISSUE TITLE
All attributes are set to lowercase

### ISSUE THREAD

**Issue by abierbaum** [cure53/DOMPurify#476]
### Background & Context

It appears that DOMPurify converts all attributes in sanitized output to lowercase.  I am using custom web components (Angular-based) that rely upon attributes that are case sensitive.  I can't find a way to work around this.

I had to override the ALLOWED_TAGS to allow my elements through and then I used a hook on 'uponSanitizeAttribute' to forceKeepAttr to allow all my attributes through.  But the case of the attribute is still changed.

Is there a way to work around this?

#### Input

`<my-component testAttrib="test"></my-component>`

#### Given output

`<my-component testattrib="test"></my-component>`

#### Expected output

`<my-component testAttrib="test"></my-component>`

**Comment by cure53** [comment]
Heya, thanks for filing this! However,m it is not us lower-casing the attribute names, it is the browser:

```
<b FooBar="123" id="xyz"></b>
<script>console.log(xyz.attributes[0]) </script>
```

This is spec compliant behavior, and I am not sure if this van be worked around easily: https://w3c.github.io/html-reference/documents.html Unless you fiddle with the sanitized string after sanitization.
