### ISSUE TITLE
Error when using in Chrome: DevTools failed to load SourceMap

### ISSUE THREAD

**Issue by arnoudkooi** [cure53/DOMPurify#477]
[bug]

### Background & Context

Mozilla enforces html sanitization in Browser Addons.
In the minified version there is a reference to the sourcemap.
This causes a browser error, leading to bug reports and confusion.

Mozilla enforces to use unchanged files, so Im not allowed to modify purify.min.js to delete the line
`//# sourceMappingURL=purify.min.js.map`

Can this line be removed or a file without this line be provided

### Bug
In browser console of Chrome you get the an error about sourcemap

#### Given output

`DevTools failed to load SourceMap: Could not load content for chrome-extension://iimpebfldpbfipbodemijjbfblmkhoeh/js/purify.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME`

#### Expected output

No browser errors

**Comment by cure53** [comment]
Afaics that is not our bug and us "fixing" it would not change things on broader scale. 
Tempted to close the issue unless there is a strong argument against it we don't see yet.

**Comment by arnoudkooi** [comment]
True, this actually is a "feature" request..

**Comment by cure53** [comment]
Gotcha, we are open for a PR producing a minified version without source-map reference, wanna shoot one over?

**Comment by arnoudkooi** [comment]
May be easier if i include this in my own build process, thanks!
