### ISSUE TITLE
Is XSS namespace mutation fixed?

### ISSUE THREAD

**Issue by syabro** [cure53/DOMPurify#478]
https://research.securitum.com/mutation-xss-via-mathml-mutation-dompurify-2-0-17-bypass/

https://news.ycombinator.com/item?id=24703230

Thanks!

**Comment by cure53** [comment]
In other words, we are not aware of any bypass right now.

**Comment by tomaszzielinski** [comment]
My understanding is that they've fixed it recently and that 2.0.7 we use is vulnerable, no?

**Comment by syabro** [comment]
Thanks, checked XSSs manually against 2.1.1 and they aren't working.
