### ISSUE TITLE
The `<dialog>` element

### ISSUE THREAD

**Issue by Malvoz** [cure53/DOMPurify#479]
Consider allowing [`<dialog>`](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element). The `open` attribute is shared with the `<details>` element, which is already in `attrs.js`:

https://github.com/cure53/DOMPurify/blob/307c7d0dde17a2d1f27049d6d39add24144ba87c/src/attrs.js#L71

 The element is [well supported](https://caniuse.com/dialog) (76% global support).

**Comment by cure53** [comment]
This makes perfect sense to add, wanna shoot over a PR? :)

**Comment by cure53** [comment]
Ah, just did it myself :D Works for you?

**Comment by Malvoz** [comment]
Yes, thanks!
