### ISSUE TITLE
Incorrect HTML generation 

### ISSUE THREAD

**Issue by jyothykundurthy** [cure53/DOMPurify#480]
> This issue proposes a [bug] which is breaking the output of DOMPurify

### Background & Context
Trying to upgrade the dependency in my project from 1.0 - latest.
Noticed one of the sample provided in [readme](https://github.com/cure53/DOMPurify#some-purification-samples-please) is failing
```
DOMPurify.sanitize('<p>abc<iframe//src=jAva&Tab;script:alert(3)>def</p>'); // becomes <p>abcdef</p>
```

Output of `1.0` and `2.0` doesn't match.

### Bug
Incorrect html generated with latest version.

#### Input
```
<p>abc<iframe//src=jAva&Tab;script:alert(3)>def</p>
```

#### Given output
```
<p>abc</p>
```

#### Expected output
```
<p>abcdef</p>
```

**Comment by cure53** [comment]
Yup, we are aware :) Content of certain elements is now being removed in case those elements are removed. 
Not doing so resulted in XSS, so we had to do it.

**Comment by cure53** [comment]
Note that this only affects certain elements, so we strongly believe it won't cripple legitimate content:

https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L256

We'll fix the README, thanks for pointing this out!
