### ISSUE TITLE
Sanitizing any <script> tag will remove it's content

### ISSUE THREAD

**Issue by dms120** [cure53/DOMPurify#481]
> Sanitizing any <script> tag will remove it's content

### Background & Context

Using DOMPurify to sanitize the following HTML will result on an empty string.

```
<script type="text/html" class="template">
  <div class="example">
  </div>
</script>
```

Using this:
```
<div class="content">
  <script type="text/html" class="template">
    <div class="example">
    </div>
  </script>
</div>
```

will result on 
```
<div class="content">

</div>
```

This looks similar to the https://github.com/cure53/DOMPurify/issues/352 
I tried using different combinations of { ADD_TAGS: ['script'],  FORCE_BODY: true, KEEP_CONTENT: false } but nothing worked.

Is this an issue or it's the expected behavior?
Thanks.

**Comment by jyothykundurthy** [comment]
https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L256 KEEP_CONTENT will be ignored for script

**Comment by cure53** [comment]
You should be able to solve this with a hook, me thinks! 
i.e. replace the script element with a harmless one and then put it back.

**Comment by cure53** [comment]
Check this example hook, where we allow scripts and pipe their content through a JS sandbox. 
This should be very close to what you would need, no?

https://github.com/cure53/DOMPurify/blob/main/demos/hooks-mentaljs-demo.html

**Comment by dms120** [comment]
Hi, i tried do this

```
// Sanitize HTML
    DOMPurify.addHook('beforeSanitizeElements', function(node, data) {
        if (node && node.tagName === 'SCRIPT' && node.textContent) {
            switchElementTag(node, 'div-temp');
        }
    });

    // Sanitize HTML
    DOMPurify.addHook('afterSanitizeElements', function(node) {
        if (node.tagName === 'div-temp' && node.textContent) {
            switchElementTag(node, 'script');
        }
    });


    var switchElementTag = function(element, newTag){
        var replacement = document.createElement(newTag);
        // Grab all of the original's attributes, and pass them to the replacement
        for(var i = 0, l = element.attributes.length; i < l; ++i){
            var nodeName  = element.attributes.item(i).nodeName;
            var nodeValue = element.attributes.item(i).nodeValue;

            replacement.setAttribute(nodeName, nodeValue);
        }

        // Persist contents
        replacement.innerHTML = element.innerHTML;
        element.parentNode.replaceChild(replacement, element);
    };


var purifiedHTML = DOMPurify.sanitize( html, { ADD_TAGS : ['script', 'div-temp'] } );
```

But i'm having the following error:
```
purify.min.js:formatted:569 Uncaught DOMException: Failed to set the 'outerHTML' property on 'Element': This element has no parent node.
    at _forceRemove (http://localhost:8080/portlet/_B922201_20201029031005_/lib/js/external/dompurify/purify.min.js:521:32)
    at _sanitizeElements (http://localhost:8080/Core-cb-mashup-portlet/_B922201_20201029031005_/lib/js/external/dompurify/purify.min.js:693:17)
    at Function.DOMPurify.sanitize (http://localhost:8080/portlet/_B922201_20201029031005_/lib/js/external/dompurify/purify.min.js:1007:21)
```

I'm doing the replace in the right way?

**Comment by cure53** [comment]
I think what you want to do here is this:

```javascript
DOMPurify.addHook('beforeSanitizeElements', function (node) {
    if (node.querySelector && node.querySelector('script[type="text/html"]')) {
        var template = node.firstElementChild;
        if(template.tagName === 'SCRIPT') {
            var container = document.createElement('my-temp');
            container.innerHTML = template.innerHTML;
            return node.replaceChild(container, template)
        }
    }
})

var html = `
    <div class="content">
      <script type="text/html" class="template">
        <div class="example">lalala</div>
      <\/script>
    </div>`;

var clean = DOMPurify.sanitize( html, { ADD_TAGS : ['script', 'my-temp'] } );
console.log(clean)
```

**Comment by cure53** [comment]
This will return the following HTML:

```html

    <div class="content">
      <my-temp>
        <div class="example">lalala</div>
      </my-temp>
    </div>
```

Note that this code doesn't work universally for all kinds of ways script blocks can be nested inside the template code. Might break if the script element is the second node, if there is multiple ones etc. - lots of tweaking needed I guess :)

But it shows how to generally approach it and take it from there.

**Comment by cure53** [comment]
Closing this issue as I believe it's not a problem in our code base and can be solved as described above, please reopen if not :)

**Comment by dms120** [comment]
Hi, that would do the trick, but i need to replace them again after.

Wouldn't it be nice to have a hook to call on the end of all the sanitize process?  If i do that on the afterSanitizeElements they are being removed anyway.

What's the most efficient way to do that?
Thanks.

**Comment by cure53** [comment]
> Wouldn't it be nice to have a hook to call on the end of all the sanitize process? If i do that on the afterSanitizeElements they are being removed anyway.

Yup, that might indeed make sense. Wanna spin up a PR? :D
