### ISSUE TITLE
Math formulas cannot be displayed normally

### ISSUE THREAD

**Issue by RanX12** [cure53/DOMPurify#484]
I used DOMPurify's sanitize to filter out my content, and then the math formulas were displayed on Bootstrap's popover, but its style eventually became ugly.
![image](https://user-images.githubusercontent.com/46048444/98337141-1b6da400-2043-11eb-90d6-733fc4413d0d.png)

I read this document, [document](https://github.com/cure53/DOMPurify#can-i-configure-dompurify), but I don’t know how to change it, please advise, thank you!

![image](https://user-images.githubusercontent.com/46048444/98338788-b0719c80-2045-11eb-84e2-55e51e046059.png)

**Comment by cure53** [comment]
Heya, would you be able to tell us how the original HTML looks like and what comes out after sanitization?

**Comment by cure53** [comment]
Closing this for lack of info, please reopen if needed
