### ISSUE TITLE
Question about dual license

### ISSUE THREAD

**Issue by joandvgv** [cure53/DOMPurify#485]
I have a question about the dual license! If we wanted to go with Apache 2.0, what would we need to do? I know this is not specific to this repository but I'm curious because I saw in other issues (#87) you decided to go with Dual License. I'm not a lawyer at all so I don't know what the process is to choose one or the other. 
Don't know if it matters but we're using this package in the backend installed directly from npm 
Thanks!

**Comment by cure53** [comment]
Oh, that is easy, you would simply have to download and fill our 45 page legal survey so we can submit it to the German ministry of justic... just kidding.

You can just use it and pick whatever license is best for you and roll with it. No need to do, document, decide or change anything :)

**Comment by joandvgv** [comment]
LMAO you almost got me haha
Awesome, thanks for the fast answer!
