### ISSUE TITLE
<noscript> sanitization is different in node and browser

### ISSUE THREAD

**Issue by jakubriedl** [cure53/DOMPurify#486]
Not sure what is the correct behavior but I can see different output from browser & node (via JSDOM) for `<noscript>` tags.

lets assume we have this html
```html
<noscript>
<span>This is content of span</span>
</noscript>
```

in node it returns `\n` (demo https://runkit.com/jakubriedl/5fa62f4f9e39ba001b417fb2)
in browser it returns `<span>This is content of span</span>` (tested in https://cure53.de/purify)

**which one is correct?** In our use-case we want to see the output of browser

### Background & Context
In our app we are processing scraped data and using DomPurify to sanitize the content we scrape which is later analyzed using Natural Language Processing. Because it is ran in node without scripting enabled we want to see content of `<noscript>`.

#### Input
```html
<noscript>
<span>This is content of span</span>
</noscript>
```

#### Given output
```html
\n
```

#### Expected output
```html
<span>This is content of span</span>
```

### Feature
If it is expected to be removed what is the reason for that? Is there some security risk I'm not aware of? Or is it possible to enable it?

Thanks

**Comment by cure53** [comment]
Good question :D I would recommend to just allow `noscript` via config and that should fix it.

**Comment by jakubriedl** [comment]
How can I do that? I've tried
```
DOMPurify.sanitize(dirty, {
  ADD_TAGS: ['noscript']
});
```
but that doesn't help

**Comment by cure53** [comment]
Hm, strange, but frankly I am not sure if this is our bug.

Have you checked this? https://github.com/jsdom/jsdom/issues/1802

**Comment by jakubriedl** [comment]
I did bit more research and it seems you are right that the issue is JSDOM or parse5.

background:
JSDOM uses parse5 to parse html. Which uses flag `scriptingEnabled` and in case that it is false it should parse `<noscript>` as dom. If true then as string. JSDOM sets this to `true` only if `runScripts: "dangerously"` which we don't use. It seems that the problem sits somewhere in that space.

temp fix:
before parsing the html do `dirty = dirty.replace(/<\s*\/?\s*noscript\s*>/g, '')` which removes all `<noscript>` tags and resolves the issue.
