### ISSUE TITLE
[Question] Sanitize string elements without root element

### ISSUE THREAD

**Issue by JeromeDeLeon** [cure53/DOMPurify#487]
I have a question regarding sanitizing multiple elements without a root element.
I have elements below:
```jsx
DOMPurify.sanitize('<title>Hello world</title><path ... />');
// output: <path ... />
```

How do I make it so that it allows multiple valid elements without the root element?

**Comment by cure53** [comment]
You can try to play with the `FORCE_BODY` flag, that might help here.

**Comment by JeromeDeLeon** [comment]
Unfortunately, it doesn't work. It just messed up the elements.

**Comment by cure53** [comment]
If there's elements being moved around then something was wrong with the element in the first place. 
DOMPurify uses the browser and never really moves elements on its own. I would recommend to 

Also, I tried myself:

```javascript
var html = `<title>Hello world</title><path />`;

var clean = DOMPurify.sanitize( html, {FORCE_BODY: true});
console.log(clean) // output: <title>Hello world</title><path></path>
```

This is the expected result according toy our ticket, no?

**Comment by JeromeDeLeon** [comment]
Hmm, I tried using without `DOMPurify.sanitize` and worked just fine, but I'll try keep look more into it and get back to you probably later. Thank you.

**Comment by cure53** [comment]
Aye, okay! :)

**Comment by JeromeDeLeon** [comment]
I tried using your demo and seems like it doesn't work to some self-enclosing tag or maybe they are not allowed to have a self-enclosing tag.

![image](https://user-images.githubusercontent.com/32805276/98456356-9e177000-21b7-11eb-8c73-1a4250dcd51c.png)

**Comment by JeromeDeLeon** [comment]
I managed to solve it by transforming self enclosing tags using regex.

```js
HTMLString.replace(/<([a-z]+)+([^><]*?)\s*\/>/g, '<$1$2></$1>');
```
