### ISSUE TITLE
More powerful and simple Hook API

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#49]
After having worked with the hooks for a while, I think we could make them more powerful. 

For example, I don't want to repeat the whole process of determining whether an attribute is an attribute and the node is a node.

I was thus thinking about passing a meta object with every hook call, that passes along some relevant info about the element/attribute to inspect. Any thoughts?

**Comment by cure53** [comment]
My proposal would be to add two additional hooks:

```javascript
                /* Execute a hook if present */
                _executeHook('uponSanitizeElement', currentNode, {
                    tagName: tagName
                });
```
and
```javascript
                /* Execute a hook if present */
                _executeHook('uponSanitizeAttribute', currentNode, {
                    attrName: attrName, attrValue: tmp.value
                }); 
``` 

Those get called once we already verified, that the element is an element and that the attribute is an attribute. In addition, we are passing the verified tag name and the verified attribute name alongside the value. 

This should make it far more secure and easy to create a hook as the developer doesn't have to do the whole tedious verification on their own.

**Comment by cure53** [comment]
@fhemberger I have added a slightly renovated hook API. Would you mind having a quick look? I think we can release 0.6.2 if all is fine.

**Comment by cure53** [comment]
@fhemberger I added some basic code to enable deletion of existing hooks. Mind reviewing it real quick please? Changes: https://github.com/cure53/DOMPurify/commit/753053b61d536bb0041becbc4049d2aa84159dec

**Comment by fhemberger** [comment]
@cure53 Two minimal annotations, besides that LGTM :+1:

**Comment by cure53** [comment]
@fhemberger Added that. Testing the whole feature on MSIE now, then I think we should be good.

**Comment by cure53** [comment]
I am fairly happy with the Hook API for now, closing this ticket until additional needs and requests come in.
