### ISSUE TITLE
Removing the false script tag.

### ISSUE THREAD

**Issue by noorulh06** [cure53/DOMPurify#500]
I have an HTML page which has an script tag with content like:
`<script>
int i = 1;
int j = 2;
if (i<j)
console.log(i);
else
console.log(j);
</script>`

Now DOMPurify removed the whole script tag which it shouldn't.
After debugging, I found that it is remove with the following condition: https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L819

Can you guys please look into this if it is a bug or is there a way to resolve this?

**Comment by cure53** [comment]
Hmm, quite frankly - while it seems that DOMPurify is overzealus with removing this element, we won't fix it. The risk to introduce XSS with a fix is too high - and the problem can also be solved with a hook.

So, if you decide to allow script elements, you can use a hook to check that their content doesn't contain any possibly offensive characters.

**Comment by noorulh06** [comment]
One thing to note that:
if I add an extra space after < then it don't sanitise it.
`<script> int i = 1; int j = 2; if (i< j) console.log(i); else console.log(j); </script>` actually works.
I guess I need to add a hook to perform this.
Just wanted to know if it is safe to go with this?

**Comment by cure53** [comment]
Well, if you allow script elements, what does safe even mean then? :D

**Comment by noorulh06** [comment]
So, ideally We should allow the script only by javascript file. Not using script tag inside HTML. Am I right?
I will discuss with my team that what we can do in this situation.
Thanks.
