### ISSUE TITLE
ALLOWED_TAGS allows tags other than those mentioned in the list

### ISSUE THREAD

**Issue by virajkulkarni14** [cure53/DOMPurify#505]
> This issue proposes a [bug, feature] which...

### Background & Context

Please provide some more detailed information about the general background and context of this issue and delete non applicable sections below.

#### Input

Some HTML which is thrown at DOMPurify.

#### Given output

The output given by DOMPurify.

#### Expected output

The expected output.

### Feature

Briefly outline the proposed feature, its value and a potentially proposed implementation from a high level.

**Comment by cure53** [comment]
I don't understand the issue, closing for now.

**Comment by virajkulkarni14** [comment]
Yes @cure53, sorry about that. It did not allow me to complete the issue description and opened the issue the moment I pressed the Return key.

Sorry for the inconvenience. Should I reopen the same issue with updated description or open a new one?
