### ISSUE TITLE
sanitize function with {ALLOW_TAGS: []} not removing strings like '&nbsp' or '&lt'

### ISSUE THREAD

**Issue by Danscap** [cure53/DOMPurify#506]
Is this a bug or a feature?

If it is a feature, how do we get around this minor quirk?

Or is it necessary to write our own regex removal for all of these extra strings?

**Comment by cure53** [comment]
Heya, if you want specific strings removed, you'd have to add your own logic. Maybe via hook?

Please keep in mind though: https://github.com/cure53/DOMPurify#is-there-any-foot-gun-potential
