### ISSUE TITLE
(Updated Description) ALLOWED_TAGS allows tags other than those mentioned in the list

### ISSUE THREAD

**Issue by virajkulkarni14** [cure53/DOMPurify#507]
> This issue reports a bug which *does not* filter the tags as per a whitelist of allowed tags.

### Background & Context

I am creating a global DOMPurify config for my React app using the `setConfig` method. That config object also contains the `ALLOWED_TAGS` attribute that contains an array of HTML tags I want to restrict my content to. But the `sanitize` method still renders the unwanted tags.

### The Config file
`dompurify.config.js`:

```javascript
import { isString } from 'lodash'
import DOMPurify from 'dompurify'

// Allow only '<a></a>', '<b></b>', '<i></i>', '<p></p>' and '<u></u>' tags
const WHITELISTED_TAGS = ['a', 'b', 'i', 'p', 'u']

DOMPurify.setConfig({
  USE_PROFILES: { html: true }, // Only allow HTML
  IN_PLACE: true, // In place mode for faster sanitization,
  ALLOWED_TAGS: WHITELISTED_TAGS, // Only allow tags specified in the whitelist above
  ADD_ATTR: ['target'] // Allow elements with the target attribute
})

/**
 * Add hook to sanitize elements with a `target` attribute.
 */
DOMPurify.addHook('afterSanitizeAttributes', (node) => {
  const target = node.getAttribute('target')
  if (isString(target) && target.toLowerCase() === '_blank') {
    node.setAttribute('rel', 'noopener noreferrer')
  } else {
    node.removeAttribute('target')
  }
})

export { DOMPurify }

export default DOMPurify.sanitize
```

### The React component file
`MyComponent.js`:

```javascript
import React from 'react'
import Typography from '@material-ui/core/Typography'
import { sanitize } from 'path/to/dompurify.config'
// Other imports and unrelated code

<Typography
	component='p'
	dangerouslySetInnerHTML={{ __html: sanitize(label) }}
/>

// More unrelated code
```
#### Input

Here, inside the `dangerouslySetInnerHTML()`, if I call `sanitize()` with the below input:

`sanitize('<img src=x onerror=alert(1)//>')`

#### Given output

I get the below output:

`<img src="x">`

#### Expected output

Since I haven't included the `img` tag in the `WHITELISTED_TAGS` array in the above config file, I expected the below output, an empty string:

`''`

I am going by the below example in the project README:
```javascript
// allow only <b> elements, very strict
var clean = DOMPurify.sanitize(dirty, {ALLOWED_TAGS: ['b']});
```

### Further notes
I also tried passing the above config object to the `sanitize()` method on every call, but the output was the same.

Please let me know if you have any questions about this bug report or if you find that I'm not doing something right.

Thank you!

**Comment by virajkulkarni14** [comment]
@cure53, I'm opening this as a new issue, just in case you do not get notified of the updated description in the [old issue](https://github.com/cure53/DOMPurify/issues/505). If you feel either of them can be closed, please let me know and I will close it.

Thanks!

**Comment by cure53** [comment]
I think the problem is that you use a profile, that will override the other setting. Removing it will solve your issue:

```html
<!DOCTYPE html>
<body>
<script src="purify.js"></script>
<script>
// Allow only '<a></a>', '<b></b>', '<i></i>', '<p></p>' and '<u></u>' tags
const WHITELISTED_TAGS = ['a', 'b', 'i', 'p', 'u']

DOMPurify.setConfig({
  IN_PLACE: true, // In place mode for faster sanitization,
  ALLOWED_TAGS: WHITELISTED_TAGS, // Only allow tags specified in the whitelist above
  ADD_ATTR: ['target'] // Allow elements with the target attribute
})

console.log(DOMPurify.sanitize('<b><img>'));
</script>
```

**Comment by virajkulkarni14** [comment]
Thank you for the quick reply @cure53. This worked and solved my issue. I can close this issue, but would you like me to add in the project README that using `USE_PROFILES` will override what is contained in `ALLOWED_TAGS`?

**Comment by cure53** [comment]
I think it makes sense to add a line indeed :)

**Comment by Disorrder** [comment]
I think, all the settings including `ALLOWED_TAGS` should override their properties when use profile. Because it's more specific and intuitive.

**Comment by adamreisnz** [comment]
The irony is that the `ALLOWED_TAGS` property is still validated even if `USE_PROFILES` is used.
I agree that specifying settings _in addition_ to a profile should override those properties for the profile.
