### ISSUE TITLE
[QUESTION] implicit declaration of window variable

### ISSUE THREAD

**Issue by lucasvazq** [cure53/DOMPurify#508]
### Background & Context

In the dist file, why the `window` argument of `createDOMPurify` is taken in a non-explicit way?

```ts
// dist/purify.js (last release and main branch)

function createDOMPurify() {
  var window = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : getGlobal();
  ...
```

Whereas when I look at the src file, this argument is declared in an explicit way.
```ts
// src/purify.js (last release and main branch)

function createDOMPurify(window = getGlobal()) {
  ...
```

This works, but it's okay? is it an expected transformation?

**Comment by cure53** [comment]
Heya, that is likely a good question but outside my realm of knowledge, @tdeekens do you have any idea?

**Comment by lucasvazq** [comment]
@cure53 
As far as I see, it's in the dist of the last release 
https://github.com/cure53/DOMPurify/blob/b11cb72fd45b9489ad989517e22b6141743a9fa3/dist/purify.js#L237

But in the src of that release, the code is the ones that I mentioned above
https://github.com/cure53/DOMPurify/blob/b11cb72fd45b9489ad989517e22b6141743a9fa3/src/purify.js#L70

**Comment by tdeekens** [comment]
Is what you call "linter" a TypeScript error? Seems like JSDom types it to DOMWindow while the regular type is Window?

**Comment by lucasvazq** [comment]
@tdeekens 

Apparently, I have confused two things that are not related.

The first thing, and what really matters to me, is to know if it is okay for the window argument to be obtained in such an implicit way.

The second thing, that I linked to that question, is a type error. It has nothing to do with the above question and is related to libraries **@types/jsdom** & **@types/dompurify**.
Forget about this.

I have updated the content of the issue, take a look.

**Comment by tdeekens** [comment]
The difference is due to the babel transformation. The code evaluates to the same result. Does that answer things?

**Comment by lucasvazq** [comment]
Yes, thanks

**Comment by cure53** [comment]
Thanks all and especially @tdeekens :)
