### ISSUE TITLE
It should have function to remove '<' and '>' instead of  return '&lt;' and '&gt;'

### ISSUE THREAD

**Issue by pratiknvyas** [cure53/DOMPurify#51]
when user pass some malicious data it should have functionality/configuration to discard  '<' and '>' character

**Comment by cure53** [comment]
Hi @pratiknvyas! You mean as in `strip_tags()` for example? Do you have sample input and expected output you can show us?

**Comment by pratiknvyas** [comment]
For ex: input < aaaa > ,output can be: aaaa, 
In current implementation library is returning &lt; aaaa &gt;

**Comment by fhemberger** [comment]
Hmm, not sure if we should have this function in core, but you can easily add this for yourself using the hooks DOMPurify provides.

**Comment by pratiknvyas** [comment]
Thanks man It helps a lot :)

**Comment by cure53** [comment]
Cheers :) Let us know if you have trouble creating that functionality using our hook API. We are happy to get feedback and enhance the API where we can.
