### ISSUE TITLE
Failing case

### ISSUE THREAD

**Issue by binarykitchen** [cure53/DOMPurify#512]
Think I've found a case that fails. Using this command and your latest version:

```js
const output = DOMPurify.sanitize(input)
```

where input is

```
"test”><img src=x onerror=alert(document.cookie)>"
```

and output is

```
"test”&gt;<img src="x">"
```

 which still causes an empty image placeholder to be rendered in the browser. I think I'm expecting something like

```
"test”&gt;&lt;img src="x"&gt;"
```

**Comment by cure53** [comment]
As far as I can see, that is exactly the expected output. Not sure if we have any issue here, wdyt?

**Comment by binarykitchen** [comment]
Hmm, on a second thought you are right.

To achieve what I need, I guess I just need some escaping and your library doesn't do that right? Cos my issue is doing an invalid HTTP call `http://x` which doesn't exist.
