### ISSUE TITLE
Expose URL sanitization API

### ISSUE THREAD

**Issue by meeque** [cure53/DOMPurify#513]
DOMPurify takes care of sanitizing URLs that appear in dangerous HTML contexts, e.g. in `src` or `href` attributes. However, the logic that takes care of URLs does not seem to be exposed via a dedicated public API.

### Background & Context

There are scenarios where a developer does not need full HTML sanitization, but might still benefit from URL sanitization. E.g. the following DOM code snippet should be safe for any string inputs `linkUrl` and `linkText`, except for the risk of a dangerous URL scheme in `linkUrl`:
```
link = document.createElement('a');
link.setAttribute('href', linkUrl);
link.append(linkText);
document.querySelector('.container').append(link);
```
Of course, one could feed `link` to DOMPurify before appending it to the document. But that seems kind of wasteful. Especially if `link` were part of a bigger DOM fragment. Also, it could burden developers with maintaining custom DOMPurify configuration when using exotic but secure elements and attributes in their DOM.

One could also use the following idiom to address this:
```
helper = document.createElement('a');
helper.setAttribute('href', linkUrl);
DOMPurify.sanitize(helper, {IN_PLACE: true});
sanitizedLinkUrl = helper.getAttribute('href');
```
This would result in `sanitizedLinkUrl` either being `null` or a string representing a URL that is safe for use elsewhere.

### Feature

DOMPurify should expose a function that addresses URL sanitization, e.g. `DOMPurify.sanitizeUrl`. With that, the above example could be rewritten to:
```
link = document.createElement('a');
link.setAttribute('href', DOMPurify.sanitizeUrl(linkUrl));
link.append(linkText);
document.querySelector('.container').append(link);
```
Not exactly sure what the `DOMPurify.sanitizeUrl` method should return in case it encounters a dangerous URL scheme. It could simply return `null`, `undefined`, or `false`. But that would mean that developers would have to check for the return value explicitly. Instead, it could return a placeholder that is always safe in any HTML context that expects a URL, possibly `#`, `about:blank`, or `javascript:false;`?

In case the URL scheme is not dangerous, the `DOMPurify.sanitizeUrl` could remove unnecessary whitespace around the URL. This is what DOMPurify already does when encountering URLs inside attributes.

Ideally, the `DOMPurify.sanitizeUrl` function should also take a configuration object as second argument, and respect all configuration settings that might be relevant for URLs.

**Comment by cure53** [comment]
We had a close look at this and decided not to expose such feature. It would collide with our security goals and open a whole new range of problems and expectations this library is not ready to handle.

**Comment by meeque** [comment]
Ok, understood. Thanks for looking into it!

Do you have any recommendation how to address this kind of problem otherwise? Would you recommend to run every DOM tree through `DOMPurify.sanitize()` even if it was constructed in a secure manner (except for URLs that is)? Or do you have any other recommendation for URL sanitization?

**Comment by cure53** [comment]
I would recommend to use the code as shown here:
```javascript
link = document.createElement('a');
link.setAttribute('href', DOMPurify.sanitizeUrl(linkUrl));
link.append(linkText);
document.querySelector('.container').append(link);
```

Instead of calling for the fictitious `DOMPurify.sanitizeUrl` method, you can use the URL API and validate the protocol (or any other part of the URL depending on the use case). Would that not do the trick?

**Comment by meeque** [comment]
Well, I tried the URL API initially and this is what I came up with so far:
```
function sanitizeUrl(url) {
    try {
        const ALLOWED_PROTOCOLS = ['http:', 'https:', 'ftp:', 'ftps:', 'mailto:', 'tel:', 'callto:', 'cid:', 'xmpp:'];
        const trimmedUrl = url.trim();
        return ALLOWED_PROTOCOLS.includes(new URL(trimmedUrl, document.baseURI).protocol) ? trimmedUrl : '#';
    } catch(err) {
        return '#';
    }
}
```
Some remarks:
* Passing a second arg to the URL constructor is necessary, because otherwise a relative URLs in the first arg causes an exception.
* The try-catch was necessary, because Chrome throws an exception when there is a null byte in the scheme component of the URL. Chrome does not seem to mind other control characters there. Firefox and Safari do not seem to mind null bytes at all.
* The `trim` was necessary when testing server-side with the URL implementation of nodejs. Browsers seem to remove whitespace around the URLs automatically, as they do when they encounter whitespace in a `src` or `href` attribute. Tested with Chrome, Firefox, and Safari.
* The code does not take character case into account explicitly. All URL implementations that I tested with will convert the scheme to lower-case though.

As you can see, there were already a couple of corner cases to tackle. And I didn't even run that code through an elaborate test suite yet.

That's why I thought that it might be better to delegate URL sanitization to a mature and well-maintained library like DOMPurify. But I understand your concerns about exposing such functionality.

**Comment by cure53** [comment]
I fully see your point, but basically it's adding a new library inside an existing one. We'd need new config options, new documentation, new tests, new threat model, etc. etc. ... :D 

I totally agree that a competent library is needed for this purpose, but I also think it's a separate project. 
And it would be harmful if we expanded DOMPurify's scope to tackle another task than sanitization of markup.

**Comment by isocroft** [comment]
I agree with @cure53 . It needs to be a separate project.

This is a wonderful discussion on the topic @meeque . I am very elated that this discussion has come up. May i present my stand-alone solution. which compliments **DOMPurify**. 

So, @meeque, I present **URISanity**.

I built this library specially for this purpose. Like **DOMPurify**, It works both on NodeJS (server) as well as the browser.Also, like **DOMPurify**, it has very simple APIs like `URISanity.vet()` - which sanitizes a URI and returns `about:blank` if the URI isn't well constructed. This library is in its' early days so i am using this opportunity to call on contributors here who are interested in building this to join me review the current codebase and (if possible) make PRs to make it better than it is now.

https://www.npmjs.com/package/urisanity
