### ISSUE TITLE
Expired link in documentation

### ISSUE THREAD

**Issue by NathanZook** [cure53/DOMPurify#515]
https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model has a link to https://code.google.com/p/mustache-security/, which yields a 404.  You might want to fix that.

**Comment by cure53** [comment]
The link resolves for me, just checked.

**Comment by NathanZook** [comment]
Very curious.  I still get a 404.  :(

**Comment by cure53** [comment]
I can see the Google Code Archive website with all info from back then, what do you see?

**Comment by NathanZook** [comment]
"404. That's an error.

The project mustache-security was not found. "

Might there be a permissions issue?  I have some Google accounts, but I try to stay logged out of all of them...

**Comment by tomholub** [comment]
Interestingly, I also see the web page (not 404), even on private browser window.
