### ISSUE TITLE
Input name/id with keywords like action,reset is getting sanitized

### ISSUE THREAD

**Issue by selvin2215** [cure53/DOMPurify#517]
> This issue proposes a bug which the input tag with name/id with value:action, reset is getting vanished after sanitize.

` let dirty = '<input type="hidden" name="action" id="action" />';`
`console.log(DOMPurify.sanitize(dirty));`

#### Result output : 
`<input type="hidden">`

Expected Output: `<input type="hidden" name="action" id="action" />`

### Feature
I was supposed to sanitize input element with name:'action' or name:'reset' but DOMPurify eliminates out when the name with 'action', 'id', 'reset' whereas if i use name:'firstname' or any non-keyword as name value, it is sanitizing the correct one.

Any thoughts or feedback would be appreciated.

**Comment by cure53** [comment]
Heya, this can be prevented by disabling the DOM Clobbering protection:

```javascript
// disable DOM Clobbering protection on output (default is true, handle with care, minor XSS risks here)
var clean = DOMPurify.sanitize(dirty, {SANITIZE_DOM: false});
```

**Comment by selvin2215** [comment]
Thanks a ton! It actually working. Does DOMPurify has any feature like logs with list of tags/elements that was blacklisted for dirty data?

**Comment by cure53** [comment]
Yup, `DOMPurify.removed`
