### ISSUE TITLE
Noticing inconsistent behavior in 2.2.6 vs 2.2.2

### ISSUE THREAD

**Issue by dejang** [cure53/DOMPurify#518]
We recently had to upgrade to DOMPurify in our codebase. We use DOMPurify in multiple places however, one particularly interesting one, is a hook we have on the `innerHTML` setter call. The following is a simplified snippet of what the code does:
```
// our innerHTML setter hook
innerHTMLSetter(value) {
    const detachedElement = document.createElement('template');
    detachedElement.innerHTML = value;
    const sanitizedValue = DOMPurify.sanitize(detachedElement.content);
    // the this value represents the DOM element you are trying to set innerHTML on
    originalInnerHTMLSetter.call(this, sanitizedValue);
}


// the following was in our test file
const svg = document.createElementNS('http://www.w3.org/2000/svg', 'svg');
svg.innerHTML = '<circle id="test"></circle>';
assertThat(svg.innerHTML).equals('<circle id="test"></circle>'); // in reality it's " "
```

Debugging the problem it seemed that the namespace enforcement that was added checks for the parent. For SVG tags the only valid parent for the given string is an `svg` tag. 2.2.2 did not enforce this. However 2.2.6 does. I believe the above snippet is a valid scenario. To upgrade to latest DOMPurify (because we want to be up-to-date) we had to rewrite our test to include the `svg` tag in the snippet, thus becoming `<svg><circle id="test"></circle></svg>`; 

I am wondering if this was intended and what your advice would be moving forward.

**Comment by cure53** [comment]
This might have been a side-effect of the namespace checks in 2.2.6 indeed. And yes, we do enforce a valid parent node now, else we would have an XSS bypass.

**Comment by dgitin** [comment]
Thank you. I will close the issue since this seems like a permanent behavior that was intended.

**Comment by cure53** [comment]
Aye, thx!
