### ISSUE TITLE
Regression: not working on Safari 9 anymore

### ISSUE THREAD

**Issue by jlowcs** [cure53/DOMPurify#523]
### Bug

On Safari 9 (and older), `Object.getOwnPropertyDescriptor(Element.prototype, 'parentNode')` returns `undefined`, even though `'parentNode' in Element.prototype` returns `true`.

Since dompurify uses `Object.getOwnPropertyDescriptor`, `lookupGetter(ElementPrototype, 'parentNode')` returns undefined, and `DOMPurify.isSupported` is therefore `false`.

**Comment by cure53** [comment]
Safari 9 is not supported any longer. 
A new release will soon offer better handling of this circumstance, commits are already on main.

**Comment by cure53** [comment]
As a matter of fact, now is a good time to do that :)

**Comment by jlowcs** [comment]
Oh, I didn't see https://github.com/cure53/DOMPurify/issues/516, sorry.

Thank you for the response though!

**Comment by cure53** [comment]
Actually my bad, we should have released after that change :) Sorry.
