### ISSUE TITLE
Closure Compiler issues warnings for version 2.2.7

### ISSUE THREAD

**Issue by bmt-systems** [cure53/DOMPurify#525]
The Google Closure Compiler issues warnings when compiling the source code to version 2.2.7. This can be verified by going to the public [Closure Compiler Service](https://closure-compiler.appspot.com/home) and compiling the code using the default Simple optimization setting.

The warnings issued are:

> JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 933 character 63
>       if (ALLOW_DATA_ATTR && regExpTest(DATA_ATTR$$1, lcName)) ; else if (ALL...
>                                                                ^
> JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 933 character 127
> ...&& regExpTest(ARIA_ATTR$$1, lcName)) ; else if (!ALLOWED_ATTR[lcName] || F...
>                                         ^
> JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 937 character 46
>       } else if (URI_SAFE_ATTRIBUTES[lcName]) ; else if (regExpTest(IS_ALLOWE...
>                                               ^
> JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 937 character 134
> ...ace(value, ATTR_WHITESPACE$$1, ''))) ; else if ((lcName === 'src' || lcNam...
>                                         ^
> JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 937 character 298
> ...ta:') === 0 && DATA_URI_TAGS[lcTag]) ; else if (ALLOW_UNKNOWN_PROTOCOLS &&...
>                                         ^
> JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 937 character 417
> ...1, stringReplace(value, ATTR_WHITESPACE$$1, ''))) ; else if (!value) ; else {
>                                                      ^
> JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 937 character 436
> ...1, stringReplace(value, ATTR_WHITESPACE$$1, ''))) ; else if (!value) ; else {
>                                                                         ^
> JSC_SUSPICIOUS_SEMICOLON: If this if/for/while really shouldn't have a body, use {} at line 1139 character 20
>       if (IN_PLACE) ; else if (dirty instanceof Node) {
>                     ^

If the Advanced optimization setting is chosen (which performs a more rigorous analysis of the JavaScript), more warnings are issued, but those caught during Simple optimization would be an initial must-do. (This Compiler provides a great punch list of potential issues to research and fix in JavaScript code.)

**Comment by cure53** [comment]
Hmmm, not sure we we would care what the Google Closure Compiler says :) 

We have our own linter and are happy with it.
Do you see any compelling reason why we should change our code to satisfy a random 3rd party tool?

**Comment by cure53** [comment]
Upon looking into this warning a bit further, it became clear that this is a non-issue.
