### ISSUE TITLE
DOMPurify.sanitize is not a function

### ISSUE THREAD

**Issue by akashgp09** [cure53/DOMPurify#526]
### Background & Context

I am using **DOMPurify** in my react App

### Bug
**DOMPurify.sanitize is not a function**

#### Input
```
import DOMPurify from "dompurify";

const dirty = `I love to do evil <img src="http://unsplash.it/100/100?random" onload="alert('you got hacked');" />`;

const App = () => (
  <div
    dangerouslySetInnerHTML={{
      __html: DOMPurify.sanitize(dirty)
    }}
  />
);
```
#### Given output

**DOMpurify.sanitize is not a function** 

#### Expected output

Should execute well

**Comment by cure53** [comment]
Not our bug, me thinks.

**Comment by binyamin** [comment]
@cure53 same problem here. Do you have any idea who's bug it _is_?

**Comment by binyamin** [comment]
Ah, maybe it needs jsdom? The readme doesn't seem to say that in node.js, you need jsdom to work

**Comment by Fensterbank** [comment]
I had this issue with NextJS on server-side rendering.
To make this work server-side and client-side the same way, you can use the wrapper https://github.com/kkomelin/isomorphic-dompurify

**Comment by duoluodexiaoxiaoyuan** [comment]
> ### Background & Context
> I am using **DOMPurify** in my react App
> 
> ### Bug
> **DOMPurify.sanitize is not a function**
> 
> #### Input
> ```
> import DOMPurify from "dompurify";
> 
> const dirty = `I love to do evil <img src="http://unsplash.it/100/100?random" onload="alert('you got hacked');" />`;
> 
> const App = () => (
>   <div
>     dangerouslySetInnerHTML={{
>       __html: DOMPurify.sanitize(dirty)
>     }}
>   />
> );
> ```
> 
> #### Given output
> **DOMpurify.sanitize is not a function**
> 
> #### Expected output
> Should execute well

i  find a question , this is a demo https://codesandbox.io/s/ei98d?file=/src/App.tsx

**Comment by s1nistr4** [comment]
Eh, if the dev is gonna not fix the bug and also be rude when people bring it up, I recommend people check out sanitize-html instead. Easy fix, works great.

**Comment by bonface221** [comment]
🤔

**Comment by mtoha2013** [comment]
I have similar issue, how to achieve this at pure javascript no framework like react?
I run it on .NET MVC app

**Comment by Bunpasi** [comment]
I had the same problem. Check `DOMPurify.isSupported`. For me it wasn't supported, because my application didn't have a global `window` object.

**Comment by Ricker2020** [comment]
there are two really simple solutions, first for the client side we just use the "use client" and on the server side touch jsdom Library to create a window for more information read -> https://sentry.io/answers/using-dangerouslysetinnerhtml-in-next-js/

**Comment by jotapepinheiro** [comment]
"use client"

**Comment by dragonscraper** [comment]
just use https://www.npmjs.com/package/isomorphic-dompurify and save yourself all the headache

**Comment by Bunpasi** [comment]
Now I use 'isomorphic-dompurify'. It's just a small wrapper, but it initializes the DOM which DOMPurify needs in order to work on the server.

**Comment by dr-iroh** [comment]
I have same issue on Node v24.21.0 DOMPurify.isSupported is false
