### ISSUE TITLE
Sanitizing conditional comments

### ISSUE THREAD

**Issue by ahmedengu** [cure53/DOMPurify#528]
Hello 👋,

This issue proposes a bug that happens with conditional comments.

### Background & Context
When I use `'#comment'` to keep comments from getting removed, it skips sanitizing the comment content even when the comment is a conditional comment. which leads to XSS on browsers that use that conditional!

### Bug
The content of conditional comments should be sanitized.

#### Input
```
const createDOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');

const DOMPurify = createDOMPurify(new JSDOM('').window);

const clean = DOMPurify.sanitize(
  `<div>
     div1
     <!--[if IE]>comment1
       <script>alert('XSS')</script>
     <![endif]-->
  </div>`,
  {
    ADD_TAGS: ['#comment'],
    WHOLE_DOCUMENT: true,
    IN_PLACE: true,
    FORCE_BODY: true,
  }
);

console.log(clean);
```
#### Given output
```
<html><body><div>
     div1
     <!--[if IE]>comment1
       <script>alert('XSS')</script>
     <![endif]-->
  </div></body></html>
```

#### Expected output
```
<html><body><div>
     div1
     <!--[if IE]>comment1
     <![endif]-->
  </div></body></html>
```

**Comment by cure53** [comment]
Heh, yeah, that is an interesting edge-case :)

**Comment by cure53** [comment]
This only happens when you sanitize on the server, store the sanitized code and then MSIE is used to render that sanitized code, correct?

**Comment by cure53** [comment]
if so, we are lucky, because we do not support MSIE9 or older :stuck_out_tongue: 

But, you can make use of a hook to get rid of those quite easily if you need to.

**Comment by ahmedengu** [comment]
Thanks for getting back to me.

Yes, correct it happens when I sanitize on the server then render in an old browser.
Cool :), well at least this issue may help people encountering something similar.

Hooks seemed a bit too much 😅, I went with replacing the conditional comments with a custom tag, then replace the tag with the conditional after sanitization, any reason not to proceed with this approach?

input:
```
<div>
     div1
     <!--[if IE]>comment1
       <script>alert('XSS')</script>
     <![endif]-->
</div>
```
replace:
```
<div>
     div1
     <custom data="IE">comment1
       <script>alert('XSS')</script>
     </custom>
</div>
```
sanatized:
```
<div>
     div1
     <custom data="IE">comment1
     </custom>
</div>
```
last replace:
```
<div>
     div1
     <!--[if IE]>comment1
     <![endif]-->
</div>
```

**Comment by cure53** [comment]
This does look solid, me thinks!

**Comment by ahmedengu** [comment]
Cool, thank you for your time 🙏 
I think we can close this issue now.
