### ISSUE TITLE
Attributes containing `/&gt;` are removed for some reason

### ISSUE THREAD

**Issue by thorn0** [cure53/DOMPurify#530]
### Background & Context

Happens since v2.1.0

#### Input

```html
<a data-foo="/&gt;"></a>
```

#### Given output

```html
<a></a>
```

#### Expected output

```html
<a data-foo="/&gt;"></a>
```

**Comment by thorn0** [comment]
Caused by this code:
```js
        /* Work around a security issue in jQuery 3.0 */
        if (regExpTest(/\/>/i, value)) {
          _removeAttribute(name, currentNode);
          continue;
        }
```
That's quite a harsh work-around. Isn't there a better way to solve this? Some kind of escaping probably?

For now, I'm doing this:
```js
	DOMPurify.addHook('uponSanitizeAttribute', (node, data) => {
		if (data.attrName === 'data-foo') {
			data.forceKeepAttr = true;
		}
	});
```

**Comment by cure53** [comment]
The folks over at jQuery rewrite HTML when using `.html()` in a way that causes XSS with sanitized markup. We would love to find a less aggressive approach  - but so far didn't manage to.

**Comment by thorn0** [comment]
Maybe escaping `/` as `&#47;` or `&sol;` would be enough to fool their regexes?

**Comment by cure53** [comment]
That might be, but we are careful with changing data - and usually prefer to just nuke an attribute or element if we have any doubts :) I think the hook you use is a good solution for now. If this becomes a more prominent issue, we'd consider looking into it again.
