### ISSUE TITLE
document.createNodeIterator() non-standard syntax cross iframe issue.

### ISSUE THREAD

**Issue by losewing** [cure53/DOMPurify#535]
> This issue proposes a bug that happens with chrome using iframe.

### Background & Context
Consider the cross-iframe usage,
```javascript
window.DOMPurify=window.top.DOMPurify(window);
```

### Bug
https://github.com/cure53/DOMPurify/blob/2.2.8/dist/purify.js#L776
createNodeIterator() using non-standard syntax causes root-window confusing in chrome.
window.top.Text and window.Text are different instances in chrome.
But in other browsers window.top.Text and window.Text are identical.

### Standard syntax
https://www.w3.org/TR/DOM-Level-2-Traversal-Range/traversal.html#Traversal-NodeIteratorFactory-createNodeIterator
The 3rd filter parameter in createNodeIterator(root,whatToShow,filter,boolean false)
 should be an object, or null to indicate no filter.

### Demo
Assume test_index.html, test_iframe.html, purify.js(v2.2.8) are in the same webroot folder.

#### purify.js (download from https://github.com/cure53/DOMPurify/blob/2.2.8/dist/purify.js)
Official release purify.js v2.2.8.

#### test_index.html
```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>test index</title>
<script src="purify.js"></script>
<script>
window.onload = function(event){
	document.getElementById("ifr1").src="test_iframe.html";
	var checkVal=(window.DOMPurify.sanitize("<div>test</div>", {RETURN_DOM_FRAGMENT: true}).textContent=="test");
	window.document.getElementById("output").innerHTML=checkVal;
};
</script>
</head>
<body>
<div>Note: All DOMPurify objects load from this window.top</div><br>
<div>window.DOMPurify.sanitize(&quot;&lt;div&gt;test&lt;/div&gt;&quot;,{RETURN_DOM_FRAGMENT:true}).textContent==&quot;test&quot;?</div>
<div id="output">
</div>
<iframe id="ifr1" name="ifr1" width="1024" height="200"></iframe>
</body>
</html>
```
#### test_iframe.html
```html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>test iframe</title>
<script>
window.onload = function(event){
	if(window!=window.top){
		var top_obj=null;
		try{top_obj=window.top.DOMPurify}catch(none){}
		if(top_obj!=null && typeof top_obj.sanitize=="function" ){//window.top.DOMPurify.sanitize=="function"
			try{window.DOMPurify=window.top.DOMPurify(window);}catch(none){}
			var checkVal=(window.DOMPurify.sanitize("<div>test</div>", {RETURN_DOM_FRAGMENT: true}).textContent=="test");
			window.document.getElementById("output2").innerHTML=checkVal;
		}
	}
};
</script>
</head>
<body>
<div>window.DOMPurify.sanitize(&quot;&lt;div&gt;test&lt;/div&gt;&quot;,{RETURN_DOM_FRAGMENT:true}).textContent==&quot;test&quot;?</div>
<div id="output2">
</div>
</body>
</html>
```

#### Given output
Output in id="output2" by chrome be false:

```text
window.DOMPurify.sanitize("<div>test</div>",{RETURN_DOM_FRAGMENT:true}).textContent=="test"?
false
```

#### Expected output
Output in id="output2" by other browser be true:

```text
window.DOMPurify.sanitize("<div>test</div>",{RETURN_DOM_FRAGMENT:true}).textContent=="test"?
true
```

### Feature
createNodeIterator standard syntax example:
https://developer.mozilla.org/en-US/docs/Web/API/NodeFilter#example

If we try to change line 775.( https://github.com/cure53/DOMPurify/blob/2.2.8/dist/purify.js#L775 )

#### original line 775, filter=function () {return NodeFilter.FILTER_ACCEPT;}
```javascript
    var _createIterator = function _createIterator(root) {
      return createNodeIterator.call(root.ownerDocument || root, root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_COMMENT | NodeFilter.SHOW_TEXT, function () {
        return NodeFilter.FILTER_ACCEPT;
      }, false);
    };
```

#### right syntax typeof filter==="object",chrome output as Expected.
```javascript
    var filter = new window.Object();
    filter.acceptNode = function (node) {
        return NodeFilter.FILTER_ACCEPT;
    };
    var _createIterator = function _createIterator(root) {
      return createNodeIterator.call(root.ownerDocument || root, root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_COMMENT | NodeFilter.SHOW_TEXT, filter, false);
    };
```
However, the "right" syntax will cause IE error. IE does Not support Standard syntax.

## Shall we set the 3rd parameter in createNodeIterator to just null? To indicate no filter.
```javascript
    var _createIterator = function _createIterator(root) {
      return createNodeIterator.call(root.ownerDocument || root, root, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_COMMENT | NodeFilter.SHOW_TEXT, null, false);
    };
```
If we set the filter parameter to null, chrome and other browsers seem to work fine.

**Comment by cure53** [comment]
So, the idea is to just set filter to null to yield correct results x-frame and avoid errors in MSIE?

**Comment by cure53** [comment]
```javascript
  /**
   * _createIterator
   *
   * @param  {Document} root document/fragment to create iterator for
   * @return {Iterator} iterator instance
   */
  const _createIterator = function (root) {
    return createNodeIterator.call(
      root.ownerDocument || root,
      root,
      NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_COMMENT | NodeFilter.SHOW_TEXT,
      null,
      false
    );
  };
```

Correct?

**Comment by losewing** [comment]
Correct.

**Comment by cure53** [comment]
Let's see what the tests will say :)

**Comment by cure53** [comment]
Tests are happy, does it work as expected for you as well now? @losewing

**Comment by losewing** [comment]
It works as expected. Thank you very much.
