### ISSUE TITLE
[Question] Sanitize just a URL

### ISSUE THREAD

**Issue by GrantGryczan** [cure53/DOMPurify#536]
I am using DOMPurify in a React web app. Currently I am running a React HTML parser (`html-react-parser`) on the sanitized output so that I can replace certain custom HTML elements with custom React components, which is absolutely necessary. One such component is a `Link` component, which replaces an element like this (no, there are no typos here):

```html
<mspfa-bb data-name="url" data-attributes="=javascript:alert('hello');">click me</mspfa-bb>
```

with a component like this:

```jsx
<Link href="javascript:alert('hello');">click me</Link>
```

I'm sure you can see the issue. Since React components are evaluated _after_ the HTML is sanitized, and the `mspfa-bb` tag I exemplified still has a JS URL despite being post-sanitization, the JS URL is never sanitized. And I assume sanitization isn't as simple as `href.startsWith('javascript:')`, or else I could easily handle this from within the `Link` component.

React is planning to forcibly block JS URLs natively, but it's still in process of being deprecated, so it still only logs an error without changing the functionality:

![image](https://user-images.githubusercontent.com/14056899/117093226-54ef4580-ad2e-11eb-96cd-f999dfdc012f.png)

Does your library have a means of sanitizing just a URL string? For example, `DOMPurify.urlIsClean(href)` (which would output a boolean). If not, is this something you would be interested in? Otherwise, what would you suggest I do?

(Note that inputting `a` tags to be sanitized instead of `mspfa-bb` is not an option due to both efficiency and readability, because I have a lot of other logic using the `mspfa-bb` tag, not just links. Also note that I would strongly prefer our users to be allowed to use unknown protocols in their links.)

**Comment by securityMB** [comment]
@GrantGryczan Actually verifying URL is just a regex (https://github.com/cure53/DOMPurify/blob/main/src/regexp.js#L8):
```javascript
export const IS_ALLOWED_URI = seal(
  /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i // eslint-disable-line no-useless-escape
);
```

You can also add a hook to treat data-attributes in a special way.

**Comment by cure53** [comment]
Heya :) I agree with @securitum-mb - this is best being done directly or via hook. Might not make sense to add that as a core feature to DOMPurify.

**Comment by GrantGryczan** [comment]
That's true, though this doesn't solve my problem, because, as I said (in the last sentence of my post):

> Also note that I would strongly prefer our users to be allowed to use unknown protocols in their links.

**Comment by cure53** [comment]
Won't this do the trick for you?

```javascript
// allow external protocol handlers in URL attributes (default is false, be careful, XSS risk)
// by default only http, https, ftp, ftps, tel, mailto, callto, cid and xmpp are allowed.
var clean = DOMPurify.sanitize(dirty, {ALLOW_UNKNOWN_PROTOCOLS: true});
```

**Comment by cure53** [comment]
Sorry, I misread your response. What we do here is use the following code:

```javascript
ALLOW_UNKNOWN_PROTOCOLS &&
      !regExpTest(IS_SCRIPT_OR_DATA, stringReplace(value, ATTR_WHITESPACE, ''))
    ) {
```

Which basically uses this block-list regex:

```javascript
export const IS_SCRIPT_OR_DATA = seal(/^(?:\w+script|data):/i);
```

Also, have tried to look at `IN_PLACE` editing as an alternative maybe?

**Comment by GrantGryczan** [comment]
Alright, thanks, I'll look into these options.

**Comment by meeque** [comment]
Just fyi, I've had a similar discussion in #513 a couple of months earlier.

**Comment by isocroft** [comment]
I agree with @cure53 . It needs to be a separate project.

This is a wonderful discussion on the topic @meeque . I am very elated that this discussion has come up. May i present my stand-alone solution. which compliments **DOMPurify**. 

So, @meeque, I present **URISanity**.

I built this library specially for this purpose. Like **DOMPurify**, It works both on NodeJS (server) as well as the browser.Also, like **DOMPurify**, it has very simple APIs like `URISanity.vet()` - which sanitizes a URI and returns `about:blank` if the URI isn't well constructed or is completely unsafe. This library is in its' early days so i am using this opportunity to call on contributors here who are interested in building this to join me review the current codebase and (if possible) make PRs to make it better than it is now.

https://www.npmjs.com/package/urisanity

```javascript
 const sanitizedUrl = URISanity.vet("icloud-sharing://www.icloud.com/photos/01eFfrthOPvnfZqlKMn")
 console.log(sanitizedUr) // 'about:blank'
```

**Comment by ezze** [comment]
Maybe I'm out of context but the following works for me:

```typescript
import { isValidAttribute } from 'dompurify';

const url = 'javascript:alert('hello');';
console.log(isValidAttribute('a', 'href', url)); // false
```
