### ISSUE TITLE
[Question] transform tags

### ISSUE THREAD

**Issue by ArvindhMangoleap** [cure53/DOMPurify#542]
Is there way to transform tags ?
For eg. I need to transform all html, body tags to div tags
`<html><head></head><body><p>HI</p></body></html>`
to 
`<div><head></head><div><p>HI</p></div></div>`

**Comment by cure53** [comment]
Heya, yep - that is possible with a hook, check this :)

https://github.com/cure53/DOMPurify/issues/417

Does this already help?

**Comment by ArvindhMangoleap** [comment]
Hi @cure53  I am trying to implement this on the server side. How to implement #417 on server side?

**Comment by cure53** [comment]
I would assume by making use of the API jsdom offers. Not sure what you can use in your deployment scenario.
