### ISSUE TITLE
DOMPurify changes order of HTML tag's markup

### ISSUE THREAD

**Issue by phoshenwen** [cure53/DOMPurify#543]
### Background & Context

The backend application is Wordpress. Content is added to any given page/post/you name it. 

### Bug

When sanitizing the HTML, specifically in this instance an IMG tag, DOMPurify changes the order of the attributes. What was `<img alt="" src="">` before, results in `<img src="" alt="">` after running DOMPurify over it.
This is the error message thrown in Chrome's dev console as a result:

`Warning: Prop `dangerouslySetInnerHTML` did not match. Server: "\n<div class=\"wp-block-columns\">\n<div class=\"wp-block-column\">\n<figure class=\"wp-block-image size-large\"><img src=\"https://via.placeholder.com/600x450\" alt=\"\"></figure>\n</div>\n\n\n\n<div class=\"wp-block-column\">\n<h2>Hi there</h2>\n\n\n\n<p>Little test. Lorem Ipsum</p>\n</div>\n</div>\n" Client: "\n<div class=\"wp-block-columns\">\n<div class=\"wp-block-column\">\n<figure class=\"wp-block-image size-large\"><img alt=\"\" src=\"https://via.placeholder.com/600x450\"></figure>\n</div>\n\n\n\n<div class=\"wp-block-column\">\n<h2>Hi there</h2>\n\n\n\n<p>Little test. Lorem Ipsum</p>\n</div>\n</div>\n"`

#### Input

```
import DOMPurify from 'dompurify';

DOMPurify.sanitize(content, {
    USE_PROFILES: { html: true, svg: true },
    FORBID_TAGS: ['script'],
})
```

Deps:

```
  "dependencies": {
    "@apollo/client": "^3.3.19",
    "@wordpress/base-styles": "^3.5.0",
    "@wordpress/block-library": "^3.2.1",
    "dompurify": "^2.2.8",
    "graphql": "^15.5.0",
    "next": "^10.2.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
  },
```

**Comment by cure53** [comment]
It's actually the browser or the browser-like environment DOMPurify is using, so not much we can do here.
