### ISSUE TITLE
ES6 package that uses shallow dev dependencies only

### ISSUE THREAD

**Issue by 4086606** [cure53/DOMPurify#545]
> This issue proposes the creation of a TS/JS package that uses shallow dev dependencies only.

### Background & Context

DOMPurify is great, but I want to use this NPM module without the clusterfuck that is the JS library landscape. This includes JQuery, Babel, and literally anything that doesn't provide core functionality inside the DOMPurify code.

### Feature

Publish a no frills package that works in an ES6-ready Node environment. This will allow TS and Node developers to use the script [without ~1000 dev dependencies](https://npmgraph.js.org/?q=dompurify@2.2.9). One approach is to create a `dompurify-ts` module that uses the `tsc` compiler instead of Babel.

**Comment by tdeekens** [comment]
Up for a contribution? ;-). We would certainly value it. It's hard to fullfil old and new distribution paths without disappointing or breaking up with anybody.

**Comment by ydaniv** [comment]
@4086606 what dependencies are you talking about? DOMPurify has 0 deps. Everything you mentioned are devDeps. You do realize there's a difference between the two, right?

**Comment by 4086606** [comment]
Yes but I didn't mention that in the issue text

**Comment by 4086606** [comment]
I tried `mkdir test; cd test; npm init; npm install dompurify; cd node_modules; tree` and yes, installation of this package doesn't need 1000 dependencies or a single dependency. Good stuff. Close this issue?

**Comment by ydaniv** [comment]
👍 😺 🥂 🎉
