### ISSUE TITLE
Update version of source files

### ISSUE THREAD

**Issue by Mathias89** [cure53/DOMPurify#547]
### Background & Context

The current released version should contain the current version as info within source files.

The issue was already mentioned in [#483 ](https://github.com/cure53/DOMPurify/pull/483).

With this issue version 2.2.2 was added and since than not altered.

The reasons remains the same:

- faster check of used version
- compare necessity of updating

#### Given output

`/*! @license DOMPurify | (c) Cure53 and other contributors | Released under the Apache license 2.0 and Mozilla Public License 2.0 | github.com/cure53/DOMPurify/blob/2.2.2/LICENSE */`

#### Expected output

Something like:
`/*! @license DOMPurify 2.2.9 | (c) Cure53 and other contributors | Released under the Apache license 2.0 and Mozilla Public License 2.0 | github.com/cure53/DOMPurify/blob/LICENSE */`

**Comment by cure53** [comment]
No issues from our end, wanna spin up a PR? :)

**Comment by cure53** [comment]
This was fixed via https://github.com/cure53/DOMPurify/commit/16d8eed5f339cca99ae337a1e0aaa80fee998431
