### ISSUE TITLE
Allow forbidding specific data-* attributes

### ISSUE THREAD

**Issue by djadmin** [cure53/DOMPurify#548]
This is to report an issue with sanitizing `data-*` attributes. The current implementation does not allow forbidding specific data attributes.

### Background & Context

There have been instances when it's needed to forbid only a few `data-*` attributes. This is to prevent XSS triggered by script gadgets or features specific to certain frameworks.

With current implementation, it's not possible to do so due to the line:

https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L917

Passing specific `data-*` attribute names to `FORBID_ATTR` would never reach https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L922 because `ALLOW_DATA_ATTR` is set to true by default.

Setting `ALLOW_DATA_ATTR` to false would disable all `data-*` and it might not be possible to provide a list of attributes to be whitelisted.

#### Input

```js
DOMPurify.sanitize(`<a data-url="https://evil.com">test</a>`, {
  FORBID_ATTR: ['data-url']
});
```
#### Given output

```html
<a data-url="https://evil.com">test</a> 
```

#### Expected output

```html
<a>test</a>
```

Allowing this can be useful when it's not possible to set `ALLOW_DATA_ATTR` as `false` and forbidding certain attributes could prevent XSS vulnerabilities.

**Comment by cure53** [comment]
Oh, good point, we will have a look soon!

**Comment by cure53** [comment]
Okay, this should be fixed on main, wanna give it  quick try?

**Comment by djadmin** [comment]
Thank you so much for the quick turnaround. It's fixed 👍
