### ISSUE TITLE
filter the src containing blob

### ISSUE THREAD

**Issue by hejh1995** [cure53/DOMPurify#549]
### issue：
Why filter out this src containing blob ？
### input:
 `
DOMPurify.sanitize('<img src="blob:https://*********"/>');
`
### Given output:
`<img />`
### Expected output
`<img src="blob:https://*********"/>`

**Comment by cure53** [comment]
You can allow that via config, see `ALLOW_UNKNOWN_PROTOCLS`

```javascript
DOMPurify.sanitize('<img src="blob:https://*********"/>', {ALLOW_UNKNOWN_PROTOCOLS: true});
```

**Comment by hejh1995** [comment]
Is there any security risk for blobs?

**Comment by cure53** [comment]
Nothing generic we are currently aware of, but not 100% sure :D

**Comment by rkok** [comment]
Just chiming in with a workaround that seems safer, adapted from https://github.com/manusa/isotope-mail/blob/3543ccbca6fdf9687e2309902e5ea7e7ae52f323/client/src/services/sanitize.js#L46

```typescript
function isImageNode(node: Element): node is HTMLImageElement {
  return node.nodeName === 'IMG';
}

const purifier = DOMPurify();

purifier.addHook('uponSanitizeAttribute', (node, hookEvent) => {
  if (isImageNode(node) && hookEvent.attrName === 'src' && hookEvent.attrValue.indexOf('blob:') === 0) {
    node.src = `${node.src.substring(5)}#allowed-blob`;
    hookEvent.attrValue = node.src;
  }
});

purifier.addHook('afterSanitizeAttributes', node => {
  if (isImageNode(node) && node.src && node.src.indexOf('#allowed-blob') > -1) {
    node.src = `blob:${node.src.replace('#allowed-blob', '')}`;
  }
});
```

**Comment by juliendorra** [comment]
I'm using:
 
```
{
ALLOWED_URI_REGEXP: /^(?:(?:ftp|http|https|mailto|tel|callto|sms|cid|xmpp|blob):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i
        };
```
which allows all the default URI protocols and add the blob protocol

Maybe less safe than the hook that, if not mistaken, allows blob only in IMG tags
