### ISSUE TITLE
Sanitizing SVG removes <use> tag elements

### ISSUE THREAD

**Issue by Gringox** [cure53/DOMPurify#550]
### Question

While working with SVGs I notice that DOMPurify removes any `<use>` tags.

I tried to look online for any vulnerabilities related to it but I didn't find any.

I'm wondering if you guys have more information about the risks related to `<use>`?

### Small replication

To replicate this small HTML would do it:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="text/javascript" src="purify.js"></script>
  <script>
    document.addEventListener('DOMContentLoaded', () => {

      const svg = `
        <svg viewBox="0 0 30 10" xmlns="http://www.w3.org/2000/svg">
          <circle id="myCircle" cx="5" cy="5" r="4" stroke="blue"/>
          <use href="#myCircle" x="10" fill="blue"/>
          <use href="#myCircle" x="20" fill="white"/>
        </svg>
      `;

      const sanitizeSvg = DOMPurify.sanitize(svg);

      document.getElementById('svg').innerHTML = svg;

      document.getElementById('sanitizeSvg').innerHTML = sanitizeSvg;
    });
  </script>
</head>
<body>
  <!-- NORMAL SVG HERE -->
  <div id="svg"></div>

  <!-- SANITIZE SVG HERE -->
  <div id="sanitizeSvg"></div>
</body>
</html>

```

It will render the following:

![Screen Shot 2021-07-14 at 4 55 40 p m](https://user-images.githubusercontent.com/6384861/125653336-c311c55b-1dbe-4807-a7b1-d4b6e85f4082.png)

Note that the last line of circles should have been repeated two more times but it was not because the `<use>` tag was removed.

**Comment by cure53** [comment]
The `<use>` element indeed enables XSS, so we disable it by default:

https://insert-script.blogspot.com/2014/02/svg-fun-time-firefox-svg-vector.html
