### ISSUE TITLE
Use RegExp constructor in DOMPurify configs

### ISSUE THREAD

**Issue by waveshell** [cure53/DOMPurify#551]
> This issue proposes a [bug, feature] which...

Not sure whether this qualifies as a bug or feature...

### Background & Context

It seems DOMPurify only accepts regex literals in the `ALLOWED_URI_REGEXP` config. 
e.g.

> `var clean = DOMPurify.sanitize(dirty, {ALLOWED_URI_REGEXP: /^(?:(?:(?:f|ht)tps?|mailto|tel|callto|cid|xmpp|xxx):|[^a-z]|[a-z+.\-]+(?:[^a-z+.\-:]|$))/i;});`

It would be greatly beneficial to be able to use RegExp constructor, as values may need to be generated programmatically.
like so:
```
const protocols = ['http', 'ftp', 'rtp'].join('|');
const rx = new RegExp(`^(${protocols}):`,'i');
const clean = DOMPurify.sanitize(dirty, {ALLOWED_URI_REGEXP: rx}
```

#### Input

Some HTML which is thrown at DOMPurify.

#### Given output

The output given by DOMPurify.

#### Expected output

The expected output.

### Feature

Briefly outline the proposed feature, its value and a potentially proposed implementation from a high level.

**Comment by cure53** [comment]
I think this might make sense indeed. Wanna spin up a PR? :)

**Comment by mikael-wejsflog1** [comment]
Sure, I'll give it a stab 😊
