### ISSUE TITLE
Possible to lets some XSS slip through

### ISSUE THREAD

**Issue by JamesPattisonRedDeer** [cure53/DOMPurify#552]
> This issue proposes a [bug, feature] which...

### Background & Context

If the xss string is not quotes in an img src tag, then the script is returned, quoted.
currently I'm getting round this by running the purification, then running the output through the following logic, and then running the purification on that result:

const replaceEscaped = (input: string): string => {
    //Make the quotes consistent, like the library expects (???)
    //.split.join is effectively replaceAll, but that feature's not available to us
    return input.replace('\\"', '"').split('"').join("'");
};

return DOMPurify.sanitize(
        replaceEscaped(
            DOMPurify.sanitize(value, {
                ...My options here
            })
        )
    );

#### Input

<IMG SRC=javascript:alert('XSS');.png>

#### Given output

<IMG SRC=\"javascript:alert('XSS');.png\">

#### Expected output

<img>

### Feature

It's not a feature, it's a bug fix I highly recommend as currently XSS can make it's way through this package

**Comment by cure53** [comment]
No XSS here, closing this as invalid
