### ISSUE TITLE
[bug] DOMPurify.sanitize() breaks tables

### ISSUE THREAD

**Issue by CorruptComputer** [cure53/DOMPurify#553]
### Background & Context

Using version DOMPurify version 2.2.2.
DOMPurify.sanitize() function breaks tables with the following code:

```javascript
function newTableRow(tableId) {
    let $clonedRow = $("#" + tableId + " tbody tr:first").clone();
    let clonedHtml = $clonedRow.get(0).outerHTML;
        clonedHtml = DOMPurify.sanitize(clonedHtml);

    $clonedRow = $(clonedHtml);
    $("#" + tableId + " tbody").append($clonedRow);

    return $clonedRow;
}
```

Tried the following as well, but no luck: 

```javascript
function newTableRow(tableId) {
    let $clonedRow = $("#" + tableId + " tbody tr:first").clone();
    let clonedHtml = $clonedRow.get(0).outerHTML;
        clonedHtml = DOMPurify.sanitize(clonedHtml, { ADD_TAGS: ["tr", "td"] });

    $clonedRow = $(clonedHtml);
    $("#" + tableId + " tbody").append($clonedRow);

    return $clonedRow;
}
```

#### Input

```html
<tr>
    <td><a href="test.html">Test</a></td>
    <td><script>alert("This should be removed!");</script></td>    
</tr>
```

#### Given output

```html
<a href="test.html">Test</a>
```

#### Expected output

```html
<tr>
    <td><a href="test.html">Test</a></td>
    <td></td>    
</tr>
```

**Comment by cure53** [comment]
You need to sanitize only the content, not the incomplete table structure. The problem is that the browser removes orphaned `<tr>` and `<td>` elements - and it seems that what you sanitize doesn't have any `<table>` around it.

You can fix this by wrapping the data in a `<table>` or by simply sanitizing the content of the `<td>`.

**Comment by CorruptComputer** [comment]
Ah I see, so doing something like the following should work around this issue then?

```javascript
function newTableRow(tableId) {
    let $clonedRow = $("#" + tableId + " tbody tr:first").clone();
    let clonedHtml = $clonedRow.get(0).outerHTML;
        clonedHtml = "<table>" + clonedHtml + "</table>";
        clonedHtml = DOMPurify.sanitize(clonedHtml);
        clonedHtml = clonedHtml.replace("<table>", "").replace("</table>", "");
        
    $clonedRow = $(clonedHtml);
    $("#" + tableId + " tbody").append($clonedRow);

    return $clonedRow;
}
```

**Comment by cure53** [comment]
That is correct. It might feel a bit counter-intuitive at first but that is one way to go.

The reason why this is as it is: As mentioned, the browser removes orphaned table rows and table data, and we don't wanna "fix" that by implementing our own crazy parsing logic - as jQuery for example does. That only leads to blat and XSS :D

**Comment by CorruptComputer** [comment]
Fair enough, thanks for your help!

**Comment by cure53** [comment]
Yw :)
