### ISSUE TITLE
Memory consumption for large files

### ISSUE THREAD

**Issue by artem-galas** [cure53/DOMPurify#555]
> This issue a [Question] which...

### Background & Context
I investigate memory usage for DOMPurify and realized that it might be not so efficient for large HTML files (~400kb) I consumed about 500MB for such files.

**Use case:** 
Have an API endpoint that got HTML content and returns a Sanitised version. That api has 1mb limit, so any user could send real big HTML data. And if the server doesn't have enough memory allocated it will throw JS memory heap error.

### Question
I just wondering if I'm doing sanitization most efficiently, maybe I should consider adding some other properties/options? 

#### Input

Here is sandbox application where you could test memory usage 
https://github.com/artem-galas/mini-dom-sanitize

#### Output

Seems sanitisation take a lot of memory for files ~400kb

#### Expected output

Would expect that sanitization requires less memory if possible. Or just a suggestion what I could improve

**Comment by cure53** [comment]
Heya,

hmmm, did you run a profile to see which parts consume lots of RAM? My assumption is that you run DOMPurify on the server (so on top of jsdom) correct? Can we be sure it is our library that causes the intense memory use and not jsdom itself?

Also, it seems I cannot check the URL you shared:
https://github.com/artem-galas/mini-dom-sanitize < 404

**Comment by artem-galas** [comment]
> My assumption is that you run DOMPurify on the server (so on top of jsdom) correct?

Yes correct, will try to run profiler in sandbox project.

Oh, sorry I anciently made repo private 🔒 , should be fine now.

**Comment by cure53** [comment]
Oh, Officer HTML - that's why the file-size is so large :D

The code looks okay to me, do you see any way to run a profiler and check what method is expensive?

**Comment by artem-galas** [comment]
Oh yes, I could say this is an "imaginary" situation, but still. The HTML is contain really huge Email, and looks like so (this is not full view) [full-page-view](https://user-images.githubusercontent.com/6387897/128514452-f98c8b31-7da6-4ba0-9b58-d9b5751d8e3e.png)

About profiler I'm not entirely sure how to understand it 😅  I would be appreciate if you could double check it.

Here is couple of screenshots from profiler:

![Screenshot 2021-08-06 at 16 15 03](https://user-images.githubusercontent.com/6387897/128515765-0f61aa90-f226-46ab-9307-a3f56b7d9cce.png)

![Screenshot 2021-08-06 at 16 17 03](https://user-images.githubusercontent.com/6387897/128516116-2a3c6965-9853-4b03-b242-8433cbd214a0.png)

**Comment by cure53** [comment]
So, we would like to know where the expensive methods are sitting, is it our code or is it jsdom. Without knowing that, there is nothing we can actually do.

**Comment by artem-galas** [comment]
Thanks for your help!

I double check the profiler, and seems all those operation from screenshot above (`exports.clone node`) are coming from `jsdom`, as well as `shadowIncludingInclusiveDescendantsIterator` method which was called several times.

I suspect that the issue in jsdom, as it goes to every node and clone it, as I could understand 🤔 

Do you know any alternatives which I could try for sake of interest?

**Comment by cure53** [comment]
Then I _guess_ at least it is their code causing the high RAM usage, but maybe I am wrong. In terms of alternatives, hard to say. Depends on the project's nature and how it will scale.

**Comment by artem-galas** [comment]
Thank you so much for the help, much appreciate it! I'll close the issue for now
