### ISSUE TITLE
Add support for removing elements but keeping their children

### ISSUE THREAD

**Issue by 0xedward** [cure53/DOMPurify#556]
### Background & Context

Hi! @mozfreddyb and I are working on a polyfill for the [HTML Sanitizer API](https://wicg.github.io/sanitizer-api/). 

Currently, the polyfill shims DOMPurify by taking a [HTML Sanitizer Configuration object](https://wicg.github.io/sanitizer-api/#configuration-object) and converting it to a [configuration DOMPurify accepts](https://github.com/cure53/DOMPurify/blob/HEAD/dist/purify.js#L342-L437), then any `sanitize` calls to the polyfill are pass along to DOMPurify.

### Feature

While working on converting a HTML Sanitizer configuration to DOMPurify configuration, we haven't found a way to support [`blockElements`](https://wicg.github.io/sanitizer-api/#dom-sanitizerconfig-blockelements). We thought that maybe using `FORBID_TAGS` with `KEEP_CONTENT` would get us the functionality we are looking for, but the limitation with that approach would mean we can't set `FORBID_TAGS` without `KEEP_CONTENT` at the same time. So our HTML Sanitizer configuration would either support `blockElements` or [`dropElements`](https://wicg.github.io/sanitizer-api/#dom-sanitizerconfig-dropelements), but not both at the same time.

Is there a configuration option we missed that we could use to achieve desired functionality of `blockElements`? Thanks! :)

**Comment by cure53** [comment]
Heya :) Indeed, I don't think we can do that via config options. But we can do that via hook, would hat be viable for the polyfill?

**Comment by 0xedward** [comment]
Thanks for the quick response! :) I'll look into hooks and give it a go. The `*SanitizeElements` hooks looks promising

If we went down the route of adding something like `BLOCK_ELEMENTS` as a configuration option, would that PR be something that the team would be open to reviewing/accepting?

**Comment by cure53** [comment]
Exactly, this one should be the one you need as it fires right before the `KEEP_CONTENT` checks happen. You could check the element and the config and then decide whether to remove child elements based on your config or let the library decide.

**Comment by cure53** [comment]
I had a closer look @0xedward - it seems that this is indeed tough to do cleanly with a hook. I think it might be better to expose the `FORBID_CONTENTS` array to be extendable. 

Assuming we did that, would the below match what you expect in terms of sanitation result?

```javascript
var clean = DOMPurify.sanitize(`
    <div><b>preserve me</b></div>
    <p><b>no not preserve me</b></p>
`, {FORBID_CONTENTS: ['p'], FORBID_TAGS: ['div', 'p']});

console.log(clean);
// <b>preserve me</b>

var clean = DOMPurify.sanitize(`
    <div><b>preserve me</b></div>
    <p><b>no not preserve me</b></p>
`, {FORBID_TAGS: ['div', 'p']});

console.log(clean);
// <b>preserve me</b>
// <b>no not preserve me</b>
```

**Comment by 0xedward** [comment]
> I had a closer look @0xedward - it seems that this is indeed tough to do cleanly with a hook. I think it might be better to expose the FORBID_CONTENTS array to be extendable.

Thanks for looking deeper into this! I'm happy to work on exposing the `FORBID_CONTENTS` to the config object so users can add more to the existing list :)

> Assuming we did that, would the below match what you expect in terms of sanitation result?
>
```javascript
var clean = DOMPurify.sanitize(`
    <div><b>preserve me</b></div>
    <p><b>no not preserve me</b></p>
`, {FORBID_CONTENTS: ['p'], FORBID_TAGS: ['div', 'p']});

console.log(clean);
// <b>preserve me</b>

var clean = DOMPurify.sanitize(`
    <div><b>preserve me</b></div>
    <p><b>no not preserve me</b></p>
`, {FORBID_TAGS: ['div', 'p']});

console.log(clean);
// <b>preserve me</b>
// <b>no not preserve me</b>
```

Yeah, I think these examples match what we are trying to do. It seems like `FORBID_CONTENTS` would result in behavior matching [`dropElements`](https://wicg.github.io/sanitizer-api/#element-drop-list), while `FORBID_TAGS` would match the behavior we want for [`blockElements`](https://wicg.github.io/sanitizer-api/#element-block-list). 

cc @mozfreddyb - let me know if I mixed it up here

**Comment by cure53** [comment]
Wow, you are fast. I was just gonna commit my changes but the PR is already finished :D Thanks!

**Comment by 0xedward** [comment]
> I had a closer look @0xedward - it seems that this is indeed tough to do cleanly with a hook. I think it might be better to expose the FORBID_CONTENTS array to be extendable.

So I implemented that in this draft PR https://github.com/cure53/DOMPurify/pull/557 and it looks like solves one of the problems we were running into. 

But there's an issue I'm running into now that's preventing us from reaching parity with the Sanitizer API configuration. For example ,we would like to have something similar to the following code:
```javascript
// https://wicg.github.io/sanitizer-api/#example-665b3412

const sample = "Some text <b><i>with</i></b> <blink>tags</blink>.";
new Sanitizer({dropElements: [ "b" ]).sanitize(sample); // Some text <blink>tags</blink>.
```
In this case, setting only `FORBID_CONTENTS` in the DOMPurify config won't work, because [`<b>` is in the default allowed tags list](https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L852)
```javascript
// This won't work
const sample = "Some text <b><i>with</i></b> <blink>tags</blink>.";
DOMPurify.sanitize(sample, { FORBID_CONTENTS: [ "b" ] }); // Some text <b><i>with</i></b> <blink>tags</blink>.
```

Also it seems like with [this line in `purify.js`](https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L852), a user configuring Sanitizer API will be able to specify which elements they want to remove, while keeping its children (`blockElements`) or which elements to remove including its children (`dropElements`), but not both at the same time.

I'm thinking of combining https://github.com/cure53/DOMPurify/pull/557 with the `*SanitizeElements` hooks to see if I can dynamically add/remove elements in `FORBID_CONTENTS` to emulate what we want for Sanitizer API or if you're open to the idea, adding another configuration option like `DROP_TAGS`, update `_sanitizeElements()` to check elements in `DROP_TAGS` and call `_forceRemove()`

**Comment by cure53** [comment]
I think we should try first if it works with hooks. If not, happy to review the possibility for another config option.

**Comment by cure53** [comment]
Closing this for now if no one objects...

**Comment by 0xedward** [comment]
Sounds good! Thanks so much for helping us figure this out! :)
