### ISSUE TITLE
How to create element in DOMPurify hook server-side?

### ISSUE THREAD

**Issue by GrantGryczan** [cure53/DOMPurify#562]
I want to create an element to append it in a hook server-side (Node.js), but the server doesn't have native access to any `document` in order to call `document.createElement`. How should I go about this? I couldn't find any examples of this in the hook demos or in other issues on this repo.

**Comment by cure53** [comment]
Hmm, no idea to be honest :) Can you work-around with innerHTML per chance?

**Comment by GrantGryczan** [comment]
I also considered using `node.ownerDocument.createElement`, which works in the browser, though I haven't tested whether it works server-side. And I probably could work around with `innerHTML`.

Either way, I actually don't need this anymore, so I'll close the issue now.
