### ISSUE TITLE
Few css rules being removed after sanitization

### ISSUE THREAD

**Issue by vikkrantxx7** [cure53/DOMPurify#563]
### Background & Context

The sanitized output doesn't contain some rules.

#### Input

``DOMPurify.sanitize('<html><head><style>.hi{font-weight: bold; color: green; border-bottom: black;}</style></head><body><div class="hi">Hi</div></body></html>', { FORCE_BODY: true })``

#### Given output
```
<style>.hi{
color:green;
font-weight:bold;
}</style><div class="hi">Hi</div>
```
#### Expected output
```
<style>.hi{
color:green;
font-weight:bold;
border-bottom: black;
}</style><div class="hi">Hi</div>
```

**Comment by cure53** [comment]
Hmm, what version are you working with? On our demo page it works as expected: https://cure53.de/purify

**Comment by vikkrantxx7** [comment]
> Hmm, what version are you working with? On our demo page it works as expected: https://cure53.de/purify

Using v2.2.2

**Comment by cure53** [comment]
Maybe try using the latest version. 

If that doesn't do the trick, then something else must be happening - outside DOMPurify. We don't actually touch those CSS properties :)

**Comment by vikkrantxx7** [comment]
I think the problem is something else ... as we are using it through webpack then the same instance is being used everywhere and I suppose somewhere some config was changed but I haven't found that out. So, getting a new instance resolved this problem.
