### ISSUE TITLE
String not sanitized

### ISSUE THREAD

**Issue by aabeborn** [cure53/DOMPurify#564]
### Background & Context

Using latest version of the library  the following string won't be sanitized as expected.

### Bug

The string won't be sanitized.

#### Input
```
"<form action="/xxx.php">inserire password:<br><input style="border:1px solid"><br><input type="submit" value="Ok"</form>"
```

#### Given output

The input.

#### Expected output

The sanitized string

**Comment by cure53** [comment]
Not sure what you mean, what is wrong here?

**Comment by aabeborn** [comment]
> Not sure what you mean, what is wrong here?

Using  `sanitize` method, I expect that the form inside the string, if added to HTML, won't be shown in HTML.
Now if I'll add it, the form is shown and any action could be done in it

**Comment by cure53** [comment]
We allow forms by default as they don't cause XSS. I recommend to block-lost forms, then it will work as expected:

`var clean = DOMPurify.sanitize(dirty, {FORBID_TAGS: ['form']});`

**Comment by aabeborn** [comment]
I tried it before but for some stupid reasons the param was incorrect, now it works....
Thank you!

**Comment by cure53** [comment]
yw :)
