### ISSUE TITLE
[Question] Why are comments removed by default?

### ISSUE THREAD

**Issue by GrantGryczan** [cure53/DOMPurify#565]
I was just wondering, why are comments not whitelisted by default? Can they somehow lead to a vulnerability?

**Comment by cure53** [comment]
Because they are risky and can introduce mXSS bugs, unexpected behaviors, XSS with some JS frameworks, etc. Also, just as with iframes, there is close to zero common use-cases for them to be part of user controlled HTML.

**Comment by GrantGryczan** [comment]
Would you be willing to give any examples? Not that I much of a use case for whitelisting comments, but I am curious.

**Comment by cure53** [comment]
Here are some:

https://html5sec.org/?comment

And here are some as well:

https://github.com/cure53/DOMPurify/blob/main/test/fixtures/expect.js (Ctrl +F "<!--")

**Comment by GrantGryczan** [comment]
Alright, thank you!
