### ISSUE TITLE
Possible bug: `style` elements are removed when they contain HTML-like syntax

### ISSUE THREAD

**Issue by GrantGryczan** [cure53/DOMPurify#569]
HTML tag syntax in a `style` element causes the `style` element to be removed.

### Background & Context

`<style>body::before { content: ""; }</style>` is allowed, but as soon as you add something in `<angle brackets>` inside the `style` element, such as `<style>body::before { content: "<hello>"; }</style>`, the sanitizer removes the entire `style` tag.

It's also worth noting the HTML tag syntax should NOT be escaped (i.e. `<` should not be converted to `&lt;`, and so on). HTML entities inside a `style` element do not act as HTML entities--they are just plain text.

#### Input

```js
DOMPurify.sanitize(`
    <style>
        body::after {
            content: "hello<br>world";
        }
    </style>
`, { FORCE_BODY: true });
```

#### Given output

```js
'\n    \n'
```

#### Expected output

```js
'\n    <style>\n        body::after {\n            content: "hello<br>world";\n        }\n    </style>\n'
```

**Comment by GrantGryczan** [comment]
This may or may not be useful.

![image](https://user-images.githubusercontent.com/14056899/133562747-227c82e2-3957-4a99-ae27-19f84174ba50.png)

**Comment by cure53** [comment]
Allowing angle brackets inside style blocks will cause several mXSS patterns to become possible, so we cannot allow that. So, sadly, this is a wontfix.

**Comment by GrantGryczan** [comment]
Ah, I see. Alright!

**Comment by cure53** [comment]
Here are some examples to illustrate the problem:
https://github.com/cure53/DOMPurify/blob/main/test/fixtures/expect.js#L1010

Sadly, nothing we can do right now other than being prohibitive, sorry.

**Comment by GrantGryczan** [comment]
It's fine, I can just recommend users to use unicode escapes instead if they want to do this.

**Comment by cure53** [comment]
Yup :)

**Comment by GrantGryczan** [comment]
Would this not be fixable by escaping `<` and `>` into `\<` and `\>` respectively (if they are not already escaped) inside `style` tags? Sounds like a simple regex, for example replacing `/(^|[^\\])([<>])/g` with `'$1\\$2'`.
