### ISSUE TITLE
`autofocus` attribute is omitted by default

### ISSUE THREAD

**Issue by GrantGryczan** [cure53/DOMPurify#570]
The `autofocus` attribute is not in the default whitelist. Is this intentional? If so, why?

**Comment by GrantGryczan** [comment]
Never mind, duplicates #364.

**Comment by cure53** [comment]
Because it can be used for attacks stealing focus and thereby leaking keystrokes.

**Comment by GrantGryczan** [comment]
(For the record: Also see https://github.com/cure53/DOMPurify/issues/571#issuecomment-920679378 for additional related discussion.)
