### ISSUE TITLE
Why is the SVG fedropshadow element disabled by default

### ISSUE THREAD

**Issue by yisibl** [cure53/DOMPurify#573]
Is there a way to manually enable disabled elements?

https://github.com/cure53/DOMPurify/blob/bc4f2ec76f288524c2eb9ce27f7cef998fc9ec71/src/tags.js#L196-L205

**Comment by cure53** [comment]
If I remember correctly there was some mXSS risk connected to those. And yes, you can of course enable them - this should work:

```javascript
DOMPurify.sanitize(
    '<svg><feDropShadow>123</feDropShadow></svg>', 
    {ADD_TAGS: ['feDropShadow']}
);
```

**Comment by yisibl** [comment]
I hope some instructions can be added to the document.

**Comment by cure53** [comment]
https://github.com/cure53/DOMPurify#can-i-configure-dompurify

^ all there :)

**Comment by SelfMadeSystem** [comment]
I've searched quite a lot today to try and find this mXSS that uses `feDropShadow.` I can't find one anywhere, not even the mention of one. Do you know anything about it and how it can be sensibly prevented without banning `feDropShadow` elements?

**Comment by cure53** [comment]
At the moment, we also have no knowledge about `feDropShadow` being risky, wanna spin up a PR and add it to the allow-lost?

**Comment by SelfMadeSystem** [comment]
Yeah I could do that. I also have some more questions, but I'll make a new longer issue about it when I Have time.
