### ISSUE TITLE
`application/xhtml+xml` parser doesn't work

### ISSUE THREAD

**Issue by securityMB** [cure53/DOMPurify#575]
Hiya,

It seems that commit https://github.com/cure53/DOMPurify/commit/12d255cd394d8c716c7545901e5365a37a9ec8cc (that attempted to fix tests for MSIE) actually broke the `application/xhtml+xml` and it's not possible to enable it currently.

The reason is the following two snippets:

```javascript
  const SUPPORTED_PARSER_MEDIA_TYPES = ['application/xhtml+xml', 'text/html'];
(...)
    PARSER_MEDIA_TYPE =
      cfg.PARSER_MEDIA_TYPE in SUPPORTED_PARSER_MEDIA_TYPES
        ? cfg.PARSER_MEDIA_TYPE
        : DEFAULT_PARSER_MEDIA_TYPE;
```

Since `SUPPORTED_PARSER_MEDIA_TYPES` is now an array, you cannot use `in` operator to check whether the element exists in array. In other words, `'application/xhtml+xml' in SUPPORTED_PARSER_MEDIA_TYPES` is always false.

I think the right approach would be to use `.indexOf` on `SUPPORTED_PARSER_MEDIA_TYPES`.

**Comment by cure53** [comment]
Oh, dang, you are right of course :sweat_smile: 

This should do the trick then:

```javascript
    PARSER_MEDIA_TYPE =
      SUPPORTED_PARSER_MEDIA_TYPES.indexOf(cfg.PARSER_MEDIA_TYPE)
        ? cfg.PARSER_MEDIA_TYPE
        : DEFAULT_PARSER_MEDIA_TYPE;
```

**Comment by securityMB** [comment]
I think it should be `SUPPORTED_PARSER_MEDIA_TYPES.indexOf(cfg.PARSER_MEDIA_TYPE) !== -1` 😄

**Comment by cure53** [comment]
You're right, after satisfying the linter, thous should do the trick

```javascript
    PARSER_MEDIA_TYPE =
      // eslint-disable-next-line unicorn/prefer-includes
      SUPPORTED_PARSER_MEDIA_TYPES.indexOf(cfg.PARSER_MEDIA_TYPE) === -1
        ? (PARSER_MEDIA_TYPE = DEFAULT_PARSER_MEDIA_TYPE)
        : (PARSER_MEDIA_TYPE = cfg.PARSER_MEDIA_TYPE);
```

**Comment by cure53** [comment]
Now it should be good, thanks for spitting this!

**Comment by cure53** [comment]
We'll do a release later today :)
