### ISSUE TITLE
DOMPurify and table rows

### ISSUE THREAD

**Issue by Baker68** [cure53/DOMPurify#576]
Two weaks after reading about [190](https://github.com/cure53/DOMPurify/issues/190) and [324](https://github.com/cure53/DOMPurify/issues/324) I have decided to give up, I can't figure it out.
The code :
```const createDOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');

const window = new JSDOM('').window;
const DOMPurify = createDOMPurify(window);

DOMPurify.addHook('uponSanitizeElement', function (node, data) {
  console.log('uponSanitizeElement node ', node.tagName);
  console.log('uponSanitizeElement data ', data.tagName);
});

const clean = DOMPurify.sanitize(`<tr>test</tr>`);
console.log(clean);
```
It outputs :
```
uponSanitizeElement node  BODY
uponSanitizeElement data  body
uponSanitizeElement node  undefined
uponSanitizeElement data  #text
test
```

It seems like it never reaches the `TR` tag (or `TD` if used) yet it returns the purified text without any tags.
I know and I am aware that you have no obligation to me, but could you please provide an example ?
Thanks in advance.

**Comment by cure53** [comment]
This looks like something happening inside jsdom, not sure if we can do much here, sorry. Generally, it makes zero sense to sanitize elements of tables when, what you likely really want, is to sanitize the content of a table cell.

So, jsdom or not, the code you produce tries to solve the problem using the wrong way :)
