### ISSUE TITLE
Running DOMPurify in a Web Worker

### ISSUE THREAD

**Issue by fabiospampinato** [cure53/DOMPurify#577]
This issue discusses a performance issue deriving from DOMPurify's dependance on the DOM.

### Background & Context

I work on a note-taking app which renders user-provided HTML documents, essentially. Those HTML documents must be sanitized, my goal is to do that as efficiently as possible. The problem is that given how DOMPurify works it's impossible for me to implement this well enough.

Initially I was just doing the following:

1. Turn the HTML into a DOM with DOMParser.
2. Sanitize the DOM with DOMPurify.

But there are multiple problems with that approach:

1. First of all sanitization time scales with the input, and it's synchronous so it blocks the thread, it follows immediately that I just can't run sanitization on the main thread if I want to provide great performance to my users under pretty much all scenarios.
2. Secondly when the HTML document is being edited by the user I probably don't actually need to sanitize it fully again, I can just split the HTML into top-level tags and sanitize each of them individually, with some caching this means only the top-level tags that changed will be sanitized again, which will be a massive speed up.

I can address the second problem pretty easily, but the first problem just can't be addressed because DOMPurify relies on the DOM, the DOM APIs aren't available in a worker context, userland implementations of DOM APIs like jsdom come with their own major issues (jsdom in particular in my experience is slow and massive), and alternative non-DOM-based HTML sanitization libraries like js-xss I just don't trust, if they work at all.

So assuming it's in DOMPurify's interest to be able to be used efficiently, what should be done to fix this?

### Feature

I think the best way to address the issue is the following: DOMPurify already accepts a raw Node as input, if it "only" accepted a relatively simple NodeLike object too, which would be an object implementing a very restricted set of DOM-like APIs, then I as a user could parse my HTML string with a third-party HTML parser, and then provide a simple adaptor to it for DOMPurify. Basically DOMPurify would work largely the same way with potentially little change to its code, and users could run it in workers with relatively little work.

Essentially I think it's fine that DOMPurify needs a DOM-like API, but if it requires the entirety  of the DOM APIs then it becomes a problem from a performance perspective, because it just can't be run in a worker.

Additionally it may be a good idea to provide an asynchronous version of the API which yields to the event loop every 5ms or so, so that no matter how big the input string is the thread will never just freeze indefinitely.

I hope these potential improvements will be implemented, as currently I don't see a way to use DOMPurify with predictable and acceptable performance.

**Comment by cure53** [comment]
Aye, thanks! Closing this one for now then :)

**Comment by CyberAP** [comment]
@fabiospampinato thanks for the link, I have tried it and must say that LinkeDOM probably is missing something that DOMPurify heavily relies on, since I basically get no sanitization whatsoever from the demo in jsfiddle (even with markdown step removed).

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/1462706/142709672-39893eb9-2a5e-4366-aec9-ffbfdf7de58a.png)

</details>

**Comment by Nantris** [comment]
@cure53 @CyberAP - I'm late to the party, and I make no claim to the correctness or safety of this approach (just spitballing with ChatGPT while investigating the code), **and unfortunately it still doesn't work**, but it does get us closer to the root cause of incompatibility, and whether it might be overcome.

Based on how linkedom works, I feel quite certain it cannot, but I fell down a rabbit hole and here we are.

```js
import { DOMParser, parseHTML } from 'linkedom';

const dp = require('dompurify');

const output = parseHTML('<!DOCTYPE html>');
const makeCompatibleWithDOMPurify = abstraction => {
  const polyfill = (title = '') => {
    const { document: doc } = parseHTML(
      `<!doctype html><html><head><title>${title}</title></head><body></body></html>`
    );
    return doc;
  };
  abstraction.document.implementation = {
    createHTMLDocument: true,
    createDocument: polyfill,
  };

  function NodeFilter() {}

  // FILTER_* constants for acceptNode()
  NodeFilter.FILTER_ACCEPT = 1;
  NodeFilter.FILTER_REJECT = 2;
  NodeFilter.FILTER_SKIP = 3;

  // SHOW_* bitmask flags for whatToShow
  NodeFilter.SHOW_ALL = 0xff_ff_ff_ff;
  NodeFilter.SHOW_ELEMENT = 0x1;
  NodeFilter.SHOW_ATTRIBUTE = 0x2;
  NodeFilter.SHOW_TEXT = 0x4;
  NodeFilter.SHOW_CDATA_SECTION = 0x8;
  NodeFilter.SHOW_ENTITY_REFERENCE = 0x10;
  NodeFilter.SHOW_ENTITY = 0x20;
  NodeFilter.SHOW_PROCESSING_INSTRUCTION = 0x40;
  NodeFilter.SHOW_COMMENT = 0x80;
  NodeFilter.SHOW_DOCUMENT = 0x1_00;
  NodeFilter.SHOW_DOCUMENT_TYPE = 0x2_00;
  NodeFilter.SHOW_DOCUMENT_FRAGMENT = 0x4_00;
  NodeFilter.SHOW_NOTATION = 0x8_00;

  abstraction.NodeFilter = NodeFilter;
};

makeCompatibleWithDOMPurify(windowAbstraction);
const DOMPurify = dp(windowAbstraction)
```

I noted that with `IN_PLACE: false` the output is returned unchanged, but with `IN_PLACE: true` the return value is `''`
