### ISSUE TITLE
Maintenance plan after Sanitizer becomes widely available

### ISSUE THREAD

**Issue by fabiospampinato** [cure53/DOMPurify#581]
I'd like to ask what is the maintenance plan once [Sanitizer](https://wicg.github.io/sanitizer-api/) lands on all major browsers, is the current plan to maintain DOMPurify indefinitely or to eventually stop maintaining it once Sanitizer or polyfills for it show up?

**Comment by cure53** [comment]
The plan is to keep maintaining DOMPurify for a wide range of reasons.
