### ISSUE TITLE
Prototype lookup breaks some server side emulations

### ISSUE THREAD

**Issue by waterplea** [cure53/DOMPurify#582]
I use DOMPurify with Angular. In browser scenario it works great but for server side rendering Angular uses `domino`. Looks like it does not properly define `Element.prototype` so the following methods break:
https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L111-L114

They were introduced in DOMPurify v2.2.5 it seems. I wonder if there's a way to solve this on DOMPurify side since it was working without them for quite some time. Is there a reason it is implemented this way now?

**Comment by cure53** [comment]
Makes sense but I believe they need to fix this, not us :)
