### ISSUE TITLE
Question: Why not `{ RETURN_DOM_FRAGMENT: true, RETURN_DOM_IMPORT: false }`?

### ISSUE THREAD

**Issue by GrantGryczan** [cure53/DOMPurify#584]
The readme states there are XSS vulnerabilities when `RETURN_DOM_FRAGMENT` is `true` while `RETURN_DOM_IMPORT` is `false`. Out of curiosity, could you give any example(s) of this? And an explanation of why it occurs or why `RETURN_DOM_IMPORT` prevents it would be appreciated :)

**Comment by cure53** [comment]
Uuuh, the bypass was discussed privately with the Chrome team, so not sure how much I can tell about it :D

If I remember correctly, it had to do with declarative shadow DOM: https://web.dev/declarative-shadow-dom/
It offered a way to make elements become invisible if the wrong flags are used, iirc that is why we do that magic.
