### ISSUE TITLE
Support passing the configuration object to the constructor

### ISSUE THREAD

**Issue by fabiospampinato** [cure53/DOMPurify#587]
Currently a configuration object can be passed directly to the `sanitize` method or to the `setConfig` method. IMO the right way to do that is instead passing a configuration object to the constructor, which is not currently supported.

It's the right way to do this because by using `setConfig` you basically get the wrong TypeScript types, as the types of the DOMPurify instance can't be changed anymore just by calling a function like that, and by using `sanitize` one wastes a huge amount of time constantly parsing the same configuration object over and over again. By passing it to the constructor you pay for it once and you get correct types, which one can't both get currently.

**Comment by cure53** [comment]
Do you think this can be done without breaking existing functionality? If so, happy to review a PR from you.

**Comment by fabiospampinato** [comment]
I think so, the library just needs to add support for a second argument in the constructor for this, and the types should be updated accordingly.

**Comment by cure53** [comment]
Awesome, looking forward to a PR then :D

**Comment by cure53** [comment]
Nah, I prefer having no open issues floating around.

**Comment by fabiospampinato** [comment]
You can disable the issue tab entirely then, your desire for a PR on this conflicts with having this issue closed 🤷‍♂️ As a user what I'm getting from that is that cosmetics are more important that correctness for this repo, or maybe that TypeScript support isn't important 🤷‍♂️ Your choice anyway.
