### ISSUE TITLE
Question: Define rules for nested elements

### ISSUE THREAD

**Issue by yaroslavputria** [cure53/DOMPurify#592]
Hi All,

I sanitize nodes which contain nested elements. And in my case it removes the contant tag from nested images (the img tag). Adding the ADD_ATTR config doesn't help. Do you know how can I prevent this?

**Comment by SethCram** [comment]
Hey @yaroslavputria, how'd you end up structuring your hook and what event did you hook into to get around this? I'd love to know as I have a similar use case but with nested tags

**Comment by yaroslavputria** [comment]
Hi @SethCram, in my case this hook did the job:
```
DOMPurify.addHook('uponSanitizeAttribute', (currentNode, hookEvent, config) => {
    if (currentNode.nodeName === 'IMG') {
        if (hookEvent && hookEvent.attrName === 'content') {
            hookEvent.forceKeepAttr = true;
        }
    }
    return currentNode;
});
```
