### ISSUE TITLE
CSS comments cause DOMPurify to remove all style tag

### ISSUE THREAD

**Issue by NNSTH** [cure53/DOMPurify#593]
> This issue proposes a bug which...

### Background & Context

We are getting an html document by using [pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX), now we want to use DOMPurify.sanitize to get a clean html, but after sanitizing- all style tags created by  [pdf2htmlEX](https://github.com/pdf2htmlEX/pdf2htmlEX) are removed, after an investigation I got the cause - because of css comments within the style tag

### Bug

If there is a css comment within style tag- all the tag is removed from the html

#### Input

```
<html><style>
    /*! 
     * Base CSS for pdf2htmlEX
     * Copyright 2012,2013 Lu Wang <coolwanglu@gmail.com> 
     * https://github.com/pdf2htmlEX/pdf2htmlEX/blob/master/share/LICENSE
     */#sidebar{position:absolute;top:0;left:0;bottom:0;width:250px;padding:0;margin:0;overflow:auto}.ir:hover{cursor:pointer}
    /*! 
     * Fancy styles for pdf2htmlEX
     * Copyright 2012,2013 Lu Wang <coolwanglu@gmail.com> 
     * https://github.com/pdf2htmlEX/pdf2htmlEX/blob/master/share/LICENSE
     */@keyframes fadein{from{opacity:0}to{opacity:1}}
    .xa{left:315.581348pt;}
    .xf{left:364.288015pt;}
    .x1{left:500.609348pt;}
    </style></html>
```

#### Given output

After sanitizing, using this code:
`DOMPurify.sanitize(html, {WHOLE_DOCUMENT: true, FORCE_BODY: true});`
I get this output: 
`<html><body></body></html>`

#### Expected output

The style tag does not contain any XSS code, so it has to remain just the same

Thanks in advance, your package is awesome!

**Comment by cure53** [comment]
I think it is the "<" and ">" inside the CSS. Nothing much we can do about that, as those characters inside style can lead to mXSS, sorry.
