### ISSUE TITLE
Allow HTML `nonce` attr?

### ISSUE THREAD

**Issue by Malvoz** [cure53/DOMPurify#594]
https://html.spec.whatwg.org/multipage/urls-and-fetching.html#attr-nonce

**Comment by cure53** [comment]
I see no issue with allowing `nonce`, wanna spin up a PR? happy to merge it in.

**Comment by Malvoz** [comment]
I get the following error, on windows:

`error: cannot spawn .git/hooks/pre-commit: No such file or directory`

Not sure why, if anyone else wants to send a PR, feel free. 🙂

**Comment by cure53** [comment]
No worries, I added it :) Does that work as expected?
