### ISSUE TITLE
DOMPurify removes all custom elements

### ISSUE THREAD

**Issue by franktopel** [cure53/DOMPurify#596]
In the almost-default configuration (except `RETURN_TRUSTED_TYPES: true`) DOMPurify strips out all custom elements, making it unusable for custom element-based applications.

It also removes the attribute values of `is`-attributes, making derived custom elements unusable.

Here's a reproducer repo demonstrating the issue: https://github.com/franktopel/dompurify-custom-elements

### Background & Context

Doing something as simple as `document.body.innerHTML = '<foo-bar></foo-bar>';` with a default policy in place will set `''` as `innerHTML`.

This is my trusted-types-defining script:

```js
// trusted-types-policies.js
import DOMPurify from 'dompurify';
DOMPurify.setConfig({
  RETURN_TRUSTED_TYPE: true,
});
const policies = {
  createHTML: (str) => {
    return DOMPurify.sanitize(str);
  },
  createScriptURL: (str) => str,
  createScript: (str) => str,
};

if (window.trustedTypes && window.trustedTypes.createPolicy) {
  window.trustedTypes.createPolicy('default', policies);
} 
```

The HTML defines this Content-Security-Policy:

```html
<meta http-equiv="Content-Security-Policy"
    content="require-trusted-types-for 'script'; trusted-types dompurify default" />
```

### Bug

DOMPurify removes any custom elements in the sanitized `TrustedHTML`.

#### Input

`<foo-bar></foo-bar><div is="custom-div"></div>`

#### Given output

`<div is=""></div>`

#### Expected output

`<foo-bar></foo-bar><div is="custom-div"></div>`

### Feature

Without this, it's impossible to efficiently work with any sort of view components that import/load their HTML from a HTML file (as a string, as we won't actually have HTML imports for quite some time).

In the current documentation, I wasn't able to find a way to configure DOMPurify to allow any custom elements. Whitelisting those tags won't work for me as the trusted types policy is implemented in the atomic web component library which is being consumed by the application, which itself is made up from composed custom elements loading HTML that includes a lot of the atomic, and even other composed custom elements.

If whitelisting is the only option, at least that would have to allow all tags based on a pattern, like all custom elements whose tag name starts with a certain string (as well as any `is`-attribute values following the same pattern).

**Comment by franktopel** [comment]
If this has been "fixed" with #184, please add specific documentation on how to use that.

**Comment by cure53** [comment]
Interesting! We never had someone requesting support for those and, so far, treated custom elements as potentially insecure, hence they disappear. What do you think makes more sense?

* A config flag that permits them categorically?
* An allow-list to permit them one-by-one?

**Comment by franktopel** [comment]
> What do you think makes more sense?
> * A config flag that permits them categorically?

This would be the preferred option **of the two**.

> * An allow-list to permit them one-by-one?

This would not work, at all, in our case, as the GUI element library (which comes with Trusted Types) cannot know what custom elements exist. We have split the GUI element lib off as we want it to serve as a base for developing many web applications based on it in the future.

Our application itself - which consumes the web component lib - is also developed in the form of custom elements (view components and view controller components).

These are examples of components in our component lib: `<company-date>`, `<company-datagrid>`, `<company-button>`, `<company-tabs>`, `<company-radio-group>`, `<a is="company-router-link">`, `<company-dialog>` etc.

These are examples of what a consuming viewcomponent `<company-address-edit></company-address-edit>` sets as its own innerHTML:

```html
<h1 is="company-main-headline"><a href="/home" is="company-router-link" id="home-link"></a> <company-span id="dirty"></company-span></h1>
<div id="editAdress" class="grid">
    <company-datagrid id="datagrid1"></company-datagrid>
    <company-text class="col-6" id="firstname"></company-text>
    <company-text class="col-6" id="lastname"></company-text>
    <company-text class="col-8 col-xl-5" id="street"></company-text>
    <company-text class="col-4 col-xl-1" id="street-no"></company-text>
    <company-text class="col-4 col-xl-1" id="post-code"></company-text>
    <company-text class="col-8 col-xl-5" id="city"></company-text>
</div>
```

This view component itself is part of a `<company-application>` component.

**Comment by franktopel** [comment]
Also compare https://github.com/WICG/sanitizer-api/pull/53

**Comment by cure53** [comment]
Hmmm, which would you prefer? Flag to turn on custom tags in general or pattern-based tag allow-list?

How would you want to talk to the API, ideally, i.e. can you provide an example how it would look like if those config flags existed? Just so I get an idea of the desired outcome.

**Comment by franktopel** [comment]
Maybe we don't want to allow `<xss-attack></xss-attack>` ... 

This would be sort of my first approach:

```js
DOMPurify.setConfig({
    ALLOW_ALL_CUSTOM_ELEMENTS: true, // convenience for a /.*/ pattern
    ALLOWED_CUSTOM_ELEMENTS_PATTERN: /^(company-|vaadin-)/, // regex, /.*/ would do the same as ALLOW_ALL_CUSTOM_ELEMENTS
});
```

**Comment by cure53** [comment]
That looks relatively reasonable.

```
ALLOW_ALL_CUSTOM_ELEMENTS: true, // convenience for a /.*/ pattern
ALLOWED_CUSTOM_ELEMENTS: 'all',
```

But is this not a bit redundant? I would propose:

```
ALLOWED_CUSTOM_ELEMENTS: 'none', // ['all', 'autonomous', 'derived', 'none', regexPattern]
```

Also, are you planning to send a PR for this?

**Comment by franktopel** [comment]
I'd be happy to create a PR, but I'd definitely need a lot of guidance which would probably result in the whole matter consuming more of your time compared to doing it yourself.

Allowing a `predicate` would grant ultimate flexibility, see my last edit in my previous comment.

**Comment by cure53** [comment]
No worries about guidance :) These are the three starting points:

Add new config option here https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L196

Merge default options with user-controlled config option https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L365

Make sure it is applied it here https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L852

**Comment by cure53** [comment]
> I'm not sure if that is also an issue, but custom elements of course can come with any amount of unknown attributes, which are definitely impossible to whitelist.

Yep, that is why we should add some text to the docs that stay "look, you need to know what you are doing here, this can cause XSS depending on what the application does with the attributes or tags. Handle with care."

Our ultimate goal is to prevent XSS and that will never change, no matter what new browser features come up with, so we need to be clear here.

**Comment by franktopel** [comment]
> Our ultimate goal is to prevent XSS and that will never change, no matter what new browser features come up with, so we need to be clear here.

That is also our goal, and using built-in technologies shouldn't be a reason to skip on `TrustedTypes`.

**Comment by cure53** [comment]
Awesome, let me know please if I can help! Also, good luck with :syringe: :)

**Comment by franktopel** [comment]
Would you prefer `null` or `'none'` as the default value (which wouldn't change the current behaviour)?

**Comment by cure53** [comment]
I believe, to be in line with existing flags, `false` would be the way to go

**Comment by franktopel** [comment]
It's not a flag, it's

```js
  /* Explicitly allow custom elements. Possible values:
   * one of ['all', 'autonomous', 'derived', 'none', regexPattern, predicate]
   */
  let ALLOWED_CUSTOM_ELEMENTS = null;
  const DEFAULT_ALLOWED_CUSTOM_ELEMENTS = 'none';
```

**Comment by cure53** [comment]
Ah, correct - `null` it is

**Comment by franktopel** [comment]
I'm kind of lost as of how (maybe https://github.com/sindresorhus/validate-element-name ?) and in what place to check for these config params.

I'm assuming it would have to happen here:

```js
    /* Remove element if anything forbids its presence */
    if (!ALLOWED_TAGS[tagName] || FORBID_TAGS[tagName]) {
      /* Keep content except for bad-listed elements */
      if (KEEP_CONTENT && !FORBID_CONTENTS[tagName]) {
        const parentNode = getParentNode(currentNode) || currentNode.parentNode;
        const childNodes = getChildNodes(currentNode) || currentNode.childNodes;

        if (childNodes && parentNode) {
          const childCount = childNodes.length;

          for (let i = childCount - 1; i >= 0; --i) {
            parentNode.insertBefore(
              cloneNode(childNodes[i], true),
              getNextSibling(currentNode)
            );
          }
        }
      }
```

**Comment by cure53** [comment]
I would say so too, this is where the checks and removals take place

**Comment by franktopel** [comment]
Are you okay with that external dependency?

**Comment by cure53** [comment]
Absolutely not, we need to stay dependency-free :)

**Comment by franktopel** [comment]
Okay, then how am I supposed to test if it's a valid custom element name? I assume Sindre won't be happy if I c&p his code.

**Comment by cure53** [comment]
Is it not a given that custom elements follow the `<\w+\-\w+` scheme?

**Comment by franktopel** [comment]
> Custom element names should start with `a-z` and contain `a-z` and at least one `-` with optionally `0-9`.

**Comment by cure53** [comment]
Exactly :)

**Comment by cure53** [comment]
https://github.com/sindresorhus/validate-element-name/blob/main/index.js

This code is horrible. Note that this battery of regexes will be matched against _every single element's name_ if the config allows custom elements, performance folks will rightfully scream in eternal pain :D

**Comment by franktopel** [comment]
So what is your suggestion?

**Comment by cure53** [comment]
To be honest, not sure. I am tempted to believe that this all means entering the devil's armpit. I wonder, how often will a developer allow a _user_ to submit HTML containing custom elements? What scenarios do exist where this is needed?

And, that being said, how would anyone be able to know what the custom element actually does, even if it looks harmless to the sanitizer?

**Comment by franktopel** [comment]
> how often will a developer allow a user to submit HTML containing custom elements

That is not the point here. We're pushing `TrustedTypes` to make potentially unsafe XSS sinks safe.

**Comment by cure53** [comment]
But that is a Chrome-only feature anyway, no?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types

I wonder if it makes sense to change the core of DOMPurify for this.

**Comment by franktopel** [comment]
That is still 70+ % of all internet users worldwide. https://caniuse.com/trusted-types

**Comment by cure53** [comment]
Be it as it may, if you see a path for DOMPurify to add this as a feature, I am very happy to support by reviewing PRs, checking testcases etc. - but as of now, I don't see it as actionable enough to invest time myself. Open to contributions, but not a prio from my end as far as I can see.

**Comment by franktopel** [comment]
Then offering a `predicate` or `regex` **only** seems like the most responsible action, with the docs pointing out that this part is totally reliant on the implementation of `predicate` or the precision of  `regexPattern`. That also keeps the checking responsibility away from DOMPurify, as well as any performance concerns.

**Comment by cure53** [comment]
Sounds good to me! :) I hope I am not coming across as a block-head, but I need to gate-keep and make sure that we only add features if they _reeeeally_ make sense or have no measurable impact on the use-cases of any other user already out there.

Technically, we should never ever do anything at all but fix bypasses and make sure the API doesn't change :D Your proposal sounds reasonable to make the library more future-proof. But any change must be non-invasive in a lot of regards.

**Comment by franktopel** [comment]
```js
/* Remove element if anything forbids its presence */
if (!ALLOWED_TAGS[tagName] || FORBID_TAGS[tagName]) {
  /* Keep content except for bad-listed elements */
  if (KEEP_CONTENT && !FORBID_CONTENTS[tagName]) {
    const parentNode = getParentNode(currentNode) || currentNode.parentNode;
    const childNodes = getChildNodes(currentNode) || currentNode.childNodes;

    if (childNodes && parentNode) {
      const childCount = childNodes.length;

      for (let i = childCount - 1; i >= 0; --i) {
        parentNode.insertBefore(
          cloneNode(childNodes[i], true),
          getNextSibling(currentNode)
        );
      }
    }
  }

  if (!FORBID_TAGS[tagName]) {
    if (ALLOWED_CUSTOM_ELEMENTS instanceof RegExp && ALLOWED_CUSTOM_ELEMENTS.test(tagName)) return false;
    if (typeof ALLOWED_CUSTOM_ELEMENTS === 'function' && ALLOWED_CUSTOM_ELEMENTS(tagName)) return false;
  }

  _forceRemove(currentNode);
  return true;
}
```

**Comment by cure53** [comment]
You can use `regExpTest()` for that

**Comment by franktopel** [comment]
```js
      if (!FORBID_TAGS[tagName]) {
        if (ALLOWED_CUSTOM_ELEMENTS instanceof RegExp && regExpTest(ALLOWED_CUSTOM_ELEMENTS, tagName)) return false;
        if (typeof ALLOWED_CUSTOM_ELEMENTS === 'function' && ALLOWED_CUSTOM_ELEMENTS(tagName)) return false;
      }
```

**Comment by cure53** [comment]
LGTM, will review PR once it's in :)

**Comment by franktopel** [comment]
I have [forked and modified DOMPurify](https://github.com/franktopel/DOMPurify) to the best of my understanding and tried it in a [FB I created on the reproducer repo](https://github.com/franktopel/dompurify-custom-elements/tree/updated-dompurify). I'm not getting any errors, but the sanitization result remains the same.

It'd be super nice if you could take a look.

**Comment by cure53** [comment]
Sorry, I cannot take this right now, PR review yes, debug help no.

**Comment by franktopel** [comment]
I was able to locate the problem and fix it. Creating a PR now.

**Comment by cure53** [comment]
This looks very good, thanks :) One question is left - are you planning to add testcases that make sure that the behavior you expect doesn't change over time? I would recommend so: https://github.com/cure53/DOMPurify/blob/main/test/test-suite.js#L1762

I will customize the README in the meantime.

**Comment by franktopel** [comment]
> add testcases that make sure that the behavior you expect doesn't change over time

Will do so after lunch. Walking the dog now.

**Comment by franktopel** [comment]
Did you forget to increase the [version number](https://github.com/cure53/DOMPurify/blob/45d1e1a5d4cf9e1943a9990f18d50245673fef64/package.json#L109)?

**Comment by franktopel** [comment]
Added the tests in #600.

**Comment by cure53** [comment]
> Did you forget to increase the [version number](https://github.com/cure53/DOMPurify/blob/45d1e1a5d4cf9e1943a9990f18d50245673fef64/package.json#L109)?

No, we haven't released yet.

**Comment by cure53** [comment]
I might in 2-3 days, some other PR is happening in parallel

**Comment by cure53** [comment]
It seems the tests are failing on MSIE:

https://github.com/cure53/DOMPurify/runs/4312730757?check_suite_focus=true#step:9:336

**Comment by franktopel** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith#polyfill

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith#polyfill

**Comment by franktopel** [comment]
# IE 10, seriously? 🤦

**Comment by cure53** [comment]
Welcome to my world :)

**Comment by cure53** [comment]
Okay, tests are all green now, I think we are good here :) Thanks again! :bow:

**Comment by franktopel** [comment]
```js
// allow HTML custom elements via regular expression
var clean = DOMPurify.sanitize(dirty, {ALLOWED_CUSTOM_ELEMENTS: false});

// allow HTML custom elements via predicate function
var clean = DOMPurify.sanitize(dirty, {ALLOWED_CUSTOM_ELEMENTS: predicate});
```
should most probably be

```js
// allow HTML custom elements via regular expression, will allow tags with tag names starting with `foo-`
var clean = DOMPurify.sanitize(dirty, { ALLOWED_CUSTOM_ELEMENTS: /^foo-/ });

// allow HTML custom elements via predicate function
var clean = DOMPurify.sanitize(dirty, { ALLOWED_CUSTOM_ELEMENTS: predicate });
```

**Comment by franktopel** [comment]
> I might in 2-3 days, some other PR is happening in parallel

Commit often, release frequently 👍

**Comment by cure53** [comment]
> ```js
> // allow HTML custom elements via regular expression
> var clean = DOMPurify.sanitize(dirty, {ALLOWED_CUSTOM_ELEMENTS: false});
> 
> // allow HTML custom elements via predicate function
> var clean = DOMPurify.sanitize(dirty, {ALLOWED_CUSTOM_ELEMENTS: predicate});
> ```
> 
> should most probably be
> 
> ```js
> // allow HTML custom elements via regular expression
> var clean = DOMPurify.sanitize(dirty, { ALLOWED_CUSTOM_ELEMENTS: regex });
> 
> // example: allow HTML custom elements via regex, will allow tags with tag names starting with `foo-`
> var clean = DOMPurify.sanitize(dirty, { ALLOWED_CUSTOM_ELEMENTS: /^foo-/ });
> 
> // allow HTML custom elements via predicate function
> var clean = DOMPurify.sanitize(dirty, { ALLOWED_CUSTOM_ELEMENTS: predicate });
> 
> // example: allow HTML custom elements via predicate, will allow tags with tag names starting with `foo-`
> var clean = DOMPurify.sanitize(dirty, { ALLOWED_CUSTOM_ELEMENTS: (tagName) => tagName.startsWith('foo-') });
> ```

Yeah, still on it - need to do day-job in parallel...

**Comment by cure53** [comment]
Now README should be fully up to date!
