### ISSUE TITLE
Node 16 support

### ISSUE THREAD

**Issue by edsalter** [cure53/DOMPurify#604]
> This issue proposes a [bug, feature] which...

### Background & Context

I saw that support was tested for Node 16 but was removed, as the logs have expired (https://github.com/cure53/DOMPurify/runs/1553121002?check_suite_focus=true) not sure what was failing

I was just wondering if there are plans to support Node 16? Thanks - Ed

**Comment by cure53** [comment]
Hey there :) We don't have tests for Node 16 _yet_ :D It was tried once but was too early... We could try to add it now, no?

**Comment by cure53** [comment]
The plot thickens... https://github.com/cure53/DOMPurify/actions/runs/1508392744

**Comment by edsalter** [comment]
Node 16 seems to work fine our end
