### ISSUE TITLE
OWASP XSS tests

### ISSUE THREAD

**Issue by caub** [cure53/DOMPurify#605]
HI guys, just wondering if the unit-tests cover the cases in https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html

I looked in the test/ folder, it looks pretty complete, but wanted some confirmation

If not, I can add more test fixtures from that page, please let me know

Quick test with OWASP CSS list: https://replit.com/@caub/dompurify-sanitize#index.js

**Comment by cure53** [comment]
Those are all legacy vectors inherited from a different project - our tests cover the relevant parts fully :)
