### ISSUE TITLE
<th> are removed if they are not inside a table

### ISSUE THREAD

**Issue by caub** [cure53/DOMPurify#606]
This issue asks for advice or proposes a feature

### Background & Context

DOMPurify removes `<th>` elements when they're out of a table, this makes sense, but we do this in purpose as part of markdown templates

`| <th colspan="2" style="text-align:center">Test</th> | | ` is changed to `| Test | |`

https://replit.com/@caub/dompurify-2#index.js

Would there be a way to allow `<th>` out of table context?

**Comment by cure53** [comment]
See here please: https://github.com/cure53/DOMPurify/issues/415

**Comment by caub** [comment]
Thanks, but does it mean there's no way in my usecase?

```js
DOMPurify.sanitize(`<th colspan="2" style="text-align:center">Test</th> | |`, {
  ALLOWED_TAGS: ['th', 'td'],
  KEEP_CONTENT: true
});
// | Test | |
```

**Comment by caub** [comment]
oh I see, it's the browser via JSDOM removing them, sorry I understand now

**Comment by cure53** [comment]
Exactly - unless the TH is user-controlled HTML, there is also no need to sanitize it. If so, it's be best to wrap in a table, sanitize and unwrap.
