### ISSUE TITLE
Unable to sanitize XHTML excerpts from XML

### ISSUE THREAD

**Issue by rfricz** [cure53/DOMPurify#607]
Hi, I'd like to be able to sanitize bits of XHTML that are subtrees of XML like in this [example](https://github.com/GfSE/ReqIF-SpecIF-Bridge/blob/e96daf50c5c6e3e208cdbe0626c87c2c8f3d9e69/examples/Dimmer%20-%20Semantically%20Integrated%20Specification%20(2020-08-19).reqif#L542). The namespace prefix can be anything, e.g. `reqif-xhtml:` instead of just `xhtml:`, but it always has the XHTML namespace URI.

I couldn't find any existing DOMPurify option that would allow this, it always removes all tags and leaves only text. I'm already using `window.DOMParser` for the XML files, so I could just pass the XHTML node to DOMPurify.

Another side issue is that I need to remove the namespaces from the XHTML subtrees altogether, but none of the available hook functions allow me to replace the node with a new one without the prefix (AFAIK it's impossible to remove it in-place using browser APIs, but maybe there is a way?).

Would it be possible to allow sanitizing of prefixed tags? Thanks so much.

**Comment by cure53** [comment]
Ooof, that might be hard to configure - can you show some examples what you tried already and where exactly it fails?

**Comment by rfricz** [comment]
Thanks for looking into it. I've tried playing with `NAMESPACE`, `PARSER_MEDIA_TYPE` and `IN_PLACE` options to no avail. It never fails with an exception, it just returns what is basically the text content of the subtree.

Looking at DOMPurify source, I think [this line](https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L908) is the cuplrit – checking against `ALLOWED_TAGS` is done with the `nodeName` property (which always contains the NS prefix), instead of `localName` that has the prefix stripped. The result is that no prefixed tag is ever allowed.

**Comment by cure53** [comment]
Ah, yep. That might be. Well, that is quite a central part :D Let me have a look what happens when we mess around here.

**Comment by cure53** [comment]
Okay, so it can be made so that we can test for `localName` to be present in that spot and the tests are green, but I am worried that this will be a way more significant change we have to do, i.e. to make all config options be compatible as well.

I'd be happy to look at a PR from you with good test cases and all, but hesitant to make the change just so as the use-case is rather exotic. 

Wdyt?

**Comment by rfricz** [comment]
Right, I wouldn't expect the tests to just allow this... There is a possible solution – a node could also be allowed if it has `prefix`, its `localName` is in `ALLOWED_TAGS` and the element's `namespaceURI` matches the allowed namespaces. I have no idea about security implications , you tell me :-)

**Comment by cure53** [comment]
Heya, I had another look - it would be quite a big change indeed with lots of new test cases. 

Would you be willing to pin up a PR? I'd be happy to review that.

**Comment by rfricz** [comment]
I have two possible workarounds for my case – I can allow the tags on the fly inside the `uponSanitizeElement` hook, or I can traverse the subtree and replace prefixed tags with non-prefixed ones (which I have to do anyway) and let DOMPurify do its work after that instead of before. Way less work than changing the insides of DOMPurify... But thanks for having a look.

**Comment by cure53** [comment]
Yeah, that likely makes most sense :) Also, most welcome!
