### ISSUE TITLE
May I keep img src ?

### ISSUE THREAD

**Issue by sundada88** [cure53/DOMPurify#613]
> This issue proposes a [bug, feature] which...

### Background & Context

If I want sanitize a tag likes `<img src="file://xxxxxx" />`, so I want it keep src attribute. What should I do? Thanks

#### Input

`DOMPurify.sanitize("<img src="file:// xxxx" />")`

#### Given output

`"<img />"`
#### Expected output

`"<img src="file:// xxxx" />"`

**Comment by cure53** [comment]
Hey, have a look at the `ALLOWED_URI_REGEXP` setting, that will allow you to permit file URIs as well.
