### ISSUE TITLE
Use npm or yarn?

### ISSUE THREAD

**Issue by is2ei** [cure53/DOMPurify#616]
@cure53 

Hi, thanks for the great tool.

Recently, I send some PRs and found a log that says:

https://github.com/cure53/DOMPurify/runs/4692262393?check_suite_focus=true

> warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
yarn install v1.22.17

I can send a PR to fix the issue, but at first, I'd like to discuss which would suit this project, npm or yarn.
I think npm is good enough.

**Comment by tdeekens** [comment]
I don't have a strong opinion (or want to). I could however volunteer to update the project to yarn@3 next week to move away from v1.

**Comment by cure53** [comment]
@tdeekens @is2ei what would you say is an advantage of yarn3 over npm or vice versa?

**Comment by is2ei** [comment]
Generally, I think the official tool is more reliable than third-party tools.
So I guess `npm` is the more simple option.

**Comment by cure53** [comment]
I am all for simple, wdyt @tdeekens ?

**Comment by tdeekens** [comment]
I haven't used npm in ages. Been using yarn@3 lately and am very happy with it. 

If others decide for npm I am happy to review PRs.

**Comment by cure53** [comment]
Let's go with NPM for now, simple is better :)
