### ISSUE TITLE
Sanitizing <DIV STYLE="background-image: url(javascript:alert('XSS'))">

### ISSUE THREAD

**Issue by parashuc** [cure53/DOMPurify#618]
> This issue proposes a [bug, feature] which...

### Background & Context

Sanitizing `<div style="background-image: url(javascript:alert('XSS')); padding-top: 50px"></div>`

#### Input

DOMPurify.sanitize(`<div style="background-image: url(javascript:alert('XSS')); padding-top: 50px"></div>`);

#### Given output

`<div` style="background-image: url(javascript:alert('XSS')); padding-top: 50px"></div>`

https://replit.com/@parashuram/DomPurifyTest

#### Expected output

<div></div>
<div style="padding-top: 50px;"></div>
<div style="background-image: url(); padding-top: 50px;"></div>

### Feature

This xss vulnerability is mentioned in owasp website https://cheatsheetseries.owasp.org/cheatsheets/XSS_Filter_Evasion_Cheat_Sheet.html#image-xss-using-the-javascript-directive . Would it be possible to fix it. 

Thanks in advance.

**Comment by cure53** [comment]
Not a bug, this only works on legacy browsers we don't support
