### ISSUE TITLE
removed property usage 

### ISSUE THREAD

**Issue by nnduc1994** [cure53/DOMPurify#620]
Hi, thanks for building this tool :)

I have a question about the `removed` property. In my use case, I just want to validate the user input if it contains any potential XSS attack string, if yes, then the system will stop immediately. 

Based on the use case, I am not interested in the clean string after calling sanitize function, but more interested in the fact if anything has been removed or not. 

I saw this text in the document ``` Please do not use this property for making any security critical decisions. This is just a little helper for curious minds. ```. I wonder how unstable this `removed` property is or is there other ways to achieve my goal.

PS: This is more like a question rather than the bug/issue report

**Comment by cure53** [comment]
Heya :) Thanks! I think `removed` is somewhat stable but we have seen similar approached in the past and were able to bypass them in a pentest. 

Generally, it depends on how much weight you put on it. If it was life and death, I would not use it. But if you have additional layers of protection in place, it might as well be fine.

**Comment by nnduc1994** [comment]
Thanks for the response. I will close the issue :)

**Comment by nnduc1994** [comment]
Unfortunately, the removed failed me on the very first try. Example code: 

DOMPurify.sanitize('<script>alert("hey")</script>')   ---> empty string
DOMPurify.removed ---> [ ] - empty array

**Comment by cure53** [comment]
Yup, and it's not even our fault :) Because here, the browser itself removes the element. DOMPurify doesn't even arrive at the point where it has to be removed. So `removed` is empty and that's even correct.

See here for example: https://github.com/cure53/DOMPurify/issues/501
