### ISSUE TITLE
About Traversal

### ISSUE THREAD

**Issue by NoXtech-zz** [cure53/DOMPurify#635]
Hello,

Happy that i found this,,, jeez... life just got better.!
Im new dev working on my project and learning so will give a STUPID question.
Does it prevents from traversal attacks ?
Its just sometimes some things makes confusion :/

Thanks for answer !

**Comment by cure53** [comment]
No, we only cover the stuff covered here: https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model

**Comment by NoXtech-zz** [comment]
Right, mb you know anything for it ?

thanks again

**Comment by cure53** [comment]
I think you just wanna make sure that user-controlled paths can only contain the stuff you want. No dots and slashes, etc. - but it really depends on the context.
