### ISSUE TITLE
Default export createDomPurify or DomPurify

### ISSUE THREAD

**Issue by PezCoder** [cure53/DOMPurify#636]
### Background & Context

I want to understand the usage of the default export of `dompurify` as a package. In the README I see two sets of usages:

```
// first usage
import { sanitize } from 'dompurify'
sanitize();

// second usage
import createDOMPurify from 'dompurify';
const DOMPurify = createDOMPurify(window);
DOMPurify.sanitize(dirty);
```

The syntax for both of these is very different. When is one used over the other for a web application which is running in the browser?

### The problem, expectation
The exact problem that I'm facing is, we have a `parent package` let's call it parent which is using dompurify. Now I've introduced a `subpackage` which is also using `dompurify` such that the structure looks like so:
```
parent
   - dompurify@2.3.5
   - subpackage
     - dompurify@2.3.5
```

The build for the parent package throws a warning for a usage of dompurify within the subpackage & the same fails on runtime with the following error:
```
WARNING in ../../node_modules/subpackage/file.js 23:14-22
export 'sanitize' (imported as 'sanitize') was not found in 'dompurify' (possible exports: default)
```

```
// subpackage/file.js
import { sanitize } from 'dompurify'

const SomeReactComponent = ({ dangerousHtml }) => {
   return <div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(dangerousHtml) }} />
};
```

Note that the same usage is working alright in two scenarios:
1. The usage within `parent` package is not throwing a warning on build
2. Since `subpackage` is a web application in itself, running it individually doesn't lead to any error for the same code.

I'm not sure how to debug this further, appreciate any help on this.

**Comment by cure53** [comment]
As usual, no idea, sorry, not my field of expertise. @tdeekens any idea?

**Comment by tdeekens** [comment]
👋🏼 Not 100% sure I yet manage to follow along. DOMPurify for historic reasons always only exported a library object as a default export. The factory is actually not exported. You can see this in the `src/purify.js`. The `createDomPurify` factory function itself has a default argument which `getGlobal`. This function is merely `const getGlobal = () => (typeof window === 'undefined' ? null : window);`. Now if you run the same code in two environments, Node.js and browser within the same process I would assume that there are issues cause one can't use the same global than the other.

**Comment by PezCoder** [comment]
@tdeekens That's interesting, it seems like purify.js is implicitly taking care of creating dom purify with a global window object.

A correction that I was using this as the import statement:
```
import { sanitize } from 'dompurify'
```

Interestingly changing this to the following fixed the issue for me:
```
import DOMPurify from 'dompurify';
```

I would expect even the first one to work, any idea when can this happen?

**Comment by PezCoder** [comment]
This is how the typescript definition looks like in the DefinetelyTyped for this package:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/dompurify/index.d.ts#L13-L21

**Comment by PezCoder** [comment]
Reproducible code pen for dompurify@2.3.4 using named import for sanitize:
https://codesandbox.io/s/dom-purify-named-import-n2jlw?file=/src/App.js

**Comment by tdeekens** [comment]
I would assume it to have something to do with how we bundle or how it is consumer. Not sure how to fix it though if we could. We use nothing special in your Rollup setup. I mainly suspect that we return a function return value possible being the culprit. Still then not sure how to solve it. If we were to start over I'd export the factory function and nothing else. That however now would break all consumers and we decided against that. 

The TypeScript definition is not maintained by us so we can't promise anything on that end.

**Comment by PezCoder** [comment]
Sure @tdeekens Thanks for the help. I'll try to dig deeper into it on my side & keep the thread updated on my findings.

**Comment by PezCoder** [comment]
That makes sense.

More: https://stackoverflow.com/questions/43814830/destructuring-a-default-export-object#:~:text=reputation%20by%20sfletche-,Can%20I%20destructure%20a%20default%20export%20object%20on%20import%3F,of%20object%20literals%20%2F%20object%20patterns.

I've anyways updated the usage of this to default exports. Thanks!
