### ISSUE TITLE
<!DOCTYPE html> is being removed when running a HTML template through dompurify

### ISSUE THREAD

**Issue by kohlikohl** [cure53/DOMPurify#638]
> This issue proposes a [bug, feature] which...

### Background & Context

When running an HTML template through dompurify the `<!DOCTYPE html>` declaration at the top of the file is removed.

e.g.
https://codesandbox.io/s/quizzical-grass-cx6vj?file=/src/index.js:0-417
```js
import dompurify from "dompurify";

const WHITELISTED_ATTR = ["content", "focusable", "nonce", "onclick"];
const WHITELISTED_TAGS = ["link", "meta", "script", "#comment"];

const config = {
  ADD_ATTR: WHITELISTED_ATTR,
  ADD_TAGS: WHITELISTED_TAGS,
  RETURN_TRUSTED_TYPE: true,
  WHOLE_DOCUMENT: true
};
console.log(
  dompurify
    .sanitize("<!DOCTYPE html><html><div>test</div></html>", config)
    .toString()
);
```
**Output**:
`<html><head></head><body><div>test</div></body></html>`

**Expected output**
`<!DOCTYPE html><html><head></head><body><div>test</div></body></html>`

**Comment by katlew** [comment]
+1. Could you please prioritize this. This can impact layout when rendering HTML.

**Comment by rfgmendoza** [comment]
+1 is this intended? if so there can be an option to not strip doctype tag?

**Comment by tosmolka** [comment]
@kohlikohl , I don't think DOMPurify is stripping doctype tag but mainly returns html element, not document. You can get to doctype if you use RETURN_DOM and inspect ownerDocument. 

```js
import dompurify from "dompurify";

const WHITELISTED_ATTR = ["content", "focusable", "nonce", "onclick"];
const WHITELISTED_TAGS = ["link", "meta", "script", "#comment"];

const config = {
  ADD_ATTR: WHITELISTED_ATTR,
  ADD_TAGS: WHITELISTED_TAGS,
  WHOLE_DOCUMENT: true,
  RETURN_DOM: true
};
console.log(
  dompurify
    .sanitize("<!DOCTYPE html><html><div>test</div></html>", config)
    .ownerDocument.doctype
);
```

**Comment by publicmays** [comment]
But you cannot use this in conjunction with `RETURN_TRUSTED_TYPE: true`
We want to return a TrustedHTML not a string when we are eventually writing to the DOM.

**Comment by priyankarathnam** [comment]
+1

**Comment by cure53** [comment]
This is a **wont-fix** as there is several ways of doing this on your own without DOMPurify core being needed for any patching and introducing additional niche-case complexity. 

You can likely use the `afterSanitizeElements` or simply attach the doctype if you find it missing. 

Keep in mind, please, we are a sanitizer and not a markup-management suite. If you have non-sanitizer related issues with the markup produced by DOMPurify, you need to fix them yourself with a hook or simply by carefully changing things after sanitization.

**Comment by cure53** [comment]
@publicmays I think the example shared by @tosmolka is already delivering exactly what you were looking for.  He just serialized it into a string to show that the doctype is definitely included, see also:

```javascript
var config = {
  WHOLE_DOCUMENT: true,
  RETURN_DOM: true
};

var doc = DOMPurify
.sanitize("<!DOCTYPE html><html><div>test</div></html>", config)
.ownerDocument;

console.dir(doc.childNodes[0]) // should give you the expected doctype declaration
```

**Comment by kohlikohl** [comment]
@cure53 - Thanks for your response. Your answer makes sense.   
Unfortunately @tosmolka example doesn't take `RETURN_TRUSTED_TYPE: true,` into account. The idea was to use the result of the `.sanitize` call and pass it directly to `document.write(doc)`.

**Comment by cure53** [comment]
Oh, I see! So you indeed need a string and want to throw it into document.write after sanitization, but it needs to be TrustedHTML, gotcha.

**Comment by cure53** [comment]
Alright, so the only clean way I see here is to in fact implement new means to add a doctype via config.

Did you happen to find a way around already, or should we have a look and implement something?

**Comment by publicmays** [comment]
We have an ugly workaround that may be insecure or may add performance
latency and would prefer a cleaner fix.

Right now for our workaround we have a large block of code describing the
significance of doc type and it’s critical impact on layout changes.

I had to revert my implementation in production using dompurify due to the
amount of layout changes it impacted for our features.

If you would kindly consider making this part of your next iteration it
would be greatly appreciated.

**Comment by cure53** [comment]
So, to make sure we build the right thing, you basically need a config option that allows a custom doctype to be added, correct?

Do you see this as a boolean flag that adds a HTML5 doctype or doesn't - or rather a string adding custom doctypes?

**Comment by publicmays** [comment]
Option 1: If `<!DOCTYPE html>` is already included within `WHOLE_DOCUMENT: true` shouldn't this be allowed to remain after the sanitization? Currently sanitization extracts it out.

Option 2: Add another boolean config that allows DOCTYPE to be included

Option 3: Allow this to be an option in WHITELISTED_TAGS ["doctype"] 

Option 4: Open to your other thoughts as we explore. 

Things I tried to think about:
* Current principles on HTML and how DOCTYPE is required
* Making things backwards compatible
* Leveraging what exists today (such as option 3)
* Understanding the intent of current attributes such as what WHOLE_DOCUMENT means

Original standing example
```ts
import dompurify from "dompurify";

const WHITELISTED_ATTR = ["content", "focusable", "nonce", "onclick"];
const WHITELISTED_TAGS = ["link", "meta", "script", "#comment"];

const config = {
  ADD_ATTR: WHITELISTED_ATTR,
  ADD_TAGS: WHITELISTED_TAGS,
  RETURN_TRUSTED_TYPE: true,
  WHOLE_DOCUMENT: true
};
console.log(
  dompurify
    .sanitize("<!DOCTYPE html><html><div>test</div></html>", config)
    .toString()
);
```

**Comment by kohlikohl** [comment]
> the browser will use HTMl4 per chance, and not HTML5 - as usual... 

Correct. 

@cure53 - As @publicmays mentioned above, the issue is that there is already a doctype in the string that is passed into `sanitize`, so the idea would be that it stays or can be whitelisted to stay.

**Comment by cure53** [comment]
Try this please, does that fix the issue?

```javascript
var config = {
  WHOLE_DOCUMENT: true,
  RETURN_TRUSTED_TYPE: true,
  FORCE_HTML_DOCTYPE: true
};

var clean = DOMPurify.sanitize("<html><div>test</div></html>", config);
console.log(clean)
```

**Comment by cure53** [comment]
If so, we will add tests etc. - so far just checking if that addresses you problem properly

**Comment by publicmays** [comment]
I left a comment, how do I test this in sandbox? Or do I have to download this commit / branch locally. Thanks for your patience this is my first time doing this.

**Comment by kohlikohl** [comment]
I am also wrecking my head for the last hour. Loading [https://raw.githubusercontent.com/cure53/DOMPurify/main/dist/purify.min.js](https://raw.githubusercontent.com/cure53/DOMPurify/main/dist/purify.min.js) as a \<script> doesn't seem to add the `DOMPurify` global to the window, as suggested by the docs. :( Any pointers @cure53?

**Comment by cure53** [comment]
You can go here: https://cure53.de/purify

Open console, run the code I showed above, then it works :)

**Comment by kohlikohl** [comment]
Yeah, this works well. Thanks @cure53, appreciate the help and putting the config in place.  
  
\`\`\`js  
const WHITELISTED\_ATTR = \["content", "focusable", "nonce", "onclick"\];  
const WHITELISTED\_TAGS = \["link", "meta", "script", "#comment"\];

const config = {  
 ADD\_ATTR: WHITELISTED\_ATTR,  
 ADD\_TAGS: WHITELISTED\_TAGS,  
 RETURN\_TRUSTED\_TYPE: true,  
 WHOLE\_DOCUMENT: true,  
 FORCE\_HTML\_DOCTYPE: true  
};

const sanitizedContent = DOMPurify.sanitize(  
 "\<!DOCTYPE html>\<html>\<div>test\</div>\</html>",  
 config  
);

const win = window.open();  
win.document.write(sanitizedContent);  
\`\`\`

![](https://user-images.githubusercontent.com/1196216/153233820-40e02471-f3ed-436d-8791-0050de608ee8.png)

  
With `FORCE_HTML_DOCTYPE: false`:  
 

![](https://user-images.githubusercontent.com/1196216/153233941-f46261f1-391e-4ee8-8fb0-8b1e61f10e81.png)

**Comment by publicmays** [comment]
I've validated on my end and can confirm I can see the same as kohlikohl. 
Are next steps to publish this into the next version?

**Comment by cure53** [comment]
@tosmolka Hmmm, I don't trust the XML Serializer and fear this might have lots of consequences in other areas. This smells like mXSS or worse, me thinks. Basically, the idea of returning XHTML and using it in a HTML website might be problematic.

**Comment by tosmolka** [comment]
@cure53 fair enough, what about something like this: https://github.com/tosmolka/DOMPurify/commit/5fe9c67aa4611b3e4ceddc364f41adf366be70a7 ?

**Comment by cure53** [comment]
Ah, so this checks if there is a doctype in the dirty HTML and, in case we return WHOLE_DOCUMENT and a string, we add it back in. 

I have two concerns, what if developers expect the doctype to be removed and can we now use a doctype as an injection source? I wonder, if the string concat operation is safe with things like `<!DOCTYPE HTML PUBLIC "bad stuff here"
   "or here">`

**Comment by tosmolka** [comment]
Very good points, we need to double check that.

**Comment by cure53** [comment]
This looks great, thanks! Just wondering about one thing - what are other possible names but "html"? Lik, why would we allow-list `^[a-z_.:]+$` if technically only "html" will be used?

**Comment by cure53** [comment]
This looks great, thanks :D Ready for a PR?

**Comment by tosmolka** [comment]
@kohlikohl , @publicmays , can you double check pls if https://github.com/cure53/DOMPurify/compare/main...tosmolka:tosmolka/fix-doctype will fix your issue? Thanks.

**Comment by publicmays** [comment]
Hey @tosmolka , 

I took a look at your PR. 

Is there a way we can test / run our scenarios previously like the above examples? 

@cure53 , do we need to deploy tobias' change to this site https://cure53.de/purify

so @kohlikohl & I can give this a try?

**Comment by tosmolka** [comment]
@publicmays - I think public files will only get updated once PR is merged and released. You can test directly with files from `dist/` folder in my experimental branch. Or with `npm link` or `npm install --save dompurify@https://github.com/tosmolka/DOMPurify.git#tosmolka/fix-doctype` or similar approaches.

**Comment by cure53** [comment]
Imho, the proposal works, I'll create a PR now

**Comment by cure53** [comment]
```javascript
var config = {
  WHOLE_DOCUMENT: true,
  RETURN_TRUSTED_TYPE: true,
  ADD_TAGS: ['!doctype']
};
// <!DOCTYPE html><html><head></head><body><div>test</div></body></html>
```

Works for me, cc @kohlikohl 

Thank you, @tosmolka :bow:

**Comment by publicmays** [comment]
Hi @cure53 , Are next steps to publish this into the next version?

**Comment by publicmays** [comment]
Hi following up on this thread @cure53

**Comment by cure53** [comment]
https://github.com/cure53/DOMPurify/releases/tag/2.3.6
