### ISSUE TITLE
DOMPurify copies slots/children outside of custom elements

### ISSUE THREAD

**Issue by quotquot** [cure53/DOMPurify#645]
Using an example from [mozilla](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots), running:

```javascript
DOMPurify.sanitize(`
<my-paragraph>
  <span slot="my-text">Let's have some different text!</span>
</my-paragraph>
`,
    {
        CUSTOM_ELEMENT_HANDLING: {
            tagNameCheck: /-/u
        }
    }
); 
```
yields:
```javascript
'\n' +
  '<my-paragraph>\n' +
  `  <span slot="my-text">Let's have some different text!</span>\n` +
  '</my-paragraph>\n' +
  `  <span slot="my-text">Let's have some different text!</span>\n` +
  '\n'
```
For some reason, DOMPurify copies the children of a custom element and inserts them as its siblings. I couldn't find an option to disable this behavior.  I fail to see the logic in general but I am particularly surprised by this behavior for slotted elements, which have no meaning outside of the custom element and its template-based content.  I hope I did not misunderstand something.

**Comment by cure53** [comment]
Oh, very nice find! We should have a fix in main very soon, currently running tests...

**Comment by cure53** [comment]
It should be fixed on main, please check if it now works properly

**Comment by quotquot** [comment]
Thank you for your quick response. As far as I can tell, it's working now. Thanks again!
