### ISSUE TITLE
[Question] Can hooks be used on a per-call basis?

### ISSUE THREAD

**Issue by fi5er** [cure53/DOMPurify#656]
I use DOMPurify in a VueJS single-page application. I can install global hooks like this:

    import DOMPurify from "dompurify"
    DOMPurify.addHook('afterSanitizeAttributes', node => {
        // ...
    })

On some pages, I would like to use [a hook like this one](https://github.com/cure53/DOMPurify/blob/main/demos/hooks-target-blank-demo.html) (adds `target` and `rel` attributes to links), but on other pages I do not want this behavior. There may also be third-party components that use DOMPurify and I don't want to interfere with their behavior by setting a global hook.

Is there a way to use a hook for a single `sanitize()` call?

Or is there a factory method to get a new "clean" DOMPurify object?

The only workaround I can see at the moment is to add a global hook directly before the `sanitize()` call, and remove it again immediatley after.

**Comment by cure53** [comment]
Good question. How about calling `removeHook` from inside the hook if you want it to be a one-time thing? :see_no_evil:

**Comment by fi5er** [comment]
That could work, too. Either way, the original hook (if any) would need be restored afterwards. Maybe something like

    function myHook () { ... }

    const oldHook = DOMPurify.removeHook("afterSanitizeAttributes")
    DOMPurify.addHook("afterSanitizeAttributes", myHook)
    DOMPurify.sanitize(dubiousHTML, { /* opts */ })
    DOMPurify.addHook("afterSanitizeAttributes", oldHook)

Only problem is that `removeHook()` would need to return the function it popped off the `hooks` array (or undefined if no hook was set), which it currently does not. Or even simpler, `addHook()` could return the hook method it replaced (or undefined).

Without this, any time I call `addHook()`, I might accidentally overwrite a hook needed by another part of the application. I can make sure to always add the hooks I need before calling `sanitize()`, but I can't predict what other components that depend on DOMPurify would need. An example would be Toast UI Editor, which we also use, but which currently doesn't use global hooks.

[This code example](https://github.com/cure53/DOMPurify/tree/main/demos#add-hooks-and-remove-hooks-link) even suggests that `removeHook()` returns something, by using its return value for `console.log()`. The return value is always undefined, so maybe that's just an oversight?

**Comment by cure53** [comment]
Hmmm, good point. I see no issue with the function being returned, wanna spin up a PR? :D

**Comment by jonatanschroeder** [comment]
Adding this here in case someone reaches this issue via search (like I did): another option (credit to @nwalters512) is to create a separate `DOMPurify` instance and add the hook to the instance:

```js
const customPurify = DOMPurify();
customPurify.addHook(...);
customPurify.sanitize(...);
```

In this case the hook is linked to the custom object, not to the global one, and won't affect any other piece of code. It can also be saved to be used multiple times.
