### ISSUE TITLE
Data attribute get's stripped when it contains a string ending in />

### ISSUE THREAD

**Issue by akshare** [cure53/DOMPurify#657]
Not a bug, but advice needed.

Our use case requires passing json string via data attribute eg. `<div data-content="string">Test</div>`.

In some situations, this json string will contain elements like `<img/>` and `<br/>` (which are html encoded).

Dompurify removes `data-content` when it comes across `/>`.

This fails:

```
<div data-content="string <br/>">Test</div>
<div data-content="string />">Test</div>

outputs as 
<div>Test</div>
```

This works:

```
<div data-content="data string <br>"></div>
<div data-content="data string / >"></div>
```

So my next steps were to find and replace matches using hooks.
I just wanted to know if this is kosher or invalidates what dompurify is trying to prevent?

**Comment by cure53** [comment]
Heya! We sadly have to do this because otherwise people who use DOMPurify with jQuery will have XSS:

https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L1172

I think you are safe when using hooks unless you pour the sanitized data into `jQuery.html()` or alike afterwards :)

**Comment by akshare** [comment]
Thank you, really appreciate the answer and your work!
