### ISSUE TITLE
#document-fragment treated as forbidden root node.

### ISSUE THREAD

**Issue by jdalton** [cure53/DOMPurify#664]
👋  Recent-sh change https://github.com/cure53/DOMPurify/commit/3207638b45859f2809f8641cafa35cab15649ec9 checks `!ALLOWED_TAGS` and  `FORBID_TAGS` for `tagName` to see if it's allowed.

I noticed this blocking things like `#document-fragment`. What is the guidance on that?

##### small side note:
> The error message could be made more helpful:
```js
if (!ALLOWED_TAGS[tagName] || FORBID_TAGS[tagName]) {
  throw typeErrorCreate(`root node ${tagName} is forbidden and cannot be sanitized in-place`);
}
```

**Comment by cure53** [comment]
Good question, do you have more details on how this causes issues?

**Comment by cure53** [comment]
Quick ping, do you have an example handy where this causes issued?

**Comment by jdalton** [comment]
```js
const template = document.createElement('template');
// later
template.innerHTML = dirty;
sanitize(template.content);
```

**Comment by cure53** [comment]
Ah, that helps, thanks! My current impression is that allowing _#document-fragment_ via `ADD_TAGS: ['#document-fragment']` would make sense, what do you think?

**Comment by cure53** [comment]
Odd it is indeed :D But somewhat similar to HTML comments and some other weirder requests we got before :)

**Comment by jdalton** [comment]
Thank you all!

**Comment by cure53** [comment]
:pray:
