### ISSUE TITLE
Direct JavaScript Method Checks!

### ISSUE THREAD

**Issue by gatkaPlayer** [cure53/DOMPurify#670]
> This issue proposes a [bug, feature] which...

### Background & Context

Sanitizing "onclick=prompt(8)"

#### Input

var dirty= 'onclick=prompt(8)'
var clean = DOMPurify.sanitize(dirty);

#### Given output

onclick=prompt(8)

#### Expected output

Blank

### Feature

Just quoting the documentation - "Better ask and be sure than guess and be vulnerable."
I think direct javascript injection should also need to be handled. Please correct me if I am wrong. Thanks!
![DOM_purify](https://user-images.githubusercontent.com/88816638/162931817-c44e3ff1-17c9-4a43-990d-c3e560010afb.JPG)

**Comment by is2ei** [comment]
@gatkaPlayer 

README says:

> DOMPurify sanitizes HTML and prevents XSS attacks.

`onclick=prompt(8)` is not HTML.

**Comment by cure53** [comment]
Yup, @is2ei is right, that is out of scope for us and needs to be taken care of by encoding or alike. You can take the resulting HTML and sanitize it using DOMPurify, then the XSS disappears as expected :)
