### ISSUE TITLE
Can I keep the 'src' attribute in my <img> tags?

### ISSUE THREAD

**Issue by elnath78** [cure53/DOMPurify#672]
I need to sanitize some HTML from malicious tags, but would like to actually display images, it keeps stripping all my images `src` attribute, and the `href` and `target` attributes from `<a>` tags. I tried something like this:

`DOMPurify.sanitize($overlay, {ADD_ATTR:['src','href','target']});`

and also:

`DOMPurify.sanitize($overlay, {ADD_TAGS: ['img','a'],ADD_ATTR:['src','href','target']});`

*edit*: it turned that it is not liking my URLs starting with 'moz-extension' still looking for a solution.

**Comment by is2ei** [comment]
@elnath78 

I tried `img` tag with `src` attribue and it won't stripe the attribute.

<img width="1440" alt="Screen Shot 2022-04-22 at 9 28 31" src="https://user-images.githubusercontent.com/3948353/164571694-5f9f5474-a9f4-4448-b66f-76c330253d1a.png">

Could you provide an examnple?

**Comment by elnath78** [comment]
Hello @is2ei 

Turns out the issue was not the `src` itself but the link. I'm using Purify in a browser extension, and the non-canonical URL was filtered out. I resolved adding the `ALLOW_UNKNOWN_PROTOCOLS:true` flag.
