### ISSUE TITLE
Attributes with value of "target" is getting stripped

### ISSUE THREAD

**Issue by akshare** [cure53/DOMPurify#677]
dompurify is removing attributes that have values titled "target".

`<input name="target">` outputs `<input>`
`<input id="target">` outputs `<input>`

But this works:

`<input class="target">` outputs `<input class="target">`

I tested it here https://cure53.de/purify.

I understand the target attribute was not allowed, but wasn't sure if the issue described above was intended?

**Comment by cure53** [comment]
That is because of the DOM Clobbering protection. You can turn the behavior off by using this flag:

```javascript
// disable DOM Clobbering protection on output (default is true, handle with care, minor XSS risks here)
var clean = DOMPurify.sanitize(dirty, {SANITIZE_DOM: false});
```
