### ISSUE TITLE
<style> tag doesn't sanitize if there is any text before

### ISSUE THREAD

**Issue by Disorrder** [cure53/DOMPurify#683]
### Bug
`style` tag doesn't sanitize if there is any text before

#### Input
```
any text here
<script>alert('ololo')</script>
<style>body{display:none!important;}</style>
<iframe src="http://google.com"></iframe>
<a href="http://google.com">link</a>
```

#### Given output
```
any text here

<style>body{display:none!important;}</style>

<a href="http://google.com">link</a>
```

#### Expected output
```
any text here

<a href="http://google.com">link</a>
```

tested here https://cure53.de/purify with v. 2.3.7

**Comment by cure53** [comment]
This should do :)

```
// glue elements like style, script or others to document.body and prevent unintuitive browser behavior in several edge-cases (default is false)
var clean = DOMPurify.sanitize(dirty, {FORCE_BODY: true});
```

**Comment by cure53** [comment]
Oh I get it now, I think. Style is allowed by default. This will remove it.

```javascript
DOMPurify.sanitize('any text here<script>alert(1)</script><style>body{display:none!important;}</style><iframe src="http://google.com"></iframe><a href="http://google.com">link</a>', {
  SAFE_FOR_TEMPLATES: true,
  FORBID_TAGS: ['style'],
  USE_PROFILES: { html: true },
  FORCE_BODY: true, // doesn't matter true, false or undefined
});
```

**Comment by Disorrder** [comment]
Thank you, I'll check it later. 
But anyway, if you remove "any text here" the style tag will disappear. So, it shouldn't then.

**Comment by cure53** [comment]
The disappearing style tag can be fixed using the flag mentioned above, it's just browser weirdness we have to work around here.

Style tags in general will not be removed, unless you tell the sanitizer to do so. So - two minor issues leading to one confusion. Hopefully this clarified a bit :smile:
