### ISSUE TITLE
Bug in CUSTOM_ELEMENT_HANDLING

### ISSUE THREAD

**Issue by shreenivas-asurion** [cure53/DOMPurify#684]
> This issue proposes a [feature] which...

### Background & Context

For custom attributes, like <foobar baz="foobar1> the CUSTOM_ELEMENT_HANDLING is not working. See input for sample

#### Input

 <foobar baz="foobar1> 

 CUSTOM_ELEMENT_HANDLING: {
        tagNameCheck: /^foo/, // allow custom tags starting with "^tag"
        attributeNameCheck: /baz/, // allow custom attributes 
        allowCustomizedBuiltInElements: false, // customized built-ins are allowed
      }

#### Given output

output is blank

#### Expected output

 <foobar baz="foobar1>

**Comment by cure53** [comment]
Custom elements [need a hyphen in their name](https://stackoverflow.com/questions/22545621/do-custom-elements-require-a-dash-in-their-name). 

If you want to allow a `<foobar>` element, it's not an actual custom element and you have to add it via `ADD_TAGS` - then it will work, see here:

```javascript
DOMPurify.sanitize(
    '<foobar baz="foobar1"></foobar>', 
    {ADD_TAGS: ['foobar'], ADD_ATTR: ['baz']}
);
// "<foobar baz=\"foobar1\"></foobar>" 
```

**Comment by shreenivas-asurion** [comment]
Actually there are many custom tags that I want it to be allowed which dont have "-" (dash) in the names. Also, the tag names require regex support as it can change slightly.

**Comment by cure53** [comment]
That makes sense, but it's not a bug in `CUSTOM_ELEMENT_HANDLING` yet a new feature you need :)

You can easily build that using a hook by the way, few lines of code and you have `ADD_TAGS` with regex support, no need to patch the core if it can be done with a hook.

**Comment by cure53** [comment]
Check out the demos, lots of good examples here: https://github.com/cure53/DOMPurify/tree/main/demos
