### ISSUE TITLE
Comments inside <style> tag

### ISSUE THREAD

**Issue by IvelinMarkov** [cure53/DOMPurify#694]
This is not a bug, but I need advice.

I'm trying to sanitize a style element with comments inside it.
```
<style>
/* Name <name@email.com> */

.css { ... }
</style>
```

Using the following cofig `{ FORCE_BODY: true, ALLOWED_TAGS: ['style'] }` 

Nothing should happen, the style element is safe however it's always being removed. When debugging I've found that it's being stripped [here](https://github.com/cure53/DOMPurify/blob/abf62956a8ac86c74b1954274dd6b5b9813094ba/src/purify.js#L928). A style element doesn't have element children, it has only one text node

Is there a way to bypass this? My idea is to replace any '<' inside comments with unique temp value, sanitize and then replace it again. Is there any better way of going thru this?

**Comment by cure53** [comment]
Unfortunately the only way to get around this is indeed to use a hook and replace the characters - or generally remove comment blocks that might contain risky characters.

We have to remove everything fishy from within CSS elements because otherwise, alerts start popping :)
