### ISSUE TITLE
Allow tags

### ISSUE THREAD

**Issue by ivelingrakov** [cure53/DOMPurify#697]
### Background & Context

We are trying to sanitise a user input that often contains graphic elements such as "path", "polygon", "rect" etc. and all of them are stripped out of the sanitised output.

#### Input

var clean = DOMPurify.sanitize("polygon points='220,10 300,210 170,250 123,234'", {USE_PROFILES: {svg: true, svgFilters: true}});

or

var clean = DOMPurify.sanitize("polygon points='220,10 300,210 170,250 123,234'",{
    ADD_TAGS: ['polygon'],
    ADD_ATTR: ['points']
});

I'm using the polygon and the rest of the elements as a tags, however adding such tag here isn't allowed.

#### Given output

"clean" variable is empty

#### Expected output

The expected output is the same as the input - polygon as a tag with points as an attribute with the corresponding value

**Comment by cure53** [comment]
This should do the trick:

```javascript
DOMPurify.sanitize("<polygon points='220,10 300,210 170,250 123,234' />", {
	USE_PROFILES: {svg: true, svgFilters: true},
	ADD_TAGS: ['polygon'],
	ADD_ATTR: ['points'], 
        NAMESPACE: 'http://www.w3.org/2000/svg'
});
```

**Comment by ivelingrakov** [comment]
This is great, much appreciated @cure53

**Comment by cure53** [comment]
yw :)

**Comment by ivelingrakov** [comment]
This works perfect for SVG graphic elements, however I want to allow not only svg  but html sanitisation as well. I've tried to sanitise img tag and it was completely stripped off of the result. Can't we use multiple namespaces?

**Comment by cure53** [comment]
Only if SVG-elements are properly wrapped inside an SVG, i.e. my second example. See here:

```javascript
DOMPurify.sanitize("<img><div><svg><polygon points='220,10 300,210 170,250 123,234'></svg>", {
    ADD_TAGS: ['polygon'],
    ADD_ATTR: ['points']
});
// "<img><div><svg><polygon points=\"220,10 300,210 170,250 123,234\"></polygon></svg></div>"
```
```javascript
DOMPurify.sanitize("<img><div><polygon points='220,10 300,210 170,250 123,234'></svg>", {
    ADD_TAGS: ['polygon'],
    ADD_ATTR: ['points']
});
// "<img><div></div>" 
```

**Comment by cure53** [comment]
This looks like you are on the right track indeed. I have no specific examples other than the hook demos we have in the repo here.

**Comment by cure53** [comment]
Maybe :) Sadly I cannot help you with debugging or developing your own code. I'll close the ticket for now, let me know please if there is anything in the core lib we need to look at.
