### ISSUE TITLE
Foot-gun question: Can I HTML encode for caret brackets and '&' after sanitizing using DOMPurify?

### ISSUE THREAD

**Issue by MelindaCardenas** [cure53/DOMPurify#702]
This issue is opened to ask a question:  Can I HTML encode for caret brackets and '&' after sanitizing using DOMPurify?

I saw that your README mentioned that "if you first sanitize HTML and then modify it afterwards, you might easily void the effects of sanitization", but I wanted to ask if this combination would be safe to do. 

Reason I ask is because I am trying to sanitize a user's name input that shows up on a page, and I would like to avoid having any HTML input appear on the page.

For example, if someone fills out a form, and enters `<a href="google.com">mwahahah</a>` as their name, and then upon form submission gets an email saying "Hello [mwahahah](https://www.google.com/) ...." , I want to HTML encode the `<` and `>` brackets to avoid the clickable link from showing at all (in addition to using DOMPurify)

**Comment by realansgar** [comment]
You can use the `USE_PROFILES: {html: false}` option like in the following snippet to remove any HTML and leave only text. In your example that would leave `mwahahaha`
```js
var clean = DOMPurify.sanitize(dirty, {USE_PROFILES: {html: false}}); 
```
