### ISSUE TITLE
High CPU Utilisation observed

### ISSUE THREAD

**Issue by Kenam18** [cure53/DOMPurify#704]
Hi team, 

We have noticed a huge increase in CPU Utilisation by using isomorphic-dompurify package in our application and since the package is just a wrapper around dompurify package, we would like to understand the reason why we see a such a spike or if there is a workaround to increase the performance.

Development Environment:

OS: MacOS
Node: v16+
NextJS: v11+
TypeScript: v4.3.2
React: v17+

Ref: https://github.com/kkomelin/isomorphic-dompurify/issues/135#issuecomment-1202416167

**Comment by cure53** [comment]
Need more info, can you check what method call causes the spike?

**Comment by Kenam18** [comment]
We are using https://www.measurethat.net/Benchmarks/Show/12596/0/dompurify-vs-sanitize-html to measure the performance.
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/32893288/182611533-e566a29c-e0f1-461e-9d9a-6b583ce0320e.png">
We are observing huge difference in the performance. Did this help in understanding our query?

**Comment by cure53** [comment]
That's not helping, sorry. Sanitize HTML uses a completely different parsing and sanitization strategy. Just showing off the different performance measurements doesn't help us in spotting possible bottlenecks and fixing them.

If you find an actual performance bottleneck in our code, happy to help and fix asap - but based on the info provided, we cannot do anything.

**Comment by Kenam18** [comment]
Hi @cure53 , we are using flamegraphs to understand the hottest functions and we see the package is identified as a hot function but what within the package causes this is something we are hoping you can help us understand.
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/32893288/182835613-dadb1afe-57e7-4b25-b4c2-190572a0afb4.png">
Flamegraphs: https://clinicjs.org/documentation/flame/04-flamegraphs/

**Comment by cure53** [comment]
Sadly, I don't see how we can help here.
