### ISSUE TITLE
DOMPurify remove attribute with specific value.

### ISSUE THREAD

**Issue by OmkarSingh7** [cure53/DOMPurify#707]
> the DOMPurify removes the attribute if it contains a specific value

#### Input
    <input type="text" name="title" id="timeline">

#### Given output
    <input type="text">

#### Expected output
    <input type="text" name="title" id="timeline">

### More Details
If attribute contain any other value then it is working file. for example below input is working fine:

#### Input
    <input type="text" name="title1" id="timeline1">

#### Given output
    <input id="timeline1" name="title1" type="text">

#### Expected output
    <input id="timeline1" name="title1" type="text">

Would you consider this a bug? If not, Can you please explain why this is happening and solution for the same?

Thanks

**Comment by cure53** [comment]
This is expected behavior to protect from DOM clobbering. You can work around that using this setting:

```javascript
var clean = DOMPurify.sanitize(dirty, {SANITIZE_DOM: false});
```

**Comment by OmkarSingh7** [comment]
Thanks for the timely response, is there any list of such values? which can help to avoid assigning these values to the attributes.

**Comment by cure53** [comment]
Not really, since it depends bit what's already existing in your DOM. DOMPurify first checks if there would be a collision (here it would be `document.title`) and then sanitizes. In many cases, DOM Clobbering is not an issue so you should be fine with the setting.

**Comment by OmkarSingh7** [comment]
Okay Thanks
