### ISSUE TITLE
Chrome: sanitizing `referrer` meta tag still applies the referrer policy

### ISSUE THREAD

**Issue by essmahr** [cure53/DOMPurify#708]
### Background & Context

Possibly related to https://github.com/cure53/DOMPurify/issues/409.

Possibly the a consequence of this Chromium bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1092930&q=meta%20referer&can=2

### Bug

In Chrome (104), if you pass a meta tag with a strict referrer policy, it removes the meta tag but the policy will still apply (and persist indefinitely)

#### Steps to reproduce

1. From the [DOMPurify demo page](https://cure53.de/purify), run a fetch (in my case https://api.sampleapis.com/beers/ale) from the console
   <img width="595" alt="image" src="https://user-images.githubusercontent.com/5510974/183764910-5620e0ff-c6e1-45f7-afdb-34c836a3a3da.png">
   The `Referer` header is correctly present on the request.
2. Run the string `<meta name="referrer" content="never">` through the sanitizer and write the result to the DOM.
3. The cleaned DOM is empty -- the meta tag has been removed.
4. Run a fetch from the console. The `Referer` header is now missing:
    <img width="610" alt="image" src="https://user-images.githubusercontent.com/5510974/183765055-5324d2bb-9bb6-44a1-8f05-879b57f54b55.png">

In our application, this means all subsequent internal network requests fail until a full refresh.

#### Suggested workaround

Our workaround (like #409) is to manually strip meta tags prior to sanitization.

**Comment by cure53** [comment]
Interesting :D Thanks for the heads-up. I am not sure if we can do much here - looks like indeed Chrome has to fix this, no?
