### ISSUE TITLE
Self-closing tags in SVG

### ISSUE THREAD

**Issue by m-gallesio** [cure53/DOMPurify#715]
I am trying to use DOMPurify to sanitize a SVG with the following code:

```javascript
sanitize(svgText, { USE_PROFILES: { svg: true } })
```

I noticed that self-closing tags get expanded, so for example

```svg
<svg><path d="M0,0 L1,1"/></svg>
```

becomes

```svg
<svg><path d="M0,0 L1,1"></path></svg>
```

Since the particular file I am working with is quite large, this expansion noticeably increases its size (about 400KB over 2MB).

Is there any option / flag to keep empty self-closing tags collapsed in environments which allow them (SVG)?

**Comment by cure53** [comment]
Mmh, interesting! I think we can get around that problem like this:

```javascript
DOMPurify.sanitize('<svg><path d="M0,0 L1,1"/></svg>', {NAMESPACE: 'http://www.w3.org/2000/svg'}) 

// <svg xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M0,0 L1,1\"/></svg>
```

Yes, it might add a namespace if it's not there yet, but it will allow you to work with self-closing tags as well.

**Comment by m-gallesio** [comment]
I can confirm **this works**, for whatever reason. Note that my original SVG already had the namespace defined.
My issue is strictly solved; I am leaving this open in case further action on your part is desired.

**Comment by m-gallesio** [comment]
Actually, this causes another problem if the SVG file starts with an `<?xml?>` declaration.

```javascript
DOMPurify.sanitize('<?xml version="1.0"?><svg></svg>', {
    USE_PROFILES: { svg: true },
    NAMESPACE: 'http://www.w3.org/2000/svg', // this causes an error
});
```

The problem is at https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L817

```javascript
      try {
        doc.documentElement.innerHTML = IS_EMPTY_INPUT ? '' : dirtyPayload;
      } catch (_) {
        // Syntax error if dirtyPayload is invalid xml
      }
```

It seems that the `<?xml?>` declaration is not allowed when setting `innerHTML`. The `catch` block prevents the error from propagating, but the sanitized output is empty.

It could be possible to just remove the declaration, but I do not know if it would open any security holes.

Right now **this is not a problem for us** (as I said I can just remove the declaration), but I wanted to note this.

**Comment by cure53** [comment]
Aye, thanks, that is good to know! I think removing the declaration is fine - but we'll have a look, this behavior is not ideal ofc.

**Comment by cure53** [comment]
@m-gallesio Yep, indeed, it's the processing instruction in the XML string causing errors to be thrown. 

What do you think is best? You would remove them yourself before feeding the XML to DOMPurify or DOMPurify tries to remove them in a throw, catch, finally, construct?

**Comment by m-gallesio** [comment]
Right now I am simply removing the declaration before feeding the data to DOMPurify since considering our use case it is most likely not needed.

I have no idea how useful / necessary XML declarations are, but in general stripping them without warning does not seem ideal.
An option I can see is having DOMPurify:
1. remove the declaration
2. upon returning the sanitized string, add back the declaration (likely sanitizing it, if it can somehow be dangerous)

This is obviously not applicable when returning a DOM.

That said please consider that our case is extremely limited and my overall coding experience is not very varied.

**Comment by cure53** [comment]
Aye, makes sense, thanks :smile: Then, in that regard, let's not touch the core library for now. As far as I can see we can close the issue?

**Comment by m-gallesio** [comment]
Thanks to these workarounds I am fine with no further action being taken.
If anything, it could be worthwhile to note these minutiae somewhere in the documentation.
