### ISSUE TITLE
RFE: DOMPurify should add polyfill for Element.setHTML() if native support is missing

### ISSUE THREAD

**Issue by mikkorantalainen** [cure53/DOMPurify#716]
The `Element.setHTML()` as defined in https://wicg.github.io/sanitizer-api/#dom-element-sethtml and also documented in https://developer.mozilla.org/en-US/docs/Web/API/Element/setHTML will be the future standard for most use cases where DOMPurify is used today. I'm requesting an enchancement that DOMPurify adds the function `setHTML()` to browser native Element after loading DOMPurify if native implementation of `Element.setHTML()` doesn't exist.

As an alternative, DOMPurify could add some function that allows doing this after loading DOMPurify if doing it by default is considered too risky. In practice, this could be implementation of `setHTML()` that could be activated with code like

```
if (!Element.setHTML)
    Element.setHTML = DOMPurify.setHTML;
```

Obviously, the implementation of `DOMPurify.setHTML` should automatically match the browser native implementation as closely as possible.

**Comment by cure53** [comment]
Hreya :) I think you might be looking for this, correct? https://github.com/mozilla/sanitizer-polyfill
