### ISSUE TITLE
How can we use This lib in Java service side 

### ISSUE THREAD

**Issue by MohanBojanapuMize** [cure53/DOMPurify#718]
We are unable to use this lib on the java service side

<dependency>
   <groupId>org.webjars.bowergithub.cure53</groupId>
   <artifactId>dompurify</artifactId>
   <version>2.3.3</version>
</dependency>

Please provide more info how to use this .

After adding the above configuration in pom.xml, which function i need to call to sanitize my content on the service side?

**Comment by cure53** [comment]
Please provide more info about what the problem is.
