### ISSUE TITLE
<annotation> tags are always removed no matter what

### ISSUE THREAD

**Issue by iernie** [cure53/DOMPurify#719]
> This issue proposes a bug which...

### Background & Context

I am using DOMPurify together with a couple of third-party libraries for WYSIWYG editing and one of them makes <annotation> tags in the HTML. 

### Bug

I know this is a custom, non-standard tag, but it seems DOMPurify has this tag in a blacklist and no matter what config I use it either get's unwrapped or removed entirely. From what I can see the tag is defiend in the `mathMlDisallowed` list and no config allows it.

#### Input

```
const value = 'Before <annotation>Lorem ipsum</annotation> after'

cont result0 = DOMPurify.sanitize(value);

cont result1 = DOMPurify.sanitize(value, {
  ALLOWED_TAGS: ['annotation']
});

cont result2 = DOMPurify.sanitize(value, {
  ADD_TAGS: ['annotation']
});

const result3 = DOMPurify.sanitize(value, {
  CUSTOM_ELEMENT_HANDLING: {
    tagNameCheck: /^annotation/
  }
});
```

#### Given output

```
result0: "Before Lorem ipsum after"
result1: "Before  after"
result2: "Before  after"
result3: "Before Lorem ipsum after"
```

#### Expected output

```
Before <annotation>Lorem ipsum</annotation> after
```

If I remove `'annotation'` from the `mathMlDisallowed` list in the source code, it works.
If I call the tag something else like `<annotations>` it works with adding it to `ADD_TAGS` or `ALLOWED_TAGS`.
It is just `annotation` that doesn't work.

Sadly I have no control over the other third-party library to change the name of this tag. Allowing this tag would be very appreciated.

**Comment by cure53** [comment]
Hmmmm, that's a tricky one. You can do it like this and then remove the namespace afterwards, would this do the trick?

```javascript
DOMPurify.sanitize(`<annotation>1</annotation>`, {
  ADD_TAGS: ['annotation'], NAMESPACE: 'http://www.w3.org/1998/Math/MathML'
});
"<annotation xmlns=\"http://www.w3.org/1998/Math/MathML\">1</annotation>" 
```

**Comment by iernie** [comment]
Thank you for your reply!

Unfortuanetly adding a namespace seems to ruin the sanitization of all html (non mathml maybe?) tags.

I've solved it by doing a find-replace of all `<annotation>` to `<annotations>` before using DOMPurify and then the reverse afterwards. I guess it works, so if you don't see a better way to handling this you can just go ahead and close this issue :)


Thanks!

**Comment by cure53** [comment]
Yeah, that should do. Sorry for the hassle, that's really one of the niche-cases where we cannot so much without compromising security. Thank you :)
