### ISSUE TITLE
DOMPurify license Issue

### ISSUE THREAD

**Issue by Prudhvicharan** [cure53/DOMPurify#721]
I am currently **using 2.3.10 version** of DOMPurify. It has one **Medium risk License** issue.
Update for new version 2.4.0 is available but both the versions has one Medium risk License issue. Is there a way to overcome that medium risk.

If yes, Please let me know what to be done.

**Comment by cure53** [comment]
I do not know what that means, can you clarify? :D

**Comment by Prudhvicharan** [comment]
We have identified DomPurify is published under Mozilla public License 2.0 and Apache License 2.0. Mozilla public license has a clause that we have to provide the source code of the project if library is used. Can you confirm if that is the licensing term of this library?

![image](https://user-images.githubusercontent.com/43751974/191490567-08860156-2ef3-4845-8d34-235c9608b125.png)

**Comment by cure53** [comment]
That is why we ship two licenses, you can go with the one that works best for you.
