### ISSUE TITLE
Sanitization removes valid scripts when attempting to prevent namespace xxs attacks

### ISSUE THREAD

**Issue by cosmonot1** [cure53/DOMPurify#722]
> This issue proposes a bug which...

### Background & Context

I am sanitizing external content and we would like to include scripts. If the script text content contains a statement like 
```js
if( someVariable<otherVariable ){
  doSomething();
}
```
the `_sanitizeElements` function will always remove the node because of the check [here](https://github.com/cure53/DOMPurify/blob/e0970d88053c1c564b6ccd633b4af7e7d9a10375/src/purify.js#L952)

#### Input
```js
const sanitizedSource = DOMPurify.sanitize(test, {
  FORCE_BODY: true,
  ADD_TAGS: ['script'],
});
```

```html
<html>
  <head><style>html,body {width: 100%;height: 100%;}</style></head>
  <body><button>button</button>
    <script>
      (()=>{
        let something = 5;
        let other = 6;
        if(something<other){ console.log('neat'); }  
      })();
    </script>
  </body>
</html>
```

#### Given output
```html
<style>html,body {width: 100%;height: 100%;}</style>
<button>button</button>
```

#### Expected output
```html
<style>html,body {width: 100%;height: 100%;}</style>
<button>button</button>
<script>
  (()=>{
    let something = 5;
    let other = 6;
    if(something<other){ console.log('neat'); }  
  })();
</script>
```

**Comment by cosmonot1** [comment]
Notice no space in the `something<other`. This is caught by the regex `regExpTest(/<[/\w]/g, currentNode.textContent)`, which matches the `<o` characters.

**Comment by cure53** [comment]
Heya, thanks for filing this. I however don't think we can do much here from a core library perspective, but you should be able to fix this using a hook. 

I would prefer not to change the core library as the risk of accidentally allowing malicious payload to go through is too big.

**Comment by cosmonot1** [comment]
@cure53 would you suggest implementing a hook that does something like (pseudo code ish)
```js
( tag )=>{
if( tag.name === 'script' ){
  return tag.internalText.replace( /</g, '< ');
}

}
```

**Comment by cosmonot1** [comment]
The `< maliciousTag` should break the html but still be valid js which is fine for our use case

**Comment by cure53** [comment]
Yes, I would say that does the trick. It ain't pretty but XSS protection is more important than script preservation :)
