### ISSUE TITLE
XSS attack in mailto

### ISSUE THREAD

**Issue by Testich95** [cure53/DOMPurify#724]
### Background & Context

We get the js script triggered in our application, which supports the mailto scheme.
#### Input

```
const createDOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');

const window = new JSDOM('').window;
const DOMPurify = createDOMPurify(window);

const clean = DOMPurify.sanitize(`<HTML><BODY><div><a href="mailto:?body=qwe%3cimg/src%3D's'onerror%3D%22try%7Bdocument.write('\x3cb\x3eLocation:\x3c/b\x3e'+location+'\x3cbr\x3e\x3cb\x3eUserAgent:\x3c/b\x3e'+navigator.userAgent+'\x3cbr\x3e\x3cb\x3eCookie:\x3c/b\x3e'+document.cookie+'\x3cbr\x3e\x3cb\x3eLocalStorage:\x3c/b\x3e'+JSON.stringify(localStorage)+'\x3cbr\x3e')%7Dcatch%28e%29%7Bdocument.write%28e.message%29%7D%22%3e%3cb%3easd1%3c/b%3e">testXSS</a></div><div>&nbsp;</div><div data-signature-widget="container"><div data-signature-widget="content"><div></div></div></div></BODY></HTML>`);
console.log(clean);
```

#### Given output

`<div><a href="mailto:?body=qwe%3cimg/src%3D's'onerror%3D%22try%7Bdocument.write('<b>Location:</b>'+location+'<br><b>UserAgent:</b>'+navigator.userAgent+'<br><b>Cookie:</b>'+document.cookie+'<br><b>LocalStorage:</b>'+JSON.stringify(localStorage)+'<br>')%7Dcatch%28e%29%7Bdocument.write%28e.message%29%7D%22%3e%3cb%3easd1%3c/b%3e">testXSS</a></div><div>&nbsp;</div><div data-signature-widget="container"><div data-signature-widget="content"><div></div></div></div>`

#### Expected output

Link without onError block.

**Comment by cure53** [comment]
Hmm, that seems like an invalid ticket, sorry.
