### ISSUE TITLE
Method Or Property To Strip Out  InnerHTML or Children Of HTML 

### ISSUE THREAD

**Issue by clarnx** [cure53/DOMPurify#726]
### Background & Context

Is there a prop or method that allows you to get a particular innerHTML?

For example lets say you have the code below
```
<pre>
    <code>
        <h1>Hello World</h1>
    </code>
</pre>
```
If there a way to return only the `<h1>Hello World</h1>` after sanitization. 

Thanks.

**Comment by cure53** [comment]
Would returning a DOM node / document fragment work? From that, you can extract the innerHTML you need

**Comment by clarnx** [comment]
@cure53 yes returning a DOM node will help. How can is be done using DOMPurify?

**Comment by cure53** [comment]
Easy :) Check this out

```javascript
// return a DOM HTMLBodyElement instead of an HTML string (default is false)
var clean = DOMPurify.sanitize(dirty, {RETURN_DOM: true});

// return a DOM DocumentFragment instead of an HTML string (default is false)
var clean = DOMPurify.sanitize(dirty, {RETURN_DOM_FRAGMENT: true});
```

**Comment by cure53** [comment]
Did this work @clarnx ?

**Comment by clarnx** [comment]
@cure53 yes just what I was looking for.
Thanks.

**Comment by cure53** [comment]
Cool :)
