### ISSUE TITLE
Special characters converted (like ™ or german ß)

### ISSUE THREAD

**Issue by huraji** [cure53/DOMPurify#727]
Using the sanitize function on special characters / symbols is preventing to show them properly.

For example:
- ™ is shown as lower case tm
- ß is transformed in double SS

Is there some configuration you can recommend, to keep these special characters?

**Comment by cure53** [comment]
Can you add some code that showcases the issue? OI cannot seem to reproduce.

**Comment by cure53** [comment]
Cannot reproduce, please reopen if you have a clean repro,
