### ISSUE TITLE
thead tag content has been removed

### ISSUE THREAD

**Issue by Snehal1112** [cure53/DOMPurify#733]
> This issue proposes a [bug, feature] which...

### Background & Context
When we try to convert HTML content to plain text the content of thead tag has been removed

I am trying the following way to convert the HTML content to plain text

DOMPurify.sanitize(`<table border="1"><thead><tr><th>Month</th></tr> </thead> <tfoot> <tr><td>Sum</td></tr> </tfoot> <tbody> <tr><td>January</td></tr> <tr><td>February</td></tr> </tbody></table>`, {USE_PROFILES: { html: false}});

#### Given output

'  Sum   January February '

#### Expected output

'Month  Sum   January February '

Please correct me if I use DOMPurify wrongly.

Thanks in advance

**Comment by cure53** [comment]
Ah, that is likely a browser-based behavior that happens when the table element is removed. Not sure if we can do much here without introducing a weird edge-case.

Why not just use `innerText` if you only want text and no HTML? A sanitizer might be the wring tool here.
