### ISSUE TITLE
Forbid nested element p > table

### ISSUE THREAD

**Issue by Hideman85** [cure53/DOMPurify#735]
I am looking for the option to forbid some nested element and if the rules is followed then unwrap the element.
I have some really dirty html like table in p, p in table dont ask me why (I think this is coming from copy pasting content from GDoc).

Here is my sample:
```js
(() => {
  const DOMPurify = require('dompurify');
  const JSDOM = require('jsdom').JSDOM;
  const html = '<p style="text-align: left;"><table><p><tr><td><p></p><p>Hello</p><p></p></td></tr></p></table></p>';
  
  const dompurify = DOMPurify(new JSDOM('').window);
  
    dompurify.addHook('afterSanitizeElements', (elem) => {
    if (elem.nodeName === 'P' && elem.innerHTML === '') {
      return elem.parentNode.removeChild(elem);
    }
    return elem;
  });

  console.info(dompurify.sanitize(html));
})()
// <p style="text-align: left;"><table><tbody><tr><td><p>Hello</p></td></tr></tbody></table></p>
```

The result is really great, I ran it on the whole doc and it is pretty fine except I want to forbid p > table and then if this is the case unwrap the p from the table.

My desired output:
```html
<table><tbody><tr><td><p>Hello</p></td></tr></tbody></table>
```

Note I checked the different options and I feel right now the only way is using the hook and doing it manually. Is there any built in way to do that? Do you think this make sense to have native support of this? Like the table > p has been removed and table > tbody is in the output :thinking: 

I am looking forward to your feedback.

**Comment by cure53** [comment]
Heya, I think indeed the best way is to use a hook. 

Basically, hook into element sanitization, check if you have a table, check if it contains a paragraph, eliminate the table, save the paragraph. That should do, no?

See here for an example: https://github.com/cure53/DOMPurify/blob/main/demos/hooks-node-removal2-demo.html#L51

**Comment by Hideman85** [comment]
Yes I came to handcraft a solution to this, I would love to see an official support for sure.

```html
IN <p style="text-align: left;">Hello<table><p><tr><td><p></p><p>Hello</p><p></p></td></tr></p></table> world <span>thing</span> <b>bold</b><div>Hello</div></p>
OUT <p style="text-align: left;">Hello</p><table><tbody><tr><td><p>Hello</p></td></tr></tbody></table><p style="text-align: left;"> world <span>thing</span> <b>bold</b></p><div>Hello</div>
```

**Comment by cure53** [comment]
Official support via core features is very unlikely to happen because 

a) you can do that with a hook and 
b) we're a sanitizer, not a markup manager :smile: 

If we support features outside our core mission, we will eventually create bypasses by accident.

**Comment by Hideman85** [comment]
But then why tbody is introduced in the table if it is not in the source html? :thinking:

**Comment by cure53** [comment]
The browser does this, to auto-repair the HTML.

**Comment by Hideman85** [comment]
Okey got you, thanks for this feedback then I guess this is not an issue and can close it there :wink:
