### ISSUE TITLE
use attributes only on specified tags 

### ISSUE THREAD

**Issue by canbax** [cure53/DOMPurify#736]
Can we force allowing an attribute only for specific tags? For example: I want to enable "target" attribute only for "a" tags.

Thanks for this nice library!

**Comment by Vinoth-deva** [comment]
yes its possible, please look into this [https://github.com/cure53/DOMPurify/issues/700#issuecomment-1187740728](comment) 
` const cleanHTML = DOMPurify.sanitize(content, {
          USE_PROFILES: { html: true },
          ADD_ATTR: ['target']
        })`
