### ISSUE TITLE
DOMPurify.sanitize() doesn't work, in case of escaped tags

### ISSUE THREAD

**Issue by gitmhd** [cure53/DOMPurify#738]
> DOMPurify.sanitize() doesn't work

`### DOMPurify.sanitize("<p>&lt;img src onerror="alert('Strange behavior!')" /&gt;</p>")
`
In the above example I tried to purify the input from xss vulnerablity, but it doesn't work.
I think that because the img tag is escaped.

#### Given output

`Given output is: <p>&lt;img src onerror="alert('Strange behavior!')" /&gt;</p>
`
#### Expected output

`The expected output: <p>&lt;img src/&gt;</p>
`

**Comment by cure53** [comment]
Exactly :) We don't sanitize escaped HTML, wouldn't make any sense to do that.

**Comment by gitmhd** [comment]
Hi,

It'll make I think :)

Let take this scenario as example.
Let say that there is a backend server that listen and handle requests made
to it, and each request go through some middlewares before reach out the
logic that handle it, and there's one of these middlewares escapes data
that sent with requests, and for some reason I decided to sanitize the data
before I save it to the database, in the targeted logic.

I hope you could get my point,

Thanks.

**Comment by cure53** [comment]
If weird things happen somewhere in the stack, it's not DOMPurify's job to clean that up. Imagine, we already did that - then someone could come and say "yeah but what if the text is double-encoded?"

We sanitize HTML (and XML), so you need to feed us HTML (or XML). If you feed us something different, we cannot guess what might happen and do things, assuming they make sense.

Imagine  the fallout if we started doing this all of a sudden. Thousands of applications would break.

**Comment by gitmhd** [comment]
Understood,
Thanks :)
