### ISSUE TITLE
Package description is too long for npm

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [cure53/DOMPurify#74]
Look here: https://www.npmjs.com/package/dompurify

This is what it looks like:

> dompurify

> DOMPurify is a DOM-only, super-fast, uber-tolerant XSS sanitizer for HTML, MathML and SVG. It's written in JavaScript and works in all modern browsers (Safari, Opera (15+), Internet Explorer (10+), Firefox and Chrome - as well as almost anything else usin

> DOMPurify is written by security people who have vast background in web attacks and XSS. Fear not. For more details please also read about our Security Goals & Threat Model

Breaking up that second line using a newline in the README should probably fix it.

**Comment by fhemberger** [comment]
I just added a break, this should be fixed with the next release pushed to npm.

**Comment by cure53** [comment]
Thx :) Okay to close this one for now?
