### ISSUE TITLE
Your code causes an entire site to not load.

### ISSUE THREAD

**Issue by ugobey** [cure53/DOMPurify#742]
> This issue proposes a bug which causes an entire site to not load when injected in the load of the page.

### Background & Context

Go to https://www.denbypottery.com/ and inject your library on page load, just before the visual part of the page shows and you will see the page will not load.

Page loads fine without your script

![image](https://user-images.githubusercontent.com/54430605/205681231-81676a8d-c9bc-40ed-b300-9492a97690db.png)

Page doesnt load with your script

![image](https://user-images.githubusercontent.com/54430605/205681428-fe737918-c9b6-4517-b21c-23fe7965d38d.png)

**Comment by paddotk** [comment]
You'll have to provide some more information, this is little to go on. How did you install/import the package? How are you using it?
Also, your network tab shows a warning, make sure whatever is causing that is not getting in the way.
