### ISSUE TITLE
Error: Module "fs" has been externalized for browser compatibility [..]

### ISSUE THREAD

**Issue by paddotk** [cure53/DOMPurify#743]
> This issue proposes a bug which...

### Background & Context
An error is thrown when using the library. The sanitation works, though the error does prevent some parts of my app to run normally.
This is used in a Vue/Nuxt app, running client-side.

### Bug
The error `Module "fs" has been externalized for browser compatibility. Cannot access "fs.promises" in client code.` is thrown.

I'm using the following setup from the readme.
```javascript
import { JSDOM } from 'jsdom';
import DOMPurify from 'dompurify';

const window = new JSDOM('').window;
const purify = DOMPurify(window);
const clean = purify.sanitize('<b>hello there</b>');
```
Not only is it strange that this library uses filesystem (why would it need to?), but this causes it to not work properly client-side.

P.S. when using the 'regular' way, it does not work at all:
```javascript
import * as DOMPurify from 'dompurify';
let clean = DOMPurify.sanitize('<b>hello there</b>');
```

#### Input
Anything, doesn't make a difference

#### Given output
The expected output is returned.

**Comment by cure53** [comment]
I am not really sure what to do with this ticket, we don't use `fs` (you are right, why would it need to :D) and I think it might be JSDOM what's messing things up here.

Have you checked that part of the docs per chance?
https://github.com/cure53/DOMPurify#running-dompurify-on-the-server

Maybe that solved it already? It seems like not our bug, but not 100% sure :smile:

**Comment by cure53** [comment]
Closing this issue under the strong assumption that it's not our bug, please reopen if it is.
