### ISSUE TITLE
DomPurify adding head tag

### ISSUE THREAD

**Issue by sureshsweb** [cure53/DOMPurify#744]
how to avoid **head** tag here
```
var dirty = '<html><body><h1>This is a Heading</h1></body></html>';
var output = DOMPurify.sanitize(dirty, {WHOLE_DOCUMENT:true});
console.log(output);
```

output will be `<html><head></head><body><h1>This is a Heading</h1></body></html>`

**Comment by sureshsweb** [comment]
here in my use case , i have to sanitize and keep the user entered text as it is.

**Comment by cure53** [comment]
Tadaa :smile: 

```javascript
var dirty = '<html><body><h1>This is a Heading</h1></body></html>';
var output = DOMPurify.sanitize(dirty, {WHOLE_DOCUMENT:true, FORBID_TAGS: ['head']});
console.log(output); 
```

**Comment by SureshbUshur** [comment]
@cure53  thanks for the quick response

above solution will fail if the user input has head tag 
for example `var dirty = '<html><head><style></style></head><body><h1>This is a Heading</h1></body></html>';`

**Comment by sureshsweb** [comment]
@cure53 thanks for the quick response

above solution will fail if the user input has head tag
for example `var dirty = '<html><head><style></style></head><body><h1>This is a Heading</h1></body></html>';`

**Comment by cure53** [comment]
No, it works as well, just tested.

**Comment by SureshbUshur** [comment]
its not working you can check here 
https://jsfiddle.net/suresh0589/subqpo4c/

**Comment by cure53** [comment]
Please describe your problem in more detail, it is unclear what is missing here. 
The head tag is being removed successfully, this is what the ticket claims to be the issue.

**Comment by cure53** [comment]
If the idea is to make sure that the head tag **stays** if actually present in user provided HTML, then the best way to approach this is by using a hook and making sure that you treat the markup as you need it. 

The `uponSanitizeElement` hook would likely be the way to go - by checking if no head was present before and then removing it if so: https://github.com/cure53/DOMPurify#hooks

**Comment by sureshsweb** [comment]
The problem is DOMPurify is adding missing html structure 

for example
- `<html><body><h1>This is a Heading</h1></body></html>` returns `<html><head></head><body><h1>This is a Heading</h1></body></html>  `
- `<table><tr><td>Table</td></tr></table>` returns `<html><body><table><tbody><tr><td>Table</td></tr></tbody></table></body></html>`

here in the first example extra head tag is added and in the second example html, head, body and tbody tags got added when pass through domPurify with   WHOLE_DOCUMENT:true

what i require is the out put should not change

**Comment by cure53** [comment]
Not a bug, it's the browser who adds those tags, not DOMPurify itself.

The tags would be added anyway upon being rendered in the browser - but if you really have to get rid of them, you can do that with a hook as described (and showcased in several demos using hooks).
