### ISSUE TITLE
release 2.4.2 has code version still set to 2.4.1

### ISSUE THREAD

**Issue by joebordes** [cure53/DOMPurify#749]

**Comment by johnbirds** [comment]
And now you have a version 2.4.3, but version in package-lock.json is still on 2.4.2 (same dependabot-commit) ...

**Comment by cure53** [comment]
I am unsure what's happening, our deploy script has not changed :disappointed:

**Comment by johnbirds** [comment]
No problem for me since I'm only using distribution-version.

**Comment by cure53** [comment]
Gotcha, thanks - we are making some changes and will soon phase out MSIE support along with a larger maintenance release. If you don't see any problems with the current state,  we would ignore the issue for now and soon go 3.0.9. Sgty?
