### ISSUE TITLE
Bad test for prototype pollution check

### ISSUE THREAD

**Issue by ElizarBatin** [cure53/DOMPurify#751]
Bad prototype pollution [test](https://github.com/cure53/DOMPurify/blob/main/test/test-suite.js#L1705)

This test added after security [fix](https://github.com/cure53/DOMPurify/commit/d1dd0374caef2b4c56c3bd09fe1988c3479166dc)

if we look at the [utils.js](https://github.com/cure53/DOMPurify/blob/main/src/utils.js#L2), we can see that hasOwnProperty destructured from Object. Therefore to pollute hasOwnProperty in utils.js we should make prototype pollution before DOMPurify import. In this [test](https://github.com/cure53/DOMPurify/blob/main/test/test-suite.js#L1705) we pollute object after DOMPurify import. Now this test is useless and successfully passed on v2.4.1

**Comment by ElizarBatin** [comment]
![2023-01-06-194800_1092x806_scrot](https://user-images.githubusercontent.com/117418547/211058775-90b189bb-965f-4574-aaa5-728a5ab4b3be.png)
![2023-01-06-194823_1082x937_scrot](https://user-images.githubusercontent.com/117418547/211058832-16b204fb-eec6-401e-8d2e-99679d0e145b.png)

**Comment by cure53** [comment]
Thanks, that's a known issue. We are doing some refactoring right now and hope to address this afterwards.

**Comment by cure53** [comment]
Just FYI, we will remove the test for now and add later after refactoring, thx again :)
