### ISSUE TITLE
add configuration property to allow binding a custom value to a custom attribute

### ISSUE THREAD

**Issue by GrumpfGrincheux** [cure53/DOMPurify#753]
Hello, would it possible to do something ... 
` const config = { `
`    ALLOWED_TAGS: ["p", "li", "button"], `
`    KEEP_CONTENT: true,`
`    ADD_ATTR: { attr: "onclick", value: "someFunction()"},`  <= ... like this ?
`    RETURN_DOM: true,`
` };`
` const sanitizedHTML = DOMPurify.sanitize(html, config);`

**Comment by cure53** [comment]
Should be doable with a hook :) You could use any of the attribute hooks and do the checks in there.

**Comment by GrumpfGrincheux** [comment]
Works fine like this, and removes pre existing `onclick=""`  attributes in the node

```
const html1 = '<p onclick="some script">Some text</p>';
const html2 = '<p >Some other text</p>';

const config = {
	ALLOWED_TAGS: ["p"],
	RETURN_DOM: true,
};

DOMPurify.addHook("uponSanitizeAttribute", function (currentNode) {
	if (currentNode.classList.contains("result-espece")) {
		currentNode.setAttribute(
			"onclick",
			`onClickDoSomething('${currentNode.innerText}')`,
		);
	}
});

const sanitizedHTML1 = DOMPurify.sanitize(html1, config);
// <p>Some text</p>

const sanitizedHTML2 = DOMPurify.sanitize(html2, config);
// <p onclick="onClickDoSomething('Some other text')">Some other text</p>
```
