### ISSUE TITLE
[Bug] HTML encoded self closing tags in attribute values leads to the removal of the attribute

### ISSUE THREAD

**Issue by AndreVirtimo** [cure53/DOMPurify#761]
When I use html encoded content in an attribute self closing tags leads to the removal of the whole attribute.

### Background & Context

Self closing tags like `<br />` or `<img />` are usually converted to single tags (`<br>`,`<img>`), which is totally fine.

#### Input

`<p data-qtip="&lt;br/&gt;">foo</p>`

#### Given output

`<p>foo</p>`

#### Expected output

`<p data-qtip="<br>">foo</p>`

### Working example with single tag

When I'm using single tags, the output is as expected:

#### Input

`<p data-qtip="&lt;br&gt;">foo</p>`

#### Given output

`<p data-qtip="<br>">foo</p>`

**Comment by AndreVirtimo** [comment]
Here is another input which leads to removal of the attribute. It seems that the HTML Encoding is not necessary to reproduce the issue.

### Input

`<input type="text" value="foo <br/>">`

### Given output

`<input type="text" >`

### Expected output

`<input type="text" value="foo <br/>">`

**Comment by cure53** [comment]
Heya, thanks for filing the issue. However, it's not a bug but a protection against an mXSS issue that has been plaguing browsers for a while. Allowing this will cause XSS.  

You can likely work around that using a hook, but then you'd have to accept the mXSS risk, in case the attribute content is user-controlled.

**Comment by AndreVirtimo** [comment]
I don't know why the whole attribute is removed. Shouldn't it be enough to change the <br/> to <br> at that point?

When I'm sanitizing <br/> not as attribute value it also get transformed to <br> and won't be removed.

**Comment by cure53** [comment]
The default is of course removal as we offer a sanitizer library, so scrubbing is the way to go :smile: 

But, you can override that easily with a hook and then do what works in your context.

**Comment by edg2s** [comment]
Downstream issue affecting Wikipedia: https://phabricator.wikimedia.org/T279215#8525105

Per the inline comment, this appears to be fixing an issue in an old version of jQuery, and previously could be disabled with a flag.

> But, you can override that easily with a hook and then do what works in your context.

To work around this with a hook would require re-implementing all the transforms and checks that are done to see if the attribute is about to be removed (SAFE_FOR_TEMPLATES, isValidAttribute), unless I have missed something?

**Comment by edg2s** [comment]
Could we add back in a renamed flag to disable the feature, e.g. ALLOW_SELF_CLOSE_IN_ATTR (default is false)?

**Comment by cure53** [comment]
Not a huge fan of the idea but if that saves the day, a PR is welcome :smile: 

Please check for which branch you need it, 2.x (MSIE is supported) or 3.x (MSIE is no longer supported).

**Comment by AndreVirtimo** [comment]
For my case I have now added the following hook. But I would prefer @edg2s solution when it is merged.

```
DOMPurify.addHook(
  'uponSanitizeAttribute',
  function (currentNode, hookEvent, config) {

    if(hookEvent.attrName === "value"){
        hookEvent.forceKeepAttr = true;
    }

    return currentNode;
  }
);
```

**Comment by cure53** [comment]
Alright, I added the flag plus test to the 2.x branch. Does that do the trick for you @edg2s ?

https://github.com/cure53/DOMPurify/commit/5f766bced9465eb9e1ffebfefc87e8ef0c75df48

If so, we will also consider adding this to main, release 3.0.0 and 2.4.4.

**Comment by AndreVirtimo** [comment]
Thank you @edg2s for the PR.
Thank you @cure53. Do you have an estimated release date?

I will give feedback when we can test the next release.

**Comment by cure53** [comment]
Hey all, we would like to release but need some confirmation that the change works as expected :smile: 

Could you confirm it works as expected? @AndreVirtimo @edg2s

**Comment by AndreVirtimo** [comment]
@cure53 I have tested https://github.com/cure53/DOMPurify/commit/5f766bced9465eb9e1ffebfefc87e8ef0c75df48 with the flag ALLOW_SELF_CLOSE_IN_ATTR set to true. This worked for me and my previously postet workaround isn't needed any more.

**Comment by cure53** [comment]
This should be fixed now in all latest releases
