### ISSUE TITLE
[Bug] iframe elements containing child nodes are still removed after adding iframe as an allowed tag

### ISSUE THREAD

**Issue by mkzhx** [cure53/DOMPurify#766]
After configuring `{ ALLOWED_TAGS: [ "iframe" ] }`, `iframe` elements containing child nodes are still removed by DOMPurify.

### Background & Context

TinyMCE implements DOMPurify for HTML sanitisation. One of our customers reported that `iframe` elements containing child nodes are removed, even though we have allowed iframe elements in the configuration. We understand that `iframe` elements containing child nodes do not adhere to HTML standards, but we believe that the content should not be altered by DOMPurify considering we have configured iframes to be allowed and the child nodes do not pose a security risk.

Example: https://codepen.io/mkzhx/pen/BaPegaX

#### Input

```
<iframe src="https://example.com/"></iframe>
<iframe src="https://example.com/"><p>Lorem ipsum</p></iframe>
```

#### Given output

```
<iframe src="https://example.com/"></iframe>

```

#### Expected output
Remove all child nodes from the iframe but keep the iframe.
```
<iframe src="https://example.com/"></iframe>
<iframe src="https://example.com/"></iframe>
```
Or, preserve all content including children where there is no security risk:
```
<iframe src="https://example.com/"></iframe>
<iframe src="https://example.com/"><p>Lorem ipsum</p></iframe>
```

**Comment by cure53** [comment]
Heya, we have iframes on our list of elements where contents are removed by default, see here: https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L300

Did you already try to work around that with a hook? It should do the trick if you want to override the behavior.

**Comment by mkzhx** [comment]
We have no concern with removing the contents of `iframe` as is configured by default. We are unsure why the parent `iframe` itself is removed when there is content within. Is this expected behaviour of content removal to remove the parent too regardless of the parent's validity?

**Comment by cure53** [comment]
The problem appears to be this code segment here, that we use to prevent mXSS in some situations:

```javascript
/* Detect mXSS attempts abusing namespace confusion */
if (
  currentNode.hasChildNodes() &&
  !_isNode(currentNode.firstElementChild) &&
  (!_isNode(currentNode.content) ||
    !_isNode(currentNode.content.firstElementChild)) &&
  regExpTest(/<[/\w]/g, currentNode.innerHTML) &&
  regExpTest(/<[/\w]/g, currentNode.textContent)
) {
  _forceRemove(currentNode);
  return true;
}
```

It checks whether the node has a child that is not an element but contains HTML-like data. Inside the iframe, the HTML is not parsed, no it's not an element, but it looks HTML-ish so DOMPurify says "okay, this thing has to go".

I am not sure if we can fix that without creating a bypass. Best try to work with a hook but handle with care, this might enable bad things and appears to be thin ice :sweat_smile:

**Comment by cure53** [comment]
If you want to fix this with a hook, then `uponSanitizeElement` would be the right one.

**Comment by TheSpyder** [comment]
Interesting, this might solve other similar problems we're having as well. We already use [an `uponSanitizeElement` hook](https://github.com/tinymce/tinymce/blob/e1df231dfb23b4f5c8e767eadfda907fb56f4d81/modules/tinymce/src/core/main/ts/api/html/DomParser.ts#L124) - how would we use that to solve the problem? There doesn't seem to be a way to adjust how that code works with a hook, or did you mean removing the child elements in the hook?

**Comment by cure53** [comment]
I would probably go at it as follows:

* Check if it's an iframe
* Check if it has "child nodes"
* If so, take the content, shove it in an attribute (like, "data-content" or alike)
* After sanitization, take content from all those attributes, reapply to iframe

That should do the trick me thinks :sweat_smile:

**Comment by cure53** [comment]
Out of curiosity whether this works, I created some really bad JavaScript and it seems to do the trick:

```javascript
var dirty = '<iframe></iframe>\n<iframe><p>hello</p></iframe>\n<iframe><img src=x onerror=alert(1)></iframe>';

DOMPurify.addHook('uponSanitizeElement', function(currentNode, data, config) {
    if (currentNode.tagName === 'IFRAME' && currentNode.innerHTML) {
        currentNode.setAttribute('data-tmp-html', currentNode.innerHTML);
        currentNode.innerHTML = ''; 
    }
});
            
DOMPurify.addHook('afterSanitizeElements', function(currentNode, data, config) {
    if (currentNode.tagName === 'IFRAME' && currentNode.getAttribute('data-tmp-html')) {
        currentNode.innerHTML = currentNode.getAttribute('data-tmp-html');
        currentNode.removeAttribute('data-tmp-html');
    }
});

var clean = DOMPurify.sanitize(dirty, {ADD_TAGS: ['iframe']});
console.log(clean);

// <iframe></iframe>
// <iframe><p>hussah</p></iframe>
// <iframe><img src=x onerror=alert(1)></iframe>
```

**Comment by TheSpyder** [comment]
That's much better than our initial experiment with iframe detection which just removed the child elements. We can probably use this to bypass the mXSS code in some other areas we've been having problems with - things that understandably DOMPurify sanitises but clients want us to retain in the document.

Thanks for your help!

**Comment by mkzhx** [comment]
Thanks for your detailed and helpful response, we can close this issue here.

**Comment by cure53** [comment]
Most welcome :)
