### ISSUE TITLE
The `shadowroot` attribute gets special treatment, but the new `shadowrootmode` attribute should too

### ISSUE THREAD

**Issue by mfreed7** [cure53/DOMPurify#767]
See the code:

https://github.com/cure53/DOMPurify/blob/main/src/purify.js#L1465

The `shadowroot` attribute, which triggers "old-style" declarative shadow DOM, gets special treatment. See this issue for context: https://github.com/cure53/DOMPurify/issues/584

Recently, the declarative Shadow DOM feature has had renewed interest, and as part of that conversation, the `shadowroot` attribute was renamed to `shadowrootmode`. Chrome has [shipped this new attribute in M111](https://chromestatus.com/feature/5161240576393216). Chrome also will [continue supporting the old `shadowroot` attribute](https://chromestatus.com/feature/6239658726391808) for some time, as developers migrate.

I believe DOMPurify should be updated to look for *both* `shadowroot` and `shadowrootmode`.

@securitymb

**Comment by cure53** [comment]
Aye, thanks - that proposal looks good to me and and worth a change.

So, the changed syntax should be this? `if (ALLOWED_ATTR.shadowroot || ALLOWED_ATTR.shadowrootmode) {` ?

**Comment by mfreed7** [comment]
> Aye, thanks - that proposal looks good to me and and worth a change.
> 
> So, the changed syntax should be this? `if (ALLOWED_ATTR.shadowroot || ALLOWED_ATTR.shadowrootmode) {` ?

Looks right to me!

**Comment by cure53** [comment]
Cool, thanks - will add in 3.x and main :)

**Comment by cure53** [comment]
This should be fixed now!
