### ISSUE TITLE
It will return error string when sanitize `<div>Passcode:&#6LQ!a7</div>`

### ISSUE THREAD

**Issue by sundada88** [cure53/DOMPurify#768]
> This issue proposes a [bug, feature] which...

### Background & Context

Please provide some more detailed information about the general background and context of this issue and delete non applicable sections below.

#### Input

 var config = {
      ALLOWED_TAGS: ['div'], // only <P> and text nodes
  };
  // Specify dirty HTML
  var dirty = '<div>Passcode:&#6LQ!a7</div>';
  // Clean HTML string and write into our DIV
  var clean = DOMPurify.sanitize(dirty, config);
  // <div>Passcode:LQ!a7</div>
  console.log(clean)

#### Given output

It will show `<div>Passcode:LQ!a7</div>` which lack of `&#6`

#### Expected output

'<div>Passcode:&#6LQ!a7</div>'

### Feature

Briefly outline the proposed feature, its value and a potentially proposed implementation from a high level.

**Comment by cure53** [comment]
Not a bug :) Your input created an HTML entity: `&#6;` - it's still there, just not a visible character.

Test here: https://cure53.de/purify
Output: `<div>Passcode:LQ!a7</div>`
