### ISSUE TITLE
<img> with base64 image data causes the whole HTML to be erased

### ISSUE THREAD

**Issue by sandorvasas** [cure53/DOMPurify#769]
If I feed in any HTML content that somewhere has `<img src="data:image/png;base64,xxxxxxxx" />` in it, `DOMPurify.sanitize() ` returns an empty string.

dompurify 2.4.3
jsdom 15.2.1

**Comment by cure53** [comment]
Hm, not really, looks fine here - can you share more info please?

https://cure53.de/purify

IN: `<img src="data:image/png;base64,xxxxxxxx" />`
OUT: `<img src="data:image/png;base64,xxxxxxxx" />`

Works as expected, me thinks.
