### ISSUE TITLE
Update page "Security Goals & Threat Model" regarding MSIE

### ISSUE THREAD

**Issue by danielrentz** [cure53/DOMPurify#772]
### Background & Context

After update to 3.0.0, the page https://github.com/cure53/DOMPurify/wiki/Security-Goals-&-Threat-Model should be updated in the "Be compatible" area to not care about MSIE anymore.

**Comment by cure53** [comment]
Excellent point, thanks, I updated the page, should be accurate enough now?

**Comment by danielrentz** [comment]
Perfect, thanks!
