### ISSUE TITLE
Please preserve Outlook Conditional Statements

### ISSUE THREAD

**Issue by Julie-House** [cure53/DOMPurify#777]
> This issue proposes a bug whereby currently it will strip out all outlook conditional comments.

### Background & Context

We provide the ability for people to construct HTML for emails. Outlook is a nasty beast but we have to support it, which means people have to be able to create snippets which work in Outlook just as well as normal browsers. In order to create a button which is visible even with images blocked, you can use Outlook (mso) conditional comments to draw a rectangle, for example.

#### Input

```
<div><!--[if mso]>
  <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="mailto:email@email.com" 
style="height:40px;v-text-anchor:middle;width:100px;" arcsize="10%" strokecolor="#ffa100" fillcolor="#ffa100">
    <w:anchorlock></w:anchorlock>
    <center style="color:#ffffff;font-family:sans-serif;font-size:13px;font-weight:bold;">RSVP</center>
  </v:roundrect>
<![endif]--><a href="mailto:email@email.com"
style="background-color:#ffa100;border:1px solid #ffa100;border-radius:4px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:13px;font-weight:bold;line-height:40px;text-align:center;text-decoration:none;width:100px;-webkit-text-size-adjust:none;mso-hide:all;">
RSVP</a></div>
```

#### Given output

```
<div><a style="background-color:#ffa100;border:1px solid #ffa100;border-radius:4px;color:#ffffff;display:inline-block;font-family:sans-serif;font-size:13px;font-weight:bold;line-height:40px;text-align:center;text-decoration:none;width:100px;-webkit-text-size-adjust:none;mso-hide:all;" href="mailto:email@email.com">RSVP</a></div>
```

#### Expected output

no changes should be made

**Comment by cure53** [comment]
I think you can do that with either allowing comment nodes via allow.list or via a hook.

Maybe this already works for you? https://github.com/cure53/DOMPurify/issues/639

**Comment by Julie-House** [comment]
That's working thanks. Took me a while to check it was ok because it was changing the order of attributes!
