### ISSUE TITLE
Provide via nuget

### ISSUE THREAD

**Issue by Julie-House** [cure53/DOMPurify#778]
### Background & Context

Is there any way you could provide this via nuget? This solves our issue quite well, but I worry about our ability to remember to get updates without a nuget package!

### Feature

Publish to Nuget

**Comment by cure53** [comment]
Probably this is possible, but I have no knowledge about Nuget and what needs to be done in this realm :)

If you want to go for it, please feel free to do so - but on our end there is no bandwidth to add support for more package repos than we already provide.

**Comment by Julie-House** [comment]
[Create NuGet Package](https://learn.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli) This is the best I can give you! Wish I could help but i've only consumed packages.

**Comment by cure53** [comment]
I checked the link, thank you. Sadly it seems you need at least VisualStudio and we are not using that (not even using Windows) :D 

If someone wants to take that task, happy to support but no way we'll be able to add into our existing workflow, sorry.
