### ISSUE TITLE
Question: Why are arrows stripped out?

### ISSUE THREAD

**Issue by bubbletroubles** [cure53/DOMPurify#779]
> This issue asks a question

### Background & Context

Azure DevOps uses DOMPurify to sanatise .svg files in the Wiki. Whenever we host a SVG file on Azure DevOps wikis, the arrows are not visible. Microsoft confirms DOMPurify is used as per [this link](https://developercommunity.visualstudio.com/t/referenced-svg-images-dont-work-in-azure-devops-wi/619280#T-N772627)

### How to reproduce

The page https://dev.azure.com/bubbletroubles/wiki/_wiki/wikis/wiki/2/SVG-no-arrows is a sample wiki file that has a link to the original SVG (with arrows, before DOMPurify), and without arrows (after DOMPurify). 

### Expected result
Arrows are retained in SVG files after parsed with DOMPurify.

**Comment by cure53** [comment]
The SVG makes use if the `<use>` element which is not allowed by default, so you need to manually add that element via `ADD_TAGS` and be aware of possible XSS risks.

**Comment by cure53** [comment]
Should be solved, closing this for now
