### ISSUE TITLE
Removed all content from html tags

### ISSUE THREAD

**Issue by Ushur-Jai** [cure53/DOMPurify#787]
Here I am trying below example
**input,**
`<scrIpt>alert('1')<scrIpt><h1>welcome</h1>`

**expected**
`<h1>welcome</h1>`

**output**
`<empty>`

**Comment by Ushur-Jai** [comment]
using DOMPurify 2.4.0

**Comment by Ushur-Jai** [comment]
could you please try now similar example:
`<scrIpt>alert('1')<scrIpt><h1>welcome</h1>`

<script> we dont have end tag. user forgot to add end tag.

**Comment by Ushur-Jai** [comment]
![image](https://user-images.githubusercontent.com/92841932/228555918-789b2ceb-192c-4ccd-bb6b-7c12e39944be.png)

**Comment by cure53** [comment]
That is actually expect behavior given that the script element never closes.

**Comment by Ushur-Jai** [comment]
Is there any way we can handle these kind of unbalanced tags? We have any kind of configuration.

**Comment by cure53** [comment]
As far as I can see, not without introducing risks greater than losing some legitimate content. We make use of the browser's parser and overriding that might have terrible consequences.
