### ISSUE TITLE
DOM Purify fix still pops up as vulnerability in Fortify XSS Scans

### ISSUE THREAD

**Issue by sajanyamaha** [cure53/DOMPurify#799]
Am I doing anything wrong here , trying to fix a XSS vulnerability which popped up in Fortify scans ,

Before ,
`$(window.opener.document).find(tableId + ' .PROMO_NM').val('Y');`

After ,
`$(window.opener.document).find(tableId + ' .PROMO_NM').val(DOMPurify.sanitize('Y'));`

On rescan the vulnerability stays !

**Comment by cure53** [comment]
I would assume that the issue might be the `tableId` on `find()`- but this or the other way that strikes me as a false alert in Fortify. Not our bug :)
