### ISSUE TITLE
SonarQube - Vulnerability Critical issue raised in purify.js

### ISSUE THREAD

**Issue by gauravoza1710** [cure53/DOMPurify#802]
> This issue proposes a Vulnerability that results as an 'Expected an assignment or function call and instead saw an expression' for the below code.

![image](https://user-images.githubusercontent.com/117167054/235904780-37bd9f92-1ab6-4ca5-b448-6f17b059e2ee.png)

also, SonarQube raises 2 more Vulnerabilities that result in 'Unsafe usage of ThrowStatement' for the SonarQube scan report in the same file as below.

![image](https://user-images.githubusercontent.com/117167054/235905207-dd9f0b63-7d25-4c05-b7e8-3f2e910d1a9e.png)

![image](https://user-images.githubusercontent.com/117167054/235905266-b9392bc0-cf8a-41a3-b24a-263d2e8f7d0d.png)

purify.js is from DOMPurify 3.0.1. And I also checked for changes in DOMPurify 3.0.2 but no updates are there.

It causes our security param fails so what should I do for this.

**Comment by cure53** [comment]
Please do not file tickets about random code scanner false alerts at us, those are not our bugs and we have no bandwidth to handle those. If you have the feeling that SonarQube produces false alerts, contact them, not us, thanks!
