### ISSUE TITLE
[QUESTION] How to use in a React Native project?

### ISSUE THREAD

**Issue by JeremyBradshaw7** [cure53/DOMPurify#806]
I want to sanitise html that is user-input before I render it in a react-native-webview. However, I'm getting this error : 

`TypeError: _dompurify.default.sanitize is not a function`

in the console. I've added both the latest `dompurify` and `@types/dompurify` packages, and imported thus:

`import DOMPurify from 'dompurify';`

I'm calling the sanitize function _outside_ the webview in the React Native realm, to sanitize the content _before_ passing that content to the webview. 

One issue may be that I don't have a DOM engine. I tried the Node approach (meant for servers) but unfortunately installing `jsdom` as well completely broke the compilation, so instead I plan to use `jsdom-jscore-rn`.

This is shown i the console if I log the package:

![image](https://github.com/cure53/DOMPurify/assets/36155348/0db1d127-1eac-4089-b45d-8d13c1114d05)

So it is importing it as it's finding the version, but is instantiated as not supported.

**Comment by cure53** [comment]
To be frank, no idea - sorry :smiling_face_with_tear: 

Most use-cases should be solvable using the documentation here: 
https://github.com/cure53/DOMPurify#using-the-minified-and-tested-production-version-source-map-available

Everything else we don't really know and would have to investigate ourselves.

**Comment by JeremyBradshaw7** [comment]
Closing as I dont think it is possible.
