### ISSUE TITLE
[QUESTION] How to sanitize style tags and attributes

### ISSUE THREAD

**Issue by JeremyBradshaw7** [cure53/DOMPurify#808]
I plan to allow style tags and attributes through, but I do want to strip out any security vulnerabilities from them, such as any `expression` or `javascript:` use as discussed [here](https://stackoverflow.com/questions/4546591/xss-attacks-and-style-attributes).

How can that be achieved in dompurify?

**Comment by cure53** [comment]
Why? Is MSIE6 part of your threat model? If so, DOMPurify won't work anyway and for no other browser, those kinds of sanitizations are actually needed.
