### ISSUE TITLE
DOMPurify.sanitize() cannot access object before initialization

### ISSUE THREAD

**Issue by zima702** [cure53/DOMPurify#813]
This issue proposes a bug with the use of DOMpurify.sanitize() in versions 3.0.2 and 3.0.3

The issue stems from the use of DOMpurify.sanitize() in versions 3.0.2 and 3.0.3. An Uncaught ReferenceError appears in Chrome DevTools (Chrome v113.0.5672.137) and blocks the use of sanitize(). The issue seems to be related to the clone(object) function, with the error arising due to the use of entries(object). This issue does not present itself in version 2.4.5. 

Valid form html is passed to sanitize()
No string is returned from sanitize()

Chrome DevTools Uncaught ReferenceError
![IMG_7565](https://github.com/cure53/DOMPurify/assets/129331879/c540ad00-f0ce-4c51-ad08-27ba60842758)

Invalid function clone(object) from 3.0.2 and 3.0.3
![IMG_7566](https://github.com/cure53/DOMPurify/assets/129331879/4c3b7a88-6083-4ebc-bb01-f532ea858305)

Valid function clone(object) from 2.4.5
![IMG_7567](https://github.com/cure53/DOMPurify/assets/129331879/70659315-1e7b-44e0-a695-5c3eeb415d67)

**Comment by cure53** [comment]
Heya, thanks for filing this. We have trouble reproducing the issue, can you share more details please?
