### ISSUE TITLE
How to sanitize api response server side?

### ISSUE THREAD

**Issue by grantspilsbury** [cure53/DOMPurify#821]
Help / discussion

### Background & Context

I have an Express Request Handler that takes a request, which includes user form input (email), makes a request to another one of my (trusted) endpoints (via newFunctionWithRequest), and then returns data from that new response (newResponse).

```
export const Handler = async (req: Request, res: Response, next: NextFunction) => {
  const { newResponse } = await newFunctionWithRequest(req)
  res.send(newResponse.data) // Snyk identifies this line as the problem
}
```

Snyk has identified a XSS vulnerability:

Unsanitized input from the HTTP request body flows into send, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS)

Am I able to use DOMPurify for this use case? I tried to sanitize the request as well as the response but sanitize expects a DOM node or string.

Any guidance would be much appreciated.

**Comment by cure53** [comment]
Yep, did you try this per chance?

https://github.com/cure53/DOMPurify#running-dompurify-on-the-server

**Comment by cure53** [comment]
Closing this for now as there is nothing to fix
