### ISSUE TITLE
Json value missed up while using Dompurify

### ISSUE THREAD

**Issue by AnjuDevkota** [cure53/DOMPurify#822]
i have input like <a href='link'>test</a>. it is a json value. but i am getting <a href="link">test</a> after sanitization. that means i am getting double quote on href by using dompurify.
and the problem is i need to pass this value in Json so it becomes " <a href="link">test</a>", which cause bad format json.
here is my code

   const sanitizedHtml = DOMPurify.sanitize(modifiedHtml, {
        ADD_TAGS: allowedTagsWithUnderscore
      });
      
      
![Uploading image.png…]()

**Comment by AnjuDevkota** [comment]
<img width="629" alt="image" src="https://github.com/cure53/DOMPurify/assets/98731560/6394f608-f225-4d03-86d1-bcd3bfa51f6b">

**Comment by cure53** [comment]
Closing this for now as there is nothing to fix
