### ISSUE TITLE
Apache license requires including full text of Apache license.

### ISSUE THREAD

**Issue by george-thomas-hill** [cure53/DOMPurify#832]
### Background & Context

The Apache licence has this requrirement: "You must give any other recipients of the Work or Derivative Works a copy of this License".

https://www.apache.org/licenses/LICENSE-2.0

### Bug

However, DOMPUrify's license file doesn't do that.

Would you please consider pasting in the full text?

Thank you.

**Comment by cure53** [comment]
Heya, thanks for noticing! The commit linked about should address the issue, please confirm.

**Comment by george-thomas-hill** [comment]
Looks good to me! Thank you for acting so quickly!

**Comment by cure53** [comment]
Cool :)
