### ISSUE TITLE
DOMPurify 2.4.6 not published on npm

### ISSUE THREAD

**Issue by 0xbb** [cure53/DOMPurify#834]
### Bug
Hello! I think version 2.4.6 was not published on npm. See https://www.npmjs.com/package/dompurify/v/2.4.6
Could you be so kind to check if the release got stuck somewhere?

**Comment by NormandoHall** [comment]
Now npm claims update to 2.4.6 but I have 3.0.4

**Comment by cure53** [comment]
Weird, try again please, we pushed 2.4.7 today.
