### ISSUE TITLE
Warnings mode?

### ISSUE THREAD

**Issue by devd** [cure53/DOMPurify#84]
Often in big web applications, one might have a good cut point to always insert purify calls. But, you can't be sure it won't break stuff. It would really help with rollout if we could pass a flag to dompurify where it would go through the tree and just get a list of nodes it would have removed if it was in enforcement mode. This can help track down nasty corner cases (which might even be vulns) and then once the warnings go down to zero, people can turn on enforcement mode.

This sort of stuff really helps in large scale deployment. CSP has this going for it.

What do you think? The simpler idea of "call purify and compare return value to input" doesn't work because the html tree serializations might have minor differences.

**Comment by cure53** [comment]
That makes a lot of sense. How should the warning mode work? With console logging? Or rather a DOM object being returned? Or a map of matched elements and attributes?

**Comment by devd** [comment]
I think anything that will tell me "list of things that DOMPurify would
have removed" would be good. Since this is very clearly something for
logging which will then go to the server and be collected across all
instances, I think we should optimize for that use case. So, e.g., a string
format is fine.

Maybe lets play with concrete examples? I think just an array of elements
and attributes that would have been cleansed would be enough for my use
case right now.

**Comment by cure53** [comment]
That should indeed be super-easy with a simple hook. No need to touch the core. A PR for a demo hook would be very welcome :)

**Comment by devd** [comment]
hah! I was worried you would say that. Ok, I should really learn how to
write hooks: seems all my feature requests end the same way :)

**Comment by cure53** [comment]
That's why we created that API :)

**Comment by devd** [comment]
hmm .. I looked a bit into how I would write the hook as a theoretical exercise and, maybe I am missing something, but there doesn't seem to be an event that is only called if the current attribute or element will be removed. For example, for the string <b onclick="alert(1)"  data-foo="bar">hi</b> (as far as I can tell), the uponSanitizeAttribute hook is called for onclick as well as data-foo. Is there some trick I am missing?

**Comment by cure53** [comment]
You can for example use `beforeSanitize` and `afterSanitize`. In the first hook you create a map of elements that exist. In the second, you have all elements that remain. That gives you all info you need to return a map of elements that were removed. 

As I understand, you would want to permit anything anyway. And only find out what would be removed. So, you wouldn't even touch the original string, correct?

**Comment by cure53** [comment]
Any assistance needed with the hook? Otherwise I'd love to close this one as I believe the intended functionality is available with the core-feature set.

**Comment by devd** [comment]
lets close this out; when I start implementing hook, I will reopen or email with issues.

**Comment by cure53** [comment]
Perfect, thanks!
