### ISSUE TITLE
Add dist to .gitIgnore

### ISSUE THREAD

**Issue by ssi02014** [cure53/DOMPurify#846]
Hello! 👏 @cure53 
I've been making good use of "DOMPurify" in my personal projects, and I'm very happy to contribute to the library. 😄

I have one improvement that I think needs to be discussed in advance, so I'm creating an issue.

Currently, Dompurify is uploading a build folder, `dist`, to the github repository.

In my opinion, the dist folder does not need to be uploaded to the github repository, this is only necessary when deploying to the actual npm. (As far as I know, many libraries don't upload build folders like dist to their github repositories.)

What do you think about adding a dist to gitIgnore?

If you agree with the above, I'd like to work on that. 
Alternatively, if there's a history I'm not aware of, please let me know! 🙏

**Comment by cure53** [comment]
I would prefer to leave things as they are in this regard. Removing it now might break things out there - and we prefer to offer our own builds here.

**Comment by ssi02014** [comment]
@cure53 
Oh yeah, I agree with your comment!
Thanks for the comment
