### ISSUE TITLE
How to allow tags with specific attr?

### ISSUE THREAD

**Issue by ShahriarKh** [cure53/DOMPurify#852]
This is not an issue; I have a question.
Is it possible to allow tags like `iframe` or `script` only if they have a specific `src` attribute?
I tried searching in the docs and some googling, but wasn't able to find the answer.

I want to do something like
```js
DOMPurify.sanitize(content, {ADD_TAGS: ['iframe', {src: "example.com"}]});
```
so only `iframes` coming from `example.com` are allowed. However, I can't find the correct syntax.

**Comment by cure53** [comment]
No core feature but you can easily do that with a hook, here are many examples:

https://github.com/cure53/DOMPurify/blob/main/demos/
https://github.com/cure53/DOMPurify/blob/main/demos/hooks-link-proxy-demo.html

**Comment by ShahriarKh** [comment]
Can you please give a full example on how to do this? Should the hook return the element? and what hook should I use?
