### ISSUE TITLE
Custom element attribute gets trimmed (end whitespace is deleted)

### ISSUE THREAD

**Issue by JSnow11** [cure53/DOMPurify#853]
> This issue proposes a bug

### Background & Context

When trying to pass an initial-value (string) attribute to a custom element it gets trimmed, the whitespaces at the end of it are disappearing.

#### Input
```js
sanitizer("<qz-element initial-value='test ' ></qz-element>", {
      CUSTOM_ELEMENT_HANDLING: {
        tagNameCheck: /^/,
        attributeNameCheck: /^/,
        allowCustomizedBuiltInElements: true,
      },
    })
```

#### Given output
```html
<qz-element initial-value="test"></qz-element>
```

#### Expected output

```html
<qz-element initial-value="test "></qz-element>
```

### I tried
```
ADD_DATA_URI_TAGS: ["qz-element"],
ADD_URI_SAFE_ATTR: ["initial-value"],
```

### Question

Is there any config to prevent this?, I couldn't find any

**Comment by cure53** [comment]
Sadly no, no config option for this :)
