### ISSUE TITLE
DOMPurify stripping valid html in xhtml mode

### ISSUE THREAD

**Issue by kjeyakanthan** [cure53/DOMPurify#865]
> This issue proposes a bug which seems to be stripping valid html after parsing a tag containing `&nbsp;`

### Background & Context

We are trying to sanitize user input from a KendoUI Editor component which outputs in XHTML which is later used in a XSL document.
The config used is { PARSER_MEDIA_TYPE: 'application/xhtml+xml' }

#### Input

`<p>abcd</p><p>abcd&nbsp;defg</p><p>efgh</p>`

#### Given output

`<p>abcd</p><p></p>`

#### Expected output

`<p>abcd</p><p>abcd&nbsp;defg</p><p>efgh</p>`

**Comment by thesunlover** [comment]
Could you please share the version number?

**Comment by kjeyakanthan** [comment]
Its 3.0.5. I will try with 3.0.6 as well

**Comment by cure53** [comment]
Have you tried this per chance? :smile: 

```javascript
console.log(
   DOMPurify.sanitize(
      '<p>abcd</p><p>abcd&nbsp;defg</p><p>efgh</p>', {
         PARSER_MEDIA_TYPE: 'text/xhtml'
      }
   ) // <p>abcd</p><p>abcd&nbsp;defg</p><p>efgh</p>
);
```

**Comment by kjeyakanthan** [comment]
Due to the fact the output is used as parameter in an XSLT transform, the data has to be in XML format (XHTML).

**Comment by cure53** [comment]
I see, however, the data you shared in the original post is not using valid XML. So, this is kind of a bit contradictory :) 

At the end of the day, it's the browser or JSDOM transforming what comes in before we even start sanitizing, so I believe it's not our bug or much we can do here.
