### ISSUE TITLE
Grunt build fails while building with the latest version of purify.min.js

### ISSUE THREAD

**Issue by farhank31** [cure53/DOMPurify#868]
JS_Parse_Error {
[INFO]   message: 'SyntaxError: Name expected',
[INFO]   filename: 'purify.min.js',
[INFO]   line: 2,
[INFO]   col: 239,
[INFO]   pos: 427,

**Comment by cure53** [comment]
We need more info here, not sure what can be done based on the error output.

**Comment by cure53** [comment]
cc @ssi02014 - maybe related to your latest PR? Not sure :slightly_smiling_face:

**Comment by ssi02014** [comment]
I didn't see anything in my latest `PR` that would be a problem, I'd need more information 🤔

https://stackoverflow.com/questions/39174738/working-js-code-gets-error-message-when-compressed-syntax-error-name-expecte

Does it resemble the reasons in the document above? I'm not sure.

**Comment by farhank31** [comment]
So basically i have used the purify.min.js files in one of my project, Earlier I was using version 2.3.4 and my build was successful, when i tried doing grunt build  with the latest version i am getting the above error.

**Comment by cure53** [comment]
Hmm, still now sure how we can actually fix this or if this is our bug after all, sorry. Please send more info and we shall reopen this ticket.

**Comment by aagrawal-solveda** [comment]
This is still there -- 

When we use ugly.js and minify purify.js we get same error 

stderr: Parse error at purify.min.js:2,239

stderr: SyntaxError: Name expected
Error
    at new JS_Parse_Error (eval at <anonymous> (build/lib/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1547:18)

looking at the same : 

const{entries:e,setPrototypeOf:t,isFrozen:n,getPrototypeOf:o,getOwnPropertyDescriptor:r}=Object
