### ISSUE TITLE
Trying to use in Angular 16, getting "CommonJS or AMD dependencies can cause optimization bailouts."  

### ISSUE THREAD

**Issue by motohead400** [cure53/DOMPurify#869]
Is it possible to have an ES6 module export version of this?

**Comment by cure53** [comment]
We're open to a PR for this if you set one up :)

**Comment by jeroen1602** [comment]
I found that manually adding `"es2020": "./dist/purify.es.mjs",` gets rid of the warning.

But I'm not sure if this is the correct method, I'm not very familiar with creating js libraries.

I also found what I believe is the order that the Angular compiler uses to find the entry point for future reference

https://github.com/angular/angular-cli/blob/d6a34034d7489c09753090642ade4c606cd98ece/packages/angular/build/src/tools/esbuild/application-code-bundle.ts#L50

**Comment by cure53** [comment]
Oha, would that be worth a PR? :smile:

**Comment by jeroen1602** [comment]
I'll make one
