### ISSUE TITLE
XSS injection vulnerability

### ISSUE THREAD

**Issue by kahoot-karl** [cure53/DOMPurify#873]
XSS injection. Can be reproduced with https://cure53.de/purify

#### Input

```
<<a>audio src/onerror=\\\"if(!window.init){alert(localStorage.getItem('token'));window.init=true;}\\\">
```

#### Given output

```
&lt;<a>audio src/onerror=\\\"if(!window.init){alert(localStorage.getItem('token'));window.init=true;}\\\"&gt;</a>
```

#### Expected output

Not sure

**Comment by cure53** [comment]
I cannot reproduce, sorry. I see no bug here.

**Comment by kahoot-karl** [comment]
Sorry, wrong copy/paste, one more try

**Comment by cure53** [comment]
There is no actual injection or bypass, you just see harmless text there, as expected.
