### ISSUE TITLE
Consider supporting happy-dom

### ISSUE THREAD

**Issue by luxaritas** [cure53/DOMPurify#876]
I've recently been using happy-dom with vitest instead of jsdom due to its focus on performance. It would be awesome if DOMPurify could also support happy-dom in NodeJS. Since this doesn't appear to have been brought up before, I'm curious if this would be of interest to the project, though I understand if there are scope/maintenance concerns.

I did some very basic checks with happy-dom on the current test suite, and while I get the impression the number of unique errors is fairly limited, it unfortunately doesn't seem completely trivial either. I would be happy to provide some assistance if it is of interest, though would probably need some guidance being a new contributor.

**Comment by cure53** [comment]
Oh, nice - I did not have that on my radar :D 

> It would be awesome if DOMPurify could also support happy-dom in NodeJS.

We are open to that.

> I would be happy to provide some assistance if it is of interest, though would probably need some guidance being a new contributor.

That would be great! We would likely need the testsuite to be extended and update the Github actions, etc. - and maybe the existing tests already help identifying possible sanitizer bypasses in Happy DOM they might want to address.

What would you say are next steps?

**Comment by luxaritas** [comment]
> What would you say are next steps?

Thinking I should open a PR that at least has the adjusted tests set up so that it's easy to review and discuss specific test failures - that way once we identify specific scenarios that fail, we can build up a list of items that need to be resolved

**Comment by cure53** [comment]
That sounds most excellent :D Thank you. Please do let know if any help is needed.

**Comment by cure53** [comment]
I am wondering, is happy-dom still maintained? No movement for two months it seems...

**Comment by luxaritas** [comment]
It was very active until 2 months ago. It appears the author is a single maintainer (which I didn't realize before) and has not been active, perhaps something has prevented them from being available recently.

**Comment by cure53** [comment]
Aye, okay, no worries - I was just surprised when checking the repo :sweat_smile:

**Comment by cure53** [comment]
Closing this for now, it seems that the ball is in happy-dom's corner and the project is inactive. Please reopen if anything changes.

**Comment by tkrotoff** [comment]
This can be re-opened,
happy-dom is active and this issue has been fixed: https://github.com/capricorn86/happy-dom/issues/1165

**Comment by cure53** [comment]
Ooooh, nice! cc  @luxaritas

**Comment by spaceemotion** [comment]
I noticed an issue while trying to switch from `jsdom` to `happy-dom`. The behavior with using `DOMPurify` is not consistent and seems incomplete.

See more over at https://github.com/cure53/DOMPurify/issues/1094
