### ISSUE TITLE
Unknown element should never be considered as void

### ISSUE THREAD

**Issue by JounQin** [cure53/DOMPurify#886]
> This issue proposes a bug

### Background & Context

https://github.com/cure53/DOMPurify/blob/main/test/fixtures/expect.mjs#L886

#### Input

```html

a<svg><xss><desc><noscript>&lt;/noscript>&lt;/desc>&lt;s>&lt/s>&lt;style>&lt;a title=\"&lt;/style>&lt;img src onerror=alert(1)>\">
```

#### Given output

```html

a<svg><desc></desc></svg>
```

#### Expected output

```html
a<svg></svg>
```
The expected output.

### Feature

The `xss` element should be considered containing all its following instead of void element which is how browser works.

**Comment by cure53** [comment]
Nah, I don't agree. Clearing the content of unknown elements would severely affect harmless sanitization results. You can change the behavior via a hook and take care of that yourself, but we won't change anything in the core library, sorry.

**Comment by JounQin** [comment]
But this is how browser works?

**Comment by cure53** [comment]
Might be, but it would harm legitimate and harmless content - so we cannot empty it.

**Comment by JounQin** [comment]
@cure53 Then I don't quite understand this case:

https://github.com/cure53/DOMPurify/blob/d1e4f216664cc9e1ba5498a00b7d88a9cbd4c7f0/test/fixtures/expect.mjs#L330-L333

Why harmless `div` is removed?

**Comment by cure53** [comment]
Because of the frameset, which causes the DIV to be removed:

**Comment by JounQin** [comment]
I'm still confused, why `div` must be removed due to `frameset`?

**Comment by cure53** [comment]
Please read the link I sent you, it's all there :)

**Comment by JounQin** [comment]
@cure53 

Sorry, but I did read, but I could just find `Deprecated`.

If you mean:

> A frameset document has a <frameset> element instead of a [<body>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body) element. The [<frame>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame) elements are placed within the <frameset>.

I think `<body>${fragment}` will make sure the output always inside body and harmless?

**Comment by cure53** [comment]
FRAMESET is a special tag has everything being removed that cannot be in there or around it, that includes a DIV.

**Comment by JounQin** [comment]
> I think `<body>${fragment}` will make sure the output always inside body and harmless?

![image](https://github.com/cure53/DOMPurify/assets/8336744/a729820e-d944-4bab-b00e-733e875f99dc)

**Comment by cure53** [comment]
Yes, again, please inform yourself about HTML, about what the body tag does, what the frameset element does - once you know that, you will see it all makes sense.
