### ISSUE TITLE
`>` as text node should not be escaped

### ISSUE THREAD

**Issue by JounQin** [cure53/DOMPurify#887]
> This issue proposes a bug/feature

### Background & Context

`>` as text node can not be XSSed?

#### Input

```html
<div>>xxx</div>
```

#### Given output

```html
<div>&gt;xxx</div>
```

#### Expected output

```html
<div>>xxx</div>
```

### Feature

Don't escape unnecessary chars

**Comment by cure53** [comment]
That is what the browser does, not us - hence we cannot and won't override this :)

**Comment by JounQin** [comment]
I'm using DOMParser, and it doesn't escape.

**Comment by cure53** [comment]
Are you sure?

```javascript
new DOMParser().parseFromString('<div>></div>', 'text/html').body.outerHTML 
// "<body><div>&gt;</div></body>" 
```

**Comment by JounQin** [comment]
Interesting, sorry, it seems I misread the diff at https://github.com/un-ts/domiso/blob/test/dompurify_cases/test/__snapshots__/dompurify.spec.ts.snap
