### ISSUE TITLE
Return removed elements after sanitize call  

### ISSUE THREAD

**Issue by xleepy** [cure53/DOMPurify#888]
Hi, 
Is there better approach than overriding push https://stackoverflow.com/a/5100420 or using `uponSanitizeElement` hook to get removed elements after sanitize call? 
```
const result = DOMPurify.sanitize(html, {
      FORCE_BODY: true,
      ADD_TAGS: ['script']
    });
``` 
With this config removed will be always in array but i need to get all scripts before html rendered and store them per component. 

`uponSanitizeElement` can't be used because hook will fire globally and will update other elements as well

**Comment by xleepy** [comment]
My idea to have something like 
```
const { html, removed } = DOMPurify.sanitize(this.rawResult(), {
      FORCE_BODY: true,
      ADD_TAGS: ['script']
});
```
to check and return removed and sanitized elements in one component scope. Right now i'm trying to use Map where i collect elements by specific component id but this solution far from ideal 😅. 
And i rely on `uponSanitizeElement` right now but this hook can fire in other subscribed components as well. Also i know that i shouldn't rely on removed 😅 but i need to display notification to user if user really wants to run scripts

**Comment by cure53** [comment]
I see, can you not make the hook check for the component scope and treat elements conditionally?

**Comment by xleepy** [comment]
[Codesandbox](https://codesandbox.io/p/sandbox/sweet-hofstadter-8573lq?file=%2Fsrc%2FApp.js%3A26%2C25&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq57b3g800063b6hub4mq9y4%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq57b3fg00023b6hzui324kp%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq57b3g100033b6hsqw2vvyb%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq57b3g100053b6hsv3jet9x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq57b3fg00023b6hzui324kp%2522%253A%257B%2522id%2522%253A%2522clq57b3fg00023b6hzui324kp%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq57j8z700023b6nb1nx7ozy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A26%252C%2522startColumn%2522%253A25%252C%2522endLineNumber%2522%253A26%252C%2522endColumn%2522%253A25%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clq57j8z700023b6nb1nx7ozy%2522%257D%252C%2522clq57b3g100053b6hsv3jet9x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq57b3g100043b6h6a6sbvkf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clq57b3g100053b6hsv3jet9x%2522%252C%2522activeTabId%2522%253A%2522clq57b3g100043b6h6a6sbvkf%2522%257D%252C%2522clq57b3g100033b6hsqw2vvyb%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq57b3g100033b6hsqw2vvyb%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)  here example. 
2 issues:
1. In react env  `uponSanitizeElement` hook will not fire in any of effects on first render (this is solvable)
2. In component scope we cannot say in which component sanitize really happened and in which component instance hook called

**Comment by cure53** [comment]
Ah, I see. And if we had a hook registered inside `_forceRemove` your problem would be solved? Like, somewhere here?

```javascript
  const _forceRemove = function (node) {
    arrayPush(DOMPurify.removed, { element: node });

    try {
      // eslint-disable-next-line unicorn/prefer-dom-node-remove
      node.parentNode.removeChild(node);
    } catch (_) {
      node.remove();
    }
  };
```

**Comment by xleepy** [comment]
Yep, i think so. at least we can give a try 😅

**Comment by cure53** [comment]
I am not against adding this, if you can confirm that it works and where exactly the hook should be placed in this method, I can add it. Or a PR from you :slightly_smiling_face:

**Comment by xleepy** [comment]
Ok, will fork project and give a try on local build. Thanks!

**Comment by xleepy** [comment]
Due to some policies i cannot work on this by myself. Discovered yesterday 😅. And we will need some key for this hook as well otherwise `removeNode` hook will be called for each subscription as well. So it will be  
```
const result = DOMPurify.sanitize(hmtl, {key: `some-unique-key`})
```
and then in hook
```
DOMPurify.addHook(`removeNode`,(node, data) => {
 if(data.key === 'some-unique-key') {
    ....do some logic here
 }
})
```
but not sure if you will like this change 😅 
. Also i found another solution to just show notification globally and for now it will be fine 😅. So we can close this issue

**Comment by cure53** [comment]
Oh, haha - okay :) Will do that now, let me know if we can do anything.
