### ISSUE TITLE
Why attitudes are resorted after purified

### ISSUE THREAD

**Issue by JounQin** [cure53/DOMPurify#889]
> This issue proposes a bug

### Background & Context

N/A

#### Input

```html
<textarea type="text" cols="50" rows="10"></textarea>//["'\`-->]]>]</div>
```

#### Given output

```html
<textarea rows="10" cols="50" type="text"></textarea>//["'\`--&gt;]]&gt;]
```

#### Expected output

```html
<textarea type="text" cols="50" rows="10"></textarea>//["'\`--&gt;]]&gt;]
```

### Feature

Don't resort attributes

**Comment by cure53** [comment]
Again, this is done by the browser. 

Please start doing some reserach what the expected browser behavior is before creating tickets here, this is a bug tracker and not a vending machine to request general HTML knowledge.

**Comment by JounQin** [comment]
@cure53 

I did, but I don't see resorting:

<img width="914" alt="image" src="https://github.com/cure53/DOMPurify/assets/8336744/b486a67e-4a4f-40df-91bf-a9ee980083f4">

And this makes a bit incompatible with my own lib [`domiso`](https://github.com/un-ts/domiso/pull/37/files#diff-b889be38c0d3ca6b447a04a6d2c1470fce3155ca32f89cab9d4ff191565675d1)

**Comment by cure53** [comment]
Please use this bug tracker for actual bugs and not for random Q&A.

The attribute sorting is nothing we can easily get rid of, also for security reasons. Compatibility with other libraries is not our goal, preventing XSS is.

**Comment by JounQin** [comment]
I'm posting this issue because I think this is a bug or at least unexpected behavior.

I'm not saying it should be compatible with other libs, I'm just observing the differences and want to discuss with about which behavior should be desired.

**Comment by cure53** [comment]
It's in fact not a bug, and very much expected behavior.

> If my issues are just meaningless to you, I'm sorry, I just want to share what I observe which might be unexpected.

They are not meaningless but also in the current form not overly helpful. Some of the questions you could have answered yourself by reading the spec, others by browsing this bug tracker. So, not meaningless - but sadly redundant because you open tickets for issues where some research would have answered all questions already.

Please first check what knowledge is there already before starting to force others to be involved and look into questions that have long been covered by other, meanwhile ancient tickets.

**Comment by JounQin** [comment]
I did read some spec and context and we may be sharing different opinions on how content should be removed:

1. non standard tag should not be considered as void, it is the spec, but you said it should be considered as harmless
2. `div` + `frameset` can also be considered as harmless with a `<body>` prefix, but you said that's not spec

I'm just confusing on your position and points, for the above questions I don't think I can find a `spec` to convince myself.

**Comment by cure53** [comment]
Again, please read what a body tag causes to happen and what a frameset causes to happen and then it becomes clear. 

You can see clearly from the code that we don't have our own parser, we rely on the browser and _lots_ of things happen there automatically. Once you understand the browsers behaviors with framesets, tables and many other crazy elements, the test cases will all make sense.

This is not about my position, this is about browser behavior. And about the browser reacting to strange HTML and us then sanitizing the result to prevent XSS.

**Comment by JounQin** [comment]
Again, I'm using `DOMParser` which is also just a browser thing.

I don't known if it is a browser version change caused difference?

> This is not about my position, this is about browser behavior. And about the browser reacting to strange HTML and us then sanitizing the result to prevent XSS.

If you don't mind, can you help to understand that do you mean non standard tags as void is parsed by browser instead of `dompurify` itself? That seems different with `DOMParser` then.

Did you tried to update all browser version for the test cases?

**Comment by cure53** [comment]
Please read the code, this will answer all your questions.

**Comment by JounQin** [comment]
If you mean I have to read the codes of the whole project before creating any issue which is unexpected, I don't know what to say then, good luck.

I'm here to try to make `dompurify` better, not an attacker.

**Comment by cure53** [comment]
Blocked for ticket spam
