### ISSUE TITLE
How to allow all tags except <script>

### ISSUE THREAD

**Issue by Sudeepa1949** [cure53/DOMPurify#891]
I want to use xml data with dom purify, but I dont want to use <script> tags,

**Comment by cure53** [comment]
You can use the config options for that, check what is allowed already and expands the list of allowed elements with the `ADD_TAGS` setting. That should do the trick.

**Comment by Sudeepa1949** [comment]
urgent help needed on this

**Comment by cure53** [comment]
If you want to allow ALL elements except for script, best use a hook where you allow everything except script.

**Comment by cure53** [comment]
Closing this as it's not a bug or feature request, can easily be solved with config options (to set parser type) and hooks (to allow everything but script).

**Comment by Sudeepa1949** [comment]
can you give an example that i can go through

**Comment by cure53** [comment]
Yep, we have lots of demos here: https://github.com/cure53/DOMPurify/tree/main/demos

Those include demos for hooks as well, I recommend using the `uponSanitizeElement` hook.
