### ISSUE TITLE
TypeError thrown by clone when configuration contains null values

### ISSUE THREAD

**Issue by bob-difronzo** [cure53/DOMPurify#897]
### Background & Context

When upgrading from `3.0.6` to `3.0.7`, a `TypeError` is getting thrown when calling `sanitize` if the configuration object contains any `null` values. The issue appears to be [this line](https://github.com/cure53/DOMPurify/blob/main/src/utils.js#L139) in the `clone` utility since `typeof null === 'object'`. For now we have replaced `null` with `undefined`.

#### Input

```js
DOMPurify.sanitize(anyString, {
  CUSTOM_ELEMENT_HANDLING: {
    tagNameCheck: null
  }
});
```

#### Given output

```
Uncaught TypeError: Cannot read properties of null (reading 'constructor')
```

#### Expected output

Expected no error to be thrown.

**Comment by cure53** [comment]
Thanks for spotting this and thanks for sending over a PR. The PR looks great and got merged :smile:
