### ISSUE TITLE
[bug] Breaking changes with tag matching (_isBasicCustomElement) in 3.0.10 

### ISSUE THREAD

**Issue by AlekseySolovey3T** [cure53/DOMPurify#920]
> This issue proposes a [bug] which should expand `CUSTOM_ELEMENT` Regex to allow underscores.

### Background & Context

When sanitizing a string (in `DOMPurify.sanitize`) with a **custom element**, it doesn't allow underscores (`_`) in `_isBasicCustomElement` method.
Currently accepted Regex: `/^[a-z][a-z\d]*(-[a-z\d]+)+$/i`

#### Input

```js
DOMPurify.sanitize('<customtag-my-custom-element_v1 />', options);
```

with `CUSTOM_ELEMENT_HANDLING`'s `tagNameCheck` in options set to `(tagName) => RegExp(/^customtag-/).exec(tagName)`

#### Given output of `_isBasicCustomElement`

`null`

#### Expected output of `_isBasicCustomElement`

`["customtag-my-custom-element_v1"]`

### Feature

`stringMatch(tagName, CUSTOM_ELEMENT)` doesn't pick up `_` in tags. The Regex should be extended to include underscores.

## Docs on a valid custom element name

[MDN](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements#name):
> The name of the element. This must start with a lowercase letter, contain a hyphen, and satisfy certain other rules listed in the specification's definition of a valid name:

> HTML Standard - **valid custom element name**: https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name

**Comment by cure53** [comment]
Oha, well spotted, thanks - we might change the regex to this, likely that woulf fix the issue, no?

`export const CUSTOM_ELEMENT = seal(/^[a-z][_a-z\d]*(-_[a-z\d]+)+$/i);`

**Comment by AlekseySolovey3T** [comment]
> Oha, well spotted, thanks - we might change the regex to this, likely that woulf fix the issue, no?
> 
> `export const CUSTOM_ELEMENT = seal(/^[a-z][_a-z\d]*(-_[a-z\d]+)+$/i);`

Ignoring the hexadecimal values, the standard suggests the potential use of `a`-`z`, `-`, `.`, `0`-`9` and `_`  as valid symbols

![image](https://github.com/cure53/DOMPurify/assets/125454621/56e4f1a9-3918-4b63-b89d-4e056f1ea9c0)

It should also follow this structure: 
`[a-z] (PCENChar)* '-' (PCENChar)*`
where `PCENChar` is `"-" | "." | [0-9] | "_" | [a-z]` in any combination

If we split these rules into groups, we have: 
(a-z) (PCENChar*) (-) (PCENChar*)
or, in Regex:
```js
([a-z])([-._a-z\d]*)(\-)([-._a-z\d]*)
```
Play around with regex rules here: https://regex101.com/r/cgnm2W/1

MDN also specifies that it 
> must start with a lowercase letter

Not sure if you want to be strict about the use of `/.../i`

### Potential full code:

```js
export const CUSTOM_ELEMENT = seal(/^([a-z])([-._a-z\d]*)(\-)([-._a-z\d]*)$/i);
```

**Comment by cure53** [comment]
Thanks, the proposed RegEx however is vulnerable to ReDos :slightly_smiling_face: 

This one should achieve mostly the same and be safe(r) and also match your example well:

`/^[a-z][_.a-z\d]*(-[_.a-z\d]+)+$/i`

Wdyt?
