### ISSUE TITLE
Question about using DOMPurify for a tricky usecase.

### ISSUE THREAD

**Issue by yam4office** [cure53/DOMPurify#927]
Hi Team, 
I have a textarea and whatever that is typed in the textarea becomes added to the end of the head of current document and end of body of current document, So 95% of the times the input are <script></script> tag contents that contains custom logic to be added to header and footer of the website so that end user can whitelabel the website for their usecase. So an XSS vulnerability has been found in this text area, because obviously the script that is entered there is going to be executed when it is added to the header and footer of the page.

The ideal data would be google analytics script logic in header and custom whitelabel content for the footer, so in this usecase I am unable to use DOMPurify because I need it to allow <script> tags but at the same time make sure the content of <script> tag is not malicious. 

So what I need help in understanding are:

- DOMPurify will not be helpful in this cases from my analysis, am I right?
- Is there a way to make this logic work without attracting XSS vulnerabilities? (Maybe using some other library, tool etc..)

**Comment by cure53** [comment]
Heya, it sounds like what you need is a JavaScript sandbox, correct?

Something like this? https://github.com/cure53/DOMPurify/blob/main/demos/hooks-mentaljs-demo.html

**Comment by yam4office** [comment]
No, let me give an example of what I need. 

The happy path value that the user types in the textarea is as below.(a generic script for adding Google analytic to page)

```
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', '1', 'auto');
ga('set', 'dimension1', '2');
ga('send', 'pageview');
</script>

```

**As soon as submit button is clicked this script is added immediately into the head of the document as last element and it executes the script hence starting a new google analytic process.** 

But if someone adds this line along with existing logic
`alert("iamhacked") 
`

like 

```
<script>
alert("iamhacked")
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', '1', 'auto');
ga('set', 'dimension1', '2');
ga('send', 'pageview');
</script>
```

Then it will execute that as well. 

So I need to go inside the script content and remove the things that might cause XSS like alert() for example.

As per my analysis what I understand is DOMPurify is not useful in this scenario, infact I see this kind of UI logic that we have itself seems conter-intuitive, am I right?

Or due you think that it is possible to prevent XSS in this particular scenario that I have explained? If so can you give me an example of how you would go about doing it?

**Comment by cure53** [comment]
That is correct, this library cannot help in that case, sorry :sweat_smile:

**Comment by yam4office** [comment]
Cool, finally any thoughts on how I can tackle my particular use-case? Like any other libraries or tools that might help me out here? Suggestions are most welcome.

**Comment by cure53** [comment]
I think without a JS sandbox or alike, this will be extremely hard. You basically need to contextually tell the good apart from the bad - while all that being raw JavaScript code. 

I think this cannot easily be solved without any form of sand-boxing mechanism - as long as users can control the JS code in full.

**Comment by yam4office** [comment]
What would be a better way of solving this do you think? Like at a design level I thought and came up with the below ideas. Feel free to add your thoughts on these as well?

Instead of allowing end users this much of capability we can ask them to send the customization logic to us and we will verify it from our side and only if the verification passed then add the customizations as they wished. 

Essentially moving this text-area to be controlled only by us and not allowing end user this control. 

If you can come up with anything else or your thoughts on the above let me know as well. And thanks a lot so far for your inputs!

**Comment by cure53** [comment]
Sadly, I cannot go further into fixing this specific problem for you here, this is a bug tracker for DOMPurify, not a general discussion group, thanks for understanding.

**Comment by SumoSumir** [comment]
> What would be a better way of solving this do you think? Like at a design level I thought and came up with the below ideas. Feel free to add your thoughts on these as well?
> 
> Instead of allowing end users this much of capability we can ask them to send the customization logic to us and we will verify it from our side and only if the verification passed then add the customizations as they wished. 
> 
> Essentially moving this text-area to be controlled only by us and not allowing end user this control. 
> 
> If you can come up with anything else or your thoughts on the above let me know as well. And thanks a lot so far for your inputs!

Maybe don't allow inline scripts and only allow javascript from client whitelisted urls ?
