### ISSUE TITLE
Question regarding DOMPurify ADD_TAGS is not allowing <script> tag

### ISSUE THREAD

**Issue by yam4office** [cure53/DOMPurify#928]
Hi Team,
For a particular use case I need to allow <script> tags in html so I tried as below:

`DOMPurify.sanitize('<script>a</script>',{ADD_TAGS:['script']})`

But it does not return the <script> and its content, rather it always removes the <script> and its content irrespective of ADD_TAGS logic. Why is this the case? 

Can we do a workaround in DOMPurify to allow this functionality? Or does it violate the basic principle of DOMPurify and its goals? (because <script> tag can have malicious content and cannot be trusted)

**Comment by cure53** [comment]
Heya, try to use the `FORCE_BODY: true` as config option, that should do the trick :slightly_smiling_face:

**Comment by yam4office** [comment]
I tried both 

`DOMPurify.sanitize('<script>a</script>',{ADD_TAGS:['script']},{FORCE_BODY: true})
` 
and

`DOMPurify.sanitize('<script>a</script>',{FORCE_BODY: true})
` 
they gave empty string as result, added screenshot from demo page below:

![image](https://github.com/cure53/DOMPurify/assets/165049826/812b1c28-0390-4509-ad57-5d35c8b4a171)

**Comment by realansgar** [comment]
> DOMPurify.sanitize('<script>a</script>',{ADD_TAGS:['script']},{FORCE_BODY: true})

`DOMPurify.sanitize` takes a single config object with all options, not multiple objects.

`DOMPurify.sanitize('<script>a</script>',{ADD_TAGS:['script'], FORCE_BODY: true})` should work instead.

**Comment by cure53** [comment]
Correct @realansgar , thanks :sweat_smile:

**Comment by yam4office** [comment]
It gave the output as 
`\x3Cscript>a\x3C/script>
`
is that expected?

attached screenshot
![image](https://github.com/cure53/DOMPurify/assets/165049826/975fb52c-e8f2-4fa6-9875-75185e869798)

**Comment by realansgar** [comment]
`\x3c` is the hex encoded `<` character. So the string actually contains `<script>`, it is just displayed differently by the Chrome console.

Today I learned: The [Chrome console does this deliberately](https://docs.google.com/document/u/0/d/1F1sO0B0rZjr_CQmbsGpiRcuBD7uFytCUWiDlUiJ5eus/#heading=h.gtvimllpz98c) and only in very specific instances to enable devs to copy paste stuff from the console directly into an inline script in their HTML file without accidently breaking out of it (or inserting a comment).
