### ISSUE TITLE
Sanitize returns empty string when PARSER_MEDIA_TYPE: application/xhtml+xml and void tags

### ISSUE THREAD

**Issue by lucamerighi** [cure53/DOMPurify#938]
### Background & Context

Porting of [this isomorphic-dompurify issue](https://github.com/kkomelin/isomorphic-dompurify/issues/263) as it's happening with vanilla dompurify as well

### Bug

`DOMPurify.sanitize` returns an empty string when ran on HTML strings containing [void elements](https://developer.mozilla.org/en-US/docs/Glossary/Void_element) when application/xhtml+xml is set as parser media type. 

Dompurify version: 3.1.0
JSDOM version: 24.0.0

#### Input

```
import { JSDOM } from "jsdom";
import DOMPurify from "dompurify";

const window = new JSDOM("").window;
const purify = DOMPurify(window);
const clean = purify.sanitize(
  `
<html lang="en">
<head>
    <title>Sample HTML5 Page</title>
</head>
<body>
    <p>Hello</p>
    <br>
</body>
</html>`,
  {
    PARSER_MEDIA_TYPE: "application/xhtml+xml",
  }
);
console.log(clean); // empty output
```

#### Given output

Empty string

#### Expected output

```
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
    <title>Sample HTML5 Page</title>
</head>
<body>
    <p>Hello</p>
    <br />
</body>
</html>
```

Same outcome for other void elements, such as meta or link tags. Removing the `<br>` in the provided input gives the correct output

**Comment by cure53** [comment]
That is indeed expected behavior, as the parser rejects non-wellformed XML and simply refuses to do anything with it. 

Once you change the type to `text/xhtml` it works again.

**Comment by lucamerighi** [comment]
With that parser is works, but void tags are kept as is. Is there some option to convert tags like `<br>` into their self closed `<br />` form?

**Comment by cure53** [comment]
Not sure, maybe by using a hook or a different parser. That would be out-of-scope for DOMPurify but can likely be achieved with a hook.

**Comment by cure53** [comment]
Closing this for now as we don't have anything to fix on our end :slightly_smiling_face:
