### ISSUE TITLE
when using bypasssecurityTrustHtml mthod to render template 

### ISSUE THREAD

**Issue by Mani9398** [cure53/DOMPurify#946]
when using bypasssecurityTrustHtml method to render template safely .it is rendering properly but aftersome time it is giving these 
SafeValue must use [property]=binding:
(see https://g.co/ng/security#xss)

this is the div element
<div class="message-content phenom-heap-redact-text" [innerHTML]="conversation?.content?.text || conversation?.content?.previewText"></div>

here we are sanitizig before passing to it
this.conversationList.forEach((conversation, index) => {
      if (conversation.channel === 'email' && conversation?.content?.text) {
        // Push the content.text to the emailConversations array
        const text = conversation?.content?.text;
        const htmlContent = this.sanitizer.bypassSecurityTrustHtml(text);
        conversation.content.text = htmlContent;
      }
      });

can you provide suggestion for these
![image](https://github.com/cure53/DOMPurify/assets/137863933/1fc4dbef-b514-4ae9-92de-96b4a84b172f)

**Comment by cure53** [comment]
Unclear what the problem is, please be more precise, else we have to close the ticket as unactionable.

**Comment by Mani9398** [comment]
const htmlContent = this.sanitizer.bypassSecurityTrustHtml(text);
iam using this method to renderhtml content it is rendering safely for the first time .
after some time nearly 1 minute iam getting  below 2 lines on rendered elemnet above and below.

SafeValue must use [property]=binding:
(see https://g.co/ng/security#xss)

**Comment by cure53** [comment]
Nothing that we can do here it seems, sorry.
