### ISSUE TITLE
Why does name="name" on an input field get purified?

### ISSUE THREAD

**Issue by halfmoonui** [cure53/DOMPurify#952]
### Bug

The issue is pretty self-explanatory. `name="name"` should not be purified, right?

#### Input

```html
<input type="text" name="name">
```

#### Given output

```html
<input type="text">
```

#### Expected output

```html
<input type="text" name="name">
```

**Comment by cure53** [comment]
With an input like this, we run into a clobbering issue as follows:

```javascript
<form name="hello">
<input name="name">
</form>
<script>alert(document.forms[0].name)</script>
```

compared to...

```javascript
<form name="hello">
<input name="foo">
</form>
<script>alert(document.forms[0].name)</script>
```

But, with the `SANITIZE_NAMED_PROPS` flag, you should be able to control this behavior.
