### ISSUE TITLE
Exception when passing 0 or "" or null to Dompurify.Sanitize Method #947

### ISSUE THREAD

**Issue by sgudishettys** [cure53/DOMPurify#953]
@cure53 - added new issue as the old one is closed(#947). 
the exception I was getting in immediate window in my .net application.  leaving about it, can we fix below issue. 
when passing 0 we are getting "" as response. .
Dompurify.sanitize(0) ---> gives "" (empty ) as response . can we get it as 0 instead of "". 

This is causing a serious problem for us. as we are showing integer values on a grid where we are seeing nothing if the value is 0 . 

please try below to check.  

var a= 0;
var b = DOMPurify.sanitize(a);
console.log("a: " + a );
console.log("b: " + b );

output we see. 
a: 0
b: 

this will be very helpful for us as we had to add zero validation before calling dompurify at every place if this is not fixed. 

thanks a lot for your time . 
![image](https://github.com/cure53/DOMPurify/assets/140207932/9ed86564-2359-4ecf-bfd2-6a8e38edd03c)

_Originally posted by @sgudishettys in https://github.com/cure53/DOMPurify/issues/947#issuecomment-2100632149_

**Comment by cure53** [comment]
Hmmm, why is there a need to sanitize numbers with a HTML sanitizer?

Why not validate if it's a number or a string and, if it's a string, only then use the sanitizer? It feels to be without added context that this is not our bug and I am not sure what to correct.

**Comment by cure53** [comment]
Oh and, what speaks against using `DOMPurify.sanitize(0..toString()) ` instead?

**Comment by sgudishettys** [comment]
@cure53 
will try using tostring() thanks .
