### ISSUE TITLE
0.6.7 has no purify.js on root

### ISSUE THREAD

**Issue by pkkummermo** [cure53/DOMPurify#96]
The old versions had purify.js on root. This breaks our requirejs scripts. If this is a "planned" feature it really should be at least a minor :)

**Comment by cure53** [comment]
Yep, it's now in `/src`, sorry!

https://github.com/cure53/DOMPurify/tree/master/src

**Comment by pkkummermo** [comment]
Found it, but should probably be at least in change log ;)

**Comment by cure53** [comment]
You are perfectly right, sorry again!
