### ISSUE TITLE
A code comment containing a tag name structure leads to removal of the entire block

### ISSUE THREAD

**Issue by ArtemAvseenko** [cure53/DOMPurify#967]
### Background & Context

In my scenario, an html page markup is returned from external service and my page is embedding the markup. The markup contains some <style> tags with code comments, containing the library author email wrapped into angle brackets. 

### Bug

As a result, the entire style node is removed which causes the broken view.

#### Input

`DOMPurify.sanitize('<html><head><style>#sidebar{position:absolute;top:0;left:0;bottom:0;width:20%;padding:0;margin:0;overflow:auto}/*! * Generatd by xyz-library * <author_emailxxxxx090131@domainexample.com> */.main-content{position:relative;}</style></head></html>',  {FORCE_BODY: true, SAFE_FOR_JQUERY: true})`

#### Given output

`''`

#### Expected output

`<style>#sidebar{position:absolute;top:0;left:0;bottom:0;width:20%;padding:0;margin:0;overflow:auto}/*! * Generatd by xyz-library *  <author_emailxxxxx090131@domainexample.com>  */.main-content{position:relative;}</style>`

**Comment by cure53** [comment]
Hmmmm, that's a tricky one and not easy to address, as doing so will open the flood-gates for mXSS attacks. 

I would recommend to wok with a hook and then to check if the XSS contains critical characters. We cannot change anything with the core code-base because, as mentioned, that would end up yielding bypassed :sweat_smile:

**Comment by cure53** [comment]
To get more into the specifics, I would recommend to use the `uponSanitizeElement`, then to check if the element is a style/CSS element, then strip all comments from it, then return it and commence.

That way, you can defuse the risky comments before even sanitizing and the mXSS checks will no longer complain and remove the whole node.
