### ISSUE TITLE
KEEP_CONTENT remove contents of all ALLOWED_TAGS

### ISSUE THREAD

**Issue by Firioesa** [cure53/DOMPurify#969]
Hi guys, thanks for creating this library. 
I've been using it for my projects and it works really well, except for the `KEEP_CONTENT` config.
The documentation states:
```javascript 
// keep an element's content when the element is removed (default is true)
const clean = DOMPurify.sanitize(dirty, {KEEP_CONTENT: false});
```
I'd expect that `KEEP_CONTENT` only affects disallowed tags (because they will be removed). However, according to my test, if `KEEP_CONTENT` is `false`, all content within the allowed tags is removed, while the tags remain.

Example:
```javascript
DOMPurify.sanitize("<b>tea</b>", {
    ALLOWED_TAGS: ["b"],
    KEEP_CONTENT: false
})
```
Output: `<b></b>`
Expected: `<b>tea</b>`

So, how do I keep the all (tags and content) of the allowed tags while removing all of other tags?

I'm using the latest version.

**Comment by cure53** [comment]
Heya :slightly_smiling_face:  I think this would do the trick, no?

```javascript
DOMPurify.sanitize("<b>tea</b>", {
    ALLOWED_TAGS: ["b", '#text'],
    KEEP_CONTENT: false
}) 
```

**Comment by Firioesa** [comment]
@cure53 Oh it does solve my issue. Thanks!
