### ISSUE TITLE
purify.js was moved into src, but the package.json wasn't updated

### ISSUE THREAD

**Issue by jakerichan** [cure53/DOMPurify#97]
https://github.com/cure53/DOMPurify/blob/master/package.json#L27

**Comment by cure53** [comment]
Thanks! Since I am not trusted with all the development voodoo but rather the security part, @tdeekens is there any other spots that need updating.

**Comment by tdeekens** [comment]
Sorry about the little mess. I went over everything in #99.

**Comment by cure53** [comment]
We'll likely go for 0.7 after we have all in place so no worries. We had to release today because of the bypass on FF. Otherwise we'd have invested more time for those details.
