### ISSUE TITLE
MathML Content Markup Removed

### ISSUE THREAD

**Issue by HaluanUskoa** [cure53/DOMPurify#976]
> This issue is generally seeking more information, not necessarily highlighting a bug or proposing a new feature.

### Background & Context

When sanitizing input and allowing both HTML and MathML (`USE_PROFILES: { mathMl: true, html: true }`), it seems that [MathML Content Markup](https://www.w3.org/TR/MathML2/chapter2.html#id.2.1.3) is being removed entirely. [MathML Presentation Markup](https://www.w3.org/TR/MathML2/chapter2.html#id.2.1.2) behavior is as expected.

It's not a bug, since these tags are being disallowed on purpose [here](https://github.com/cure53/DOMPurify/blob/main/src/tags.js#L262).

The library has flexibility to add these back in if necessary:
`const clean = DOMPurify.sanitize(dirty, {ADD_TAGS: ['my-tag']});`

I'm curious to learn what the reason is for disallowing these in the first place. Any info would be appreciated! If there are common security risks associated with these, then I wouldn't want to allow them. If there isn't much of a security risk, then I could add them back in, or maybe they could not be disallowed at the library level.

#### Input

[Mixed Markup Examples](https://www.w3.org/TR/MathML2/chapter2.html#fund.mix)

#### Given output

Returns only the `<math>` element enclosing the first `<mrow>` child and its children. `<semantics>` and `<annotation-xml>` (along with its children) are removed.

#### Expected output

I expected that it would do this since it's purposefully disallowed. Just curious to learn more about the security risks behind these MathML Content Markup elements.

### Feature

If there are no security risks, maybe these MathML Content Markup elements could be allowed at the library level. I'm not expecting this to be the case necessarily, since they've been purposefully disallowed.

**Comment by cure53** [comment]
The risk here is XSS, sadly and the tags are prohibited purposefully. We will not allow semantics and/or annotation tags anytime soon, sorry.

**Comment by HaluanUskoa** [comment]
Good to know! Thanks.
