### ISSUE TITLE
Reliability after uglification

### ISSUE THREAD

**Issue by cure53** [cure53/DOMPurify#98]
Hi all (cc @tdeekens because potentially affected by this),

I would like to kick-off a discussion as to whether DOMPurify is reliable after being "uglified", "closureized" or otherwise optimized and/or compressed. My main concern stems from this article:

 https://zyan.scripts.mit.edu/blog/backdooring-js/

Should we maybe add this case to our tests? As in, running the tests with an uncompressed DOMPurify but also several versions that are compressed and/or optimized?

Cheers,
.mario

**Comment by tdeekens** [comment]
Lovely just wanted to open an issue regarding this. I'll go over the article later. Nevertheless, I think as people will somehow minify `purify.js` for most of their production use-cases we should at least ensure that it won't introduce leaks. Either by just "knowing" or running tests against a production version. I guess we could have to suites one consuming a src and one a distribution version.

What do you all think about offering a minified production version as `/dist`-asset so people don't use some minifier available as we surely won't test all, right?

**Comment by cure53** [comment]
> What do you all think about offering a minified production version as /dist-asset so people don't use some minifier available as we surely won't test all, right?

I think that makes sense. It is better to have "our" reliable compressed version rather than have completely unpredictable side effects with other unknown compressors.

**Comment by cure53** [comment]
How should we best create the dist-version? What compressor would be ideal and/or most common? I suspect we should run the entirety of tests against the compressed version as well. 

Would it make sense to compress on the fly and test or rather have a static version?

**Comment by fhemberger** [comment]
https://www.npmjs.com/package/uglify-js is the most common compressor (also used by most build tools)

**Comment by tdeekens** [comment]
I'd go for uglify-js if we don't have any solid reason not to.

I can see three paths from a development/testing perspective

1. Create a static minified version with an uglify-js binary and test it assuming that the unminified version will work without leakage if the minified does
- Create a static minified version but also test the unminified version (all tests will run twice obviously)
- Create the minified version on the fly in karma using a webpack uglify-js preloader (should work will look into it) and test only minified code while later creating the minified version under `/dist` using the same minification

Hope this doesn't raise too much confusion. Any preferences?

**Comment by cure53** [comment]
I think we should go for 2.) Run the test once with uncompressed DOMPurify and once with the compressed version we create on the fly and then drop in the `/dist` folder. Is that technically possible?

**Comment by fhemberger** [comment]
Maybe using a pre-commit hook to automatically create and commit the minified version locally with each commit?

**Comment by tdeekens** [comment]
@cure53: ...feels like the most secure way even if it slows down the CI run.
@fhemberger: Could work but git-hooks needs to be activated by hand and won't just be there when somebody clones the repo. Which has been kind of a pain for me in most cases. As soon as somebody checks in something without a build we miss a version and tests might break, right?

We could also use npm's and bower's lifecycle methods like postinstall two minify then for people using it via `bower install` or `npm install`. It would also work on the CI system which installs things and minifies right after.

**Comment by fhemberger** [comment]
@tdeekens There is this handy tool: https://github.com/observing/pre-commit

**Comment by tdeekens** [comment]
@fhemberger I guess hooks have the charm of having control of the environment which minification is performed on whereas with a lifecycle method you'd just hope things to work on any host system.

**Comment by fhemberger** [comment]
Sorry, I don't understand what you mean.

You change something, you (try to) commit, a minified version is generated and all tests are run locally, the commit gets pushed and both minified and unminified versions are tested again against browserstack as well.

**Comment by tdeekens** [comment]
Sorry for being unclear. I am with you on git-hooks by now and completely agree with the flow you recommend. I just meant that obviously the git-hooks runs on the programmers machine which has its advantages I guess whereas a npm lifecycle event would run on any machine which consumes our package so different consumers may get different compression results depending on their machine.

**Comment by cure53** [comment]
We have that covered meanhwile, suggesting to close this for now.

**Comment by tdeekens** [comment]
:+1:
