### ISSUE TITLE
DOMPurify.sanitize() leaves executable code

### ISSUE THREAD

**Issue by pdelancie** [cure53/DOMPurify#986]
> Bug: an can action to be passed via a sanitized string to a tag that is built on the fly using that string.

### Background & Context

We use DOMPurify.sanitize() to protect an input field used for search. Once the input has been sanitized it is displayed in a lozenge beneath the search field. In a recent pen test it was discovered that despite the input string being sanitized it was possible to pass a script into the tag for this lozenge element.

#### Input

&lt;&lt;qript&gt;vAr onmouseover=alert(“SEVN-XSS”)&gt;xss

#### Given output

![Screenshot 2024-08-19 at 1 14 31 PM](https://github.com/user-attachments/assets/700ce020-d022-49e0-8c4d-a976f3444a22)

&lt;vAr onmouseover=alert(“SEVN-XSS”)&gt;xss
In the above the "<" and ">" are actually html entities (less than/greater than) but GitHub is not rendering them here.

In the rendered page this "var" tag becomes part of the following div, whose innerHTML should only be the string "xss" :
![Screenshot 2024-08-19 at 12 58 57 PM](https://github.com/user-attachments/assets/e35808a0-1cef-4fa8-93db-813d3e6deb0c)

Hovering over the div results in an alert whose text is "SEVN-XSS"

#### Expected output

xss

### Feature

N.A.

**Comment by cure53** [comment]
Hmm, this does not seem to be an issue on our end to be frank. Not sure what we are expected to fix, it feels like the implementation our your end is flawed.

Can you share more details what happens to that string?

**Comment by pdelancie** [comment]
Hi. Thanks for your response. I'm confused, though, because I thought that the point of DomPurify is to remove tags and code from a string. That does not seem to be happening in this case.

To answer your question, the string is used for the text -- "xss" -- in the lozenge pictured here:

![Screenshot 2024-08-21 at 8 32 08 AM](https://github.com/user-attachments/assets/b2dba3f5-3364-40a7-9615-06215b3e1dee)

And since DomPurify did not remove the tag surrounding the string, which includes an "onmouseover" attribute, when you hover on the text in the lozenge the browser opens an alert (as called for in the code that was not stripped out), as shown here:

![Screenshot 2024-08-21 at 8 32 26 AM](https://github.com/user-attachments/assets/03c02ae0-8da7-486d-8b56-02c9eac18b26)

**Comment by pdelancie** [comment]
@cure53 Could you please explain why this issue was closed without a response to the information above provided at your request? Thanks

**Comment by cure53** [comment]
What DOMPurify correctly produces is this:

`&lt;vAr onmouseover=alert(“SEVN-XSS”)&gt;xss`

The application must then use it in such way that the entities get decoded, which causes the XSS. As far as I can see, there is nothing DOMPurify does wrong - but rather the application utilizing the sanitized result in an unsafe manner.

**Comment by pdelancie** [comment]
No, it's not the application. It's the browser, Firefox, that isdinterpreting the purified output and rendering is as "&lt;vAr onmouseover=alert(“SEVN-XSS”)&gt;xss"
Since all browsers will do this there is nothing unique to my application about this issue.

**Comment by Gigabyte5671** [comment]
Hi @pdelancie

I'm also unable to reproduce the issue. DOMPurify is successfully sanitizing the specified input.

How have you configured DOMPurify?  
How are you adding the sanitized string to your DOM?

**Comment by pdelancie** [comment]
To reproduce, the string entered in your input field would have to be exactly as shown in my original issue submission (a) in the Input field, and (b) in the searchText variable in the Watch Expressions part of the first screenshot. 

From this string, DomPurify is removing only "<qript>". The purified string still contains a "var" opening tag with a mouseover attribute that has JS as it's value. The browser is then auto-completing this with a closing tag that makes the mouseover value executable. Ideally after being purified the remaining string would instead be only "xss"

**Comment by cure53** [comment]
Either way, this in very likely not a DOMPurify bug :smile: 

It seems that what you are doing in your code example is concatenating HTML snippets to a full HTML string. And you sanitize snippets of that HTML string. DOMPurify sanitizes HTML, not fragments of strings that might later end up in HTML. 

What you want to do here is encode or escape, but not sanitize, me thinks.

**Comment by pdelancie** [comment]
Are you saying that DOMPurify is not intended to be used to protect against an input field being used to introduce executable code? I thought that was the point of it.

Also, isn't it always the case that a purified string undergoes some manipulation in order to present it in the page. That's all I'm doing, not changing the purified string at all, just wrapping it and inserting it. It's the browsers that are auto-completing it, turning it into a complete tag because it includes an opening tag that hasn't been removed by DOMPurify.

My point is that if the purified string below is being recognized by a browser as html then effectively DOMPurify is not removing all executable code from its output:
`&lt;vAr onmouseover=alert(“SEVN-XSS”)&gt;xss`

**Comment by cure53** [comment]
> Are you saying that DOMPurify is not intended to be used to protect against an input field being used to introduce executable code? 

Yep. We sanitize actual _HTML_, not string snippets that might arrive in HTML later on. Our job is to receive a string of potentially dirty HTML and then clean it from all things that might cause harm.

**Comment by pdelancie** [comment]
I guess we might have different understandings of what is "actual HTML." 
But -- assuming that the HTML tag represented by `termDiv` in the code below, in which `searchTerm` would be the entered string, would be considered as actual HTML -- I'll try purifying that, and see what happens.
`let termDiv = '<div class="TermDiv" id="Term' + stringNum + '" onclick="Search_SetCurrent(\'' + stringNum + '\')">' + searchTerm + '</div>';`
