### ISSUE TITLE
DOMPurify.removed isn't reporting inline scripts with arbitrary text afterwards

### ISSUE THREAD

**Issue by Bengejd** [cure53/DOMPurify#988]
> This issue proposes a [bug] which...

### Background & Context

`.removed` isn't reporting script tags as having been removed if they are the first tag encountered and the string ends with arbitrary characters. However, the content is correctly purified. So that's nice.

#### Input

Leading script with text at the end (FAILS TO BE REPORTED):
```
<script>alert('XSS');</script> Some arbitrary text at the end doesn't matter
```

#### Given output

`removed: []`

#### Expected output

`removed: [{ element: script }]`

While I know that `.removed` is just for funzies, this is a legitimate bug, unless there is a reason it is removed but not reported as having been removed.

**Comment by cure53** [comment]
In this case, it never gets removed by DOMPurify, but by the browser before sanitization happens. Hence, it never lands in `.removed` :slightly_smiling_face: 

Try this, then it shows: `A<script>alert('XSS');</script> Some arbitrary text at the end doesn't matter`

**Comment by cdrini** [comment]
To calrify in case anyone else hits this, it seems like the browser-native `DOMparser` library also ignores leading `<script>` tags 🤔 Not sure why.

Eg

```js
new DOMParser().parseFromString('<script></script>', 'text/html').body.outerHTML
// Outputs: "<body></body>" 
new DOMParser().parseFromString('A <script></script>', 'text/html').body.outerHTML
// Outputs: "<body>A <script></script></body>"
```
