### ISSUE TITLE
The DOMPurify.removed does not work as expected 

### ISSUE THREAD

**Issue by Asish-Work** [cure53/DOMPurify#991]
> This issue proposes a bug which concerns the "DOMPurify.removed" .

### Background & Context
Here if we see that there is **script** tag only in the dirtyHTML(before sanitisation) then then DOMPurify.removed is not able to catch it .
But if are other risks before the script tag then the DOMPurify.removed is able to catch it .

#### Input
```
<script type="text/javascript" src="src/purify.js">Asishfdafdqf</script>
<script>feadfabfa</script>

```
#### Given output
<img width="387" alt="image" src="https://github.com/user-attachments/assets/9ee6e0ec-9229-42b4-9c27-6a3ca025a65d">

#### Expected output

That should be able to get the count as 2 errors

### When it works out of the box

But surprisingly it works when I give another error with the script tag
For ex if the input is 
 ```
<img src="https://nodei.co/npm/dompurify.png" onerror=alert(1)>
<script type="text/javascript" src="src/purify.js">Asishfdafdqf</script>
<script>feadfabfa</script>
```

then the output it renders is :-
<img width="462" alt="image" src="https://github.com/user-attachments/assets/73986b1a-715c-4389-9a9c-7e81902fa27d">

and this is expected .

**Comment by cure53** [comment]
Duplicate and invalid, please see here:

https://github.com/cure53/DOMPurify/issues/988
